### ISSUE TITLE
Catching KeyboardError makes an infinite loop possible

### ISSUE THREAD

**Issue by moshekaplan** [sassoftware/saspy#109]
If a username or config is not specified, it's not possible to Ctrl-C out of the script, because the KeyboardException is caught and the prompt is called again in an infinite loop.

For example, in sasbase.py replace:
```
def _prompt(self, prompt, pw=False):
    if self._kernel is None:
        if not pw:
            try:
                return input(prompt)
            except KeyboardInterrupt:
                return ''
        else:
            try:
                return getpass.getpass(prompt)
            except KeyboardInterrupt:
                return ''
    else:
        try:
            return self._kernel._input_request(prompt, self._kernel._parent_ident, self._kernel._parent_header,
                                                   password=pw)
        except KeyboardInterrupt:
            return ''
```

With:
```
def _prompt(self, prompt, pw=False):
    if self._kernel is None:
        if not pw:
            try:
                return input(prompt)
            except KeyboardInterrupt:
                raise
        else:
            try:
                return getpass.getpass(prompt)
            except KeyboardInterrupt:
                raise
    else:
        try:
            return self._kernel._input_request(prompt, self._kernel._parent_ident, self._kernel._parent_header,
                                                   password=pw)
        except KeyboardInterrupt:
            raise
```

This would have to be changed in sasbase, sasioionm, and sasiostdio

**Comment by tomweber-sas** [comment]
Yes, that is a poor implementation there. My bad and good catch on your part. Do you think just raising the error is the thing to do, or would prompting the user asking if they want to bail out of this or continue? I suppose passing the exception along is fine. Though, as we know we're in the loop asking for which config to use, it might make sense to ask if they want to break out (and then raise the exception), or continue (as it does now). I guess that only makes sense if they didn't mean to hit ctl-C, which probably isn't the case. Guess I'm talking myself into just raising the exception. If they didn't do ctl-C  on purpose, then just resubmit the SASsession() and continue.

Do you want to do a PR for this, or would you like me to fix it? Either way is fine.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Ah, sorry if I confused you. You identified this w/ prompting for user/pw, while I said it was when prompting for config definition. As this is in the common prompt method, it's the same issue for both cases. Fixing this in the prompt routine (which is what you're showing) will address both (and any other) case(s). 
Tom

**Comment by moshekaplan** [comment]
I think re-raising is wisest.

An alternate approach would be to return a value of `None` and have the calling function check for that special value. The downside of that approach is that a caller might forget to validate the result and you wouldn't detect the error until you tried operating on the `None` in an unsupported fashion.

**Comment by moshekaplan** [comment]
Sorry, I didn't respond to your direct question:
> Do you want to do a PR for this, or would you like me to fix it? Either way is fine.

I'd prefer if you fixed it.

**Comment by tomweber-sas** [comment]
No problem. I'll try to get to it this week!

Thanks,
tom

**Comment by tomweber-sas** [comment]
Well, I didn't get to this last week, but I'm looking at it now.
Just fyi.
Tom

**Comment by tomweber-sas** [comment]
Ok, I've made these changes and pushed them to the reconnect branch also (have 3 issues coded in there, all the same files). Having multiple people testing that out, even if for their own issue, is good overlap testing.
I ended up catching the Keyboard exception in the prompt code, but return None so each caller could tell and do what they needed to do. There are different situations that needed to be handled differently.
I believe I have them all handled appropriately. But, before pushing them to master, want to validate that more.
Can you pull from the reconnect branch and try it out to see what you think? 
Let me know if you come across anything that doesn't do what you think. 

Thanks,
Tom

**Comment by moshekaplan** [comment]
Looks fine to me.

**Comment by tomweber-sas** [comment]
Great, thanks for checking it.
Tom

**Comment by tomweber-sas** [comment]
this has been merged to master.
Tom
