### ISSUE TITLE
IOM connection writes to stdout 

### ISSUE THREAD

**Issue by moshekaplan** [sassoftware/saspy#110]
sasioiom.py contains two print statements that execute in all circumstances.

https://github.com/sassoftware/saspy/blob/9f96e2d54e2cbd9a282ef6d50a3e597a7fe004d6/saspy/sasioiom.py#L456

https://github.com/sassoftware/saspy/blob/9f96e2d54e2cbd9a282ef6d50a3e597a7fe004d6/saspy/sasioiom.py#L502

Would it be possible to control those print statements via a verbose or quiet parameter?

**Comment by tomweber-sas** [comment]
Yes, that would certainly be possible. I don't have an option for it currently, but adding one should be simple. Out of curiosity, are those problematic? Or just trying to get 'clean'  output without extra messages?

What's your take on the option? Verbose, quiet, other? And scope? at the saspy (everything level), SAS session level? ...?

I would think the default would be current behavior, of course. And setting the option could then restrict it. These are the only two messages, or the only two you've noticed so far; regarding being controlled by an option?

Thanks,
Tom

**Comment by moshekaplan** [comment]
>Yes, that would certainly be possible. I don't have an option for it currently, but adding one should be simple. Out of curiosity, are those problematic? Or just trying to get 'clean' output without extra messages?

The main reason I want it is for clean output, but it would also be useful in the event someone needs to run the script from a cronjob (which treats stdout content as indicative of an error).

> What's your take on the option? Verbose, quiet, other? 
> I would think the default would be current behavior, of course. And setting the option could then restrict it. 

That depends on what the default should be. If you want the default to print those messages, then it would be to add a 'quiet' option. Personally, since that's "debug" output, I'd prefer if it were only printed with a `--debug` parameter and the default were to not print it.

> And scope? at the saspy (everything level), SAS session level? ...?

Since the output is at the SAS session level, I'd think it would make sense to also set the verbosity there.

> These are the only two messages, or the only two you've noticed so far; regarding being controlled by an option?

The rest of the print messages I had noticed were only printed in the event of an error and were followed by raising an Exception or returning. In error conditions, printing is reasonable (although writing to stderr might likely be a better option).

**Comment by tomweber-sas** [comment]
@moshekaplan I've made this enhancement. Since it's in the same code as #99, I've pushed it to the reconnect branch. I hope you can grab that and try it out. I added a 'verbose' key to the 'SAS_config_options' dictionary in sascfg. I also allow verbose=True|False on the SASsession() method so you can override the sascfg value for a given connection. I kept the default as True since without it there is no response from SASsession() or _endsas() (del(SASsession object)). 
You can set it to false in your sascfg and never see those messages again.
Let me know what you think. I'll get this to master when I merge in the reconnect branch.
After merging, I'll built a new PiPy package that has these and other enhancements in it.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Oh, BTW, these print statements are in both access methods (IOM and STDIO). I'm made the changes to both, of course.
Tom

**Comment by moshekaplan** [comment]
Overall, seems fine.

One minor point. You had written:
> I kept the default as True since without it there is no response from SASsession() or _endsas() (del(SASsession object)).

However, anyone migrating an existing config will not print by default, per:

https://github.com/sassoftware/saspy/blob/09e4ada96bda9992b022c0a74ebe1359ca26fd6a/saspy/sasioiom.py#L88

Change that to `self.verbose = self.cfgopts.get('verbose', True)` to make it print by default.

**Comment by tomweber-sas** [comment]
Great, thanks for looking it over. And yes, you're right! I will put that back to True. I was playing with it either way and must have forgotten to set it back. Thanks!

**Comment by tomweber-sas** [comment]
this has been merged to master
Tom
