### ISSUE TITLE
load sas file in server

### ISSUE THREAD

**Issue by LmYjQ** [sassoftware/saspy#112]
I've got some sas file in the server that can be load by sas code below(G:\EGHome\ is a remote path in the server)
![image](https://user-images.githubusercontent.com/12581433/37513137-1cb48b10-293f-11e8-9954-b765f9067911.png)
But I can't find these file in python:
![image](https://user-images.githubusercontent.com/12581433/37515005-73c5b50a-2944-11e8-8bb2-0b5c89decfa3.png)
Also I can't define the libref by sas code:
![image](https://user-images.githubusercontent.com/12581433/37515089-adba2c46-2944-11e8-9dbb-2626e3b2200d.png)

**Comment by LmYjQ** [comment]
the workpath setting not work
![image](https://user-images.githubusercontent.com/12581433/37515844-2030b6f8-2947-11e8-838a-199bf5815ee2.png)

**Comment by LmYjQ** [comment]
Thank you, Tom. I'm not sure if I did what you want, here are the results.

> I'm guessing you're connected to a remote workspace server? 

Yes, I'm connecting to a remote workspace server.

**1. config**

> test204 = {
>         'java'    : '/usr/bin/java',
>         'iomhost'   : '20.1.1.204',
>         'iomport'   : 8591,
>         'classpath' : testnew,
>         'omruser':'liuyiquan',
>         "omrpw":"somepass"

**2. submit sas**

> SAS Connection established. Subprocess id is 44271
> Access Method         = IOM
> SAS Config name       = test204
> WORK Path             = F:\tmp_data\_TD16928_WIN-PMLJOJS6778_\Prc2\
> SAS Version           = 9.04.01M2P07232014
> SASPy Version         = 2.2.1
> Teach me SAS          = False
> Batch                 = False
> Results               = Pandas
> SAS Session Encoding  = UTF-8
> Python Encoding value = utf-8

**3. proc iomoperate**
![image](https://user-images.githubusercontent.com/12581433/37574279-b271229a-2b5a-11e8-82fa-7c93726983c2.png)

![image](https://user-images.githubusercontent.com/12581433/37574304-e0df6196-2b5a-11e8-8b7c-41d038d4cbfe.png)

**Comment by tomweber-sas** [comment]
@LmYjQ Thanks, yes those were what I was asking for. So everything looks good except for those paths not existing for you to assign as librefs. 
It appears that you don't have multiple App Servers, just 'SASApp', so it doesn't appear you're connecting to a different one with saspy then with EG, so you don'e need to specify the appserver key in your configuration definition.
But, you aren't able to assign the library that you can in EG.
So, I'm wondering if the difference could be that in EG you are connecting to a Pooled workspace server, not the regular workspace server? There can be different configurations for those, so maybe those libraries are available in the Pooled and not in the non-pooled ones. The other possibility with that is they are available to both, but it's a permission issue. I believe the pooled workspace servers are launched with specific credentials, whereas reguler workspace servers are launched with the individual users (yours) credentials. So, it could also be that those libraries are there but you're userid (on the workspace server) can't access them, while when connected to a pooled WS, the credentials it's running under does have permission to assign those libraries.

Can you check to see if that is the issue? I don't see any other reason for this from what I'm seeing.

Thanks,
Tom

**Comment by LmYjQ** [comment]
@tomweber-sas  Thank you Tom, I'm so sorry that I made a big mistake. There are two servers 20.1.1.204 and 20.1.1.4,  I mixed them up. 

After I corrected the server and file path, the libref has set, but when I try to read the data

![image](https://user-images.githubusercontent.com/12581433/37633585-ead063c0-2c2d-11e8-9e6e-193a4ef4568d.png)

**Comment by tomweber-sas** [comment]
@LmYjQ No problem! Glad you're up and running!
Tom
