### ISSUE TITLE
SASpy 2.2.3 contains sascfg_personal.py

### ISSUE THREAD

**Issue by DaymondLing** [sassoftware/saspy#117]
Just upgraded to 2.2.3 and it wiped out my sascfg_personal.py. 

Documentation (https://sassoftware.github.io/saspy/index.html) says it's not supposed to be part of repository :)

**Comment by tomweber-sas** [comment]
It absolutely shouldn't be. You are correct. I do not see it at master, it's not there.
But, I see now, I must have been in the wrong directory when I created the pypi package!
I truly apologize. That is my mistake. Bad day with creating pypi  package.
I will fix that and make a 2.2.4
I hope you can recover your _personal. I am sorry for that.
Tom

**Comment by tomweber-sas** [comment]
I've built 2.2.4 on pypi. I created it from the correct source. Again,I am sorry about that and I hope you can recover your _personal file. 2.2.4 should be good. Thank you for reporting this to me!
Tom

**Comment by DaymondLing** [comment]
Thanks, Tom. Fixed and restored.

**Comment by tomweber-sas** [comment]
Thanks! I'm going to leave this open the rest of the week, just in case I messed up anyone else. They will at least see this and know what's up
Tom

**Comment by tomweber-sas** [comment]
going ahead and closing
