### ISSUE TITLE
Passing options and format searching

### ISSUE THREAD

**Issue by bikashdube** [sassoftware/saspy#118]
How can we pass various options that we use at the beginning of SAS code in python cells? like 
NOSOURCE NOERRORABEND NOFMTERR FMTSEARCH etc?

**Comment by tomweber-sas** [comment]
Let's see. For the STDIO access method, you can pass startup options (invocation only options) via the 'option' key in the configuration definition (or on the SASsession()). For IOM, all invocation only options must be part of the workspace server configuration, there's no way to pass those via IOM.
For any other option (that you can specify during the SAS session), I guess I don't have a options() method off the SASsession object. I can add one of those easily. I can take a dictionary of the option names and values. Is that what you're looking for? Also, I believe #54 was implemented back then, so you should be able to share a SASsession between sas_kernel and the magics. 

Let me know if the options() method with a dictionary is what you're thinking or if it's something else. 

Thanks,
Tom

**Comment by bikashdube** [comment]
Thanks Tom, that is exactly what I am looking for in terms of an "options()" method to pass to a SASsession object that currently we can't do via the options python dict in sascfg.py for STDIO connections. 

e.g I have tried various ways to set fmtsearch but it doesn't seem to work via the config options but works fine in command line

```
/path/to/sas -fullstimer -nofmterr -fmtsearch /path/to/formats/ -nodms -stdio -terminal -nosyntaxcheck -pagesize MAX
```
For this I we have the following in the config

```
default  = {'saspath'  : '/path/to/sas',
            'options' : ["-fullstimer", "-nofmterr","-fmtsearch=/pat/to/formats/"]
            }
```

The fullstimer and nofmterr options work fine. I ran the following to see all the options available.

```
proc options;run;
```

https://github.com/sassoftware/saspy/pull/54 -> This works fine when you are working in a python notebook and want to share a previously open sessions by passing an argument to the sas magic like 
```
%%SAS myexisitingsession
```
where myexistingsession is a subprocesses that was initiated earlier in any cell in the same python notebook via
```
myexistingsession = saspy.SASsession()
```

If we are working on a SAS notebook, how can we share the session that is spawned in the background ? Invoking '''%%python''' creates a new session.

Thanks
Bikash

**Comment by tomweber-sas** [comment]
Ok, Let's start with the 'option' list. Each token has to be its own entry, like it looks on the command that you showed. So it should be this:
```
default  = {'saspath'  : '/path/to/sas',
            'options' : ["-fullstimer", "-nofmterr", "-fmtsearch" , "/pat/to/formats/"]
            }
```
I thought I had an example like this in the sascfg.py file (I probably did at one point), but it' sin the doc instead (showing autoexec):
```
default  = {'saspath': '/opt/sasinside/SASHome/SASFoundation/9.4/bin/sas_u8',
            'options' : ["-fullstimer", "-autoexec", "/user/tom/autoexec"]
            }
```

I can add an option() method. But for invocation only options, they will still have to be in the 'options' list, as an sas.option() method will only be useful for options you can change after SAS has started. At the moment, you can set those using the submit() method; res = sas.submit('options stimer;')
I think fmtsearch is invocation only. So just code it in the config def.

For the magic, I guess I didn't understand what you were asking for. I thought it was the %SAS magic.
The %python magic I have no control over. Can you give me an example of what you would be trying to do from a SAS Kernel notebook in this case?

If this is really all just about getting an ivocation option set, I think you just put the right syntax in the config def, and it already will do what you want. Just had the wrong syntax, that's all.

Let me know,
Thanks,
Tom

**Comment by bikashdube** [comment]
OK thanks Tom. That correct syntax did help and now I am able to set fmtsearch. However all users of the hub will be forced to use the formats I have defined in their individual Labs/notebooks, something that I'd like to avoid and hopefully this is where a sas.options() can help.

For the magic, say I am working on a notebook that i have chosen to use SAS kernel only for all cells. I choose to run the following sas code in the first cell
```
proc options;
run
```
I see the following after I choose to run the cell, followed by the output in the cell output
```
SAS Connection established. Subprocess id is 930161
```

Now in a second cell I want to run the following
```
%%python
other saspy statements I want to run
```
How do I refer to the SASsession object here? The subprocess 930161 session in this case.

**Comment by tomweber-sas** [comment]
So, I'm still thinking you're looking for an options() method to somehow put on the SASsession; to set invocation only options. Is that right?
You can specify any of the configuration definition keys as an option on the SASsession() already. Like this:
```
sas = saspy.SASsession(cfgname='tdi', options=["-fullstimer", "-nofmterr",  "-fmtsearch" , "/pat/to/formats"])
```
You do have to set the config_option 'lock_down' : False  if you want to allowed these config values on the SASsession() to override the config def values at run-time. That is for values you have in your config definition. If you don't specify a given key in your config def, then It can already be specified on the SASsession(), even with 'lock_down' : True since that's not 'Overriding; the config def, as it's not specified.
```
SAS_config_options = {'lock_down': False,
                      'verbose'  : True
                     }
```
It sounds like you want users to be able to override these at run-time. They can then do this, or you can not put these in the config def and just specify them yourself in the SASsession() method already.

No, I don't think we have a _%saspy_ magic, to do what you're asking from the sas_kernel. The %SAS magic is to just type in SAS code, from a saspy (python kernel) session (it's nothing more than a convenience wrapper over the submit() method). Don't believe we ever made the reverse to submit saspy code from the SAS kernel session.

**Comment by bikashdube** [comment]
Perfect and understood. Thanks again.

**Comment by tomweber-sas** [comment]
So, then. Does this actually solve what you are trying to do then? That would be good, as it's all already there :)
Thanks,
Tom

**Comment by bikashdube** [comment]
Yup :) good to close this. Perhaps update https://sassoftware.github.io/saspy/getting-started.html#start-a-sas-session with your config examples :+1:

**Comment by bikashdube** [comment]
@tomweber-sas 
Can you please test this in your environment? Setting the following in options
```"-fmtsearch" , "/path/to/formats"```

When I run proc options to see if this is getting set correctly, I see the following
FMTSEARCH=/PATH/TO/FORMATS (gets converted or reported in upper case?) and the format still cannot be found. Also get 
the following error
ERROR: Invalid option value /PATH/TO/FORMATS for SAS option FMTSEARCH.
ERROR: Invalid option value /PATH/TO/FORMATS for SAS option FMTSEARCH.
ERROR: Invalid option value /PATH/TO/FORMATS for SAS option FMTSEARCH.

Contents of /path/to/formats
```
sashost:/path/to/formats _$ ls -lrt
total 4792
-rw-r--r-- 1 user group 4870144 Feb  9 09:57 formats.sas7bcat
-rw-r--r-- 1 user group   40960 Feb  9 09:57 templat.sas7bitm
sashost:/path/to/formats _$
```

**Comment by tomweber-sas** [comment]
Yes, the upper casing is just SAS displaying it normalized. It's not using it upper case with the file system. So  there must be something else going on here. 
Here's what I see with this:
```
sas = saspy.SASsession(cfgname='tdi', options=["-fullstimer", "-nofmterr",  "-fmtsearch" , "/tmp"])
SAS Connection established. Subprocess id is 24262

print(sas.submit("proc options;run;")['LOG'])
 FIRSTOBS=1        Specifies the observation number or external file record that SAS processes first.
 NOFMTERR          Issues a note for missing variable formats, uses w. or $w., and continues processing.
 FMTSEARCH=/TMP    Specifies the order in which format catalogs are searched.
 FONTEMBEDDING     Enables font embedding for Universal Printing and SAS/GRAPH printing.

tom64-3> ps -ef | grep 24262
sastpw   24262 24005  0 Mar26 pts/10   00:00:03 /tdi/mva-v940m5/usrlibsas/laxno.17w38.20170913.weekly/SASFoundation/9.4/sasexe/sas -fullstimer -nofmterr -fmtsearch /tmp -nodms -stdio -terminal -nosyntaxcheck -pagesize MAX
```
Ah, looks like it doesn't take file system paths, but rather librefs:
http://go.documentation.sas.com/?docsetId=lesysoptsref&docsetTarget=p1fvn6rwmpf1njn1whkud1hmsc97.htm&docsetVersion=9.4&locale=en

Basically:
```
FMTSEARCH=(catalog-specification(s))
   catalog-specifications
        libref</LOCALE>
        libref.catalog</LOCALE>
```

Sorry I didn't notice that before. I was just getting the parameter list specified correct, not checking on the syntax of the option. Here's an example that looks right:
```
sas = saspy.SASsession(cfgname='tdi', options=["-fullstimer", "-nofmterr",  "-fmtsearch" , "(work, libref2)"])
SAS Connection established. Subprocess id is 29472

print(sas.submit("proc options;run;")['LOG'])
 FILESYNC=HOST     Specifies when operating system buffers that contain contents of permanent SAS files are written to disk.
 FIRSTOBS=1        Specifies the observation number or external file record that SAS processes first.
 NOFMTERR          Issues a note for missing variable formats, uses w. or $w., and continues processing.
 FMTSEARCH=(WORK, LIBREF2)
                   Specifies the order in which format catalogs are searched.

tom64-3> ps -ef | grep 29472
sastpw   29472 24005  2 12:24 pts/11   00:00:00 /tdi/mva-v940m5/usrlibsas/laxno.17w38.20170913.weekly/SASFoundation/9.4/sasexe/sas -fullstimer -nofmterr -fmtsearch (work, libref2) -nodms -stdio -terminal -nosyntaxcheck -pagesize MAX
``` 

Just be sure to assign any extra librefs you need first thing in your program.
Tom

**Comment by bikashdube** [comment]
Yup that worked. Thank you again.

**Comment by tomweber-sas** [comment]
Good deal! I'll close this one. 
Tom
