### ISSUE TITLE
ValueError from sas.sasdata('table','libref').tail()

### ISSUE THREAD

**Issue by bikashdube** [sassoftware/saspy#120]
Getting this for a dataset that has 433122487 observations.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-9ed15ce1cc06> in <module>()
      5 out = sas.sasdata('table','libref')
----> 6 out.tail(1)

/path/to/saspy/sasbase.py in tail(self, obs)
   1156             lastobs = ll['LOG'].rpartition("lastobs=")
   1157             lastobs = lastobs[2].partition(" tom")
-> 1158             lastobs = int(lastobs[0])
   1159         else:
   1160             lastobs = obs

ValueError: invalid literal for int() with base 10: '4.3312E8'
```

**Comment by tomweber-sas** [comment]
Submit the following and lets see what we're dealing with.
```
sas
print(sas.saslog())
```
thanks,
Tom

**Comment by bikashdube** [comment]
Do you want the logs preceding the out.tail(1) statement?

**Comment by tomweber-sas** [comment]
I'm expecting there's an error in SAS, such that I didn't get back the info I was querying, as I expect, I need to catch that case better. There's a couple methods where I have to gather info before doing the final work, and if those steps fail for some reason, I'm not catching them and putting out a good message, just getting an error trying to parse the log for the info.
You can email the sas log if you want, Don't have to post it here.
I want to see what version you're running (submitting the 'sas' object will display that). And the saslog to see what happened.

**Comment by bikashdube** [comment]
Ok sent email. Please let me know if you would like for me to run anything else to troubleshoot this.

**Comment by tomweber-sas** [comment]
Oh, wait. That's not the libref you were assigning for the formats. You need to assign that format path, like you're assigning the other library, and specify that libref in your ftmsearch.
```
sas = saspy.SASsession(cfgname='default', options=["-fullstimer", "-nofmterr", "-fmtsearch" , '(fmtlib)'],results='html')
sas.saslib('fmtlib', ,path="/rar/mxg3601/formats")
```

**Comment by bikashdube** [comment]
Doh, I had made the updates in the SAS notebooks but forgot in the python ones. I removed all the options since they are in the sascfg_personal.py and assigned it via an additional sas.saslib statement but the error remains same. Also after failing at the tail statement, it doesn't execute any other statement past it. Sending you updated logs.

**Comment by tomweber-sas** [comment]
We've taken this offline. Got the log after the tail fails. Wanted to document this, as it's a problem I'll have to fix in my code.
The problem is:


That’s it! See it in the log now.

63 ! lastobs=&lastobs tom;quit;
lastobs=**4.3312E8** tom

The number of observations I’m getting (so I can set (obs= firstobs=); Is being returned in expotential notation, instead of a number that I can parse
with the python code I have: lastobs = int(lastobs[0]).

That’s the problem. Needed to see the log after that tail!
So it’s no error with anything you’re doing, that’s a new bug for me. 

I’ll see about how to fix this and get that to you. Probably will be tomorrow.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
@bikashdube Can you try a quick fix? Edit sasbase.py and change the following line:
```
-> 1158             lastobs = int(lastobs[0])
```
to
```
-> 1158             lastobs = int(float(lastobs[0]))
```

That should fix this.

I'll see about getting it out to master tomorrow. But that should get you by for the moment.

thanks!
Tom

**Comment by bikashdube** [comment]
@tomweber-sas 

Yup that fixed it nice and easy. Thanks for the support on this.

**Comment by bikashdube** [comment]
Well I do see one more issue and that may be the actual proc sql that is running. The problem is that tail is not giving the accurate last 5 observations or it may be due to this float conversion. 

The last 5 observations that are being output are 
433119996 , 433119997, 433119998, 433119999 and 433120000

In pure SAS code I can get these values and they are the actual last observations

(firstobs=433122483 obs=433122487)

**Comment by tomweber-sas** [comment]
Yes, that was way too easy. Looks like I will have to fix it in the SAS code I generate. The exponential notation lost precision.
Thanks!
Tom

**Comment by bikashdube** [comment]
Tested a simple fix for this and it works great. count(*) is always going to be integer so instead of it defaulting to best12. (hence scientific output for large datasets) we can set the format to bestdxx. instead to force integer output. 

-> 1147
```
code = "proc sql;select count(*) format=bestd14. into :lastobs from " + self.libref + '.' + self.table + self._dsopts() + ";%put lastobs=&lastobs tom;quit;"
```
and revert the change for 
-> 1158             
```lastobs = int(lastobs[0])```

chose bestd14 arbitrarily there, should be good enough to handle the largest of datasets or perhaps make it a configurable option.

**Comment by bikashdube** [comment]
In fact something like this can work if we define a new formal parameter.

```python
    def tail(self, obs=5, maxintwidth=14):
        """
        display the last n rows of a table

        :param obs: the number of rows of the table that you want to display. The default is 5
	:param maxintsize: the maximum width of the integer format for total observations. The default is 14 (format=bestd14.) 
        :return:
        """
        if maxintwidth > 32:
            maxintwidth = 32
        code = ("proc sql;select count(*) format=best" + str(maxintwidth)+ '.' + " into :lastobs from " + \
                self.libref + '.' + self.table + self._dsopts() + ";%put lastobs=&lastobs tom;quit;")

        nosub = self.sas.nosub
        self.sas.nosub = False
```
So now tail can take an additional optional argument for those insane sized datasets ensuring upper bound integrity for bestd format. 

```tail(5,14)```

**Comment by tomweber-sas** [comment]
Formatting it on the SAS side is the correct answer. Just specifying best32. should solve it without the need of extra parameters. This query is just an internal metadata query, not part of what tail actually returns. I think just adding 'format best32.' will fix this for all cases. 
Would you like to do a pull request to add this? Or would you like me to do it? Either is perfectly fine!
Python int handles 32 char numbers, so this should work just fine.

```
>>> x = '12345678901234567890123456789012'
>>> int(x)
12345678901234567890123456789012
>>> x = '92345678901234567890123456789012'
>>> int(x)
92345678901234567890123456789012
>>> x = '99999999999999999999999999999999'
>>> int(x)
99999999999999999999999999999999
```

Thanks,
Tom

**Comment by bikashdube** [comment]
Yes I agree extra parameters would make more sense if we were expecting an equivalent return. But I am not sure if 'format best32.' is better than 'format bestd32.' For those (fringe/test-only) cases where if hypothetically the count(*) is 32 chars wide, I think best32. would convert it again to scientific notation and the problem here isn't python handling 32 char numbers but the metadata conversion to exponential output of count(*). 'bestd32.' would ensure integer output for all cases.

Also please go ahead and submit the PR. I am not sure about internal policies here wrt contributions to open source projects but do intend to follow up on it for future PRs.

**Comment by tomweber-sas** [comment]
I will add this in. I've talked to our format expert. For an integer, the two formats will do the same thing. Only for decimal values will it behave different. So, either is fine here. The one caveat though, is that the integer value will only be correct up to about 16 digits anyway. As these values are floats internal to SAS, when they get larger than 16 digits, they will not necessarily be accurate when converted to integers.
Since this is specifically a row count for the table, 16 digits gets you into the quadrillions range, which, is still pretty big for a single table, even these days. So I think this should be a good fix for some time :)

Neither turn to scientific notation, for numbers that have 32 or less digits, they just aren't accurate anymore.

16 digits:
```
>>> print(sas.submit("proc sql; select 1234567890123456 format bestd32. into :lastobs from sashelp.cars; %put lastobs=&lastobs tom;quit;")['LOG'])

69   ods listing close;ods html5 (id=saspy_internal) file=stdout options(bitmap_mode='inline') device=svg; ods graphics on /
69 ! outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: STDOUT
70
71   proc sql;
71 !           select 1234567890123456 format bestd32. into :lastobs from sashelp.cars;
71 !                                                                                    %put lastobs=&lastobs tom;quit;
lastobs=                1234567890123456 tom
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.21 seconds
      cpu time            0.19 seconds
```
32 digits:
```
>>> print(sas.submit("proc sql; select 12345678901234567890123456789012 format bestd32. into :lastobs from sashelp.cars; %put lastobs=&lastobs tom;quit;")['LOG'])

62   ods listing close;ods html5 (id=saspy_internal) file=stdout options(bitmap_mode='inline') device=svg; ods graphics on /
62 ! outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: STDOUT
63
64   proc sql;
64 !           select 12345678901234567890123456789012 format bestd32. into :lastobs from sashelp.cars;
64 !                                                                                                    %put lastobs=&lastobs tom;
64 ! quit;
lastobs=12345678901234566802609541218304 tom
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.21 seconds
      cpu time            0.20 seconds
``` 

So, you can see that after the 16th digit, it turns to approximation.

**Comment by bikashdube** [comment]
Yup, good ole precision vs accuracy :+1: Thanks for taking this.

**Comment by tomweber-sas** [comment]
Ok, I've pushed this to master.
Thanks for your help on this!
Tom
