### ISSUE TITLE
Use __file__ in sascfg.py for iom.jar

### ISSUE THREAD

**Issue by pmgaccount** [sassoftware/saspy#122]
If there is going to be a default configuration file, why not use __file__ in the sascfg.py file to define the location of `java/saspyiom.jar`? I know that the docs say to edit the config file, but that would only break if the config file was moved, and if you use the config file from a non-standard location you're already going to have to edit it.

I think in general it would be very helpful to have the `pip install` into a virtual environment be easier, which could be accomplished by making the defaults slightly more dynamic.

**Comment by pmgaccount** [comment]
If there isn't something philosophically wrong with having more than simple, editable dictionaries in sascfg.py, then something like this is what I currently have working:
```
# build out a local classpath variable to use below for Windows clients
cpW = ""
# these are the jars we need
targetsW = ["sas.svc.connection.jar", "log4j.jar", "sas.security.sspi.jar", "sas.core.jar"]
# this is the default location on Windows
depDir = "C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\"
# try to get the folders in that location - else set ls = [] to skip building cp
if os.path.isdir(depDir):
	ls = os.walk(depDir)
else:
	ls = []
# check each folder for the jars we want (only look in deploywiz folder) and remove from targetsW to avoid duplicates
for path, _, files in ls:
	for fname in files:
		if fname in targetsW:
			if path.lower().find("deploywiz") > -1:
				cpW += path+'\\'+targetsW.pop(targetsW.index(fname))+';'

# address the sspiauth.dll issue!
os.environ["PATH"] += ';'+r'C:\Program Files\SASHome\SASFoundation\9.4\core\sasext'
```
 I picked the deploywiz folder because it was in the original sascfg.py, but I have no idea if it should get preference like that.

Perhaps the best of both worlds would be a setup script run by pip that creates an editable config file that can be read by ConfigParser?

**Comment by tomweber-sas** [comment]
Hey, thanks. I'm always looking to make this better and easier. I'm still trying to understand, specifically, what the problem is that you're running into, that this it the solution to. I'd like to understand the problem better first. Let me throw out some things to see if I'm on the right track.

1) This seem specific to the jars for the IOM access method. Specifying their location.
2) it seems you're running a local SAS install on your windows box? So Local IOM connection?

A couple things I'm unclear on:
1) about if you have paths to the jars in your config file, but you move the config file it's broke? I don't understand that exactly. 
2) pip install to a virtual environment. Maybe this is where I'm missing something? Is this specific to the problem? What virtual environment are you referring to?


And, here a couple other things, just to make sure we're both on the same page to the over all picture.

1) the sascfg.py file is a example, with templates that have realistic values for various configurations. It's expected that you create a sascfg_personal.py and edit that to your specific requirements; there are many different configurations, even for just the IOM access method.
2) the sascfg_personal.py file can live anywhere, as long as it's found in the python path.
3) The IOM access method can be used from any client, not only windows. Linux, Mac, Windows. It can be used for a local connection on Windows, or for remote connections from any client platform.
4) There's no requirement that the client system have a SAS install on it. Many use this to connect to remote IOM, and there is no deployment on their client. They copy the 4 jars from the SAS server to their client machine and put them in any directory they like, and specify that in their config file.

So, can you help me understand the problem, and we can then see what the best solution might be?

Thanks!
Tom

**Comment by pmgaccount** [comment]
I understand the purpose of the current sasfcg provided - and let me say thanks for making this possible in the first place! I don't think there's a problem with the current setup - I'm just brainstorming things that might make this noticeably easier to set up, particularly for people whose previous experience is with SAS rather than Python/Java.

Part of it is specific to IOM, though the idea could also apply to options like 'ssh' and 'saspath' for the other connection methods.

The idea would be that there's a .py script that generates a default config file at install time, attempting to find the necessary paths/files on your machine by searching in the default locations (regardless of Linux/Mac/Windows). It can still be edited directly, just like it is now, but it has a greater chance of "just working" on machines that have a SAS install. So instead of having the default sascfg.py program have example paths, sascfg_generator.py creates a sascfg.py with reasonable machine-specific guesses (that can default to the paths currently in sascfg.py). 

The goal would be minimizing difficult-to-automate configuration in order to make regular builds wherein you create a python env, install this package, then when connecting you specify a config file using a path. I think that would make it easier for enterprise-wide configurations, but you would still 

1) default to a config file generated at install time using system-specific defaults
2) be able to modify an example config file, should you want to create a sascfg_personal.py

(in response to your two points of confusion above:
1) I simply meant that _my_ version would fail if you moved sascfg.py because it references __file__
2) I only bring up pip as a motivator - anything that makes it easier to move away from the idea of "one single python installation for your whole machine" and toward "environments that can be built/torn down easily" is worth considering.

Thanks for the quick response, let me know if you think this makes sense!

**Comment by tomweber-sas** [comment]
Ok, yes, that does make this more clear in my head. And, yes, that's not a bad idea. Trying to have saspy auto-configure itself, if it can, at install time, while still being able to configure it the same as you can now (if it doesn't get it right, or can't - SAS isn't even there to find it), does seem like a nice feature.

I think I like the idea of a script that would generate a configuration file. That file could be the middle one to use (first look for sascfg_personal.py, then sascfg_generated.py, then sascfg.py).
If this didn't work, or got close, you could still copy it to your _personal and finish tweaking it; maybe it will be mostly right. This way, it won't break anything people have now (when they upgrade saspy), and it won't be required to work. Just a nice convenience when it does.

Do you want to try to work up other cases? For local IOM windows, this could work. For remote, it may get the jars right, but you'd still need to add the rest; iomhost/port, credentials. But, it may give you a better starting point for the _personal if it had the classpath done (if you have a local SAS install). For STDIO, I guess it could search for a SAS install and configure local, and if not found, try to configure an SSH version; you'll still need to add the host info/..., but again, it might be a better starting point for your _personal you'll need.

This is a cool idea!

Thanks,
Tom

**Comment by pmgaccount** [comment]
I would happily work on other cases (though my knowledge is limited - I'm not currently using SAS much but I can follow the examples from the docs).

Are you okay with the idea that sascfg.py reads a flat [config](https://docs.python.org/3/library/configparser.html) file instead of itself containing the dicts? It wouldn't break anyone's current setup, but it would require adding to the docs to explain that if you want to use a flat file, edit the new `sascfg.ini` file instead of directly editing sascfg.py.

The idea would be that it still honors (sascfg_personal.py > sascfg.py) but if you leave sascfg.py alone in a new install, it will actually just read in `sascfg.ini` which was generated at installtime. But if you have sascfg_personal.py somewhere else, it will still work, and if you overwrite the new sascfg.py with an older version of sascfg.py, it will also still work.

**Comment by tomweber-sas** [comment]
Well, I can't say I can picture what that means. I've never seen the configparser bit nor the ini file. So, I would have to see that to know what it really means. Again, I'm open to new and better, but I will have to end up supporting it and need to be able to fix it a year from now after I forget it :)   So I will tend to go with simple and obvious over complicated and convoluted. Not saying this is; just saying I don't know it yet so I can't tell if I'd like it or not. 
If you want to mock this up just for the local IOM case, that you're using, so I can see it in my head (for the broader picture), that will probably be good enough for me to see if it make sense to me, or if I have a better idea or not. That sound reasonable?
FWIW, I'm no python guru; just being transparent here. saspy is my first python program. So, there's plenty I don't know about yet, which is probably apparent from some of my code and how I have done some of this. I'm up for learning more and doing it better :)

Thanks!
Tom

**Comment by pmgaccount** [comment]
So `sascfg.ini` is just what I'm calling a config flat text file. 

The way to picture it I think is this:

Right now configuration takes place inside a script which is executed by python. The script uses python syntax and objects (dicts, strings) to define ways of connecting. They exist at the module level in `saspy.sascfg.dict_name`. To change the defaults, you would edit the actual python script.

The alternative is that there is still a `sascfg.py`, but it doesn't get edited. When it gets imported, it simply reads in a flat textfile that is formatted according to a certain specification. It then assigns the same variables at the module level (`saspy.sascfg.dict_name`) based on the contents of the config file. In addition, there is a script run at install-time that generates this config file (called `sascfg.ini` perhaps) with reasonable defaults based on the environment in which it's installing.

I'll try to mock something up! I don't know much about how to test it (ideally we'd be able to test installing it in many environments).

**Comment by tomweber-sas** [comment]
Honestly, I don't know. I haven't had time to look into this myself yet. Seemed like an interesting idea, but I'm not sure of the implementation.

**Comment by pmgaccount** [comment]
I'll have something soon to demonstrate my rough thoughts, and if it's an issue it can just remain in my fork.

But my goal would be to not _require_ people to use `sascfg.py` or `sascfg_personal.py` as a package, imported absolutely, that contains their config info. Instead I would imagine it to be easier if `sascfg.py` is imported, but pointed at a flat config file (.txt, .ini, whatever, not .py). That makes it easy to edit, easy to generate defaults at install time, and enables functionality like
```
sas1 = SASsession(config_file="my_personal_config.txt")
sas2 = SASsession(config_file="my_enterprise_config.txt")
```

I think it's possible to accomplish this while still maintaing backward compatibility with the old method of importing the config as a python module. But to do so cleanly is probably best accomplished with a little refactoring, so I'm just taking a shot at it with IOM.

**Comment by pmgaccount** [comment]
For refactoring purposes, is it important to maintain `SAS_config_names` as a property of the configuration? Is it there so that you can define certain configurations in the sascfg.py file, yet not make them available at SASsession() create-time?

**Comment by pmgaccount** [comment]
@FriedEgg by the way, this is the way I started trying to implement the post-install script:
https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools

https://github.com/pmgaccount/saspy/blob/new_config/setup.py

**Comment by pmgaccount** [comment]
This seems to work well for `pip install -e` editable installs, but is failing for me otherwise. I think there are ways to fix it listed in the S.O. post I linked to above, but the other option would be that `init_config()`  just gets called each time someone imports `saspy` or maybe `saspy.sascfg`. That probably wouldn't confuse anyone, wouldn't hurt anyone explicitly pointing to a predefined config file, and could avoid issues with setuptools vs distutils etc...

**Comment by pmgaccount** [comment]
After some testing on my end, I think that it might be unnecessarily complex to do this at install time, particularly because if someone builds from a .whl or binary things could get messy.

Instead my proposal would be to add the following functionality:
1) Allow the use of a flat config files that are simple editable text files.
2) Create a method in sascfg.py that the user can call one time (or many times) to create a default_config.ini flat text file
3) Allow the user to specify the config filename when they create a `SASsession()`

This is probably cleaner (no one gets defaults unless they want them), but can still easily be accomplished if someone wants to do programmatic installation (using something like `python -c "from saspy.sascfg import init_config; init_config()"`). It can still preserve 100% of the old functionality, as the SASconfig object can still be initialized by importing sascfg.py or sascfg_personal.py directly.

**Comment by tomweber-sas** [comment]
@pmgaccount I'll try to look at this today. Sorry, I've been booked on other things that were higher priority. 
Thanks,
Tom

**Comment by tomweber-sas** [comment]
Ok, sorry, been on other things, but wanted to get you an answer. I've prototyped what I was imagining, based upon your code you put together to find the files and generate a config for the winlocal case; which is the one case this would work for. This isn't complete by any means, but something to poke at as well.

I tried to get this to run in the install, but didn't have luck with that yet. I was able to drive it at import time, so it **can** be done under the covers. But doing this every time someone import saspy isn't right. 

This should be a one time thing after installing. So, I've just taken your code and created a script to run post install and if everything is just windows with SAS where it defaults to, Java installed such that 'java' is a found command (which  it isn't necessarily; search and generate the full path to java.exe is another thing to do), I have the sspi dll in my path, so I'm assuming that os.environ deal works, which is neat.

This can be run anytime and can take a file name to write out to. All of the details can still be changed, but here's what happens with a fresh install of this then running the script; it dynamically creates the config that works. Here's what I ran:

```
pip install .\saspy-issue122\  # this downloaded branch
pip show saspy   # to see the location of where it was installed - concatenate '\saspy\autocfg.py' to the loc to gen the config:
python C:\programdata\anaconda3\lib\site-packages\saspy\autocfg.py
```



```
PS C:\> pip install .\saspy-issue122\
Processing c:\saspy-issue122
Requirement already satisfied: pygments in c:\programdata\anaconda3\lib\site-packages (from saspy==2.2.4)
Requirement already satisfied: ipython>=4.0.0 in c:\programdata\anaconda3\lib\site-packages (from saspy==2.2.4)
Building wheels for collected packages: saspy
  Running setup.py bdist_wheel for saspy ... done
  Stored in directory: C:\Users\sastpw\AppData\Local\pip\Cache\wheels\b0\72\fa\d2856e66b28b71c434946b33e92e6df64b095ba41fa55297b9
Successfully built saspy
Installing collected packages: saspy
Successfully installed saspy-2.2.4
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\>
PS C:\> pip show saspy
Name: saspy
Version: 2.2.4
Summary: A Python interface to SAS
Home-page: https://github.com/sassoftware/saspy
Author: Tom Weber
Author-email: Tom.Weber@sas.com
License: UNKNOWN
Location: c:\programdata\anaconda3\lib\site-packages
Requires: ipython, pygments
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\>
PS C:\> python C:\programdata\anaconda3\lib\site-packages\saspy\autocfg.py
Generated configurations file: C:\programdata\anaconda3\lib\site-packages\saspy\sascfg_personal.py

PS C:\> more C:\programdata\anaconda3\lib\site-packages\saspy\sascfg_personal.py

SAS_config_names=['winlocal']
SAS_config_options = {'lock_down': False,
                      'verbose'  : True
                     }

cpW  =  "C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cpW += ";C:\\programdata\\anaconda3\\lib\\site-packages\\saspy\\java\\saspyiom.jar"

winlocal = {'java'      : 'java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW
            }
import os
os.environ["PATH"] += ';'+r'C:\\Program Files\\SASHome\\SASFoundation\\9.4\\core\\sasext'

PS C:\> python
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession()
Using SAS Config named: winlocal
SAS Connection established. Subprocess id is 5148

>>> saspy.SAScfg
<module 'saspy.sascfg_personal' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\saspy\\sascfg_personal.py'>
>>> cars = sas.sasdata('cars', 'sashelp', results='text').head()

                                                           The SAS System                         15:23 Thursday, April 12, 2018   1

                                       Drive                   Engine                                 MPG_
 Obs Make  Model          Type  Origin Train     MSRP  Invoice  Size  Cylinders Horsepower MPG_City Highway Weight Wheelbase Length

   1 Acura MDX            SUV    Asia  All    $36,945  $33,337   3.5      6         265       17       23    4451     106      189
   2 Acura RSX Type S 2dr Sedan  Asia  Front  $23,820  $21,761   2.0      4         200       24       31    2778     101      172
   3 Acura TSX 4dr        Sedan  Asia  Front  $26,990  $24,647   2.4      4         200       22       29    3230     105      183
   4 Acura TL 4dr         Sedan  Asia  Front  $33,195  $30,299   3.2      6         270       20       28    3575     108      186
   5 Acura 3.5 RL 4dr     Sedan  Asia  Front  $43,755  $39,014   3.5      6         225       18       24    3880     115      197

>>>
```

**Comment by pmgaccount** [comment]
No worries about the time.

I see why creating a .py is a easier in terms of not needing much refactor. So perhaps in terms of addressing this github issue, this is the right solution.

My goal at a higher level is to move away from the idea of config as a python module and towards it being a simple, easy-to-edit config file. The reason being imports and packaging aren't python's strong suit. It's certainly better than it was 5 years ago, but most of the gains have come from virtual environments. Looking on sys.path for a config module to import is somewhat antithetical to the idea of the clean virtual environment.

So for example, let's say I have two projects, A and B. Project A is listed on my PATH because something in it gets executed from the command line often. It also contains a `sascfg_personal.py.`  Now when Project B tries to import a default configuration, it has to hack at sys.path or make sure sascfg.py is in the same dir as the script is executing. If instead SASsession() took a path to the config file as a param, it would be easy to avoid that.

Overall, I think a flat config file would make the codebase more flexible and more explicit.

**Comment by pmgaccount** [comment]
So for example, this would be a 'build' of a project from scratch (`build.bat`):
```
conda create -y -n my_proj python=3.6 pip>=9.0.3
call activate my_proj 
pip install -e git+http://github.com/pmgaccount/saspy.git@new_config#egg=saspy
python -c "from saspy.sascfg import init_config;init_config()"
```
Once that executes, I can call this to use the default from `init_config()`
```
sas = saspy.SASsession(cfgname="winlocal")
```
or to use corporate defaults of some kind, I can call 
```
sas = saspy.SASsession(cfgname="winlocal", filename=path_to_enterprise_config)
```
or, perhaps the most common at the project level would be to just include a `sas_config.ini` in your source code, so it'd just be
```
sas = saspy.SASsession(cfgname="winlocal", filename="./sas_config.ini")
```
That guarantees I know exactly which config I'm using, and it's the one that was actually included with my source code.

Let me know what you think. If you're strongly opposed, I'll just develop in the fork. If you are interested in seeing what it might look like with a bigger refactor, I can look into rewriting more of the config logic.

**Comment by pmgaccount** [comment]
I forgot to mention that this is what the config.ini ends up looking like, roughly. Nice and easy to edit:

```
[SAS_config_names]
names = default,winlocal

[SAS_config_options]
lock_down = False
verbose = True

[SAS_output_options]
output = html5

[winlocal]
java = java
encoding = windows-1252
classpath = C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94200__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94200__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94200__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94200__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;e:\xxxxx\xxxxx\src\saspy\saspy\java\saspyiom.jar


```

**Comment by tomweber-sas** [comment]
Ok, so I guess this is about these virtual environments. What does the ini file look like for a different one of those? This one seems like the only thing that could really be different is the path to the jars. But other than saspyiom.jar, the SAS ones are in the SAS install on the PC. I imagine those don't change, right? 
I'm guessing that in these different environments the location of where saspy is installed can be different, so it's the path of saspyiom.jar that can vary?
I guess this gets us back to the title of the issue :)  So is this the change in the config that addresses this? 
```
cpW  =  "C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
#cpW += ";C:\\programdata\\anaconda3\\lib\\site-packages\\saspy\\java\\saspyiom.jar"
cpW += ";"+__file__.replace("sascfg_personal.py" ,"java\\saspyiom.jar")
```
When I run with that I get saspyiom.jar from the installed saspy location.  That gets me the same path that I commented out in there. I can easily change the autoconfig script to generate this instead of resolving it to a path, so that  __file__ is in the config file and will thus be resolved at run time for whatever environment and wherever saspy is installed.

Sorry, I'm am still trying to understand this fully. Am I getting closer?
Tom

**Comment by pmgaccount** [comment]
I think we're getting closer for sure. The basic idea is that I'd rather have configuration be specified at runtime rather than "installed." That might be because I have two separate virtual environments, it might be because I want to include my configuration in source control, etc. The more pieces of using this package that are hard to specify in source control, the harder it is to use in a build process/CI.

When we use the `import sascfg` syntax, it's sensitive to sys.path and to where you're running python. If instead we allowed for the option of specifying the location of the file, you'd know precisely what configuration you were using.

The goal of making the autoconfig functionality work is the same regardless though, so we're on the same page there. Whether the configuration is hard-coded into sascfg.py or read in from a config file, `init_config()` seems like a good idea to me.

**Comment by tomweber-sas** [comment]
ok, so I've taken another attempt at this. Just pushed out a few more changes.
I've removed the sascfg imports from the access method modules, they just get the SAScfg from sasbase.
I've removed the _prompt functions from the access methods, just use the one in sasbase.
Those are both good clean ups that you suggested. 

I've added an option for the SASsession() method, cfgfile=, which can point to a sascfg file (still .py, same as it is; it can be named anything), but it can live anywhere. You can still specify cfgname= as well, so the file can have multiple definitions, same as is.

See if this solves everything. I think this does all of what you want, except for rewritting the whole config system to be windows .ini files. I'm really not interested in doing that. I do like all of these changes and enhancements though. I think they will give you what you want while not breaking anything, nor rewriting the whole thing.

Here's a little example. I just copied my sascfg_personal.py to a directory not anywhere in the sys.path, and named it something different; sascfg_file.py.

```
tom64-3> python3.5
Python 3.5.1 (default, Jan 19 2016, 21:32:20)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession()
Please enter the name of the SAS Config you wish to run. Available Configs are: ['default', 'SASgrid', 'http', 'httptest', 'ssh', 'sshtun', 'httpfred', 'grid', 'tdi', 'tdilat', 'iomj', 'iomc', 'iomjwin', 'winiomj', 'winiomjwin', 'winlocal', 'gridiom', 'win
gridiom', 'zos', 'zos2', 'winzos', 'winzos2', 'sshtest', 'sshloc', 'sdssas', 'saskr', 'vb010', 'vb015', 'pune', 'notpune'] vb015
SAS Connection established. Subprocess id is 6401

>>> sas2 = saspy.SASsession(cfgname='iomj')
SAS Connection established. Subprocess id is 6429

>>> sas3 = saspy.SASsession(cfgfile='/u/sastpw/tkpy2j/sascfg_file.py')
Please enter the name of the SAS Config you wish to run. Available Configs are: ['default', 'SASgrid', 'http', 'httptest', 'ssh', 'sshtun', 'httpfred', 'grid', 'tdi', 'tdilat', 'iomj', 'iomc', 'iomjwin', 'winiomj', 'winiomjwin', 'winlocal', 'gridiom', 'win
gridiom', 'zos', 'zos2', 'winzos', 'winzos2', 'sshtest', 'sshloc', 'sdssas', 'saskr', 'vb010', 'vb015', 'pune', 'notpune'] vb015
SAS Connection established. Subprocess id is 6453

>>> sas4 = saspy.SASsession(cfgfile='/u/sastpw/tkpy2j/sascfg_file.py', cfgname='iomj')
SAS Connection established. Subprocess id is 6481

>>> sas
Access Method         = STDIO
SAS Config name       = vb015
WORK Path             = /sastmp/SAS_workBC780000190E_tom64-3/
SAS Version           = V.03.04M0D04232018
SASPy Version         = 2.2.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = UTF-8
Python Encoding value = utf-8

>>> sas2
Access Method         = IOM
SAS Config name       = iomj
WORK Path             = /sastmp/SAS_work6D4800004B3C_tom64-3/SAS_work67FF00004B3C_tom64-3/
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 2.2.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = WLATIN1
Python Encoding value = cp1252

>>> sas3
Access Method         = STDIO
SAS Config name       = vb015
WORK Path             = /sastmp/SAS_work9B8300001942_tom64-3/
SAS Version           = V.03.04M0D04232018
SASPy Version         = 2.2.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = UTF-8
Python Encoding value = utf-8

>>> sas4
Access Method         = IOM
SAS Config name       = iomj
WORK Path             = /sastmp/SAS_work6D4800004B3C_tom64-3/SAS_work27FD00004B3C_tom64-3/
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 2.2.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = WLATIN1
Python Encoding value = cp1252

>>>
SAS Connection terminated. Subprocess id was 6453
SAS Connection terminated. Subprocess id was 6481
SAS Connection terminated. Subprocess id was 6401
SAS Connection terminated. Subprocess id was 6429
tom64-3>
```

**Comment by pmgaccount** [comment]
Sorry about the long pause.

I think this does most of what I'm envisioning. The .ini files aren't meant to be windows specific (that'd be awful) nor do they need to be .ini  - they could be txt files, yaml, json, whatever. I still feel that reading in a text config file and parsing it is cleaner than using an `import` statement on a config file, but I can see the hesitance to refactor that drastically.

In order to keep in line with master I'll rewrite my config.ini files to be .py's and start using this functionality. Thanks for your help!

**Comment by tomweber-sas** [comment]
Thanks! I will see about merging these changes into master as soon as I get the chance.
Thanks!
Tom
