### ISSUE TITLE
sd2df returns error - ChildProcessError: [Errno 10] No child processes

### ISSUE THREAD

**Issue by rd5802** [sassoftware/saspy#123]
In this scenario I`m playing around to test SASPy connection. The SAS server is a Windows machine, SASPy is a Linux JupyterHub server. Both linked by IOM.

`import saspy`
`sas = saspy.SASsession(cfgname='iomwin', iomhost='10.24.4.145', iomport='8591', omruser='', omrpw='')`
`sas.saslib('dochod', path="\\\lodzfl023\\USERS\\DPR\\_WS15778\\Model dochodu")`
`sas.workpath`
`tab = sas.sasdata(table='BIK_ZMIENNE_ALL_TRANS_2', libref='dochod', results='Pandas' )`
`tab.head()`
`sas.submit('proc sql; select * from dochod.BIK_ZMIENNE_ALL_TRANS_2 (obs=10); quit;', results='HTML')`

So far everything goes fine, the code above returns expected results.
Next thing I want to do is to load SAS data set to Pandas CSV data frame.:

`tabela_model_dochodu = sas.sd2df(table='BIK_ZMIENNE_ALL_TRANS_2', libref='dochod')`

The code returns error:
`...`
`ChildProcessError: [Errno 10] No child processes`

After submitting line above there is work going on SAS side. sasdata2dataframe.sas7bvew and temporary files _tomods1 and sastmp-000000021.sas7butl are created in WORK. But the process for some reason stops with error.

Please tell me what I'm doing wrong or what could be a mistake.

**Comment by tomweber-sas** [comment]
Well, I don't see you doing anything wrong. That all looks fine. So, we'll figure it out and get you back running.

Can you show me the results of submitting your SASsession object and get the log; just submit
```
sas
tabela_model_dochodu = sas.sd2df(table='BIK_ZMIENNE_ALL_TRANS_2', libref='dochod')
print(sas.saslog())
```
That will print out version info and other stuff. And the log, in case there's something in there that will help.  Submit 'sas' before the failure, but the saslog() after the failure.

Thanks!
Tom

**Comment by rd5802** [comment]
The log goes as follows. The table has 1028 variables, I removed part of the log output for lenght and confidentiality resons. Modified places are marked with XXX.
After submitting `sd2df` it looks like the sth is broken, executing `sas.saslib...` or `tab = sas.sasdata(table='BIK_ZMIENNE_ALL_TRANS_2', libref='dochod', results='Pandas' )` results in `ChildProcessError: [Errno 10] No child processes` . It was working before.

Thanks in advance!
R

Submit:
`sas`

Log:
`Access Method         = IOM`
`SAS Config name       = iomwin`
`WORK Path             = F:\TEMP\SASApp_DEV\_TD2976_LODZFS121_\Prc2\`
`SAS Version           = 9.04.01M5P09132017`
`SASPy Version         = 2.2.4`
`Teach me SAS          = False`
`Batch                 = False`
`Results               = Pandas`
`SAS Session Encoding  = WLATIN2`
`Python Encoding value = windows-1252`

Submit:
`tabela_model_dochodu = sas.sd2df(table='BIK_ZMIENNE_ALL_TRANS_2', libref='dochod')`

The code returns error:
`...`
`ChildProcessError: [Errno 10] No child processes`

Submit:
`print(sas.saslog())`

Log:

`1                                                              System SAS                                12:42   Saturday, April 7, 2018`

``
`NOTE: Copyright (c) 2016 by SAS   Institute Inc., Cary, NC, USA. `
`NOTE: SAS (r) Proprietary Software 9.4   (TS1M5) `
`        Licensed to XXX., Site XXX.`
`NOTE: This session is executing on the   X64_SRV16  platform.`
``
``
``
`NOTE: Updated analytical products:`
`        `
`        SAS/STAT 14.3`
`        SAS/ETS 14.3`
`        SAS/IML 14.3`
``
`NOTE: Additional host information:`
``
` X64_SRV16 WIN 10.0.14393  Server`
``
`NOTE: Inicjacja SAS-a used (Total   process time):`
`        real time           0.01   seconds`
`        cpu time            0.01   seconds`
`        `
`NOTE: The autoexec file,   F:\SASConfig\DEV\Lev1\SASApp\WorkspaceServer\autoexec.sas, was executed at   server initialization.`
`1          ;*';*";*/;`
`2          options svgtitle='svgtitle';   options validvarname=any pagesize=max nosyntaxcheck; ods graphics on;`
`3`
`4          ;*';*";*/;`
`5          %put   E3969440A681A2408885998500000001;`
`E3969440A681A2408885998500000001`
`6`
`2                                                              System SAS                                12:42   Saturday, April 7, 2018`
``
`7          ods listing close;ods html5   (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg;   ods graphics on /`
`7          !  outputfmt=png;`
`NOTE: Writing HTML5(SASPY_INTERNAL) Body   file: _TOMODS1`
`8          ;*';*";*/;`
`9          libname work list;`
`NOTE: Libref=   WORK `
`        Scope=    IOM ROOT COMP ENV`
`        Engine=   V9`
`        Access=   TEMP`
`        Physical Name= F:\TEMP\SASApp_DEV\_TD2976_LODZFS121_\Prc2`
`        Nazwa pliku= F:\TEMP\SASApp_DEV\_TD2976_LODZFS121_\Prc2`
`        Właściciel= LODZCD\RD5802`
`        Rozmiar pliku=              0KB`
`        Rozmiar pliku (w bajtach)= 0`
`10`
`11         ;*';*";*/;ods html5   (id=saspy_internal) close;ods listing;`
`12`
`13         %put   E3969440A681A2408885998500000002;`
`E3969440A681A2408885998500000002`
`14`
`3                                                              System SAS                                12:42   Saturday, April 7, 2018`
``
`15         ods listing close;ods html5   (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg;   ods graphics on /`
`15         !  outputfmt=png;`
`NOTE: Writing HTML5(SASPY_INTERNAL) Body   file: _TOMODS1`
`16         ;*';*";*/;`
`17         %put SYSV=&sysvlong4;`
`SYSV=9.04.01M5P09132017`
`18`
`19         ;*';*";*/;ods html5   (id=saspy_internal) close;ods listing;`
`20`
`21         %put   E3969440A681A2408885998500000003;`
`E3969440A681A2408885998500000003`
`22`
`4                                                              System SAS                                12:42   Saturday, April 7, 2018`
``
`23         ods listing close;ods html5   (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg;   ods graphics on /`
`23         !  outputfmt=png;`
`NOTE: Writing HTML5(SASPY_INTERNAL) Body   file: _TOMODS1`
`24         ;*';*";*/;`
`25         proc options option=encoding;run;`
``
`      SAS (r) Program chroniony prawem Edycja 9.4  TS1M5`
``
` ENCODING=WLATIN2  Specifies the default character-set   encoding for the SAS session.`
`PROCEDURE\| _DISARM\|         STOP\| _DISARM\|   2018-04-07T12:42:33,896+02:00\| _DISARM\| WorkspaceServer\| _DISARM\| SAS\|   _DISARM\| \| `
`_DISARM\| 26095616\| _DISARM\| 18440192\|   _DISARM\| 10\| _DISARM\| 10\| _DISARM\| 2272\| _DISARM\| 8798198\| _DISARM\| 0.000000\|   _DISARM\| `
`0.000000\| _DISARM\| 1838716953.897000\|   _DISARM\| 1838716953.897000\| _DISARM\| 0.000000\| _DISARM\| \| _ENDDISARM `
`NOTE: PROCEDURE OPTIONS used (Total   process time):`
`        real time           0.00   seconds`
`        cpu time            0.00   seconds`
`        `
``
`26`
`27         ;*';*";*/;ods html5   (id=saspy_internal) close;ods listing;`
`28`
`29         %put   E3969440A681A2408885998500000004;`
`E3969440A681A2408885998500000004`
`30`
`5                                                              System SAS                                12:42   Saturday, April 7, 2018`
``
`31         ;*';*";*/;`
`32         libname dochod    '\\lodzfs121\USERS\DPA\_RD5802'  ;`
`NOTE: Libref DOCHOD was successfully   assigned as follows: `
`        Engine:        V9 `
`        Physical Name: \\lodzfs121\USERS\DPA\_RD5802`
`33`
`34         ;*';*";*/;`
`35         %put   E3969440A681A2408885998500000005;`
`E3969440A681A2408885998500000005`
`36`
`6                                                              System SAS                                12:42   Saturday, April 7, 2018`
``
`37         ;*';*";*/;`
`38         data _null_; e =   exist('dochod.BIK_ZMIENNE_ALL_TRANS_2');`
`39         te='TABLE_EXISTS='; put te e;run;`
``
`TABLE_EXISTS= 1`
`PROCEDURE\| _DISARM\|         STOP\| _DISARM\|   2018-04-07T12:42:47,211+02:00\| _DISARM\| WorkspaceServer\| _DISARM\| SAS\|   _DISARM\| \| `
`_DISARM\| 26357760\| _DISARM\| 16617472\|   _DISARM\| 10\| _DISARM\| 10\| _DISARM\| 2272\| _DISARM\| 8939399\| _DISARM\| 0.000000\|   _DISARM\| `
`0.000000\| _DISARM\| 1838716967.212000\|   _DISARM\| 1838716967.212000\| _DISARM\| 0.000000\| _DISARM\| \| _ENDDISARM `
`NOTE: DATA statement used (Total process   time):`
`        real time           0.00   seconds`
`        cpu time            0.00   seconds`
`        `
``
`40`
`41`
`42         ;*';*";*/;`
`43         %put   E3969440A681A2408885998500000006;`
`E3969440A681A2408885998500000006`
`44`
`7                                                              System SAS                                12:42   Saturday, April 7, 2018`
``
`45         ;*';*";*/;`
`46         proc sql;`
`46         !           create view   sasdata2dataframe as select * from dochod.BIK_ZMIENNE_ALL_TRANS_2;`
`NOTE: SQL view WORK.SASDATA2DATAFRAME   has been defined.`
`46         !                                                                                           quit;`
`PROCEDURE\| _DISARM\|         STOP\| _DISARM\|   2018-04-07T12:42:47,320+02:00\| _DISARM\| WorkspaceServer\| _DISARM\| SAS\|   _DISARM\| \| `
`_DISARM\| 26619904\| _DISARM\| 16617472\|   _DISARM\| 10\| _DISARM\| 10\| _DISARM\| 7392\| _DISARM\| 8947030\| _DISARM\| 0.000000\|   _DISARM\| `
`0.000000\| _DISARM\| 1838716967.321000\|   _DISARM\| 1838716967.321000\| _DISARM\| 0.000000\| _DISARM\| \| _ENDDISARM `
`NOTE: PROCEDURE SQL used (Total process   time):`
`        real time           0.00   seconds`
`        cpu time            0.00   seconds`
`        `
``
`47         data _null_; file LOG; d =   open('sasdata2dataframe');`
`48         length var $256;`
`49         lrecl = attrn(d, 'LRECL'); nvars =   attrn(d, 'NVARS');`
`50         lr='LRECL='; vn='VARNUMS=';   vl='VARLIST='; vt='VARTYPE='; vf='VARFMT=';`
`51         put lr lrecl; put vn nvars; put vl;`
`52         do i = 1 to nvars; var =   compress(varname(d, i), '00'x); put var; end;`
`53         put vt;`
`54         do i = 1 to nvars; var = vartype(d,   i); put var; end;`
`55         run;`
``
`LRECL= 8272`
`VARNUMS= 1028`
`VARLIST=`
`XXX Here is a list of 1028 variables,   removed because of output lengh and confidentiality reasons. XXX`
``
`MVA_DSIO.OPEN_CLOSE\| _DISARM\|         STOP\| _DISARM\|   2018-04-07T12:42:47,352+02:00\| _DISARM\| WorkspaceServer\| _DISARM\| SAS\| `
`_DISARM\| \| _DISARM\| 204539\| _DISARM\|   19861504\| _DISARM\| 10\| _DISARM\| 10\| _DISARM\| 564\| _DISARM\| 9149785\| _DISARM\|   0.031250\| `
`_DISARM\| 0.032000\| _DISARM\|   1838716967.321000\| _DISARM\| 1838716967.353000\| _DISARM\| 0.031250\| _DISARM\| \|   _ENDDISARM `
`MVA_DSIO.OPEN_CLOSE\| _DISARM\|         STOP\| _DISARM\|   2018-04-07T12:42:47,352+02:00\| _DISARM\| WorkspaceServer\| _DISARM\| SAS\| `
`_DISARM\| \| _DISARM\| -1\| _DISARM\|   18452480\| _DISARM\| 10\| _DISARM\| 10\| _DISARM\| 566\| _DISARM\| 9150062\| _DISARM\|   0.015625\| _DISARM\| `
`0.016000\| _DISARM\| 1838716967.337000\|   _DISARM\| 1838716967.353000\| _DISARM\| 0.015625\| _DISARM\| \| _ENDDISARM `
`PROCEDURE\| _DISARM\|         STOP\| _DISARM\|   2018-04-07T12:42:47,352+02:00\| _DISARM\| WorkspaceServer\| _DISARM\| SAS\|   _DISARM\| \| `
`_DISARM\| 26619904\| _DISARM\| 18452480\|   _DISARM\| 10\| _DISARM\| 10\| _DISARM\| 203084\| _DISARM\| 9150353\| _DISARM\|   0.031250\| _DISARM\| `
`0.032000\| _DISARM\| 1838716967.321000\|   _DISARM\| 1838716967.353000\| _DISARM\| 0.031250\| _DISARM\| \| _ENDDISARM `
`NOTE: DATA statement used (Total process   time):`
`        real time           0.03   seconds`
`        cpu time            0.03   seconds`
`        `
``
`56`
`57         ;*';*";*/;`
`58         %put   E3969440A681A2408885998500000008;`
`E3969440A681A2408885998500000008`
`59`
`8                                                              System SAS                                12:42   Saturday, April 7, 2018`
``
`60         ;*';*";*/;`
`61         data _null_; set   dochod.BIK_ZMIENNE_ALL_TRANS_2(obs=1 );put 'FMT_CATS=';`
`XXX Here are 1028 lines as below for   each variable XXX`
`1089       _tom =   vformatn('varieble_name_lk'n);put _tom;`
`1090       run;`
``
`FMT_CATS=`
`XXX List of formats fo all 1028   variables XXX`
`NOTE: There were 1 observations read   from the data set DOCHOD.BIK_ZMIENNE_ALL_TRANS_2.`
`MVA_DSIO.OPEN_CLOSE\| _DISARM\|         STOP\| _DISARM\|   2018-04-07T12:42:48,164+02:00\| _DISARM\| WorkspaceServer\| _DISARM\| SAS\| `
`_DISARM\| \| _DISARM\| 204539\| _DISARM\|   19759104\| _DISARM\| 10\| _DISARM\| 10\| _DISARM\| 66835\| _DISARM\| 9414771\|   _DISARM\| 0.031250\| `
`_DISARM\| 0.031000\| _DISARM\|   1838716968.134000\| _DISARM\| 1838716968.165000\| _DISARM\| 0.031250\| _DISARM\| \|   _ENDDISARM `
`PROCEDURE\| _DISARM\|         STOP\| _DISARM\|   2018-04-07T12:42:48,164+02:00\| _DISARM\| WorkspaceServer\| _DISARM\| SAS\|   _DISARM\| \| `
`_DISARM\| 28454912\| _DISARM\| 19759104\|   _DISARM\| 10\| _DISARM\| 10\| _DISARM\| 264456\| _DISARM\| 9415048\| _DISARM\|   0.031250\| _DISARM\| `
`0.031000\| _DISARM\| 1838716968.134000\|   _DISARM\| 1838716968.165000\| _DISARM\| 0.031250\| _DISARM\| \| _ENDDISARM `
`NOTE: DATA statement used (Total process   time):`
`        real time           0.03   seconds`
`        cpu time            0.03   seconds`
`        `
`1091`
`1092       ;*';*";*/;`
`1093       %put   E3969440A681A2408885998500000009;`
`E3969440A681A2408885998500000009`
`1094`

**Comment by rd5802** [comment]
Hi Tom,
I reqested SAS Workspace Server logs from my administrators. It shows more than saslog. The problem seems to be _TOMODS1 file and it results in breaking the connection.

As I saw earlier in the log the file is defined like that:

`2018-04-09T11:54:34,569 INFO  [00000013] :user@domain - 15         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg; ods graphics on /
2018-04-09T11:54:34,569 INFO  [00000013] :user@domain - 15       !  outputfmt=png;
2018-04-09T11:54:34,631 INFO  [00000013] :user@domain - NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1 `

Is it an output for pandas purposes or some kind of log or results file? It has twice rows as input sas table.
The log follows as below and it results in breaking the connection. 

`2018-04-09T11:54:56,977   INFO  [00000023] :user@domain -   1103       data _null_; set dochod.BIK_ZMIENNE_ALL_TRANS_2;`
`2018-04-09T11:54:56,977 ERROR [00000023]   :user@domain - ERROR: The row has exceeded the maximum length of 32768 bytes.`
`2018-04-09T11:54:56,977 INFO  [00000023] :user@domain - 1105        run;`
`2018-04-09T11:54:56,977 INFO  [00000023] :user@domain - `
`2018-04-09T11:54:56,977 INFO  [00000023] :user@domain - NOTE: The file   _TOMODS1 is:`
`2018-04-09T11:54:56,977 INFO  [00000023] :user@domain -       File   name=F:\TEMP\SASApp_DEV\_TD11068_LODZFS121_\Prc2\_tomods1,`
`2018-04-09T11:54:56,977 INFO  [00000023] :user@domain -       RECFM=V,LRECL=131068,`
`2018-04-09T11:54:56,977 INFO  [00000023] :user@domain -       File size (in bytes)=0,`
`2018-04-09T11:54:56,977 INFO  [00000023] :user@domain -       Last modified=09Apr2018:11:54:56,`
`2018-04-09T11:54:56,977 INFO  [00000023] :user@domain -       Created=09Apr2018:11:54:56`
`2018-04-09T11:54:56,977 INFO  [00000023] :user@domain - `
`2018-04-09T11:55:28,151 INFO  [00000023] :user@domain - NOTE: 409078   records were written to the file _TOMODS1.`
`2018-04-09T11:55:28,151 INFO  [00000023] :user@domain -       The minimum record length was 694.`
`2018-04-09T11:55:28,151 INFO  [00000023] :user@domain -       The maximum record length was 32767.`
`2018-04-09T11:55:28,151 INFO  [00000023] :user@domain - NOTE: The SAS   System stopped processing this step because of errors.`
`2018-04-09T11:55:28,151 INFO  [00000023] :user@domain - NOTE: There were   204539 observations read from the data set DOCHOD.BIK_ZMIENNE_ALL_TRANS_2.`
`2018-04-09T11:55:28,151 INFO  [00000023] :user@domain - NOTE: DATA   statement used (Total process time):`
`2018-04-09T11:55:28,151 INFO  [00000023] :user@domain -       real time           31.19 seconds`
`2018-04-09T11:55:28,151 INFO  [00000023] :user@domain -       cpu time            31.12 seconds`
`2018-04-09T11:55:28,151 INFO  [00000023] :user@domain -       `
`2018-04-09T11:55:28,151 INFO  [00000013] :user@domain - `
`2018-04-09T11:55:28,151 INFO  [00000013] :user@domain - 1106       `
`2018-04-09T11:55:28,151 INFO  [00000013] :user@domain - 11                                                             System SAS                                    11:54 Monday, April 9, 2018`
`2018-04-09T11:55:28,151 INFO  [00000013] :user@domain - `
`2018-04-09T11:55:28,151 INFO  [00000013] :user@domain - 1107       `
`2018-04-09T11:55:28,151 INFO  [00000013] :user@domain - 1108       %put   E3969440A681A2408885998500000008;`
`2018-04-09T11:55:28,151 INFO  [00000013] :user@domain -   E3969440A681A2408885998500000008`
`2018-04-09T11:55:28,151 INFO  [00000013] :user@domain - 1109       `
`2018-04-09T11:55:33,444 DEBUG [00000003]   2:user@domain - IOM LOGIC VOIMapWrcodeToWoiStatus() Mapping error severity   wrcode: 0x80002006`
`2018-04-09T11:55:33,444 DEBUG [00000003]   2:user@domain - IOM LOGIC VOIMapWrcodeToWoiStatus() No wrcode mapping - using   generic error (WOIRAISE): wrcode=0x80002006`
`2018-04-09T11:55:33,788 DEBUG [00001709]   2:user@domain - Peer has disconnected.`
`2018-04-09T11:55:33,788 DEBUG [00001709]   2:user@domain - Bridge PE [2cf7460] Unregistered`
`2018-04-09T11:55:33,788 DEBUG [00001709]   2:user@domain - The peer (2) has disconnected with reconnect enabled.`
`2018-04-09T11:55:33,788 DEBUG [00001709]   2:user@domain - IOM CALL   {compRef:4b8bfe0}->LaunchedServerActivityProxy::ClientDisconnect()`
`2018-04-09T11:55:33,788 DEBUG [00001709]   2:user@domain - IOM RETURN   0={compRef:4b8bfe0}->LaunchedServerActivityProxy::ClientDisconnect()`

**Comment by tomweber-sas** [comment]
@rd5802 Thanks for getting the workspace server log, that does show the problem:
ERROR: The row has exceeded the maximum length of 32768 bytes.
I'll have to investigate this to see where that limit is coming from and see how I can work around it.
But, this might just work with the CSV version of sd2df, and that is significantly faster too, especially for larger data. Try running this and see if it solves this:
```
tabela_model_dochodu = sas.sd2df_CSV(table='BIK_ZMIENNE_ALL_TRANS_2', libref='dochod')
```
Thanks!
Tom

**Comment by rd5802** [comment]
@tomweber-sas Thanks for quick response. I already tried sd2df_CSV and unfortunately the result is the same.

**Comment by tomweber-sas** [comment]
Really? Ok. I'll try to simulate this and see what I can do.
Thanks!
Tom

**Comment by tomweber-sas** [comment]
ok, so it's the filename lrecl limit not the data step. Looks like I can bump that up to 1G from the 32k default it's taking now. I'll verify this on each platform and get a fix to master for you asap.

thanks,
Tom

**Comment by tomweber-sas** [comment]
ok, so it's a good news bad news situation. Yes, both Windows and Linux support LRECL=1G but default to 32K. However, I can't just hard code that, which would just make this all go away. The reason for that is that wx, the I/O subsystem for filename, need to allocate buffer(s) for this file, and if we say a line can be a G then it's trying to allocate at least that, maybe a couple rows worth of buffer. It's not uncommon for MEMSIZE to be set to 1 or 2 G for a workspace server, or any SAS session. When that's the case, the allocation for the buffer will fail and this still won't work. 

This file is used to stream ODS output, data for sd2df, and the CSV ouput for the _CSV version of sd2df. It's allocated up front and reused for the life of the session.

So, what I can do is bump it up to a significantly bigger size, but still within reasonable size as to not run out of memory. The file's deleted and reopened new each time it's used, so the buffers go away and there shouldn't be any real issue. But, having a hard coded value I don't like (kinda have one now at 32k, but ...). So, I can default it to a better size, maybe 1M, but I'll need to add and LRECL key for the IOM access method so this can be tuned and set to whatever anyone ends up needing it to be. 

I see in your workspace server log that your max length for a record in this case may be LRECL=131068.
I'm not positive, but it looks like maybe proc export calculated that. Can't be sure from the log, but it seems plausible.

 I've built a new jar (this file is allocated in the java client). It has 1M hardcoded; to try out. I'll add the option and get it passed through and do this all right, once we verify this works without issue for you.

[saspyiom.zip](https://github.com/sassoftware/saspy/files/1891662/saspyiom.zip)

Can you point your classpath (in your config definition in your sascfg) to this saspyiom.jar instead of the one you are using now (put it wherever you like on your client) and see if this get's your data over to the data frame and runs everything without issue. I'll work on the rest of the fix, but let's be sure this gets you running.

Thanks,
Tom

**Comment by rd5802** [comment]
It Works!!! Great and quick response :) 

MEMSIZE in my case is 3.2GB so the result is as you clearly explained.
I cant see any sign of proc export in the log, system option is LRECL=32767. 

During testing I noticed SASPy is using systems /tmp to store dataframe. /tmp is on a tmpfs file system that uses virtual memory. Is there a way to change it to other dedicated location to isolate temporary SASPy work from systems location?

Regards,
Rafał

**Comment by tomweber-sas** [comment]
Good deal! Yes, I have to write the csv to disk on the saspy side to use the read_csv() which is what makes this method so much faster then building the dataframe in memory. I was just using a temp file so it would be all behind the scenes and be cleaned up, no permission issues, ...
I can add an option to the my CSV method to specify a file to use. Then I need to know if I am creating it, reusing an existing file, deleting it when I'm done? The usual stuff that the temp file kind of eliminates.

I'll create a branch for this, so we can make all of these changes and verify all of it before committing it to master. I'll try to get these changes out there today. Let me know your thoughts on the file you specify (create, delete, reuse...). 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Ok, I've pushed all of these changes to a new branch; sd2df_CSV. The changes are as follows:
1) you can specify LRECL in the configuration definition or on the SASsession()
```
   'lrecl' : 1048576    # this is the new default value I'm now using; 1M

   sas = saspy.SASsession(lrecl=1048576)
```
2) On the _CSV versions of sd2df and aliases:  sd2df_CSV(), sasdata2dataframe_CSV(), sd2df(method='CSV'),  sasdata2dataframe(method='CSV') 
You can specify your own file to use for the temporary CSV file.
```
   df = sd2df_CSV(tempfile='/home/mycvsfile.csv')
```
Current;y I don't try to delete that file, if specified, after using it. We can adjust that as needed.
If not specified, I create a temp file and clean that up after using it (same as I was).

Let me know if you have any questions or issues with any of this. I've still got some more testing to do, trying it all on windows, but I've run through the variations on Linux so far and it looks good.

Thanks,
Tom

**Comment by rd5802** [comment]
Hi Tom !

I have installed and tested saspy from d2df_CSV branch and it seems everything works fine. Amendments you have made are fine, it`s convenient and versatile from my point of view.
An option to delete file, if specified, would be good.

Does tweaking lrecl may give any benefit in performance?

It was a great experience to see how you cope with this issue :)
Should I update saspy after you merge d2df_CSV  it with master?

Regards,
Rafał

**Comment by tomweber-sas** [comment]
I've merged this into master. You should be good to go with what you have, or you can re-pull master and get the latest of all of this. 
Let me know if you have any other issues!

Thanks!
Tom
