### ISSUE TITLE
HTML Output Style Settings

### ISSUE THREAD

**Issue by chrishales709** [sassoftware/saspy#126]
Is it possible to change the HTML output style (ex: HtmlBlue, Journal, etc.)?

**Comment by tomweber-sas** [comment]
It doesn't look like it. I just tried changing it to something other than the default, but it appears the style needs to be specified each time we submit our ODS statement.
So, I can add an option, or a attribute you can set and we can specify that style each time so you can have the output look like you want it too. 

Any preference on how/where to set this? If it's just an attribute of the SASsession object, you can just do this whenever you want to change it for any given output (it will stay what you set it to until you change it again):

```
sas = saspy.SASsession()
cars = sas.sasdata('cars', 'sashelp')
sas.HTML_Style = 'Raven'
cars.head()
cars.tail()
sas.HTML_Style = 'Journel'
cars.means()
...
```

Tom

**Comment by chrishales709** [comment]
I don't have any particular preference. They way you outlined the solution works for me. Thanks!

**Comment by tomweber-sas** [comment]
Hmmm, I thought I posted another comment here saying I added this code to a branch for you to try out; HTML_Style. Must have not hit enter.
Give it a try and see if it works for you. Just like the example above.

Thanks!
Tom

**Comment by chrishales709** [comment]
Sorry for the late response, but yes, everything is working for me. Thanks!

**Comment by tomweber-sas** [comment]
Great, thanks! I'll go ahead and merge this into master. That's a good enhancement, thanks for asking for it!
Tom
