### ISSUE TITLE
Connecting to ORACLE Server

### ISSUE THREAD

**Issue by lyncodes** [sassoftware/saspy#139]
it seems like the current version saspy does not support to connecting to oracle databse server,I highly recommend to add the feature and other databse!!!

**Comment by tomweber-sas** [comment]
Well, saspy won't connect to Oracle, but if you have SAS/Access to Oracle, then you can use saspy to work with data fro Oracle. Just assign a libref in SAS and all the methods should work. From the other issue, it looks like you have SAS/Access licensed. You can assign a libref with the saslib() method, from the SASsession object, or even just use the sumit() method to code it directly:
```
sas.saslib('oralib', 'Oracle', "rest of the connection options")
#or
sas.submit("libname oralib Oracle, rest of the connection options;)

#and then reference an oracle table and use it
oratab1 = sas.sasdata('some_table', 'oralib')
oratab1.head()  #and all the rest of the methods and analytics :)
```

Let me know if you have any trouble with this!
Tom

**Comment by tomweber-sas** [comment]
@lyncodes Were you able to try using SAS/Access engines w/ saspy? 
Thanks,
Tom

**Comment by lyncodes** [comment]
@tomweber-sas 
it works one week ago.but a little bit porblem ocoured when pandas dataframe contains a char that out of range of utf-8 encoding.or we can say that was a illegal encoding(cause my data set contains some Chinese strings),the link between SASpy and localhost will be release unstoppable.
i wish that the program can ignore the encoding mistake.
Thanks.

**Comment by tomweber-sas** [comment]
Well, there are many places where transcoding takes place. python, SAS, IOM, java. If you can provide me with the scenario you're running, I can track it down to see if there's something I can do or not. Even if I it's something I can control, keeping the connection alive, you clearly won't get what you expect if you have embedded character data in the wrong encoding from what these various pieces of code are expecting. UTF-8 supports Chinese data. When encoding are you using instead? 
Thanks,
Tom

**Comment by tomweber-sas** [comment]
@lyncodes I did find an issue with my code regarding transcoding of data. I have fixes for that in a branch called nls2. Not really knowing what your running into with your last post here, I can't say this will fix it. But, it may as it was a bug in my code. Can you try out that branch with your problem case and see if it addresses it? Do you have any other information about the case you're having problems with, so I can try to track it down?
Thanks,
Tom

**Comment by tomweber-sas** [comment]
Any update with trying either 2.2.8 or 2.2.9 with the UTF-8 error? I did find some issues a while back with translated versions of SAS that I hadn't been able to reproduce previously. I don't have enough info to say it would fix what you saw, but it might.
Do you still want this issue open?

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Closing this as no response. If there are further questions on this, just reopen.

Thanks!
Tom
