### ISSUE TITLE
Connect to SAS_Kernel

### ISSUE THREAD

**Issue by chrishales709** [sassoftware/saspy#142]
Is it possible to connect SASPy to an existing sas_kernel instance? It looks like there may be a way according to the documentation, but it sounds like it is for internal use only. Here's what I saw in the documentation under the SASSession object:

"kernel – None - internal use when running the SAS_kernel notebook"

Would it be possible to open that up to external use as well?

**Comment by tomweber-sas** [comment]
That flag is really only for the prompting code. prompting in Jupyter requires different calls than normal python. The sas_kernel uses saspy to connect to SAS. There's not a way to try to have a sas_kernel process share an existing connection with a separate python process, or visa versa.
Do you have a usage case you're trying to accommodate? Or just thinking of it conceptually?

**Comment by chrishales709** [comment]
I'm using the Hydrogen package of the Atom IDE to run SAS queries. I would like to create a Hydrogen add-on to add some additional features, but I don't know JavaScript or any of its variants well enough to do anything with it. So I was using pyqt to build a Python UI that I could launch from within the Atom IDE. This would open up a separate window where I could add additional features (ie. browse the SAS file structure, view tables in a library, etc). The only problem then is that Atom and the Python UI would be using separate SAS connections (Atom through sas_kernel and Python through saspy).

**Comment by tomweber-sas** [comment]
Well, unfortunately, I'm not familiar enough with any of those to provide any useful insight. But, I can explain that the SAS sessions saspy connects to are single user sessions. So there isn't a way to have more then one client connected to them. It would require a multi-user session, like SAS/Share or other server technology. 
Sorry about that,
Tom

**Comment by chrishales709** [comment]
OK, that makes sense. You can go ahead and close this issue.
