### ISSUE TITLE
Saspy installation issue

### ISSUE THREAD

**Issue by OxfordParis** [sassoftware/saspy#143]
![image](https://user-images.githubusercontent.com/40459118/41714802-ce1829a8-7551-11e8-904a-5a6e7fd87fb7.png)

**Comment by tomweber-sas** [comment]
Well, I'm afraid I don't know what any of those things are :(. Oh, but I do see that you seem to be using python 2.7. That is a problem (maybe THE problem,). saspy needs python3. Can you install python3 on there and see if will install with that? I know of a couple people that have run it on a mac book, so it can run there. I don't have one of those, so I've not tried using it on one myself. 
If you have any trouble with it using python3, we can work through that if necessary. 
Thanks!
Tom

**Comment by OxfordParis** [comment]
Hi Tom,

Thank you for your reply.

I indeed also thought that that might be the issue, so I upgraded python prior to posting the question, but ATSAS seems to be defaulting to the 2.7 version. Whenever I install it the python folder is python2.7. Not sure what is going on there.

Thanks,
Stephanie

**Comment by OxfordParis** [comment]
Hi again Tom,

Yes, PyMol is a visualisation program for protein crystal structures and it can run the saspy plugin build into ATSAS (a program to analyse small angle x-ray scattering data) via a plugin manager.
I hope your mates might know some tricks for this.

Thanks,
Stephanie

**Comment by FriedEgg** [comment]
@OxfordParis, this is a utility for SAS (http://SAS.com) not ATSAS.  The two have nothing in common.  I'm afraid you are using the wrong tool for the job.

**Comment by tomweber-sas** [comment]
Thanks @FriedEgg , I just thought those were MAC things I don't know anything about.
@OxfordParis I see where you got derailed. In https://www.embl-hamburg.de/biosaxs/manuals/saspy.html are the instruction for the saspy you're looking for.
Apparen't there's a name collision between their plugin for PyMOL and my python package for SAS.
FriedEgg is right in that this module (saspy) isn't the saspy you're looking for :)
The link above had the instructions for installing the plugin you want. Hopefully those will work for you and you'll be up and running with that saspy.
Sorry I didn't pick up on that to start with. 
Tom

**Comment by OxfordParis** [comment]
Ah, damn. OK, thank you for helping out clarifying this. What a mess I created :)

**Comment by tomweber-sas** [comment]
Ha!, no problem. Glad to get it resolved easily. I don't even have to fix any code :)
Thanks to @FriedEgg for figuring it out so quickly! Good luck with it!
Tom
