### ISSUE TITLE
SAS process has terminated unexpectedly. RC from wait was: 0

### ISSUE THREAD

**Issue by PaalSchau** [sassoftware/saspy#147]
I'm running this code from Jupyter Notebook on my local pc: Windows 10, HP Elitebook 840 G3, 32 GB Ram, System 64bit with Python 3.6.0, Anaconda and SASPy 2.2.6. I have SAS on local PC with SAS 9.4 TS Level 1M4.

import pandas as pd
import saspy
import numpy as np
import matplotlib.pyplot as plt
sas1 = saspy.SASsession(cfgname='winlocal')
sas1.saslib('Mylib', path="C:\\tmp")
dataset_sas=sas1.sasdata('NyTest','mylib')
t=dataset_sas.to_df()

The dataset in “Mylib” contains 40.000 observations and 8 variables and are created by this code in SAS Base:

libname Mylib "C:\tmp";

data Mylib.NyTest ;
 Length t1 t2 t3 8. t4 t5 $100. t6 8.;
 do i=1 to 40000;
 t1=1;
 t2=.;
 t3=3;
 t4='ÆØÅ -678';
 t5='ÆØÅ-678';
 t6=.;
 t7='ÆØÅ- 678 ';
 output;
 end;
run;

The SAS dataset has encoding lik “wlatin1 Western (Windows)” and as you can see it contains some fields with Norwegian special characters “ÆØÅ”.

When I run the code in Python, the process ends with log: “SAS process has terminated unexpectedly. RC from wait was: 0”.

Strangely, if I run the SAS code and replace the "ÆØÅ" with "ABC" or just drop the fields “t6”, “t7” and “i” like this: “data Mylib.NyTest (drop=  t6 t7 i);”) the code in Python/Jupyter Notebook runs successful and without error. Even if I do not drop “t4 “and “t5” which also contains special characters.

**Comment by tomweber-sas** [comment]
@PaalSchau I am able to reproduce this. I believe these three characters are part of the WLATIN1 code page: hex values C6 D8 C5, respectivly? So, this should be valid and work. The failure is happening in the java process reading the binary stream from the SAS process. The error and traceback are:

```
Invalid string.com.sas.iom.SASIOMDefs.GenericError: Invalid string.
	at com.sas.iom.SASIOMDefs.GenericErrorHelper.read(GenericErrorHelper.java:22)
	at com.sas.iom.SASIOMDefs.GenericErrorHelper.extract(GenericErrorHelper.java:47)
	at com.sas.iom.SAS._portable_stub_IBinaryStream.Read(_portable_stub_IBinaryStream.java:95)
	at pyiom.saspy2j.main(saspy2j.java:335)
```

I will track this down further to see what is really causing this, but it will be after the 4th (holiday).
In the mean time, you can use the _CSV version to retrieve the data into a dataframe. It's even faster for larger data too. I've run that with this case and it doesn't exhibit this problem. They are two completely different methods.
```
t=dataset_sas.to_df_CSV()
```
Thanks!
Tom

**Comment by PaalSchau** [comment]
Thanks Tom and have a nice vacation,
Yes, the hex values is "C5", "C6", "D8" and "E5", "E6", "F8"

In addition to CSV, it seems that this also works:

```
t=pd.read_sas('C:\\tmp\\nytest.sas7bdat', \
              format = 'sas7bdat', encoding="latin1")
```

**Comment by tomweber-sas** [comment]
@PaalSchau I believe I've fixed this, finally! I have a new branch called 'nls2'. Can you try that out and see if it works for all cases? It is for me with your test case and a bunch of other cases I've been testing out.
Thanks!
Tom

**Comment by PaalSchau** [comment]
Thanks Tom, I will be able to check this next week when I'm back from vacation // Pål

**Comment by tomweber-sas** [comment]
Cool, thanks! Enjoy your vacation!

**Comment by PaalSchau** [comment]
Hi Tom and thangs for good guidance and help. I have now successfully installed the nls2 version and tested it on several cases. Everything seems to work fine and I’m not receiving any error/termination.
Thank you once again // Paal

**Comment by tomweber-sas** [comment]
@PaalSchau that's great. Thanks for verifying this for me on your system. Even though I can see it work here, it's good to be sure you see the same :)  I'm hoping to hear back on a couple other issues to see if this addresses them as well, but I believe I'll be merging this in before long and then building a new 2.2.7 package with it in there.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
I've merged this in to master, so I'll close out this issue.
Let me know if you have any other issue!
Tom
