### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by Rhadadi** [sassoftware/saspy#148]
My machine's SAS was upgrade to M5 and after that I receive the Java error below:

![image](https://user-images.githubusercontent.com/11033482/42648937-4059f322-85d6-11e8-8b58-f7a88f7bd176.jpeg)

![image](https://user-images.githubusercontent.com/11033482/42649206-0153bce8-85d7-11e8-9d7f-8e9efb541f36.jpeg)

**Comment by tomweber-sas** [comment]
@Rhadadi It seems odd to me the error would be that it can't find saspy2y jar, as it appears to be in your python path, which shouldn't be affected by upgrading SAS. But, check the pahts to the rest of the jars that are in your SASHome path, as the 'deploywiz__94472__prt__xx__sp0__1' part varies from install to install.
That's the most likely thing to have changed. It may be that the error is because those dependencies aren't found, as opposed to saspy2j.jar itself.

**Comment by Rhadadi** [comment]
@tomweber-sas 
Thanks for the quick response. 
I fixed the folder name in cpW , but I still have the same problem:

Java Error:
Error: Could not find or load main class pyiom.saspy2j


Subprocess failed to start. Double check you settings in sascfg.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94494__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94494__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94494__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94494__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil_904300.0.0.20150204190000_v940m3\\sas.rutil.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil.nls_904300.0.0.20150204190000_v940m3\\sas.rutil.nls.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sastpj.rutil_6.1.0.0_SAS_20121211183517\\sastpj.rutil.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '55090', '-stdoutport', '55091', '-stderrport', '55092', '-zero', '-lrecl', '1048576', '']

If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
java -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94494__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94494__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94494__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94494__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\ProgramData\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar;C:\Program Files\SASHome\SASVersionedJarRepository\eclipse\plugins\sas.rutil_904300.0.0.20150204190000_v940m3\sas.rutil.jar;C:\Program Files\SASHome\SASVersionedJarRepository\eclipse\plugins\sas.rutil.nls_904300.0.0.20150204190000_v940m3\sas.rutil.nls.jar;C:\Program Files\SASHome\SASVersionedJarRepository\eclipse\plugins\sastpj.rutil_6.1.0.0_SAS_20121211183517\sastpj.rutil.jar" pyiom.saspy2j -host localhost -stdinport 55090 -stdoutport 55091 -stderrport 55092 -zero -lrecl 1048576  

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.

**Comment by tomweber-sas** [comment]
@Rhadadi Can you run the java command manually and see if there's more info for the error? Sometimes running it in the command line produces a traceback or more info. Not always, but sometimes.
One other question, you have the encryption jars in your classpath. Is your local SAS running that way?
I'm assuming this was all working before upgrading SAS too?
Thanks,
Tom

**Comment by LightnerAndrew** [comment]
@tomweber-sas I have the same issue with configuring saspy on my work windows laptop. 

sascfg.py specification: 
```
# build out a local classpath variable to use below for Windows clients
cpW  =  'C://Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94490__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar'
cpW += ";C://Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94490__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";C://Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94490__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";C://Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94490__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cpW += ";'C://Users\\alightner\\AppData\\Local\\Continuum\\anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar"

winlocal = {'java'      : 'java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW
            }
```


### Returns: 
``` 
Java Error:
Error: Could not find or load main class pyiom.saspy2j


Subprocess failed to start. Double check you settings in sascfg.py file.

Attempted to run program java with the following parameters:['java', '-classpath', "C://Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94490__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C://Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94490__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C://Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94490__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C://Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94490__prt__xx__sp0__1\\deploywiz\\sas.core.jar;'C://Users\\alightner\\AppData\\Local\\Continuum\\anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar", 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '61849', '-stdoutport', '61850', '-stderrport', '61851', '-zero', '-lrecl', '1048576', '']

If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
java -classpath "C://Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94490__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C://Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94490__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C://Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94490__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C://Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94490__prt__xx__sp0__1\deploywiz\sas.core.jar;'C://Users\alightner\AppData\Local\Continuum\anaconda3\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 61849 -stdoutport 61850 -stderrport 61851 -zero -lrecl 1048576  

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
```

If I run the java code directly, it returns: 
```
048576
Error: Could not find or load main class pyiom.saspy2j
```


### Adding Javaparms: 

Adding the "javaparms": ["--add-modules=java.corba"] returns the following response: 

```
Unrecognized option: --add-modules=java.corba
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

The documentation does not appear to have any next steps for this problem. 


Any ideas on the next steps?


Thank you for your time and effort.

**Comment by tomweber-sas** [comment]
@LightnerAndrew , it looks like your slashes are going the wrong direction:
```
c:/bla\bla
```
So the classpath is bad.

**Comment by tomweber-sas** [comment]
Sorry for being terse, was in the middle of something, but wanted to get that to you asap. 
It's the C:// that should be C:\\ in the class paths. 

Out of curiosity, if you cut n paster that whole java command and run it from a shell, do you get a better traceback or more error information? I can't remember off hand what case it was, but there was a case where running the command in a shell (DOS or PS), produced more diagnostics that made it more clear.
Wondering if this is one of those cases.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Ok, that's the error you get when you don't have the path to the sspiauth.dll file in your system PATH variable.
See this doc about that: https://sassoftware.github.io/saspy/install.html#local
Running the java command for that error shows what would be expected - a socket error. That validates your classpath at least. 
After putting the path to that .dll into your system path, you will have to restart whatever python to get it to pick up that change. I've even sometimes needed to reboot windows to get it all working.
However, I've also see this work, which is easier. In python before you import saspy and try to create a session, you can update your path variable via python (be sure it's really your path on your system):
```
import os
os.environ["PATH"] += ';'+r'C:\Program Files\SASHome\SASFoundation\9.4\core\sasext'

import saspy
sas = saspy.SASsession()
```

Tom

**Comment by LightnerAndrew** [comment]
All working well.  Thank for the help!

**Comment by tomweber-sas** [comment]
Great @LightnerAndrew ! Glad to help!

**Comment by Rhadadi** [comment]
@tomweber-sas Thanks,  it is resolved. We needed to reinstall the java.

**Comment by tomweber-sas** [comment]
@Rhadadi Good deal. That makes more sense too! 
Thanks!
Tom

**Comment by eweisbrod** [comment]
> Ok, that's the error you get when you don't have the path to the sspiauth.dll file in your system PATH variable.
> See this doc about that: https://sassoftware.github.io/saspy/install.html#local
> Running the java command for that error shows what would be expected - a socket error. That validates your classpath at least.
> After putting the path to that .dll into your system path, you will have to restart whatever python to get it to pick up that change. I've even sometimes needed to reboot windows to get it all working.
> However, I've also see this work, which is easier. In python before you import saspy and try to create a session, you can update your path variable via python (be sure it's really your path on your system):
> 
> ```
> import os
> os.environ["PATH"] += ';'+r'C:\Program Files\SASHome\SASFoundation\9.4\core\sasext'
> 
> import saspy
> sas = saspy.SASsession()
> ```
> Tom

Hi I tried to do the autoconfig, and I got the error for the sspiauth. But I think the autoconfig should have added the path for me?  It just seems to have a slight typo/difference from what you put in this post?

your version works:
import os
os.environ["PATH"] += ';'+r'C:\Program Files\SASHome\SASFoundation\9.4\core\sasext'
the version the autoconfig makes does not:
import os
os.environ["PATH"] += ";C:\\Program Files\\SASHome\\SASFoundation\\9.4\\core\\sasext\\sspiauth.dll"

**Comment by tomweber-sas** [comment]
@eweisbrod , thanks, you're right. The autocfg has the sspiauth.dll specified, which it shouldn't; should just be the directory it's in. I wonder if when I was testing that out before merging it in, if I didn't remove the path from my system PATH, such that I didn't see the problem. Can't remember now. But I'll remove that so the path is correct. I do know it works when it's the correct path. I had put that together a long time ago and know that I did remove that from my PATH to be sure it works just adding it to the environment in the config file. But, it got reworked and enhanced and I didn't see that the file name had been added to the path. 

If you remove '\sspiauth.dll' from what the autocfg generates, does it work? Is there any other issue beyond that? is should just be 
os.environ["PATH"] += ";C:\Program Files\SASHome\SASFoundation\9.4\core\sasext'

Thanks,
Tom

**Comment by eweisbrod** [comment]
Once I edited the config file to use your example from this thread to set the path then everything works. I do have the ';'+r' at the beginning following your example. I haven’t tried it without that. Not sure if that part is important or not.

**Comment by tomweber-sas** [comment]
Thanks, I appreciate you verifying that for me. On windows, you either have to use double backslashes '\\' or the 'raw' string specification r'\' to keep from having strings that have file system paths get messed up due to the escape sequences (any string of course, but file system paths are the issue here).
For instance, 't' gets converted to a Tab character instead of staying backslash-t. So you either use r'\...\' or '\\...\\' to avoid the escape sequence conversions.

I have removed that path from my system environment variable so I don't have it in there anymore, and only have this in my config file from now on, so I have verified it's working as it should again too.

I've pushed this to master, and cleaned up the autocfg notebook in the saspy-examples so it looks correct too.

Thanks for reporting this!
Tom

**Comment by tomweber-sas** [comment]
Ha, the double backslashes resolved to single in here. Let's try this:


Thanks, I appreciate you verifying that for me. On windows, you either have to use double backslashes '\\\\' or the 'raw' string specification r'\\' to keep from having strings that have file system paths get messed up due to the escape sequences (any string of course, but file system paths are the issue here).
For instance, 't' gets converted to a Tab character instead of staying backslash-t. So you either use r'\\...\\' or '\\\\...\\\\' to avoid the escape sequence conversions.
