### ISSUE TITLE
sas._endsas() not terminating process on the Workspace server

### ISSUE THREAD

**Issue by jc639** [sassoftware/saspy#150]
Hi, I think this may be similar to issue #137,  I have been using saspy at work to connect to a Workspace server by the IOM connection method. Recently, the server admin let me know that I had lots of orphan processes hanging around on the server, so I started using sas._endsas() explicitly to terminate my sessions.

However we have had the same conversation, attached is screenshot the processes I had left open on the server. 

![sas_server](https://user-images.githubusercontent.com/28015710/43203176-5c3ac60e-9015-11e8-8796-b3ac155672c9.jpg)

We did a quick test after all these were killed, whereby I opened a new connection through saspy and then ended it with ._endsas(). Whilst in the spyder console it was reported as terminated, and the subprocess IDs matched between connection and termination, it didn't terminate on the server.

**Comment by tomweber-sas** [comment]
Hmm, ok. What version of saspy are you running?  Are these workspace servers part of SAS/Grid, or not? Do you know if they are configured for reconnecting, in OMR (metadata)? You can verify that by just submitting the sas.disconnect() method. The output from it will identify the situation.
So, regardless of if you submit _endsas() or not (when python shuts down, I do _endsas() myself), they processes are not going away? 
On your client side, are the java processes going away? I'm assuming you're connecting to remote workspace servers?

Thanks,
Tom

**Comment by jc639** [comment]
Hi Tom (wow, speedy reply!),

Yes that is correct, ._endsas() and shutting down python doesn't seem to terminate the processes. 

Running version 2.2.4, and that is correct, it is a remote IOM server running on Windows. I have just tried sas.disconnect() and get the 'successfully disconnected' message.  The java processes disappear locally when ._endsas() is used. 

I am just trying to repeat this behavior on the dev server, so will let you know how that goes.

Cheers,
Jack

**Comment by jc639** [comment]
Same thing happens on the dev server. Created a session and ended it with ._endsas(), five times in a row. Closed spyder, closed Anaconda prompt. 5 processes remain on the Dev server.

**Comment by tomweber-sas** [comment]
Ah, well that's perfect. I implemented the reconnect feature in 2.2.4, but stupidly forgot about when you are actually trying to disconnect for good :)
The fix for this is in 2.2.5 (and there's a 2.2.6 also).  If you can upgrade to either of those, this should be fixed. 2.2.5 happened to require python 3.5 or higher, so if you're not at that version yet, use 2.2.6.
If you can try out either of those and see that they fix those for you, that's be great. they should.

Thanks!
Tom

**Comment by jc639** [comment]
Success! Apologies, I have just read the release versions page now and I can see that listed as a fix. Thanks for your help and your awesome work on saspy. I was getting a bit worried I would have to quit my job without it :)

**Comment by tomweber-sas** [comment]
Well, we can't have that! LOL
I'm glad I already had the fix for that; those are the best kind of issues :)
And I'm glad you like it. Let me know if you need anything else!
Tom
