### ISSUE TITLE
Cannot get access to SAS from Jupyternotebook! Help!

### ISSUE THREAD

**Issue by cheer117** [sassoftware/saspy#159]
Hi Sir or Madam,

I am trying to connect Jupyter notebook with SAS (on my PC, windows 10). But I fail. Attached is the error reported by Jupyter Notebook. Report is suggesting something wrong with JAVA, about which i have not idea.
![capture1](https://user-images.githubusercontent.com/10582938/44312216-9d217a80-a3c2-11e8-8d72-4321cd16614e.PNG)

I guess there might be something wrong with the setting in the SASCFG.py file. Please see attached:
![capture3](https://user-images.githubusercontent.com/10582938/44312253-49636100-a3c3-11e8-8e78-67c438edd4fb.PNG)

I check nothing wrong with my SAS (My sas version is 9.4). I run the same command in SAS. It works.
![capture2](https://user-images.githubusercontent.com/10582938/44312233-ebcf1480-a3c2-11e8-8c81-cb37d92bf3fc.PNG)

BTW, I am using Python3, but not in the Annocando environment. Because i use python3 first and then use Jupyter notebook. So what i did is directly installing Jupyter notebook without Annocando (it works when it comes to Python). So I guess Annocando may not be a the issue here.

Thank you for you time!

Best,
Cheer117

**Comment by tomweber-sas** [comment]
Hey, this should be easy :) The error is
```
The native implementation module for the security package could not be found in the path.
```
This IOM error is due to not having the spiauth.dll in the system path. Check out this link for the instructions for doing that. 
https://sassoftware.github.io/saspy/install.html#local

After adding that path (verify your path is correct where you have SAS installed), you will have to restart the juptyer process so that it picks it up. 

Let me know if you have any trouble with this or if it doesn't solve this.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
@cheer117 , that looks like the right directory to specify. But it needs to be specified in the PATH variable, not in a SAS variable. scroll up a little and look at the PATH variable. It probably already has a number of directories concatenated together. Add this directory to that variable and then restart jupyter after saving the change to PATH. That should get you past this error.
Tom

**Comment by cheer117** [comment]
It works!
Thanks so much! I didn't realize I made that stupid mistakes! Thanks a lot!

Best,
Cheer117

**Comment by tomweber-sas** [comment]
That's great! Glad that was all it was. I'll close this out. Just let me know if there's anything else!
Thanks,
Tom
