### ISSUE TITLE
SASdata.contents() uncovers an error

### ISSUE THREAD

**Issue by mikemckiernan** [sassoftware/saspy#16]
This sequence generates an error and points a finger at sasiostdio.py:sasdata2dataframe. I'm using 2.1.1.

```
import saspy
sasconn = saspy.SASsession() # this was with the 4th mtce release of SAS 9.4 
sasconn.read_csv('http://support.sas.com/documentation/onlinedoc/viya/exampledatasets/baseball.csv')
baseball_ds.contents()
```

**Comment by tomweber-sas** [comment]
Tracked that down to the way contents works w/ pandas being returned, failed when the sorted by table wasn't created, which happens for tables that weren't sorted. checked for the existence of that table before trying to add it into the results.
