### ISSUE TITLE
trying to connect to remote sas server via IOM, get Java Error  Could not find or load main class pyiom.saspy2j

### ISSUE THREAD

**Issue by Tullsokk** [sassoftware/saspy#162]
I am trying to connect a remote sas server. I have added winiomwin to the SAS_config_names. I do not have a local sas base installation, but the .jar files can be found under C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\, which I have added to the cpW variable. I have also added the path variable to global enviromental path variables.

if i run the following in a python terminal:
`sas=saspy.SASsession(cfgname='winiomwin')`

I get a prompt for 
> Please enter the IOM user id:

whatever I enter, I get the following error (no further prompt for password): 

> Java Error:
 Error: Could not find or load main class pyiom.saspy2j
 Subprocess failed to start. Double check you settings in sascfg.py file.
 Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;
C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\log4j.jar;
C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;
C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\\products\\deploywiz__94485__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar',
 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '52319', '-stdoutport', '52320', '-stderrport', '52321', '-iomhost', 'windows.iom.host', '-iomport', '8591', '-user', 'asdf', '-lrecl', '1048576', '']

**Comment by tomweber-sas** [comment]
@Tullsokk That error,
```
Java Error:
Error: Could not find or load main class pyiom.saspy2j
```
is pretty specific about not being able to get at that jar, based upon the classpath. First, let's verify that path: C:\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar
and also the permissions on it; could be a permission problem as opposed to the path not being correct, I suppose.
Can you elaborate on the other jars too? You said you don't have SAS installed, but those jars are there in what looks like a install location for SAS. You don't have to have SAS installed; you can get those jars from a different deployment and just copy the jars to your system so they can be found. So that's ok if that's where they came from. But then I would expect something more like 'C:\saspyjars\*.jar'. So, just checking on those too, since we're at a java classpath, jar problem at the moment.

Thanks,
Tom

**Comment by Tullsokk** [comment]
Thank you for the reply! 

I dont have SAS BASE, as in a program that can execute sas code on my local machine. I do har some other SAS software installed though, and do have the .jar files in those folders. These programs execute code on a SAS server, not on my local PC. 

I have confirmed the filepath of the syspyiom.jar file. I seem to have permission to read and run the file. 

I have tried different ways of writing the paths. using r"..\..\", doubles \\, /, and confirmed that I can  read a file with a similar path using double forward slash ("C://Anaconda//Lib//site-packages//saspy//java//test.txt"). Is there a way to test your permission hypothesis? Is there a simple code I can try to run from console, something like
 `java -cs "C://Anaconda//Lib//site-packages//saspy//java//saspyiom.jar"`
just to find out why it wont get to the jar?

**Comment by Tullsokk** [comment]
I inadvertently closed the issue when responding. Reopened it

**Comment by tomweber-sas** [comment]
Yes, usually following the error you have there will be another message telling you to try running the java command from a cmd prompt to see if you get more messages (sometimes you do). And there will be a formatted version that you can cut-n-paste. I don't see that part in what you posted. But here's the line given your error above:
```
java -classpath "C:\Program Files\SASHome94\SASDeploymentManager\9.4\products\deploywiz__94485__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome94\SASDeploymentManager\9.4\products\deploywiz__94485__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome94\SASDeploymentManager\9.4\products\deploywiz__94485__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome94\SASDeploymentManager\9.4\products\deploywiz__94485__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar” pyiom.saspy2j -host localhost -stdinport 52319 -stdoutport  52320 -stderrport 52321 -iomhost windows.iom.host -iomport 8591 -user asdf -lrecl 1048576
```
give that a try and see what you get.

**Comment by tomweber-sas** [comment]
Hey, those are my favorite problems :) Super easy to fix once you realize them!
I'm glad you're up and running. Let me know if there's anything else!
Tom
