### ISSUE TITLE
Not able to connect to Linux IOM server

### ISSUE THREAD

**Issue by torhhu** [sassoftware/saspy#164]
Hi,

I hope this is just a simple error/misconfiguration on my side. I'm trying to connect from a Linux client to our SAS server running on Linux. Using proc iomoperate I've found the following information:
`25           list DEFINED FILTER="Object";

Foundation repository (A0000001.A5DSS9ZI)

    Object Spawner - xyzsasapp1p (A5DSS9ZI.AZ000003)
        Server class : IOM Spawner
        Spawnable server component : Operating System Services - xyzsasapp1p
        Spawnable server component : SASApp - Pooled Workspace Server
        Spawnable server component : SASApp - Stored Process Server
        Spawnable server component : SASApp - Workspace Server
        Spawnable server component : SASOther - Workspace Server
        Operator port : 8581
        PortBank port : 8801
        PortBank port : 8811
        PortBank port : 8821
        Machine name : xyzsasapp1p.internal.ompany.com
`
and
`25           list DEFINED FILTER="- Workspace";

Foundation repository (A0000001.A5DSS9ZI)

    SASApp - Workspace Server (A5DSS9ZI.AZ00000A)
        Server class : 440196D4-90F0-11D0-9F41-00A024BB830C
        Logical name : SASApp - Logical Workspace Server
        Server context : SASApp
        Bridge port : 8591
        Machine name : xyzsasapp1p.internal.company.com

    SASOther - Workspace Server (A5DSS9ZI.AZ00000L)
        Server class : 440196D4-90F0-11D0-9F41-00A024BB830C
        Logical name : SASOther - Logical Workspace Server
        Server context : SASOther
        Bridge port : 8591
        Machine name : xyzsasapp1p.internal.company.com
`

In sascfg.py I've configured this:
`SAS_config_names=['iomlinux']
....
# build out a local classpath variable to use below for Linux clients
cpL  = "/home/user/SAS_jar/sas.svc.connection.jar"
cpL += ":/home/user/SAS_jar/log4j.jar"
cpL += ":/home/user/SAS_jar/sas.security.sspi.jar"
cpL += ":/home/user/SAS_jar/sas.core.jar"
cpL += ":/home/user/anaconda3/lib/python3.6/site-packages/
saspy/java/saspyiom.jar"

iomlinux = {'java'      : '/usr/bin/java',
            'iomhost'   : 'xyzsasapp1p..internal.company.com',
            'iomport'   : 8591,
            'encoding'  : 'latin1',
            'classpath' : cpL,
            'appserver' : 'SASOther - Workspace Server'
            }
`
Running this in Jupyter will result in this error:

`Please enter the IOM user id: user
Please enter the password for IOM user : ·················

SAS process has terminated unexpectedly. 
Pid State= (5279, 256)
SAS Connection failed. 
No connection established. 
Double check you settings in sascfg.py file.

Attempted to run program /usr/bin/java with the following parameters:['/usr/bin/java', '-classpath', '/home/user/SAS_jar/sas.svc.connection.jar:/home/user/SAS_jar/log4j.jar:/home/user/SAS_jar/sas.security.sspi.jar:/home/user/SAS_jar/sas.core.jar:/home/user/anaconda3/lib/python3.6/site-packages/
saspy/java/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '57800', '-stdoutport', '58715', '-stderrport', '46641', '-appname', "'SASOther - Workspace Server'", '-iomhost', 'xyzsasapp1p.internal.company.com', '-iomport', '8591', '-user', 'user', '-lrecl', '1048576', '']
`

I've also tried running the java command from a windows client (using winiomlinux config), and the output from that is:
`java -classpath "C:\Software\SAS_jar\sas.svc.connection.jar;C:\Software\SAS_jar\log4j.jar;C:\Software\SAS_jar\sas.security.sspi.jar;C:\Software\SAS_jar\sas.core.jar;C:\Anaconda\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 63822 -stdoutport 63823 -stderrport 63824 -appserver "SASOther - Workspace Server" -iomhost xyzsasapp1p.internal.company.com -iomport 8561 -user user-lrecl 1048576
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at pyiom.saspy2j.main(saspy2j.java:162)
Exception in thread "main" java.lang.NullPointerException
        at pyiom.saspy2j.main(saspy2j.java:171)`

I normally log on using SAS EG with username and password. Any ideas to what I might be doing wrong?

**Comment by tomweber-sas** [comment]
Well, a couple things seem a little strange to me. First, I don't think you can have 2 different workspace servers configured for the same port on the same machine. The second is that I don't see an IOM Error Message in the output. If the connection fails, there's usually some IOM message that would give us an idea of what the problem was.
The error you got running the java command directly looks right. It shows java ran, the saspyiom.jar was found, and it got an error trying to connect back to saspy; because saspy wasn't running. Did you try running saspy on windows? Did it provide any error?

The other thought is about your jars (the 4 sas jars). Are they from a real SAS install (SASFoundation, Base SAS)? Or are they from a client only install; EG? I have seen a few cases where jars from a client only install don't seem to work. I don't see an error indicating that, but I don't see any error as to why it's not connecting.

What version of saspy is this? Did you try connecting to the other workspace server?   

Thanks,
Tom

**Comment by torhhu** [comment]
Update: it's now working :)
I received the 4 jar files from what I believe was a local Windows installation. Replaced them with files from our linux server, and now it just works.

Thank you for the very fast response,
Tor Helge

**Comment by tomweber-sas** [comment]
Hey, that's great. Thanks!
The jars are compatible between windows and linux, but not necessarily between a client only install and a full SAS install. 
Glad you're up and running!
Thanks,
Tom
