### ISSUE TITLE
saspy hangs after creating a SASsession in winiomlinux

### ISSUE THREAD

**Issue by kjnh10** [sassoftware/saspy#166]
@tomweber-sas 
I think my situation is somewhiat related to #78, but made this issue to start fresh with my problem.

My code hangs after SASsession() like below.
![image](https://user-images.githubusercontent.com/6933428/44965932-4d6eb180-af73-11e8-9b3b-c14ff4e8aed9.png)

My client is on windows7, and my sas server is on linux.

```sascfg_personal.py
SAS_config_names = ['winiomlinux']
SAS_config_options = {'lock_down': False,
                      'verbose'  : True
                     }
SAS_output_options = {'output' : 'html5'}
cpW  =  "D:\\Profiles\\watkoji\\Desktop\\SAS Software Depot\\products\\deploywiz__94460__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";D:\\Profiles\\watkoji\\Desktop\\SAS Software Depot\\products\\deploywiz__94460__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cpW += ";D:\\Profiles\\watkoji\\Desktop\\SAS Software Depot\\products\\deploywiz__94460__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";D:\\Profiles\\watkoji\\Desktop\\SAS Software Depot\\products\\deploywiz__94460__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar"

winiomlinux = {
            'java'      : 'C:\\Program Files\\Java\\jre1.8.0_161\\bin\\java.exe',
            'iomhost'   : '##########.com',  # masked for my comapny security policy
            'iomport'   : 8592,
            'encoding'  : 'utf8',
            'classpath' : cpW
            }

```

Best regards,

**Comment by tomweber-sas** [comment]
@kjnh10 Thanks. I'm curious about somehitng in this info you've showed me. In the notebook, the result for saspy.SAScfg shows your sascfg_personal.py in D:... but the claspath for the saspyiom.jar is in C:...
Is that true, or an edit when getting this info and pasting it here? Is it possible to be mixing 2 different installs?
So this just hangs, and you never get an error? Can you see the python process and it's Java subprocess in task manager, or process explorrer? If so, can you kill the Java process and see what error you get in python?

I'm also a little curious why the path for sascfg_personal shows up w/ what would appear to be double backslashes '\\' as other characters. Is python running in something other than utf8? Any reason why it would be displaying like that?
 
Thanks,
Tom

**Comment by kjnh10** [comment]
Also I was able to read a local csv.

![image](https://user-images.githubusercontent.com/6933428/45069322-e8e45b80-b106-11e8-8f2e-852010fb1ed4.png)

Thanks a lot!

**Comment by tomweber-sas** [comment]
Hey, good deal.! :)
yes, the read_csv() method is for on the SAS server side, so the path would have to be something it can acccess. Pulling in a local file and moving it to the remote SAS to then process, like you did, is perfect. 
That's a funny read about the backslash/yen. So, I see that's to be expected :)

Looks like you're good to go?

Thanks!
Tom

**Comment by kjnh10** [comment]
@tomweber-sas 
Yeah, thanks for your support and this nice module!

Thanks,
