### ISSUE TITLE
saspy.SASdata.to_df Method is still too Slow

### ISSUE THREAD

**Issue by okaradeli** [sassoftware/saspy#167]
The issue on
https://github.com/sassoftware/saspy/issues/65
Still alive.

sas_dataframe.to_df() method is still too slow when DF has more then 30K entries.

None of the workarounds based are working : i.e. to_df_CSV, to_df ( method='CSV') or NamedTemporaryFile due to unsuccesful creation of empty temporary local file ( Windows ) and such. 

Platform: Windows
saspy version: 2.2.6

Please advice. 
Thank you

**Comment by tomweber-sas** [comment]
@okaradeli ok. Can you give me some information on what isn't working with the CSV version? What are you submitting, what are you getting? How are you running; Local or Remote? Can you submit your SASsession object and show me the results? 
```
import saspy
sas = saspy.SASsession()
sas
```

Thanks,
Tom

**Comment by okaradeli** [comment]
Hello sorry for the late response.

```
import saspy
sas = saspy.SASsession(cfgname='winiomwin')
df_sas = sas.sasdata("mygoodoldtable","mygoodoldlibrary")

df = df_sas.to_df(method="CSV")
```
and It gives the following error:
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ONUR~1.KAR\\AppData\\Local\\Temp\\tmp2d4f3335\\tomodsx'

If I use the new 
`df = df_sas.to_df_CSV(tempfile="c://tmp//sastmp.csv",tempkeep=True)`
It does not raise an exception but the CSV file created is empty !

I also tried giving all admin permissions and used "Run as Administrator" with PyCharm.

**Comment by okaradeli** [comment]
Ok Tom I resolved the issue after divide and conquer numereous times and extensive forum research.

It appears the .to_df_CSV is failing due to some UNICODE char set in the SAS datatable in the half way after 30 minutes.  with the error:  
`"SAS process has terminated unexpectedly. RC from wait was: 0" `
I removed that column and to_df_CSV completes in a few mins.

Now my question evolves to the following. How to easily review the detailed error returning from SAS ? 

BR 
Onur

**Comment by tomweber-sas** [comment]
@okaradeli Did you have a chance to try a more recent version? I found a couple issues w/ translated version of SAS that I hadn't been able to reproduce previously. 2.2.8, 2.2.9 have these fixes.

Do you still want to keep this issue open?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Ok, good deal. I'll close this. Let me know if there's anything else!

Thanks,
Tom
