### ISSUE TITLE
Kerberos Keytab authentication possibility?

### ISSUE THREAD

**Issue by srinicreddy** [sassoftware/saspy#169]
While setting up remote SAS invoke (both source/target servers are Linux) - STDIO SSH - frowned upon by enterprise security as an exposure risk to publish SSH keys, hamper enforcement of MFA tokens etc.

Security analysts suggest use Kerberos key tabs, TGTs which are safer than SSH keys.

Can this be enabled as additional authentication mechanism?

**Comment by tomweber-sas** [comment]
@srinicreddy Well, I googled this a bit and it appears that SSH can use Kerberos for its Authentication and Authorization; maybe specific versions or higher, don't know about that. 
saspy STDIO over SSH states it needs passwordless ssh keys, as that was pretty much standard way of doing ssh's AA without prompting or passwords or any of that. It seems that the TGT is comparable to the pwless keys, in that regard. saspy doesn't do anything special (it doesn't know about the keys at all), when trying to connect over ssh. So if you have Kerberos set up for ssh, such that 'ssh host' just works, then saspy over ssh should probably just work already.
If there is an extra flag or something that needs to be specified on the ssh command to make it use the TGT's, then I could certainly add that into the STDIO access method. 

So, from the few minutes of looking at this, I think it looks very possible. Do you have Kerberos set up to work w/ ssh? I do not, so if you do and want to try this out, I'm happy to help try to get it working.

Tom

**Comment by srinicreddy** [comment]
@tomweber-sas Thanks for quick response... I was OOO yesterday, will get some setup going and try this out soon. BTW, in order to use IOM, is it essential to have SAS Grid? We are trying to connect to SAS object spawners, the session just keeps hanging. Wanted to check requirement before dwelling too deep in to troubleshooting.

**Comment by tomweber-sas** [comment]
@srinicreddy Cool, I'm curious to see if this 'just works' with Kerberos. As for IOM, no you don't have to have Grid.
Any Workspace server, via an Object Spawner will work. Also, for a local SAS install on the same machine as python (saspy) you can use IOM. That case doesn't need obj spawn or any of that; it just connects to the local SAS as if it were the whole setup (obj spawn, metadata, workspace server...).

As for the hang, can you provide some more details? What's your configuration definition? I assume it's remote? Windows/Linux? How are you running, what version of python / SAS / saspy? ...

Thanks!
Tom

**Comment by srinicreddy** [comment]
@tomweber-sas 

Here is error I am getting
Please enter the name of the SAS Config you wish to run. Available Configs are: ['ssh', 'iomlinux73', 'iomlinux75'] iomlinux73
Please enter the IOM user id: userid
Please enter the password for IOM user : ········
We failed in getConnection
An exception was thrown during the encryption key exchange.

SAS process has terminated unexpectedly. Pid State= (220, 64000)
SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

**Comment by tomweber-sas** [comment]
Ok, so that's not a hang, but an outright error. That's easier to track down. 
So I need to see what you have for iomlinux73. Also your classpath (where you got the sas jars) and what versions of saspy, and SAS are you running. Also, what OS is your client (saspy) and your workspace server? 

I haven't seen this error before, so I'll need to check w/ the IOM folks to see what it implies, also.
```
An exception was thrown during the encryption key exchange.
```

Thanks,
Tom

**Comment by srinicreddy** [comment]
Yep, updated quite a few settings in IOM entry, it is much closer now, should be easier to fix.

I have blanked out server name which has SAS running remotely for obvious reasons as XXXXXXX
SAS we are at 9.4MR3
Python at 3.6
saspy is latest version at 2.2.4
Jars were copied from SAS linux server.

# build out a local classpath variable to use below for Linux clients
cpL  =  "/saspy/sas.svc.connection.jar"
cpL += ":/saspy/log4j.jar"
cpL += ":/saspy/sas.security.sspi.jar"
cpL += ":/saspy/sas.core.jar"
cpL += ":/saspy/saspyiom.jar"

iomlinux73 = {'java'      : '/usr/bin/java',
              'iomhost'   : 'xxxxxxx',
              'iomport'   : 48581,
              'encoding'  : 'latin1',
              'classpath' : cpL,
              'appserver' : 'SASApp--xxxxxxxx'
             }

**Comment by tomweber-sas** [comment]
Cool, thanks. Hey, just a quick guess, but have you tried adding the encryption jars, as this is an encryption error you're getting? 
```
# And, if you've configured IOM to use Encryption, you need these client side jars.
cp += ";C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil_904300.0.0.20150204190000_v940m3\\sas.rutil.jar"
cp += ";C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil.nls_904300.0.0.20150204190000_v940m3\\sas.rutil.nls.jar"
cp += ";C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sastpj.rutil_6.1.0.0_SAS_20121211183517\\sastpj.rutil.jar"
```
Tom

**Comment by srinicreddy** [comment]
@tomweber-sas Thanks for connecting with us and working on figuring out IOM configuration options. Since IOM is working great for us, we will not pursue Kerberos for now. Appreciate your help Tom!
