### ISSUE TITLE
Opens a SAS dataset

### ISSUE THREAD

**Issue by hjsdssz** [sassoftware/saspy#170]
Hi,

I connected Python to SAS server by using the following method and it works!
sas = saspy.SASsession(cfgname='winiomwin')
Please enter the IOM user id: x200232
Please enter the password for IOM user : ········
SAS Connection established. Subprocess id is 7176

However when I tried to open a dataset in our SAS server, the error message shows the dataset does not exist, but it does exist, wondering did I do something right here?
Here is the code and error message
fcm = sas.sd2df(table='abc',libref='libname')
The SAS Data Set libname.abc does not exist

Thank you!

**Comment by tomweber-sas** [comment]
Hey, @hjsdssz . My first guess is that you are connecting to a workspace server in a different AppServer context that you are expecting. Assuming you have this library and dataset pre assigned in the workspace server, and you have more than one appserver defined in metadata, and you're connecting to a different one than you expect.
Or, it's not really assigned. :)
Can you run print(sas;saslog()) and get the log to see what's in there.
Also sas.datasets('library') will show what's in the library, or if it isn't even assigned, as opposed to that specific data set isn't in there.

If it's what my guess is, then you can set 'appserver' in your configuration definition to specify which workspace server you are trying to connect to. You can see examples of this in the remote section of the config doc:
https://sassoftware.github.io/saspy/install.html#remote

You can also submit a rpoc iomoperate to see what appservers exist. See this part of the doc  https://sassoftware.github.io/saspy/advanced-topics.html#using-proc-iomoperate-to-find-object-spawner-hosts-and-workspace-server-ports

Thanks!
Tom

**Comment by hjsdssz** [comment]
Hi, @tomweber-sas 

Sorry for late reply.
Actually I tried to connect to a different appserver, but it stills shows that the dataset does not exist.
I am pretty sure this dataset exist in both appservers.
So my guess is the library is not really assigned?
Let me know what I should do, thanks!

**Comment by tomweber-sas** [comment]
So, you are specifying the 'appserver' key, so you know which one you're connecting to?
You can submit 'libname_all_ list' and run proc datasets if you see the library to see what members it has.
```
print(sas.submit('libname _all_ list;')['LOG'])
sas.datasets('libref')

# also to see the log, maybe there something in there 
print(sas.saslog())
```
Is it supposed to be pre-assigned based upon metadata? Assigned via a autoexec?

libname _all_ list; will show you what IS assigned. 

Tom

**Comment by tomweber-sas** [comment]
So, the other possibility is that the dataset you're trying to get at is a VIEW. I have an open issue for that, and a fix at master for that. If that is the case, then you would see the library in the output from LIST and the tablename will be in the output from datasets showing memtype=view.

If that's the case, then grab the code from master and see if that resolves this for you. 

That would account for the library being assigned, like you expect, and it still saying the data set isn't there.

Should have thought about that sooner. Sorry bout that. I bet that's it. No, you'r not crazy; it's me :)

Tom

**Comment by hjsdssz** [comment]
Actually my bad. Just realized that those libraries are manually generated by myself, they did not pre-exist in the appserver.
That is a stupid question, just wondering do you have any recommendation regarding to how to run SAS code in python apart from the link below?
https://sassoftware.github.io/saspy/getting-started.html

**Comment by tomweber-sas** [comment]
Oh, ok. so you are assigning them yourself? Cool then :)

And yes, there's an example Jupyter notebook that walks through many of the features of saspy here:
https://github.com/sassoftware/saspy-examples/blob/master/SAS_contrib/saspy_example_github.ipynb

You can view it there and you can also download it and then upload it into your jupyter and you should be able to run it and try out the various features.

Tom

**Comment by tomweber-sas** [comment]
@hjsdssz , just following up. Is there anything else you need with this issue, or can I go ahead can close it?
Thanks!
Tom

Hey, BTW, I added another key to the Configuration Definition called 'autoexec'. With this, you can put those libname statements in it and they will get preassigned for you when you get a connection. For instance, you could do the following:
```
winiomwin   = {'java'      : 'java',
               'iomhost'   : 'windows.iom.host',
               'iomport'   : 8591,
               'encoding'  : 'windows-1252',
               'classpath' : cpW,
               'autoexec' : " libname preassign1 'some path'; libname preassign2 teradata conn_options...'; "
              }
```
That way you don't need to submit those yourself every time you connect. That's in the 2.2.9 release that's out there now.

Tom

**Comment by hjsdssz** [comment]
@tomweber-sas Sorry I am way too busy recently. Yes feel free to close it and thanks for sharing the info above.

**Comment by tomweber-sas** [comment]
Hey, no problem. I know how it goes!
Hope that's useful to you, and just let me know if there's anything else.

Thanks!
Tom
