### ISSUE TITLE
SASPY does need seem to read Views

### ISSUE THREAD

**Issue by cvandenhout** [sassoftware/saspy#173]
Hello Team, 

When I'm trying to use the saspy.sasdata() function to access a VIEW from a sas library it does not seem to find it. To exclude any config issues that might cause it I should add that the code works fine with DATA sets (memype == "DATA"). 

Here is the code I'm using:
```
sas = saspy.SASsession(cfgname='iomwin')
sas.saslib(libref=libref, engine=engine, options="ACCESS=READONLY", path=libname_path)
data = sas.sasdata(table = table_name, libref = libref)
```
Here is the  message:
```
Table _libref.table_name_ does not exist. This SASdata object will not be useful until the data set is created.
The SAS Data Set that this SASdata object refers to, _libref.table_name_, does not exist in this SAS session at this time.
SAS Connection terminated. Subprocess id was 15433
```
Now I would have expected this to work because looking at the code generated by a SAS EG project  getting data from a VIEW it does not differ from a DATA set. It is still locating the libname.table_name using the FROM statement within a PROC SQL and accessing a VIEW works fine inside an SAS EG session. From what I can tell looking at the functions in saspy modules you submit the same PROC SQL towards SAS.

```
 if libref:
         tabname = libref+"."+table
      else:
         tabname = table 

code  = "proc sql; create view sasdata2dataframe as select * from +tabname+self._sb._dsopts(dsopts)+";quit;\n"
```
Ofcourse I could access the actual DATA set underlying the VIEW but this protected by a password within our organisation. The views are specific for user access and I have to use those. So can you help me figure out why I can't access views using saspy? 

Thanks in advance and let me know if you need anymore context.

Kind regards

C.

**Comment by cvandenhout** [comment]
Hi Tom,

No worries! Thanks for the really quick reply!
Keep me posted when you found a fix! 

C.

**Comment by cvandenhout** [comment]
Hi Tom, 

I tried it again using a fresh pipenv:
`saspy = {ref = "master", git = "https://github.com/sassoftware/saspy.git"}`

But it does not seem to work with the same view I tried to approach earlier. 
I get the same message saying that it cannot find the table.
I removed Pipfile.lock and did a hard remove of previous environments to make sure it was not holding on to any previous version. So I'm pretty sure I'm using the master. 

I am starting to get a feeling that it might be related to the way we have our datawarehouse setup internally. Any advice or idea's what could still cause this problem?

Thanks!

C.

**Comment by tomweber-sas** [comment]
Well, let's make sure you're really running the code. Can you submit
```
print(sas.saslog())
```
and look at the exist() calls that should be scattered through there? They should look like this:

42         data _null_; e = exist('WORK.bb');
43         v = exist('WORK.bb', 'VIEW');
44          if e or v then e = 1;
45         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 0
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds

The problem was that the function only checks one memtype (data by default), so I added in view.
If it has this then you're running the fix and if it still says your view doesn't exist, then maybe we can see something in the log as to why. 

Thanks!
Tom

**Comment by cvandenhout** [comment]
Hi Tom, 

Sorry it took a while but I had to check it again after the weekend. 
The funniest thing happens when I add the log statement you gave. It works! It's funny because it only seems to work with the log statement in my function and not without it. 

With it I get the following result in the log:
```
37         ;*';*";*/;
38         data _null_; e = exist('_libref.table_name_ ');
39         v = exist('_libref.table_name_ ', 'VIEW');
40          if e or v then e = 1;
41         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      user cpu time       0.00 seconds
      system cpu time     0.00 seconds
      memory              536.87k
      OS Memory           13652.00k
      Timestamp           10/01/2018 01:25:27 PM
      Step Count                        8  Switch Count  32
```
Without it I get the same message saying that it cannot find the table.

So I think this fix is almost ready.
For me it works (as I have no issue with a log being printed). 
But still I do wonder why one has to add a log function for it to work 🤔 ? 
Got any idea's? 

Thanks!

C.

**Comment by tomweber-sas** [comment]
Are you referring to the 'print(sas.saslog())' statement?
That can't have any bearing on whether it works or not. That's just displaying what already happened. It can't make the code work or not work.
It sounds like you're not necessarily running with the code all the time. I'm not familiar with
saspy = {ref = "master", git = "https://github.com/sassoftware/saspy.git"}
so I'm curious if it;s really something with your ''environments' and or that syntax that's not giving you a consistent run.
In the case where it still fails, then you print the log after that, does it still have both exist calls and displays TABLE_EXIST= 0? Or does it not have the second one with 'VIEW'?

Can you install what's at master into your actual installation? Do you have one install, or is the environments you mentioned, different versions of the code? I've seen that before with Conda; they had multiple environments, with different versions and weren't running what they thought they were running. This kinda sounds like that.
Tom

**Comment by cvandenhout** [comment]
Hi Tom, 

My bad, it works now. Superthanks for your fix!
I'll try to give a little insight where I think the problem was at.

I'm using the line of code:
`saspy = {ref = "master", git = "https://github.com/sassoftware/saspy.git"}`
within a .Pipfile to start up a virtual environment for the SAS data access.

For some reason it still kept an environment containing the saspy package before your fix. It somehow grabbed that environment when I runned the code without the log tricking me into thinking a log statement would have something to do with it.  It is funny that even removing the Pipfile.lock or removing the environment with `pipenv --rm` did not work but that is an entirely different issue. 

To conclude, starting with a fresh folder, fresh set of code within a fresh environment made all the pain go away. I can access views! Issue solved!

C.

**Comment by tomweber-sas** [comment]
Hey, that's great! And thanks for the explanation; it sounded like something fishy like that. :)
I've gone ahead and promoted that code too; it had to be better than not, but I really wanted to see that it worked for you too.
Nothing worse than hearing a developer say ;Well, it works for me...' 
Thanks!
Tom
