### ISSUE TITLE
saspy.SASsession hangs after entering user id

### ISSUE THREAD

**Issue by tszklarski** [sassoftware/saspy#174]
Hi

I have trouble getting saspy initial configuration work.
I'm trying to connect to SAS 9.4.4.0 on linux server with saspy 2.2.8 on Windows 7 desktop using IOM configuration.

The problem is that when I run 
`sas = saspy.SASsession(cfgname='winiomlinux')`
there is prompt saying 
`Please enter the IOM user id:`
and when I enter any id (no matter right or wrong) program hangs and nothing happens.
Same happens if I change sascfg_personal.py to use different port or host, effect is always the same. No error message and hanging python process.

Could you please help me find solution?

Regards
Tom

**Comment by tomweber-sas** [comment]
Well that doesn't sound right. Can you show me your configurations definition? What python are you running? What java? No error if you break out of the 'hang'?

**Comment by tszklarski** [comment]
Hi,

java:
`(base) C:\>java -version
java version "1.6.0_43"
Java(TM) SE Runtime Environment (build 1.6.0_43-b01)
Java HotSpot(TM) 64-Bit Server VM (build 20.14-b01, mixed mode)`

`(base) C:\>python -V
Python 3.6.5 :: Anaconda, Inc.`

I don know how to break out. I've tried Crt+C in Anaconda prompt or "Iterrupt kernel" in Jupyter Notebook with no effect.

I've attached sascfg_personal.py cleaned of sensitive company data.

[sascfg_personal_clean.py.txt](https://github.com/sassoftware/saspy/files/2415196/sascfg_personal_clean.py.txt)

Regards
Tom

**Comment by tomweber-sas** [comment]
Ah, I think it may be a problem with Java 6. That's pretty old and I've seen problems with folks trying to run with that a couple times. Installing a more current version of Java has solved that before. The python version is good and your config file appears fine as well (assuming the paths and values  are correct, of course). 
Can you install a newer version of java and give it a try? As you have simply 'java' for the java executable in your configuration definition, be sure that after installing a new version, 'java' will be resolved to the new executable. You can always use the fully qualified path to java.exe also if it doesn't magically get updated inthe registry, though, hopefully it will.

Thanks,
Tom

**Comment by tszklarski** [comment]
Hi, what version of JAVA do you recommend?

**Comment by tszklarski** [comment]
Hi, 

With java 1.8 problem didn't occur.

Thaks!

**Comment by tomweber-sas** [comment]
Awesome, thanks for letting me know. I need to document that so others don't get caught by this too.
