### ISSUE TITLE
Reverse of sas.sasdata - write df into sas library

### ISSUE THREAD

**Issue by MateuszKonopelski** [sassoftware/saspy#177]
I am working with saspya nd it's a great help for me. 

Although I cannot find in documentaiton one feature thata is crucial for me. 

Basically what I do:

```
sas = saspy.SASsession(cfgname='winiomlinuxPROD', omruser='usernum', omrpw='pass')
db = sas.sasdata('table_name','libref').to_frame()   
'''
Lots of calculations
''
# Convert df to SAS using: 
result = sas.df2sd(db)

# Now how can I use something like "sas.sasdata" to write the result table to some "libref" in my SAS session.
# Ideally, I would like to take any df and using name of table and library "export" it to SAS server configured above.
```

I am pretty sure it's possible - I just can't find it in documentation.

Thanks!

**Comment by tomweber-sas** [comment]
@MateuszKonopelski I think I understand, and if so, you're already about there.

Here's a link from the doc: https://sassoftware.github.io/saspy/api.html
```
df2sd(df: pandas.core.frame.DataFrame, table: str = '_df', libref: str = '', results: str = '', keep_outer_quotes: bool = False) → saspy.sasbase.SASdata
```

So, your code above already has the SASdata object for the SAS data set you wrote to SAS from the dataframe; 'result'. You wrote the data set to the WORK library  as table name _df. But I think you just wanted to write it to another libref with a better name, right?

I think what you want is the following, 
```
# just change your line from
result = sas.df2sd(db)
# to
result = sas.df2sd(db, 'tablename', 'libref')
```
results is the SASdata object for the data set you created in whatever libref you wanted with whatever tablename you chose.
So you can do 
```
result.head()   # or any other methods already.
```
Is that what you're trying to do?
Tom

**Comment by MateuszKonopelski** [comment]
This `sas.df2sd(db, 'tablename', 'libref')`  worked like charm. 

Thank you guys you are best!

Matt

**Comment by tomweber-sas** [comment]
Appreciate it :) 
Let me know if you need anything else!
Tom

**Comment by jld23** [comment]
@MateuszKonopelski can we close this issue?

**Comment by MateuszKonopelski** [comment]
No thank you.

It can be closed. :)

Matt

pon., 29 paź 2018 o 15:21 Jared <notifications@github.com> napisał(a):
