### ISSUE TITLE
Connecting to SAS session using saspy without prompting for the password

### ISSUE THREAD

**Issue by sudipto84goswami** [sassoftware/saspy#18]
Hi Team,

Can we pass on the password from a program file instead of getting prompted while connecting to SAS Session using SASPY.

Right now I can think of the below 3 scenarios:
Scenario 1 : We maintain a password file at Jupyter Server owned only by Admins.
Scenario 2: Password Files located at home directory of respective users - /home/<user>
Scenario 3: Reading the password file from local system after you submit the query from Jupyter.

If you would like to suggest any alternatives for these, that will be really helpful.

Regards,
Sudipta

**Comment by tomweber-sas** [comment]
Yes, being able to get the credentials from a file would be nice. The authinfo file is a standard way to do this and can work on both windows and linux. We can have a key in the Configuration Definition for this which will identify which entry in the .authinfo file to use. I'll code this up.

**Comment by FriedEgg** [comment]
An authinfo file is only really relevant to a SAS Viya/CAS configuration.  Supporting the IOM configuration XML files would also be a nice addition, which can define both server and user configuration.

**Comment by tomweber-sas** [comment]
Hey, I hate to say it, but I have a bug in this code. I check for the authinfo file and look for the authkey in it, and if I can't find either, I catch that exception and continue on to prompt for credentials. BUT, depending on the error, I can get another error trying to print out the message. I've fixed this so that it will continue and prompt. Sorry for that, but I have this fixed and a new PyPI package built for this feature (and this fix). The PyPI version is saspy-2.1.3.

**Comment by tomweber-sas** [comment]
Actually, that's saspy-2.1.4 for the PyPI package. It's the latest one out there.

**Comment by tomweber-sas** [comment]
@sudipto84goswami have you had a chance to confirm that this is working for your users? If so, we can close this issue.

Thanks!
Tom

**Comment by sudipto84goswami** [comment]
I tried with one user only. It worked fine. However we are yet to move this to production. You can close this for the time being, I will reach out again if we face any issue during prod configuration.

**Comment by tomweber-sas** [comment]
Thanks @sudipto84goswami ! I'll close this now, but, as always, if you need anything just let me know. I believe others are using this successfully as well.

Thanks,
Tom
