### ISSUE TITLE
Improve Session Start-Up Time

### ISSUE THREAD

**Issue by hhubbell** [sassoftware/saspy#185]
Currently four requests are made to the SAS provider at session initialization.  I think we can lower the time required to start by only making one request.

I have a PR that addresses this that I will submit shortly.

It's not a major improvement, but it should increase the responsiveness slightly (especially in a server environment with many concurrent active users!).

I briefly considered lazy-loading the provider metadata during `SASsession.__repr__` instead of `SASsession.__init__`, but don't know if that would necessarily be a better option.  The code is setting `self.workpath`, `self.sascei`, `self.sasver`, and `self.SASpid` using that metadata; none of these attributes are _required_ for the session object to function, but it's a nice to have - especially `self.workpath`.

Here's a comparison under nearly no load (after work hours).  I only ran a few cycles to avoid thrashing our org's server.

**Before:**
```python
timeit.timeit('sas = saspy.SASsession()', setup='import saspy', number=5)
# Average execution time: 4.32641398289111
```

**After:**
```python
timit.timeit('sas=saspy.SASsession()', setup='import saspy', number=5)
# Average execution time: 1.2895394228386808
```

**Comment by tomweber-sas** [comment]
This all looks great :) Yes, no reason to have these all be separate calls. just evolution I suppose. Good to go back and clean it up! This format you've used will also make it very easy to add in others as needed in the future. I'll go ahead and merge this in.
Thanks for contributing this!
Tom
