### ISSUE TITLE
v2.3.0 - list index out of range

### ISSUE THREAD

**Issue by chrishales709** [sassoftware/saspy#190]
When I create a SAS session in v2.3.0, I get an IndexError saying "list index out of range", and it points to sasbase.py on line 323.

 `self.sascei   = vlist[1].split('=')[1]`

To create a SAS session, I'm just running:

`sas = saspy.SASsession(cfgname="server_name")`

**Comment by tomweber-sas** [comment]
Hmmm. I can't get that to fail. Can you show me your configurations definition?
Also, after that fails, can you submit (asuming your SASsession object is 'sas'):
```
sas
print(sas.saslog())
```

**Comment by chrishales709** [comment]
I actually can't create a SASsession object because it errs out, so I can't show you sas.saslog(). However, I put a print statement to get the values of vlist in sasbase.py, and I am seeing something like this:
['WORKPATH=...'
, 'SYMBOLGEN: ...'
, 'ENCODING=...'
, 'SYMBOLGEN: ...'
, 'SYSVLONG=...'
,...
]
Since the second item in vlist doesn't have a '=', it is throwing an error. I guess I have SYMBOLGEN on, so it is throwing this logic off.

**Comment by chrishales709** [comment]
I updated line 307 in sasbsae.py to:
`options nosource nonotes nonumber nosymbolgen;`
and line 320 to:
`vlist = res.split('options nosource nonotes nonumber nosymbolgen;\n')[1].split('\n')`
and that seemed to fix the issue.

**Comment by tomweber-sas** [comment]
Ah, yes, I see. I'll fix this up so it's not dependent on these options. Thanks for tracking it down!

**Comment by tomweber-sas** [comment]
I've pushed a fix to master to make this work in dependent of what options you might have, and not changing any of them either. Can you pull from master (just copy sasbase.py if not), and try this with your environment?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
great! thanks for verifying. I'm going to create a new version w/ this fix, so this doesn't bite anyone else. v2.3.1.
Thanks again!
Tom
