### ISSUE TITLE
proc forest (maybe others): can I pass a string ("lib.table") instead of a data object?

### ISSUE THREAD

**Issue by sascis** [sassoftware/saspy#193]
as a SAS programmer transitioning to python, I still think about programming "the SAS way".  as such, I spent far too long trying to determine why this code was failing:

ml = sas.sasviyaml()
out = ml.forest(data="casuser.pricedata"  # <-- here
            , target="sale / level=interval"
            , input="price / level=interval"
            , id="price"
            , stmtpassthrough="savestate rstore=casuser.myAstore"
           )
Ultimately, I figured out that it was because I was passing the dataset name as a string, instead of a python SASdata object.  Would it be possible for the methods to accept either??

**Comment by tomweber-sas** [comment]
yes, I understand. When we started this, we used strings for everything too, but that wasn't very pythonic. We figured it out and got on the object wagon. Jared just reworked all of these analytic methods, and that is in version 2.4.0. I'll have to check with him about is he happened to add support for this, or if he thinks he can do that or not. 
Did it give a useful error? I'm guessing not. 
On the other side of the coin, there are good things using objects in python code. Same with lists,  dictionaries, ...  I know there's a lot to learn w/ a new language, but once you get the hang of it it starts making more sense and being useful. 
I'll ping Jared about this, as he support these analytic methods (procs).
Tom

**Comment by tomweber-sas** [comment]
@jld23 Can you speak to this? thanks!

**Comment by jld23** [comment]
I'm looking at adding support now.

**Comment by jld23** [comment]
Closing this has been fixed.
