### ISSUE TITLE
ETS methods generate the wrong code in certain situations

### ISSUE THREAD

**Issue by jld23** [sassoftware/saspy#194]
Setup:
```
import saspy
sas = saspy.SASsession()
ets = sas.sasets()
air = sas.sasdata('air', 'sashelp')
outAir = sas.sasdata('air')
```
Call the method:
```
b = ets.arima(data=air, identify='var=air(1,12)', out=outAir, procopts='plots=none')
```
The code produced is this:
```
Proc code submission:
 %macro proccall(d);
proc arima data=sashelp.air plot=all out=output out=WORK.air
; plots=none ;
identify var=air(1,12);
run; quit; %mend;
%mangobj(ari0002,arima,air);
```
Which is wrong. I'll fix it after my other PR.

**Desktop (please complete the following information):**
 - OS: [All]
 - SAS Version: [All]
 - SASPy Version: [2.4.0]

**Comment by tomweber-sas** [comment]
This hasn't been fixed in years and no one has mentioned it. Jared, if you ever fix it, great, but it isn't an issue that anyone seems worried about.
