### ISSUE TITLE
saspy does not start anything

### ISSUE THREAD

**Issue by hmmmcho** [sassoftware/saspy#201]
Hi, I am trying to use saspy, howerver, it seems that it does not work on my computer.
The below figure is where I am stopped.
I can load saspy, and I've editted the configuration file to start with 'winlocal'.
Even I add the path where .dll file is in.

However, there is no progress in my jupyter kernel.

Please help me.

![image](https://user-images.githubusercontent.com/37096179/50039151-69a0e500-0070-11e9-9a09-44b8ce8351b5.png)

This is my configuration information.
I am currently using SAS9.4, python3.6, and probably saspy would be the lastest version becasue I've just installed it.

![image](https://user-images.githubusercontent.com/37096179/50039177-c7353180-0070-11e9-9b24-8864e4fdca5a.png)

**Comment by tomweber-sas** [comment]
Well, I don't have enough info to tell you what's happening here. I am a little confused why the backslashes render as some other character. What encoding is the sascfg file in? Python should all be utf-8, Can it be that the file was saved, after editing, in some other encoding?

If you interupt the kernel, what is the traceback you get; I assume it's hung at this point in the notebook?

Is there a java process and/or a SAS process created when you've submitted this? In process explorer on windows you would see these sub-processes like this:

![pe](https://user-images.githubusercontent.com/17710182/50110576-9f78d180-0208-11e9-8aa4-e6fe1f4a9d3b.png)

What encoding does your SAS session actually run in? What's your SAS Session Encoding?

Thanks,
Tom

**Comment by hmmmcho** [comment]
Hi, thank you for your comments.

The backslashes are represented as some other character in my country. I will check the encoding.

The following figure is process tree of the running saspy.
![image](https://user-images.githubusercontent.com/37096179/50144228-0920da80-02f2-11e9-9b4b-240ec2328174.png)

It seems that no JAVA program is called. SAS isn't called as well.

And the session is not interrupted. After some time, it still operating without any message.

Should I check my java related settings?

Thank you.
Sangheum

**Comment by tomweber-sas** [comment]
Well, that's very strange. I'm less suspicious of your java settings, as normally this would fail and you'd get an error message. This makes me think there's something else wrong. Like this really isn't python 3 running for these jupyter processes or there's something else strange w/ jupyter or the install.
Can you try this from python in line mode? And, can you confirm the python version in the jupyter notebook (it does appear to be anaconda3)? 

Also, what version of saspy? there's a version.py file in the repo. And it looks like Java 8, which is good. Is it 64 bit java, I'm assuming windows is 64bit? 

to check the version you can submit:
```
import sys
sys.version
```
In line mode, just submit the same code:
```
import sys
sys.version

import saspy
saspy
sas = saspy.SASsession(cfgfile=...)
sas
``` 

In the line mode case, if it hangs, check the processes before hitting ctl-c, then try ctl-c to see if it interrupts and produces a traceback. It's strange that that doesn't happen in jupyter. 

As a last thing to try, you could try manually running what should be being run by saspy. If you had a java error you would normally get an error showing the command saspy tried to run, suggesting you try that from the command line to see if there were any other error messages. This would show a command like the following:
```
java -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94508__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94508__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94508__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94508__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\ProgramData\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 59668 -stdoutport 59669 -stderrport 59670 -zero -lrecl 1048576
```
You could replace the 'java' with your java path in your config, and the classpath with the paths you have in your config, and try running that command from the command line also to see if it provides any useful information, as a diagnostic. If that 'works' you should get an error like the following about not connecting to the socket (cuz saspy isn't listening):

```
java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at pyiom.saspy2j.main(saspy2j.java:109)
Exception in thread "main" java.lang.NullPointerException
        at pyiom.saspy2j.main(saspy2j.java:116)
```
If you don't see the error above, then there would be something suspicious about java.

Can you try all of this and see what we see?

Thanks,
Tom

**Comment by sangheumcho2** [comment]
Thanks for your suggestions.

I've tried above procedures, but it does not show any of error message.

What I think strange is that on the command shell, even "ctrl - c" does not work. It still hangs.

So I could not see any of error message.

Should I remove my java and install again?
Is it the problem regared to java?

Thank you.
Sangheum

**Comment by tomweber-sas** [comment]
Sorry for the delay, I was on holiday the past couple of weeks.  Yes, this is strange. I haven't seen symptoms like this before. Did you try running the 'java -classpath ...' (substituting your paths in there) from the command line? What was the result of that? If that 'did nothing' then I would suspect your java installation. But that's still speculation. Can you run that command and send the results?

I guess the other place to start is how did you install python and saspy? Maybe there's something not right there. It's strange that ctl-c does nothing in your line mode python. That doesn't make sense either.

If I bring up python in line mode and use ctl-c, even not running a method, it shows 'KeyboardInterupt'. If I hit ctl-c when trying to start a SASsession it will do something (depends upon what line of code is executing when ctl-c is entered). Here's an example. I typed in [ctl-c] where I entered them; they don't show, of course, so I put them there to show where I entered them. Can you also do this and show what you get?

```
C:\Users\sastpw>python
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> saspy
<module 'saspy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\saspy\\__init__.py'>
>>> [ctl-c]
KeyboardInterrupt
>>> sas= saspy.SASsession(cfgname='winlocal')
[ctl-c]
Exception caught!
SAS attention handling is not yet supported over IOM. Please enter (T) to terminate SAS or (C) to continue.t
b'SAS process terminated'
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94508__prt__xx__sp0_
_1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94508__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SA
SHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94508__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\dep
loywiz__94508__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinpo
rt', '56569', '-stdoutport', '56570', '-stderrport', '56571', '-zero', '-lrecl', '1048576', '']

Be sure the path to sspiauth.dll is in your System PATH

>>>
```
Do you also have the sspiauth.dll is in your System PATH? That needs to be there, but again, if not you should get an error. 

Thanks,
Tom

**Comment by kingfischer16** [comment]
As somebody who spent 3 days trying to get saspy to work and then succeeded, I can say that the System PATH is super important. Depending on what I put in my sascfg file I could get a variety of error messages pointing to different jars and logs. It was that last line plus another, now closed, issues that help me fix it. The folder paths to both the sspiauth.dll and your sas.exe files must be on the System PATH. Upon fixing that, everything worked perfectly. No reinstalling of anything required.

**Comment by tomweber-sas** [comment]
Hey, just going through open issues. Did you ever figure out what was going on with this? Still need this open?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
If this is still a problem, feel free to reopen.

Thanks,
Tom
