### ISSUE TITLE
SASpy and SAS University Edition

### ISSUE THREAD

**Issue by chrishales709** [sassoftware/saspy#203]
I would like to help out with saspy issues on my home computer, so I was wondering if there is a way to connect saspy to SAS University Edition. I believe SAS University Edition comes with saspy. However, it is locked away in the Linux disc image, so I can't access the saspy files on the image.

**Comment by tomweber-sas** [comment]
Well, unfortunately, no. UE is a closed system (w/ saspy in it already). And there's anew version available now too. But, no, you can't change the code in it, nor will it allow you to connect to it's SAS from outside the closed system. Given that this is a free copy of SAS, that anyone can get, it needed to be closed and not able to be used as a production version. I'm sure you understand. 
Would you be able to VPN to work and connect from saspy on your home computer to a work version of SAS?

**Comment by chrishales709** [comment]
OK, that's what I figured. I'll see what I can do on my end. I'll go ahead and close the issue.
