### ISSUE TITLE
cannot connect to CAS from a %%SAS magic block or a submit() method

### ISSUE THREAD

**Issue by sascis** [sassoftware/saspy#204]
**Describe the bug**
I'm trying to mix 'traditional' SAS code with CAS-related code, but I've tried every permutation I know to connect to CAS either from a saspy.submit() method, %%SAS magic cell, or a SAS kernel (in Jupyter Notebook), using the exact parameters/credentials that work from non-python access - unsuccessfully.  What is the secret??  FWIW, the SWAT package (I know, unrelated package) connection fails also.  I've set these in a previous cell:
os.environ["CAS_CLIENT_SSL_CA_LIST"] = '<myHomeDir>/miniconda3/envs/py36/lib/python3.6/site-packages/mm/myServer.pem'
os.environ["LD_LIBRARY_PATH"] = "/lib64/"

**To Reproduce**
%%SAS sas

options cashost='myServer.myCompany.com';
options casuser=myUID;
options casport=5570;

cas mySess sessopts=(password='XXXXXX' timeout=1800 locale="en_US" caslib=Public);
caslib _all_ assign; 

**Expected behavior - (or, what I see in a SASStudioV session or a NODMS SAS session)**
A successful connection to the CAS server, and all the CAS libraries successfully assigned.

**My Results**
945   cas mySess sessopts=(password='XXXXXX' timeout=1800 locale="en_US" caslib=Public);
ERROR: OpenSSL error 336134278 (0x14090086) occurred in SSL_connect/accept at line 4720, the error message is "error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed".
ERROR: Secure communications error status 807ff008 description "10.104.85.170: The certificate sent from the remote host cannot be validated by any of the public keys in the root certificate store specified by SSLCALISTLOC or SSLCACERTDIR."
ERROR: OpenSSL error 336134278 (0x14090086) occurred in SSL_connect/accept at line 4720, the error message is "error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed".
ERROR: The TCP/IP negClientSSL support routine failed with status 807ff008.
ERROR: Failed to connect to host 'myServer.myCompany.com', port 5570.
ERROR: Unable to connect to Cloud Analytic Services myServer.myCompany.com on port 5570. Verify connection parameters and retry.
946   caslib _all_ assign;
ERROR: A connected session is required to complete the Caslib request. Session CASAUTO identified by the option SESSREF= is not connected. Start the session or reconnect to the session.

**Desktop (please complete the following information):**
 - OS: Linux (Jupyter Notebook)
 - SAS Version: Viya 3.3
 - SASPy Version: 2.2.9

**Additional context**
I will send you my 'working' code via direct email.  ***And my development is blocked until I can successfully get this connection made.***

**Comment by sascis** [comment]
My mistake - I didn't have a .authinfo file in the right place.

**Comment by tomweber-sas** [comment]
That's great. Glad that's all it was and you were able to track it down!
Tom
