### ISSUE TITLE
Documentation update:  saspy 2.4.2 requires pandas 

### ISSUE THREAD

**Issue by DaymondLing** [sassoftware/saspy#209]
If python environment does not have pandas, import saspy fails on version 2.4.2, it works if pandas is installed.  Documentated instruction "pip install saspy" does not automatically install pandas, if pandas is indeed required, documentation should reflect this.

![image](https://user-images.githubusercontent.com/25850001/52973220-53bee180-338b-11e9-970c-4131f18cc4f9.png)

- OS: Win10
- SASPy: 2.4.2

**Comment by tomweber-sas** [comment]
@DaymondLing Oh man, I think Jared must have added that import w/out realizing. He went through a big refactor of all the proc code (the analytic methods). Restructured a bunch of code. This isn't a doc issue, saspy is NOT dependent on Pandas, though, of course, there's a lot of functionality that integrates w/ it.

I'll fix this and build a fresh version that fixes this; 2.4.3. I didn't catch that as I have pandas, of course, so I didn't notice that line int here (right before the try/except of the import pandas!).

thanks for letting me know! I'll update this when I have this fixed and built.
Actually, it's out there now! Give 2.4.3 a go and see if this is back to how it was before; not requiring pandas.

Thanks!
Tom

**Comment by DaymondLing** [comment]
Thanks, Tom. Tried out 2.4.3 and it's back to the way it was - not needing pandas to install and run saspy (although having pandas is super useful of course for other reasons).

I wouldn't have caught it either as sas-kernel and saspy was working well, but then I upgraded Python and had to reinstall all of the packages.

**Comment by tomweber-sas** [comment]
Great! thanks for verifying that for me too. As always, let me know if you run into anything else!

Thanks,
Tom

**Comment by DaymondLing** [comment]
I run into issues with managed desktops where the user can't update the registry, and then need to use javaparms to get saspy working 

```
winlocal = {'java'      : 'java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW,
            'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE']
            } 
```

Perhaps this should be more visible in the documentation.

**Comment by tomweber-sas** [comment]
Gotcha, is this what's in this part, number 4 and 5 when you scroll down?
https://sassoftware.github.io/saspy/troubleshooting.html#iom

If I rework this to have a better index which each of the specific issues up front, with a link to the specifics, would it make this Troubleshooting Guide better? I've thought about that more than once. It does seem more of a 'narrative' as it is; you kinda have to read through it to get to your specific error.

Would that help?

Thanks,
Tom

**Comment by DaymondLing** [comment]
Thanks, Tom.  Serves me right for not reading the documentation carefully.  Yes, if there's a clickable index link for each of the issues, that would help a lot.  Faster navigation should be less intimidating.

ps:  giving a tutorial at SGF2019 on Using SAS & JupyterLab.

**Comment by tomweber-sas** [comment]
Yes, I find it hard to refer people to those specific problems in that doc too, since I don't have each indexed. 
It'll be better and easier if I rework the doc page so each issue is easier to identify. I'll see about do ing that.

Ah, I see that, you're session id 4033. I'll actually be at SGF this year too. I'll be in the demo area mostly. Turned out most of the questions there last year were about Python support, so they wanted me there this year :)

I'm hoping to get to a couple papers on the topic too. It's cool that our users are already writing papers on saspy and other python integration we have. I'm looking forward to it!

Thanks!
Tom

**Comment by tomweber-sas** [comment]
@DaymondLing I've updated the Troubleshooting section. To be sure you have it, it should now be version 2.4.3. I didn't get down to every error being a link in the TOC, but I grouped them in indexed groups (links to the left in the TOC), and numbered them by the error message so they would be easier to see, then you scroll down to that number to see the content - screen shot of the error and what to do about it to fix it. 
Let me know if you think this is better or if you have more skill at markdown than me - that's about as good as I can get it :) 

At least I can send a link: https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors
and say number 4 in that section, 
or even just say 'troubleshooting->IOM->iom-specific-errorors->4 
and you can tell it's the sspiauth.dll path that's the problem.

Thanks,
Tom

**Comment by DaymondLing** [comment]
It's more helpful, Tom.  Thanks for playing with Markdown!
