### ISSUE TITLE
SAS connection

### ISSUE THREAD

**Issue by Jayrrus** [sassoftware/saspy#211]
Hello

I am new to python and am helping and end user with her Jupyter project.

I have followed all the steps to install saspy and that has gone fine.

However i am having issue with connecting SAS.

Tom has helped out so far and thanks to Tom for his mastery at this.

> Oh, sorry @Jayrrus I didn't see there were multiple people on this thread. In my previous post, you will see that the error you have is that java.exe is not found. Depending on how you install java, it may configure itself into your system path so that just saying 'java' works, but it may not. You can just specify the full path in your configuration definition to address this.

```
java -
(Required) The path to the Java executable to use. For Linux, use a fully qualified path. On Windows, you might be able to simply enter java. If that is not successful, enter the fully qualified path.
```
Also, it may be beneficial to open a new issue for these so that each has it's own specific thread.

Thanks!
Tom

Hello Tom i am confused by this . I know i have to edit the sascfg.personal.py file.
i am just confused about the path to java.
Do you want the path to java itself or the java.exe that is located in 
SASHome\SASPrivateJavaRuntimeEnvironment\9.4\jre\bin\java.exe.

my winlocal in sascfg.personal.py looks like this
`winlocal = {'java'      : 'java' 'C:\Program Files\SASHome\SASPrivateJavaRuntimeEnvironment\9.4\jre\bin\java.exe',
            'encoding'  : 'windows-1252',
            'classpath' : cpW
            }`

Is this wrong?

Thanks Tom for helping this noob.

This is my result from Jupyter now.

![image](https://user-images.githubusercontent.com/1568842/53183405-36775680-35c9-11e9-9f70-6c2814aca0b2.png)

**Comment by tomweber-sas** [comment]
@Jayrrus Ah, now I see why the command printed out seemed to smash 'java' and C:\Program...  all together. You are correct, your configuration definition is not valid,
The 'java' key can only be the java command. You put 2 things together as the value, both 'java' and 'C:\Prog...'.  So the error you got wasn't that it couldn't find 'java.exe', it was that it couldn't find 'javaC;\Program...'
Only put the java command in the java key. So, for what it looks like you are trying to do, try the following:
```
winlocal = {'java'      : 'C:\Program Files\SASHome\SASPrivateJavaRuntimeEnvironment\9.4\jre\bin\java.exe',
            'encoding'  : 'windows-1252',
            'classpath' : cpW
            }
```
Assuming that your classpath is correct, then you should should either be up and running with this, or there are 2 other usual issue you may hit. You need the sspiauth.dll path in your system path. This is documented as follows:

= = =
There is one additional requirement. The sspiauth.dll file–also included in your SAS installation–must be in your system PATH environment variable, your java.library.path, or in the home directory of your Java client. You can search for this file in your SAS deployment, though it is likely in SASHome\SASFoundation\9.4\core\sasext.

If you add the file to the system PATH environment variable, only list the path to the directory–do not include the file itself. For example:

C:\Program Files\SASHome\SASFoundation\9.4\core\sasext
= = =
 
And the other issue that could happen is if the path to sas.exe isn't configured correctly in the windows registry. That doesn't happen very often but it can happen. You can find that issue documented, and how to resolve it, in the very last few paragraphs of this section of the Troubleshooting guide:
https://sassoftware.github.io/saspy/troubleshooting.html#iom

Hopefully that isn't an issue and you've already added the sspiauth.dll path, per the config guide. And if you, you ought to be up and running.

Let me know, and we'll address anything else if need be.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
If you have java installed on your system and want to use that, then you would likely use this, assuming java is found in your path (if you installed java, it usually sets itself up in your system path so that 'java' or 'java.exe' is found.:
```
winlocal = {'java'      : 'java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW
            }
```

**Comment by FriedEgg** [comment]
With the 'new-ish' config key javaparms, adding the sasext folder to the path is not totally necessary.  You can simply put the folder path into the SASPy configuration for java.  Such as the following:

`
winlocal = {'java' : 'C:\Program Files\SASHome\SASPrivateJavaRuntime\9.4\jre\bin\java.exe',
                 'javaparms': ['-Djava.library.path="C:\Program File\SASHome\SASFoundation\9.4\core\sasext"'],
                 'classpath' : cpW
                }
`

**Comment by tomweber-sas** [comment]
posting the following back on this thread; went to the other one accidentally.


Hello Tom thanks for the quick response.

I have done what you have asked and still no connection

this is the error I receive now

![image](https://user-images.githubusercontent.com/1568842/53195973-dbebf380-35e4-11e9-8696-406a1315042d.png)

Here is the sascfg.personal.py code:
`SAS_config_names=['winlocal']

SAS_config_options = {'lock_down': False,
'verbose' : True
}
SAS_output_options = {'output' : 'html5'}

default = {'saspath' : '/opt/sasinside/SASHome/SASFoundation/9.4/bin/sas_u8' 'C:\Program Files\SASHome\SASFoundation\9.4'
}

ssh = {'saspath' : '/opt/sasinside/SASHome/SASFoundation/9.4/bin/sas_en',
'ssh' : '/usr/bin/ssh',
'host' : 'remote.linux.host',
'encoding': 'latin1',
'options' : ["-fullstimer"]
}

cpL = "/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94496__prt__xx__sp0__1/deploywiz/sas.svc.connection.jar"
cpL += ":/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94496__prt__xx__sp0__1/deploywiz/log4j.jar"
cpL += ":/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94496__prt__xx__sp0__1/deploywiz/sas.security.sspi.jar"
cpL += ":/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94496__prt__xx__sp0__1/deploywiz/sas.core.jar"
cpL += ":/opt/github/saspy/java/saspyiom.jar"

iomlinux = {'java' : '/usr/bin/java',
'iomhost' : 'linux.iom.host',
'iomport' : 8591,
'encoding' : 'latin1',
'classpath' : cpL
}

iomwin = {'java' : '/usr/bin/java',
'iomhost' : 'windows.iom.host',
'iomport' : 8591,
'encoding' : 'windows-1252',
'classpath' : cpL
}

cpW = "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar"
cpW += ";C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\log4j.jar"
cpW += ";C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar"
cpW += ";C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\sas.core.jar"
cpW += ";C:\ProgramData\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar"

winlocal = {'java' : 'java',
'encoding' : 'windows-1252',
'classpath' : cpW
}

winiomlinux = {'java' : 'java',
'iomhost' : 'linux.iom.host',
'iomport' : 8591,
'encoding' : 'latin1',
'classpath' : cpW
}

winiomwin = {'java' : 'java',
'iomhost' : 'windows.iom.host',
'iomport' : 8591,
'encoding' : 'windows-1252',
'classpath' : cpW
}

winiomIWA = {'java' : 'java',
'iomhost' : 'windows.iom.host',
'iomport' : 8591,
'encoding' : 'windows-1252',
'classpath' : cpW,
'sspi' : True
}
`
If you want the file itself you can grab it from here --> https://drive.google.com/file/d/13fPt1QyZNDfuLQR_j2VMYJmAhOMzA4b1/view?usp=sharing

Thank you again for you help.

**Comment by tomweber-sas** [comment]
Ok, that error is that the path you provided in the classpath for that jar, isn't right.
You have this,: C:\ProgramData\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar

You can submit the following to see where the path to saspy is that you are actually running:
```
import saspy
saspy
```
Then you need to correct that path in the class path to point to the saspyiom.jar file.
For instance, 
```
import saspy
saspy
<module 'saspy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\saspy\\__init__.py'>
```
So the correct path for me is
'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\saspy\\java\\saspyiom.jar'

Tom

**Comment by Jayrrus** [comment]
hello Tom

I have done the corrections.

i also fund out that the "\\" needs to used in the sascfg.perspnal.py as well.

With you help i was able to get a connection with SAS. i will contact the user and ask her what does she need help with next. 
Thank you again Tom. If I need help. Ill put in another thread. Thx.

**Comment by tomweber-sas** [comment]
Great! Glad you're up and running.
I'll close this issue, and, if you need anything else, just open another for whatever you need.

Thanks!
Tom
