### ISSUE TITLE
sas.list_tables() is throwing index of range

### ISSUE THREAD

**Issue by mailbagrahul** [sassoftware/saspy#213]
Trying to list out the tables(for example I'm retrieving sashelp tables) but it is throwing index out of range error. Any thoughts?

![image](https://user-images.githubusercontent.com/15937179/53264474-8705b700-3690-11e9-9518-30957aba7ecd.png)

**Comment by tomweber-sas** [comment]
@mailbagrahul I'll need to see the whole part of the SASLOG for running that method. And the whole traceback.
Also, the output from submitting your SASsession object.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
I believe that this is due to the problem described in #210 
This should be fixed at master. Waiting for verification from your side, as you have a number of steps and code which is also being run. But I think this is all the same problem.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
I believe you have verified this as fixed with what is at master, is that correct? 

Thanks,
Tom

**Comment by mailbagrahul** [comment]
Yes. Thanks a lot for fixing it. I will close this issue.
