### ISSUE TITLE
sd2df returns None for empty datasets. should get empty dataframe instead?

### ISSUE THREAD

**Issue by tomweber-sas** [sassoftware/saspy#217]
The various sd2df methods return None when the SAS data set had no observations (rows). I think that it could be more useful to return an empty data frame with the correct metadata; the column names and data types set the same as they would be if there happened to be rows of data.

As I don't really 'use' saspy, I write it :), I'm not sure which behavior would be the best. It strikes me that returning the dataframe matching the data set (rows or no) is really what this should be doing.

Changing this would be a change in behavior, though subtle and hardly the usual case. Still ...
Though, if this is considered a bug, that it isn't creating the empty dataframe, which is perfectly valid and could be seen as what is already expected, then this would be a bug fix.

So, do any users have an opinion on this?

I'm working on the implementation and think I have it. Need to vet it some more though. Trying to decide to fix/enhance it or leave it as is.

Thanks,
Tom

**Comment by mailbagrahul** [comment]
In my opinion, receiving an empty dataframe would be useful. And specific to my usecase, Since I'm planning to transfer the table output directly to HTML layout, it may avoid hard coding few things.

Returning "None" seems to be nothing is present as a dataset itself. So, returning metadata is very appropriate.

**Comment by tomweber-sas** [comment]
Great, yes that correlates to my thinking too. I think None is wrong just because the table is empty. I think getting the same table (data frame) with the valid metadata is the way it should work. None is for it failed. 
In SAS terms, if I did a proc copy, or data a; set b; run;, then I would get a new data set w/ all the columns and data types/formats but no rows. Same as the one I was copying. Same should be true here.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
I've pushed this fix to master. So the sd2df methods will now return a dataframe consistent with the SAS data set regardless of number of ovservations. They will still return None if there is an error or if the data set doesn't exist or things like that.

Thanks,
Tom
