### ISSUE TITLE
Why `print` when you can `raise`?

### ISSUE THREAD

**Issue by hhubbell** [sassoftware/saspy#218]
There are a number of instances where an error is caught and partially handled by this library, leaving the program in a semi-broken state or requiring checks before evaluating additional clauses.  A more robust approach is to halt execution with an exception instead of `print(...)`-ing the debug statement to the user.

Here's an example from [`sasbase.py`](https://github.com/sassoftware/saspy/blob/21623e6dec0fb56e5067f0d604147b57b425b53d/saspy/sasbase.py#L315-L321):
```python
if self.sascfg.mode in ['STDIO', 'SSH', '']:
    if os.name != 'nt':
        self._io = SASsessionSTDIO(sascfgname=self.sascfg.name, sb=self, **kwargs)
    else:
        print("Cannot use STDIO I/O module on Windows. No "
            "SASsession established. Choose an IOM SASconfig " 
            "definition")
```

This script should be interrupted here as there is no viable alternative for it to continue processing.

Exceptions are a pragmatic and idiomatic approach to handling error cases.  Raising an exception would provide the following benefits over printing:
1. Exceptions can be caught and handled by the user.
2. Exceptions provide a traceback pointing the user to the exact location their script failed.
3. Exception objects can be defined once and used in multiple places (DRY).
4. Uncaught exceptions halt processing, reducing the need for additional error handling.  For instance, the use of `if self._io` in `sasbase.py` is not required if the workspace connection failure raises an exception.  Examples [here](https://github.com/sassoftware/saspy/blob/21623e6dec0fb56e5067f0d604147b57b425b53d/saspy/sasbase.py#L326) and [here](https://github.com/sassoftware/saspy/blob/21623e6dec0fb56e5067f0d604147b57b425b53d/saspy/sasbase.py#L392).

Exception documentation: https://docs.python.org/3/tutorial/errors.html

I am happy to help contribute fixes if this is seen as a valid enhancement.

**Comment by tomweber-sas** [comment]
@hhubbell Thanks for your input on this. My first thought was that this would be good in the 'batch ' mode where saspy is actually running in a script, as opposed to interactively, like in a notebook. However, I think your points are just as valid in an interactive session, as it can still provide the same (more helpful) message about the failure (not just a traceback), while allowing for the more programmatic approach to handling these issues/errors.

Yes, I'd like it if you wanted to provide some example fixes for this or even outline a more holistic approach - you mentioned defining and exception object (saspy exception?). Always looking to make this better and more robust. I recently made a number of enhancements to provide more programmatic handling of some things, but, clearly, there's still more to be done! 

I look forward to seeing what you're thinking and having you contribute.

Thanks!
Tom

**Comment by hhubbell** [comment]
Hi Tom,

Thanks for your feedback.  I've just submitted an initial PR (#219) with two new exceptions.  The PR includes a few tests for these exceptions.  I'm hoping to add more coverage in the future.

If these changes look OK to you, I'll continue to work on some additional changes and submit PRs incrementally.

Thanks!

**Comment by tomweber-sas** [comment]
@hhubbell Are you good with closing this issue?
Thanks,
Tom

**Comment by hhubbell** [comment]
Hi Tom,

Sure, sounds good.  I have some additional changes in mind, but I will just submit PRs as they are ready.  You can close this issue.

**Comment by tomweber-sas** [comment]
cool, that sounds good! Thanks again :)
