### ISSUE TITLE
Java Error when connecting to remote SAS-server through IOM

### ISSUE THREAD

**Issue by mhldst** [sassoftware/saspy#222]
**Describe the bug**
I try to connect to our remote SAS-server through IOM and get the following error:
```
Java Error:
Exception in thread "main" java.lang.NoSuchMethodError: com.sas.services.connection.BridgeServer.setOption(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at pyiom.saspy2j.connect(saspy2j.java:712)
	at pyiom.saspy2j.main(saspy2j.java:213)

Subprocess failed to start. Double check your settings in sascfg_personal.py file.
```

**To Reproduce**
I have used the following configuration (PYTHON_PATH, SERVERNAME and PORT are substituted):
```python
SAS_config_names=['default', 'iom']

SAS_config_options = {'lock_down': False,
                      'verbose'  : True
                     }
SAS_output_options = {'output' : 'html5'}

cpW  =  "C:\\Program Files\\SASHome\\SASDeploymentManager\\9.3\\products\\deploywiz__93550__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.3\\products\\deploywiz__93550__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.3\\products\\deploywiz__93550__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.3\\products\\deploywiz__93550__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cpW += ";*PATH_TO_PYTHON_ENVIRONMENT*\\Lib\\site-packages\\saspy\\java\\saspyiom.jar"
iom  = {'java'    : 'C:\\Program Files (x86)\\Java\\jre1.8.0_201\\bin\\java',
            'iomhost'   : '*SERVERNAME*',
            'iomport'   : *PORT*,
            'encoding'  : 'windows-1252',
            'classpath' : cpW,
            'sspi'			: True
            }
```
and try to start the SAS-session with the following command in a jupyter notebook:
```python
sas = sp.SASsession(cfgfile='../sascfg_personal.py', cfgname='iom')
```

**Desktop:**
 - OS: Windows 7
 - SAS Version: 9.3
 - SASPy Version: 2.43

**Additional context**
I have tried "telnet *SERVERNAME* *PORT*" and it connects.

**Comment by tomweber-sas** [comment]
Hey, given the error:

Exception in thread "main" java.lang.NoSuchMethodError: com.sas.services.connection.BridgeServer.setOption(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

I have to wonder about your jars. Oh, I see this is trying to use version 9.3 of SAS. saspy has a requirement of 9.4. Do you have a 9.4 deployment you can access?

Tom

**Comment by mhldst** [comment]
Hey Tom.
That was it. I looked around and found a 9.4 deployment and managed to get it working.
Thanks

**Comment by mhldst** [comment]
Hey Tom.
That was it. I looked around and found a 9.4 deployment and managed to get it working.
Thanks

**Comment by tomweber-sas** [comment]
Awesome, that's great! Let me know if you need anything else.
Tom
