### ISSUE TITLE
read a sas data set in a library other than SASHELP 

### ISSUE THREAD

**Issue by chungj001** [sassoftware/saspy#224]
Hello
I use spyder as my IDE.
I want to read a sas data set in a library in SAS EG other than SASHELP through saspy. I can read data sets in SASHELP library but I cannot read any sas data set in a library other than SASHELP. Please let me tell me how to resolve this issue.

**Comment by chungj001** [comment]
Hello 
I want to read a sas data set in a library in SAS EG other than SASHELP through saspy.  I can read data sets in SASHELP library but I cannot read any sas data set in a library other than SASHELP.  Please let me tell me how to resolve this issue.

**Comment by jld23** [comment]
You can use the [saslib method](https://sassoftware.github.io/saspy/api.html?highlight=saslib#saspy.SASsession.saslib) to assign a library name. If the libname is defined in your autoexec you can create a sasdata object like this:
```
d = sas.sasdata('mydata', 'foo')
```

**Comment by chungj001** [comment]
In saslib(libref: str, engine: str = ' ', path: str = '', options: str = ' ', prompt: dict = None) → str
Could you please give me an example in the case of SAS EG?  I even do not know the path in SAS server.

**Comment by chungj001** [comment]
A related to question:  how to query sas data set in a pre-assigned libraries in SAS EG? When I turn on SAS EG there are libraries exiting already.  I want to query sas data set from those libraries.

**Comment by tomweber-sas** [comment]
Are you connecting to the same server that you connect to with EG? Can you show the code you are successful with, using the sashelp libref? Maybe that will help. You should just need to use the other librefs that are assigned for you instead of sashelp. Also, can you run the assigned_librefs() method and see what librefs there already are?

Thanks,
Tom

**Comment by chungj001** [comment]
This is my code.  I do not think I use remote desktop connection to connect to SAS server. 
import saspy
sas = saspy.SASsession()
cars = sas.sasdata("CARS","SASHELP")
cars.describe()
# so far this is fine
'''
I have a library named as "XYZ" in a server named as "SASApp" in a Engine 
named as "ODBC".  "XYZ" library is in a location named as "/aaa/bbb" with Libref named as "ABC". 
 "XYZ" library is not ready only. "Hello" table is in "XYZ" library.
'''

temp1 = sas.sasdata("Hello","ABC")
'''
This returns Table ABC.Hello does not exist. This SASdata object will not be useful 
until the data set is created.
'''

sas.assigned_librefs()
'''
This returns ['WORK', 'STPSAMP', 'SASDATA', 'SASHELP', 'MAPS', 'MAPSSAS', 'MAPSGFK', 'SASUSER'] \
This does not include "XYZ" library.

My question: how to query data from "Hello" table in "XYZ" library with "ABC" libref?

**Comment by tomweber-sas** [comment]
Ok, so it sounds like when you connect EG to the SASApp workspace server, libref ABC is preassigned.
Since it's not assigned in the server you had saspy connect to, it doesn't seem that you're connected to that same SASApp server.
What's your configuration definition? Did you specify the appserver key? Are you connecting with the same credentials?

The answer to your question is simply what you tried:
temp1 = sas.sasdata("Hello","ABC")

But, you don't have ABC assigned, so the data isn't there to be accessed.
We need to get you connecting the the same workspace as you connect to with EG.

Tom

**Comment by chungj001** [comment]
I run this line
sas.saslib(libref = 'XYZ', path = '/aaa/bbb')
It returns
libname XYZ    '/aaa/bbb'  ;
NOTE: Library XYZ does not exist.
How to resolve the issue?

**Comment by tomweber-sas** [comment]
Where are you connected to? That means the directory /aaa/bbb doesn't exist, or you don't have permission to access it. Can you submit your SASsession object?
```
sas
```
and show me your configuration definition?

**Comment by tomweber-sas** [comment]
For that matter, how about the following as well
```
print(sas.saslog())
```
thanks,
Tom

**Comment by chungj001** [comment]
'/aaa/bbb' is a meta data location.  It is not a physical location where the "Hello" sas dataset is.  Is there any way to let me run the  code as the below in python?
libname XYZ meta library='XYZ';

**Comment by chungj001** [comment]
Hi Tom,
162        ;*';*";*/;
163        data _null_; e = exist('XYZ.Hello');
164        v = exist('XYZ.Hello', 'VIEW');
165         if e or v then e = 1;
166        te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 0

**Comment by chungj001** [comment]
Is there any way to let me run the code as the below in python?
libname XYZ meta library='XYZ';  

Please guide me please

**Comment by tomweber-sas** [comment]
Yes, that's what the saslib method does:
```
saslib(libref: str, engine: str = ' ', path: str = '', options: str = ' ', prompt: dict = None) 
```
sas.saslib('XYZ', engine='meta', options="library='XYZ'")

**Comment by tomweber-sas** [comment]
The saslib method is just a python methode that generates and submits a libname statement for you.
You can run any code explicitly using the submit method() also. So the saslib() above will do the same thing as the following:
```
res = sas.submit("libname XYZ meta library='XYZ';")

**Comment by tomweber-sas** [comment]
if you follow the submit with this, you should see the same as the log that's shown for saslib()
print(res['LOG'])

**Comment by chungj001** [comment]
After running sas.saslib('XYZ', engine='meta', options="library='XYZ'"), it returns
   libname XYZ meta library='XYZ';
NOTE: Libref XYZ was successfully assigned as follows: 
      Engine:        META 
      Physical Name: EDW

BUT after running temp1 = sas.sasdata("Hello","XYZ"). it returns 
Table XYZ.Hello does not exist. This SASdata object will not be useful until the data set is created.  
How to resolve the issue?

**Comment by tomweber-sas** [comment]
try the following to see what is in that library
```
sas.datasets('XYZ')
```

**Comment by chungj001** [comment]
I run this line sas.assigned_librefs()
Out[16]: 
['WORK',
 'XYZ',
 'STPSAMP',
 'SASDATA',
 'SASHELP',
 'MAPS',
 'MAPSSAS',
 'MAPSGFK',
 'SASUSER']

**Comment by tomweber-sas** [comment]
yes, you assigned XYZ, but there doesn't seem to be a table names Hello in it.

**Comment by chungj001** [comment]
But Hello table does exist within XYZ library.  How to fix this?

**Comment by tomweber-sas** [comment]
show me what 
sas.datasets('XYZ') 
displays

**Comment by chungj001** [comment]
25                                                                                                                       The SAS System                                                                                             11:37 Monday, April 22, 2019

252        
253        proc datasets dd=XYZ;
                                                                                                                           Directory

                                                                                                                 Libref         XYZ            
                                                                                                                 Engine         META           
                                                                                                                 Physical Name  EDW            
                                                                                                                 Schema/Owner   CreditAnalytics
WARNING: No matching members in directory.
253      !                       quit;

NOTE: PROCEDURE DATASETS used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

**Comment by tomweber-sas** [comment]
So, again, where are you connected to? What is your configuration definition you are using? Are you using different credentials than when you connect with EG? You're not connecting to what you think you're connecting to, or not as who you think you are connecting as.

**Comment by chungj001** [comment]
please let me know what I can do to know the exact configuration definition I am using.

**Comment by tomweber-sas** [comment]
well, if you submit your SASsession object, it will tell you which configuration definition name it connected with. and the other line shows you the file it's in
```
sas
sas.sascfg.SAScfg
```
for instance:
```
>>> sas
Access Method         = STDIO
SAS Config name       = sdssas
WORK Path             = /sastmp/SAS_work88A800004FFF_tom64-5/
SAS Version           = 9.04.01M4D11092016
SASPy Version         = 2.4.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = latin9
Python Encoding value = iso8859_15
SAS process Pid value = 20479


>>> sas.sascfg.SAScfg
<module 'saspy.sascfg_personal' from '/opt/tom/github/saspy/saspy/sascfg_personal.py'>
>>>
```

**Comment by chungj001** [comment]
sas
Out[23]: 
Access Method         = IOM
SAS Config name       = autogen_winlocal
WORK Path             = H:\saswork\_TD9444_DEV-SASAPPDB1_\Prc2\
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 2.4.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = windows-1252
SAS process Pid value = 9444

**Comment by chungj001** [comment]
sas.sascfg.SAScfg
Out[24]: <module 'saspy.sascfg_personal' from 'C:\\Users\\chungj\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\saspy\\sascfg_personal.py'>

Please guide me further after this

**Comment by tomweber-sas** [comment]
Yes, so you are connecting saspy to your local SAS deployment on your own PC. But EG is configured to connect to the remote workspace server SASApp, presumably on a linux system somewhere, based upon the file system paths you showed.

You need to follow the configuration instructions to add another configuration definition to your sascfg_personal.py file to use to connect to the remote workspace server that EG connects to, then all of your data will be there and accessible.

Read https://sassoftware.github.io/saspy/install.html#iom
Your autogen_winlocal is a Local config def, but you need a Remote one for the workspace server you're trying to connect to.

Since you have most of what you need in the file and working already (classpath, a local config def,....),
it should be easy to add another config def and you will need the host where the object spawner is running, the port for the workspace server and your metadata credentials (which you can put in the _authinfo file so you don't have to type them in each time you connect). You may need to use the appserver key as well, but I can't tell that from here.

Thanks,
Tom

**Comment by chungj001** [comment]
For this https://sassoftware.github.io/saspy/install.html#iom,  do I need to look into IOM section and Remote all together?

**Comment by tomweber-sas** [comment]
Yes

**Comment by chungj001** [comment]
How to find out the host where the object spawner is running and the port for the workspace serve?

**Comment by tomweber-sas** [comment]
You could look at your EG configuration. Ask whoever administers those servers. Or see the follow doc https://sassoftware.github.io/saspy/advanced-topics.html#using-proc-iomoperate-to-find-object-spawner-hosts-and-workspace-server-ports
You can run those queries from EG.

**Comment by chungj001** [comment]
Currently sascfg_personal.py file has  

SAS_config_names=["autogen_winlocal"]
SAS_config_options = {
	"lock_down": False,
	"verbose"  : True
	}

cpW  =  "C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cpW += ";C:\\Users\\chungj\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\saspy\\java\\saspyiom.jar"

autogen_winlocal={
......
......
}

My question: to connect to the remote workspace server that EG connects to, do I need to change the current content of cpW?  I guess what I need: 1. create another SAS_config_names, 2. duplicate the content of SAS_config_options, 3. within a new created SAS_config_names, at least provide a new iomhost, a new iomport?  Please let me if there is something I miss.  Thanks

**Comment by chungj001** [comment]
Another question: Iin proc iomoperate
  uri="iom://omrhost.abc.xyz.com:8561;Bridge;USER=omruserid,PASS=omrpasswd";
  list DEFINED FILTER="Object";
quit;
How to find out uri?

**Comment by tomweber-sas** [comment]
No, you don't do anything with the classpath, that's correct and it's on your PC.
Yes, you add another configuration definintion, copy autogen_winlocal and change the name and then add that name to the SAS_config_name list

```
SAS_config_names=["autogen_winlocal", "EGserver"]
SAS_config_options = {
"lock_down": False,
"verbose" : True
}

cpW = "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94470__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar"
cpW += ";C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94470__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar"
cpW += ";C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94470__prt__xx__sp0__1\deploywiz\sas.core.jar"
cpW += ";C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94470__prt__xx__sp0__1\deploywiz\log4j.jar"
cpW += ";C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\saspy\java\saspyiom.jar"

autogen_winlocal={
......
......
}

EGserver={
......
......
}
```
For the IOM query, the host is the metadata server host and it's port. Again, can't you get any of that from how you've configured EG?

**Comment by tomweber-sas** [comment]
I don't use EG, but i did bring it up and pointed it to a workspace server. If you click properties on a server it shows you the host and port. Have you tried that?
![image](https://user-images.githubusercontent.com/17710182/56609195-8202ac80-65da-11e9-9227-8d0aa04a8e7c.png)

**Comment by chungj001** [comment]
Let me try it.  Is it necessary to see host name to start with "www"?  Thanks

**Comment by tomweber-sas** [comment]
I'm sorry, I don't understand that question.

**Comment by chungj001** [comment]
I meant that the host is www. something something.  I will talk to system administrator to get more inform. Thank you

**Comment by tomweber-sas** [comment]
yes, they would know. I have no idea what your hostnames are. I've not seen anything to have any idea.
Can you run the proc iomoperate queries and show me their output? Then I should be able to tell.
Isn't the metadata server host/port in your EG profile? And I think the object spawner host and metadata server port are what I showed before in the properties of the EG server. Though that host could be the metadata server; I can't tell from any doc nor from any deployment I can connect to because they are all a single machine deployment, so it's the same host name.

Why don't you run the queries and let's look at the output? And, you can just try the host from the server properties and see if it works; it probably IS the obj spawner, and the port is the workspace server port, so that might just be it.

**Comment by chungj001** [comment]
Hi Tom,
I can access the SAS table via SASPY.   The issue is resolved. You can close the ticket.  Thank you.

**Comment by tomweber-sas** [comment]
That's great, thanks for letting me know. 
Tom

**Comment by bikashten** [comment]
Hello,
Do we have the solution for this issue? I am trying to access the data in SASAPP server using SASPY. I am using the remote desktop to access the office desktop due to a covid-19. Before jump in to the SASApp data, I am using this simple code, but I keep getting error.

import saspy
sas = saspy.SASsession()

but I got this error
Traceback (most recent call last):
  File "C:/Users/BBhandari2/Desktop/Python/template/dang2.py", line 2, in <module>
    sas = saspy.SASsession()
  File "C:\Users\BBhandari2\Desktop\Python\template\venv\lib\site-packages\saspy\sasbase.py", line 485, in __init__
    raise SASIONotSupportedError(self.sascfg.mode, alts=['IOM'])
saspy.sasexceptions.SASIONotSupportedError: Cannot use STDIO I/O module on Windows. Try the following: IOM

I am looking for a help.

**Comment by chungj001** [comment]
Is covid-19 referred to Wuhan virus?

J

**Comment by tomweber-sas** [comment]
Yes, this issue was resolved. It sounds like you have you own issue. Can you open an issue for this and I'll help you thorough it!
Thanks,
Tom

**Comment by bikashten** [comment]
Thank you guys. I created the issue a few hour ago. I think @chungj001 know more about this issue too, I am trying to do a quite similar project like access the SASAPP server data and manipulated them in a Python. Here is my picture for server. 
![image](https://user-images.githubusercontent.com/67710829/86487940-79088180-bd2d-11ea-90db-92f8fd21359d.png)

**Comment by chungj001** [comment]
Do you mind telling me how big your SAS dataset is?

**Comment by tomweber-sas** [comment]
Hey, do you both want to switch over to #304 so all the discussion is in one thread? Thanks! That'll just be more helpful in the long run 😎

**Comment by chungj001** [comment]
sure.  Let me know what issues are.  Maybe I can give help.  I struggled
with saspy before and finally resolved the issues I had.

Jason

**Comment by bikashten** [comment]
@tomweber-sas It looks like it is working. I restarted the pycharm and run the same code again. I got this message: 
sas = saspy.SASsession()
Using SAS Config named: bikash_test
SAS Connection established. Subprocess id is 32464
No encoding value provided. Will try to determine the correct encoding.
Setting encoding to cp1252 based upon the SAS session encoding value of wlatin1.

**Comment by tomweber-sas** [comment]
Ah, you switched issues :)   Yes, if you added that path to your config, you would need to restart the python process for it to see the change. So then, you do have that file there, it would appear. Do you have SAS installed on that client? I'm guessing you do?

**Comment by kshank5** [comment]
@tomweber-sas  Hi Tom -  I need help with a similar issue but with SaS Academic OnDemand version. I am connecting to the ondemand version and the session is created. However, it will not recognize any of my libraries. I am able to run sample codes to test my session with the SASHELP.CARS data. I tried qualifying the my library (Mylib) with the full pathname etc. Nothing has worked so far. 

`print(sas.dirlist('/home/kshank0/EPG1V2/1_ Stats Programming/Final Project/')) `
is able to list the files in this directory. But the following will only list the SAS standard libraries.
```
for libref in sas.assigned_librefs():
    print(libref)
```

WORK
SASDATA
STPSAMP
SASHELP
MAPS
MAPSSAS
MAPSGFK
SASUSER
SAS

Finally, even if I have a table under WORK, it gives the error "Table WORK.stroke does not exist. This SASdata object will not be useful until the data set is created."

I read through this thread but dont understand what I need to do to fix it in the ondemand version. Please help. Thank you!
K

**Comment by tomweber-sas** [comment]
@kshank5 can you open a new issue for this. I tried converting this bit that didn't do what I thought it would. This is a closed, 5 year old issue. Just open a new issue with your information in it please.
Thanks,
Tom
