### ISSUE TITLE
What is an efficient way to convert a big SASDATA to a pandas dataframe?

### ISSUE THREAD

**Issue by chungj001** [sassoftware/saspy#229]
Hello 

type(temp2)  returns  saspy.sasdata.SASdata.
Now I want to convert temp2 to be a Pandas Dataframe.   
I use temp2_1=temp2.to_df(method='CSV').  

It takes a long while.  Are there any other suggestions?  
Thanks
Jason

**Comment by tomweber-sas** [comment]
Well, is this the same as with the following error? I would seem the data is more than you can fit in memory of your python process on your client. Which would speak to why it took a 'long while' to transfer the data over. Can you run a contents() on that data set to see what the size of it is and rows and record length?

```
I got this error with this big file.  Any suggestions to resolve the issue are very welcome.

temp3_1=temp3.to_df(method='CSV')
Traceback (most recent call last):

  File "<ipython-input-7-2d5f90532ab9>", line 1, in <module>
    temp3_1=temp3.to_df(method='CSV')

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\saspy\sasdata.py", line 991, in to_df
    return self.sas.sasdata2dataframe(self.table, self.libref, self.dsopts, method, **kwargs)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\saspy\sasbase.py", line 985, in sasdata2dataframe
    return self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\saspy\sasioiom.py", line 1474, in sasdata2dataframe
    return self.sasdata2dataframeCSV(table, libref, dsopts, **kwargs)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\saspy\sasioiom.py", line 1858, in sasdata2dataframeCSV
    df = pd.read_csv(tmpcsv, index_col=False, engine='c', dtype=dts, **kwargs)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 446, in _read
    data = parser.read(nrows)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1051, in read
    df = DataFrame(col_dict, columns=columns, index=index)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 348, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 459, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py", line 7364, in _arrays_to_mgr
    return create_block_manager_from_arrays(arrays, arr_names, axes)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals.py", line 4872, in create_block_manager_from_arrays
    blocks = form_blocks(arrays, names, axes)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals.py", line 4938, in form_blocks
    object_blocks = _simple_blockify(items_dict['ObjectBlock'], np.object_)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals.py", line 4976, in _simple_blockify
    values, placement = _stack_arrays(tuples, dtype)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\internals.py", line 5037, in _stack_arrays
    stacked = np.empty(shape, dtype=dtype)

MemoryError
```

**Comment by chungj001** [comment]
For this case how to resolve the issue?

**Comment by tomweber-sas** [comment]
Well, I have no real information with which to base a decision on exactly what the problem is. But, I see from the traceback, and your comment that it 'took a while', that it apparently exported a large SAS data set as a CSV file, transferred that file from the server to your client and wrote it to disk. Then it called the pandas method to read in the csv file and create a data frame from it. That's what failed above with 'MemoryError'.

Having no other information to go on, I would guess you don't have enough memory on your client computer for pandas to load that much data into the python process. But, you should be able to assess that since you're on the computer and can see what processes are running and what the memory consumption is and anything else happening on there. 

I don't know what other possibilities there are for getting that error in that layer of pandas code, but this would be the first thing I would look into.

Have you tried to pull only a subset of the data, to see if that works or if there's really some other problem going on? I don't have any information to assess this from here.

Thanks,
Tom

**Comment by chungj001** [comment]
I will put only a subset of the data.  Another question:  I got this as the following:

temp3_1.to_pickle('HOB_temp3_1')
Traceback (most recent call last):

  File "<ipython-input-17-4c7ae4e845a0>", line 1, in <module>
    temp3_1.to_pickle('HOB_temp3_1')

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py", line 2192, in to_pickle
    protocol=protocol)

  File "C:\Users\chungj\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\pickle.py", line 77, in to_pickle
    f.write(pkl.dumps(obj, protocol=protocol))

OSError: [Errno 28] No space left on device

My question:  What is the meaning of "no space left on device"?  Is it pickle the best way to save dataframe in a disk drive?  What are other better ways to use pickle?

**Comment by tomweber-sas** [comment]
So, it worked with a subset of the data?

I'm afraid I don't know much about pickle or storing data frames. That errors sounds like now you're out of disk space, but again, I have nothing to go on here, so I don't know. Can you see where it's trying to write and if there's space?

**Comment by chungj001** [comment]
The second question (pickle) I asked is a separate issue.  I will tackle it later.  For the first one I will pull some of sasdata to see if the issue still exists.   We know type(temp2) returns saspy.sasdata.SASdata.
My question is how to save temp2 as a physical file so that after I quite python I can still access temp2.  Also if I can save temp2 as a physical file, how to access it later?

**Comment by tomweber-sas** [comment]
well, temp2 is a SASdata object. That;s just a python reference to a SAS Data Set on your SAS server. I don't necessarily understand why you're trying to pull all of that data (as it's too big for your pc), onto your pc in python and save it to disk (that you don't have enough of) so you can use it in python by itself later. Is that what you're trying to do? The SAS data set never went away on your SAS server and it's there to access whenever you connect back. Can you explain what you are really trying to do?

As for saving pandas data frames, I don't know what you should do. That's not really my area. I think all these questions really depend on what you're really trying to do.

**Comment by chungj001** [comment]
I got your point, Tom.   Subset of data is important.  This is what I am doing. 
temp1  is in WORK libref.  temp1 is a small subset of a very big subset of temp0, which is a sas dataset.
Then I type temp3=sas.sasdata("TEMP_1","WORK")
Then  I got
Table WORK.TEMP_1 does not exist. This SASdata object will not be useful until the data set is created. 
How to fix this problem?

**Comment by tomweber-sas** [comment]
you don't have a data set named temp_1 in the work library on that server.

**Comment by chungj001** [comment]
I got your point.  
A question:  since we can use read_sas method to access a sas dataset,  what is the benefit to use SASPY  API?

**Comment by tomweber-sas** [comment]
If the only thing you want to do is read a .sas7bdat file into python as a pandas data frame, then nothing.
If you are trying to **use** SAS but interface to it from python, then everything. 
I'm really not sure what you are trying to do, so I'm not sure which path you should choose.

Perhaps read through this example notebook to get an idea of what the whole point of saspy is, and then you may have a better idea of if it is or isn't something you would be using to do whatever it is you're trying to accomplish.
 https://github.com/sassoftware/saspy-examples/blob/master/SAS_contrib/saspy_example_github.ipynb

That notebook is a good basic overview of the kinds of things you would use this for. Of course there's more, but that should get the concept across as a start.

Tom

**Comment by chungj001** [comment]
Got it.  Thank you.  I  close this issue.
