### ISSUE TITLE
Windows: SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 3-4: truncated \UXXXXXXXX escape

### ISSUE THREAD

**Issue by tomweber-sas** [sassoftware/saspy#23]
Got a message from someone not able to run local windows. The error was flagged in there sascfg.py on their classpath line. I've reproduced the error (which I hadn't seen before) and am documenting it here. I'll add it to the Troubleshooting doc next. 
The problem is having a \u  or \U (either way) in a string - like in the classpath in the sascfg.py file:

cpW += ";C:\Users\user\AppData\Roaming\Python\Python36\site-packages\saspy\java\saspyiom.jar"

The error is like in the title of this issue. The fix is to either code \\u or \\U  anywhere you happen to have \u in you strings, or prefix the string with an 'r' (for raw string - don't transcode) as follows (either of these will work):

cpW += ";C:\\Users\user\AppData\Roaming\Python\Python36\site-packages\saspy\java\saspyiom.jar"
cpW += r";C:\Users\user\AppData\Roaming\Python\Python36\site-packages\saspy\java\saspyiom.jar"

**Comment by tomweber-sas** [comment]
I've added this problem to the install doc where it talks about the classpath for windows (where it will be hit). Closing this out now. Btw, adjusted the doc version to match the repo/pypi version. everything is at 2.1.4 now.

**Comment by execptionerror** [comment]
Already Solved [SyntaxError: (unicode error) ‘unicodeescape’ codec can’t decode bytes in position 2-3: truncated \UXXXXXXXX escape](https://flutterq.com/syntaxerror-unicode-error-unicodeescape-codec-cant-decode-bytes-in-position-2-3-trunca/)
