### ISSUE TITLE
Error in authkey after installing saspy library on windows sas 9.4

### ISSUE THREAD

**Issue by Nrad06** [sassoftware/saspy#233]
**Describe the bug**
Hello,
I just installed the saspy library using pip install saspy from the command line on WIndows 7. Then I called import saspy from a cell in Jupyter and gor the following error:

File "C:\ProgramData\Anaconda3\lib\site-packages\saspy\sascfg.py", line 208
    'authkey' : 'viya_user-pw',
              ^
SyntaxError: invalid syntax

I have attached the sascfg.py file here:
[sascfg.py.txt](https://github.com/sassoftware/saspy/files/3173935/sascfg.py.txt)

I am not sure where to make the changes to the config file to make it work in my environment.

Best regards,
Nick

**Desktop (please complete the following information):**
 - OS: Windows 7 
 - SAS Version:  9.4M6
 - SASPy Version: latest as of May 12th, 2019

**Comment by tomweber-sas** [comment]
Aw man, that's my bad. It's missing a comma in the new http examples at the bottom of the file. 
You can just add tha comma or delete those whole config definitions, as you probably aren't using those in your sascfg_personal.py file anyway. 


Here;s the problem:
```
# HTTP access method to connect to the Compute Service
# These need ip addr, other values will be prompted for - python Dict
# valid keys are:
# 'ip'      - [REQUIRED] host address 
# 'port'    - port; the code Defaults this to based upon the 'ssl' key; 443 default else 80
# 'ssl'     - whether to use HTTPS or just HTTP protocal. Default is True, using ssl and poort 443
# 'context' - context name defined on the compute service  [PROMTED for at runtime if more than one defined]
# 'authkey' - identifier for user/password credentials to read from .authinfo file. Eliminates prompting for credentials.
# 'options' - SAS options to include (no '-' (dashes), just option names and values)
# 'user'    - not suggested [REQUIRED but PROMTED for at runtime]
# 'pw'      - really not suggested [REQUIRED but PROMTED for at runtime]
# 
#
             
httpsviya = {'ip'      : 'sastpw.rndk8s.openstack.sas.com',
             'context' : 'Data Mining compute context'                 <---- missing coma here
             'authkey' : 'viya_user-pw',
             'options' : ["fullstimer", "memsize=1G"]
             }

httpviya = {'ip'      : 'sastpw.rndk8s.openstack.sas.com',
            'ssl'     : False,  # this will use port 80
            'context' : 'Data Mining compute context'                <---- missing coma here
            'authkey' : 'viya_user-pw',
            'options' : ["fullstimer", "memsize=1G"]
            }
```

**Comment by Nrad06** [comment]
Thank you Tom. No worries, actually I am glad it was just that. It works now.

**Comment by tomweber-sas** [comment]
Cool, sorry about that. I'm going to reopen this just so it right there up front in case someone else hits this; they'll hopefully sew this. I'll close it back after I push a new release with the fix, so it's really gone out pf pypi and all.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
V3.0.0 is now the current pypi version and has this fix, so closing this issue now.

Thanks,
Tom
