### ISSUE TITLE
SASIONotSupportedError

### ISSUE THREAD

**Issue by Nrad06** [sassoftware/saspy#234]
**Describe the bug**
I let autocfg.opy generate my sascfg_personal.py file and everything seems to be int he right p
place/path but I keep getting this error:

SASIONotSupportedError                    Traceback (most recent call last)
<ipython-input-36-3a4eee4acd25> in <module>()
----> 1 sas = saspy.SASsession()
      2 sas

C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py in __init__(self, **kwargs)
    316                 self._io = SASsessionSTDIO(sascfgname=self.sascfg.name, sb=self, **kwargs)
    317             else:
--> 318                 raise SASIONotSupportedError(self.sascfg.mode, alts=['IOM'])
    319         elif self.sascfg.mode == 'IOM':
    320             self._io = SASsessionIOM(sascfgname=self.sascfg.name, sb=self, **kwargs)

SASIONotSupportedError: Cannot use STDIO I/O module on Windows. Try the following: IOM

Where do I tell it to use the IOM method?

[sascfg_personal.py.txt](https://github.com/sassoftware/saspy/files/3175067/sascfg_personal.py.txt)

 - OS: Windows 7
 - SAS Version: 9.4m6
 - SASPy Version: latest

**Comment by tomweber-sas** [comment]
Yes, that looks fine. So my guess is that the file it's in isn't what is being picked up but rather the sascfg.py example file in the repo. 

Submit the following to see which resolves and to what file. The autocfg program should tell you the filename it created, also.

import saspy
saspy.sascfg
saspy.sascfg_personal

I think sascfg will be what it's finding and using.
Tom

**Comment by Nrad06** [comment]
Thanks Tom. It is using the sascfg_personal now. 
But I ran into another issue. I believe it has to do with java. The version I am using is 1.8.0_211). 

This is the error I get when I run sas= saspy.SASsession():
Using SAS Config named: autogen_winlocal
The OS Error was:
The system cannot find the file specified

SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94524__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94524__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94524__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94524__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '49604', '-stdoutport', '49605', '-stderrport', '49606', '-zero', '-lrecl', '1048576', '']

This is the error I get when I run the java command with the list of SAS jar files in my path:
"The native implementation module for the security package could not be found in the path"

**Comment by tomweber-sas** [comment]
Sorry, on my phone at the moment so terse. These are all in the troubleshooting guide in the doc, if you can look at the doc. 
The first error is that in whatever environment you are running saspy, 'java' isn't in there PATH, so it's not found. You can specify the fully qualified path to it in your config so it will be found. 
In the second case, wherever you ran Java, did have it in its path to be found. But you don't have the sspiauth.dll for in your path. For your saspy case that is added in the config file for you, so it will be found. 
You can give the path to Java as a parameter to the autocfg, or just edit the file after. See the doc on the autocfg for examples- it's in the example notebook.
Ok, maybe this wasn't terse 😁
Tom

**Comment by Nrad06** [comment]
Hi Tom. I did have the path pointing to the newly installed java.exe file. But then I tried this file instead: "c:\\Program Files\\SASHome\\SASPrivateJavaRuntimeEnvironment\\9.4\\jre\\bin\\java.exe"  and it worked like a charm. Thanks!

**Comment by tomweber-sas** [comment]
Good deal. Though the error you showed had the java command as only 'java' with no filesystem path as part of it:

```
Attempted to run program java with the following parameters:[**'java'**, '-classpath', 'C:\Program ...
```
But, I'm glad you're up and running!
Tom

**Comment by tomweber-sas** [comment]
So, is this one also able to be closed then? You're up and running?

Thanks,
Tom

**Comment by Nrad06** [comment]
Yes I am and running. Thank you!
