### ISSUE TITLE
hist() fails with some column names 

### ISSUE THREAD

**Issue by tomweber-sas** [sassoftware/saspy#235]
Got an email question about a failure when using some census data which has some column names containing dashes, which aren't valid SAS variable names, but can be used if quoted in SAS as n-literals: 'column-name'n

I'll need to go through all the methods that take column names and see about wrapping the column names with n-literal syntax so that these don't fail, and the saspy user doesn't have to pass then through wrapped as n-literals in python - that will work, but shouldn't have to be done by the user.

email reaponse:
Hey, I had a chance to play with this and it is what I suspected. A dash isn’t a valid part of a SAS name, so any column name with that has to be wrapped as an n-literal to work. If I do that in saspy it works, but I’ll see about adding that to the saspy code, to do it, so you (the user) doesn’t have to. I’ll have to make sure that won’t cause a problem, which I don’t think it will.

census.hist("education-num")
fails:
```
48621      proc sgplot data=WORK.census;
48622          histogram education-num / scale=count;
                               _
                               22
                               200
ERROR: Variable EDUCATION not found.
48623          density education-num;
                             _
                             22
                             200
ERROR: Variable EDUCATION not found.
ERROR 22-322: Syntax error, expecting one of the following: ;, /.  
ERROR 200-322: The symbol is not recognized and will be ignored.
48624      run;

NOTE: The SAS System stopped processing this step because of errors.
NOTE: PROCEDURE SGPLOT used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
```
census.hist("’education-num’n")
succeeds:
```
48577      proc sgplot data=WORK.census;
48578          histogram 'education-num'n / scale=count;
48579          density 'education-num'n;
48580      run;

NOTE: PROCEDURE SGPLOT used (Total process time):
      real time           0.27 seconds
      cpu time            0.09 seconds
      
NOTE: There were 45222 observations read from the data set WORK.CENSUS.
```
Thanks,
Tom

**Comment by tomweber-sas** [comment]
I've fixed this (at master) to wrap provided variable name parameters w/ n-literal syntax for the following methods:
heatmap, hist, top, bar, series, scatter, 

There still exist places where users can specify variable names, where they would need to code the '...'n themselves, as I am not trying to parse and replace what they have, like a where clause, for instance.. And the by= parameter in sort() which takes a string of the form: 
(BY <DESCENDING> variable-1 <<DESCENDING> variable-2 ...>;)

But this cleans up all of these plotting methods which take a variable names as parameters, and should do this for the user, as it's a SAS-ism that should be hidden from python side code as much as possible.

Tom

**Comment by tomweber-sas** [comment]
So, another place where a user types in a string that contains variables (and other stuff) is in the analytic methods. For instance in the simple stat.reg() example:
```
stat_results = stat.reg(model="horsepower = Cylinders EngineSize",data=cars)
```
the model statement is a free form string. In this example it only contains variable names, but all the various statements for all the various analytics aren't only variables, such that saspy would blindly '...'n everything in them. So, had hosrsepower been named horse-power (an invalid sas name), to get this to work you would have to specify:
```
stat_results = stat.reg(model="'horse-power'n = Cylinders EngineSize",data=cars)
```
And, prior to the fix I just pushed this would have gotten an error in some internal libname generation from ODS outputs names. But now this runs clean with that fix for n-literals. 

Tom

**Comment by tomweber-sas** [comment]
Here's another example of an analytic method using that original census data from the first post on here.
Showing how to code up multiple statements, which aren't necessarily only variable names in the string.
```
univariate_results = util.univariate(data=census, var="'capital-gain'n 'capital-loss'n",
                                     histogram = "'capital-gain'n 'capital-loss'n / VSCALE=PERCENT")
```

**Comment by ngrajales1** [comment]
Thank you Tom! You have been a great help in resolving this issue. I really appreciate the quick response and fix.
