### ISSUE TITLE
The application could not log on to the server "localhost:0". Integrated Windows authentication failed. 

### ISSUE THREAD

**Issue by tudou531** [sassoftware/saspy#236]
When I'm using anaconda prompt to activate python and entering below code:
import saspy
sas=saspy.SASsession()

I'll get below error:

![image](https://user-images.githubusercontent.com/34270174/58395293-0339dd00-807a-11e9-9d1a-e233da8460e9.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - SAS Version: 9.4
 - SASPy Version: 

Could you please help me with it? Thank you a lot.

**Comment by FriedEgg** [comment]
On the last line of your screen shot it points you toward the most likely source of your issue.  Using WINLOCAL configuration has an additional requirement you are expected to configure outside of Python.  See the second paragraph or the documentation for this connection configuration.

https://sassoftware.github.io/saspy/install.html#local

**Comment by tudou531** [comment]
Thanks a lot for your reply, I've set the user environment variable, it's point to the sas path.
![image](https://user-images.githubusercontent.com/34270174/58464598-92bdb980-8168-11e9-9813-99b89aba5837.png)

But I don't have admin access to update the path in system environment variable, I'm not if it's the reason why it doesn't work.

**Comment by tomweber-sas** [comment]
Can I see your configuration definition; your config file? Also, did you try running the autocfg.py file:
https://sassoftware.github.io/saspy/install.html#local

That will add the sspi path in the config script so it doesn't have to be in the system path. You'll see it in the config file it generates, So you can do it that way if you can't update the system path.

Thanks,
Tom

**Comment by tudou531** [comment]
Hi Tom,

Thank you so much for your help. sorry for the late reply.

I try to run the autocfg.py file, but it fails as below:
![image](https://user-images.githubusercontent.com/34270174/58771070-e440cb00-85e4-11e9-9839-573bf16fe0fb.png)

Could you give some input about it?
Because in my computer the SASHOME is not same as the normal one.

**Comment by tomweber-sas** [comment]
Hey, so all you really need in that config is like in the example notebook:
```
SAS_config_names=["autogen_winlocal"]

SAS_config_options = {
	"lock_down": False,
	"verbose"  : True
	}

cpW  =  "C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94508__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94508__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94508__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94508__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\lib\\site-packages\\saspy\\java\\saspyiom.jar"

autogen_winlocal = {
	"java"      : "java",
	"encoding"  : "windows-1252",
	"classpath" : cpW
	}

import os
os.environ["PATH"] += ";C:\\Program Files\\SASHome\\SASFoundation\\9.4\\core\\sasext"
```

So, what's in any of your config files? I am guessing that you pretty much have all of this with the exception of the sspi bit. If your classpath is ok, and the other pieces are ok too, which I suspect they are, you just need to put the sspi path in there. That's what seemed to be missing from the start and it sounded like you can't add it to your path. So find the directory where the sspiauth.dll is and add that to your config file like the following:
```
import os
os.environ["PATH"] += ";C:\\Program Files\\SASHome\\SASFoundation\\9.4\\core\\sasext"
```

With that in the config file, does it connect?

Thanks!
Tom

**Comment by tudou531** [comment]
Hi Tom,

My sascfg_personal.py file is like below:
SAS_config_names=["winlocal"]

cpW  =  "C:\\Program Files\\SAS94 32 bit\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";C:\\Program Files\\SAS94 32 bit\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cpW += ";C:\\Program Files\\SAS94 32 bit\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";C:\\Program Files\\SAS94 32 bit\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar"


SAS_config_options = {
	"lock_down": False,
	"verbose"  : True
	}

# Windows client and Local Windows IOM server
winlocal    = {'java'      : 'C:\ProgramData\Oracle\Java\javapath\java.exe',
               'encoding'  : 'windows-1252',
               'classpath' : cpW,
			   'javaparms': ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd="C:\\PROGRA~1\\SAS94 32 bit\\x86\\SASFOU~1\\9.4\\SAS.EXE" -config "C:\\PROGRA~1\\SAS94 32 bit\\x86\\SASFOU~1\\9.4\\sasv9.cfg" -objectserver -nologo -noterminal -noprngetlist']
              }

import os
os.environ["PATH"] += ";C:\\Program Files\\SAS94 32 bit\\x86\\SASFoundation\\9.4\\core\\sasext"

the path is what's inside my computer. I'm not sure why it's not working after I make the update.
Could you give some more help on it.
![image](https://user-images.githubusercontent.com/34270174/59016271-75c56c80-8873-11e9-9b4a-f90a0d1909c8.png)

There are three py file inside my saspy folder, could you please help me check if there are any issue with them? 

[autocfg.txt](https://github.com/sassoftware/saspy/files/3260534/autocfg.txt)
[sascfg.txt](https://github.com/sassoftware/saspy/files/3260535/sascfg.txt)
[sascfg_personal.txt](https://github.com/sassoftware/saspy/files/3260536/sascfg_personal.txt)

**Comment by tomweber-sas** [comment]
Well, that all would seem correct. This specific error has a tech support track associated with it which implies that your etc/hosts file may not have localhost defined correctly as 127.0.0.1. 
http://support.sas.com/kb/55/227.html
Can you see what's in your hosts file? Probably a path like this: C:\Windows\System32\drivers\etc\hosts
though it may be slightly different on a 32 bit system - I don't have one of those to look at.

BTW, why the javaparms? Can you not fix your registry with the [C:\...\]sas.exe /regserver  command documented in number 5 here:
https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors

https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors

That would eliminate all of that extra junk in your config. 

But lets look at your hosts file first.
Also, from a command prompt, can you run the following as well
ipconfig /all
nslookup localhost
nslookup 127.0.0.1

Thanks,
Tom

**Comment by FriedEgg** [comment]
What version of Java?

Try using the java included with your SAS installation.  Path should be something like:
`C:\Program Files\SAS94 32 bit\SASPrivateJavaRuntime\9.4\jre\bin\java.exe`

Rather than the os.environ["PATH"] method try the following:
```
# Windows client and Local Windows IOM server
winlocal    = {'java'      : 'C:\ProgramData\Oracle\Java\javapath\java.exe',
               'encoding'  : 'windows-1252',
               'classpath' : cpW,
               'javaparms': ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd="C:\\PROGRA~1\\SAS943~1\\x86\\SASFOU~1\\9.4\\SAS.EXE" -config "C:\\PROGRA~1\\SAS9432~1\\x86\\SASFOU~1\\9.4\\sasv9.cfg" -objectserver -nologo -noterminal -noprngetlist',-Djava.library.path="C:\\PROGRA~1\\SAS943~1\\x86\\SASFOU~1\\9.4\\sasext]
              }
```

**Comment by tudou531** [comment]
Hi Fried,

I've made the update to sascfg_personal.py as below:
# Windows client and Local Windows IOM server
winlocal    = {'java'      : 'C:\Program Files\SAS94 32 bit\x86\SASPrivateJavaRuntimeEnvironment\9.4\jre\bin',
               'encoding'  : 'windows-1252',
               'classpath' : cpW,
               'javaparms': ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd="C:\\PROGRA~1\\SAS943~1\\x86\\SASFOU~1\\9.4\\SAS.EXE" -config "C:\\PROGRA~1\\SAS9432~1\\x86\\SASFOU~1\\9.4\\sasv9.cfg" -objectserver -nologo -noterminal -noprngetlist, -Djava.library.path="C:\\PROGRA~1\\SAS943~1\\x86\\SASFOU~1\\9.4\\sasext"']
              }

it got below error:
![image](https://user-images.githubusercontent.com/34270174/59076273-cd151c80-8907-11e9-8ec0-0b7360c6918f.png)

Thank you so much.

**Comment by tudou531** [comment]
Hi Tom,

Thank you for your help. 

when I run  "nslookup localhost" command it shows our company server and address.
companyserver.com can't find localhost: Non-existent domain.

when I run "nslookup 127.0.0.1" it shows:
Server:  companyserver.com
Address:  companyserver address

Name:    localhost
Address:  127.0.0.1

Thanks again.

**Comment by FriedEgg** [comment]
Seems like @tomweber-sas is onto something with your hosts file being the current issue.

**Comment by tomweber-sas** [comment]
Yeah, that seems to correlate with the tech support track. What's in your hosts file?

**Comment by tudou531** [comment]
hi Tom，

inside my hosts file only have three lines:
the first two lines are company cloudmail address, another one is the localhost:
![image](https://user-images.githubusercontent.com/34270174/59181396-dc12fd80-8b99-11e9-8c0c-1e571f5158d0.png)

Thanks again.

**Comment by tomweber-sas** [comment]
Yep, that's the problem. The IOM client needs 'localhost' to resolve. You can try adding localhost to that line (after the # is just comment):
```
127.0.0.1 localhost view-localhost # view localhost server
```
I think you can list multiple aliases on one line. At least you can on linux. Else, just try making it only
```
127.0.0.1 localhost
```
to see if it works. No idea why this would have view-localhost. Don't know what that's supposed to be.

**Comment by tudou531** [comment]
Thank you so much Tom, I believe it will work on my personal computer, thanks a lot.
