### ISSUE TITLE
saspy unable to connect to SAS Linux server from a windows client

### ISSUE THREAD

**Issue by veerendra-pappoppula** [sassoftware/saspy#240]
[cfg.txt](https://github.com/sassoftware/saspy/files/3277885/cfg.txt)

I edited the cfg file accordingly, but I am getting an error when i try to run this,

saspy.SASsession(cfgfile='C:/Python/Lib/site-packages/saspy/sascfg.py')

Error:

Using SAS Config named: default
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    saspy.SASsession(cfgfile='C:/Python/Lib/site-packages/saspy/sascfg.py')
  File "C:\Python\lib\site-packages\saspy\sasbase.py", line 340, in __init__
    raise SASIONotSupportedError(self.sascfg.mode, alts=['IOM'])
saspy.sasexceptions.SASIONotSupportedError: Cannot use STDIO I/O module on Windows. Try the following: IOM

I did not make any environment variable change for saspy.

**Comment by tomweber-sas** [comment]
Well, the attached cfg.txt file isn't the file that was used which produced that error. It has:
SAS_config_names=['winiomlinux']
so there's only one configuration definition and it's named winiomlinux but this failure is because the config file this used only had 'default' and that uses the STDIO access method, which you can't use to connect like you want to.
So, you're not using a valid configuration. I can't tell from this though what files you have where or what's in them. That looks like the example config file from the saspy install that it's using.

**Comment by veerendra-pappoppula** [comment]
I made a copy of the cfg file and edited the actual file. Am i missing any step. What files do I need to provide?

**Comment by tomweber-sas** [comment]
Well, I'm still not quite clear on what you have. But here are the instructions for configuring this:
https://sassoftware.github.io/saspy/install.html#configuration

You want to use the IOM Access method
https://sassoftware.github.io/saspy/install.html#iom-using-java

and specifically the Remote version of the configuration
https://sassoftware.github.io/saspy/install.html#remote

The sample named winiomlinux that you seemed to be trying to use is the right example. From the file you had attached, all you need is the following from it for a valid config file (with, of course, the paths and values being correct for your system). Are the jar file in that path on your machine? You need to specify the iomhost and port. You'll need you OMR credentials And you need to be using the config file you have this in. All of this is in the instructions, so I think you'll be good after reading them and finishing getting your config right. Looks like you are on the right track.

Tom

```
SAS_config_names=['winiomlinux']

SAS_config_options = {'lock_down': False,
                      'verbose'  : True
                     }

cpW  =  "C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\products\\deploywiz__94496__prt__xx__sp0__1\\sas.svc.connection.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\products\\deploywiz__94496__prt__xx__sp0__1\\log4j.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\products\\deploywiz__94496__prt__xx__sp0__1\\sas.security.sspi.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\products\\deploywiz__94496__prt__xx__sp0__1\\sas.core.jar"
cpW += ";C:\\Python\Lib\\site-packages\\saspy\\java\\saspyiom.jar"

winiomlinux = {'java'   : 'java',
            'iomhost'   : 'linux.iom.host',
            'iomport'   : 8591,
            'encoding'  : 'latin1',
            'classpath' : cpW
            }
```

**Comment by veerendra-pappoppula** [comment]
I believe the issue was the cache. Uninstalling and Installing saspy and deleting the saspy folder helped. But now I am facing this error:

We failed in getConnection
The client has connected to a SAS Metadata Server (v1.0) when it intended to connect to a SAS Workspace Server.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Python\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '55835', '-stdoutport', '55836', '-stderrport', '55837', '-iomhost', 'xxxxx', '-iomport', '8561', '-user', 'xxxx', '-lrecl', '1048576', '']

I have replaced the server and username with x's.


No SAS process attached. SAS process has terminated unexpectedly.

**Comment by tomweber-sas** [comment]
Good! That's better. This one's easy. You specified the port for the metadata server instead of the workspace server. try 8591 instead of 8561.

**Comment by veerendra-pappoppula** [comment]
Thank you, worked perfectly. I also tried specifying the omruser and omrpw in the winiomlinux parameter list and it worked. But is that the only way to do it?

**Comment by tomweber-sas** [comment]
Great! nope, you can store your credentials in the _authinfo file. 
you should see that there in the config doc too.

**Comment by tomweber-sas** [comment]
Were you able to set up the authinfo file? Is there anything else you need at this time? 
Wondering if you're good and we can close this?

Thanks!
Tom

**Comment by veerendra-pappoppula** [comment]
I did not get a chance to set up the authinfo but Ill do it later. we can close this for now. Thank you once again for your help.

**Comment by tomweber-sas** [comment]
Ok, great. Just open up another issue if you have anything else!
Tom
