### ISSUE TITLE
Proc Generation for Proc STDIZE runs with an error. 

### ISSUE THREAD

**Issue by ngrajales1** [sassoftware/saspy#241]
**Describe the bug**
**I attempted to use the proc generation code to add proc STDIZE to the sas stat object. I successfully added the proc statement but when I run the function I get the following error:** 

95666      %macro proccall(d);
95667      proc stdize data=WORK._df plot=all  ;
95668      var age education_num capital_gain capital_loss hours_per_week;
95669      run; quit; %mend;
95670      %mangobj(std0002,stdize,_df);

NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      

NOTE: Libref STD0002 was successfully assigned as follows: 
      Engine:        BASE 
      Physical Name: C:\Users\negraj\AppData\Local\Temp\SAS Temporary Files\_TD9068_l10c252_\Prc2\f505db6e-0104-4dbd-8385-81e01878c6a4
NOTE: Line generated by the invoked macro "PROCCALL".
95670                proc stdize data=WORK._df plot=all  ; var age education_num capital_gain capital_loss hours_per_week; run;
                                               ____
                                               22
                                               76

ERROR 22-322: Syntax error, expecting one of the following: ;, (, ADD, DATA, FUZZ, INITIAL, KEEPLEN, METHOD, MISSING, MULT, NMARKERS, NOMISS, NORM, OPREFIX, OUT, OUTSTAT, PCTLDEF, PCTLMTD, PCTLPTS, PSTAT, REPLACE, REPONLY, SNORM, SPREFIX, UNSTD, 
              UNSTDIZE, VARDEF.  

ERROR 76-322: Syntax error, statement will be ignored.

**I took a deeper look at the documentation and I thought I needed to add the method statement to specify my option (even though it should default to std). So I went ahead and added it and then I got the following error message:**

95648      %macro proccall(d);
95649      proc stdize data=WORK._df plot=all  ;
95650      method std;
95651      var age education_num capital_gain capital_loss hours_per_week;
95652      run; quit; %mend;
95653      %mangobj(std0002,stdize,_df);

NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      

NOTE: Libref STD0002 was successfully assigned as follows: 
      Engine:        BASE 
      Physical Name: C:\Users\negraj\AppData\Local\Temp\SAS Temporary Files\_TD14128_l10c252_\Prc2\368cd448-ca55-43cb-b877-9d6cbe0b9f3c
NOTE: Line generated by the invoked macro "PROCCALL".
95653                proc stdize data=WORK._df plot=all  ; method std; var age education_num capital_gain capital_loss hours_per_week; run;
                                               ____        ______
                                               22          180
                                               76

ERROR 22-322: Syntax error, expecting one of the following: ;, (, ADD, DATA, FUZZ, INITIAL, KEEPLEN, METHOD, MISSING, MULT, NMARKERS, NOMISS, NORM, OPREFIX, OUT, OUTSTAT, PCTLDEF, PCTLMTD, PCTLPTS, PSTAT, REPLACE, REPONLY, SNORM, SPREFIX, UNSTD, 
              UNSTDIZE, VARDEF.  

ERROR 180-322: Statement is not valid or it is used out of proper order.

ERROR 76-322: Syntax error, statement will be ignored.
The method statement has been separated from where it should be:

Proc stdize data= WORK._df method= std;
Var ….
Run;

**So after messing around with the statement I decided to go back to SAS and try it out:**

proc stdize data=SASuser.test_data;
      var age education_num capital_gain capital_loss hours_per_week;
run;

**This statement ran correctly. I did not need to include the method statement as it defaults to STD. So I decided to try and run the statement from SASPy in SAS to see if I got the same error message:**

proc stdize data=SASuser.cendata6 plot=all;
      var age education_num capital_gain capital_loss hours_per_week;
run;
808  proc stdize data=SASuser.cendata6 plot=all;
                                       ----
                                       22
                                       76
ERROR 22-322: Syntax error, expecting one of the following: ;, (, ADD, DATA, FUZZ, INITIAL,
              KEEPLEN, METHOD, MISSING, MULT, NMARKERS, NOMISS, NORM, OPREFIX, OUT, OUTSTAT,
              PCTLDEF, PCTLMTD, PCTLPTS, PSTAT, REPLACE, REPONLY, SNORM, SPREFIX, UNSTD,
              UNSTDIZE, VARDEF.
ERROR 76-322: Syntax error, statement will be ignored.

**It seems the statement has an issue with the plot=all statement. Now I am unsure why that statement is there but it seems to be causing the error. So I am reaching out to see if you may have an idea on what could be causing this issue.** 

**To Reproduce**
1. Follow the instructions to add proc stdize to SASPy
2. Attempt to use stdize function from the sas stat object
3. observe the error in the log
4. 

**Expected behavior**
the procedure should normalize the data

**Screenshots**

**Desktop (please complete the following information):**
 - WIN 10
 - SAS 9.4 TS1M3
 - SASPy Version: 2.4.3

**Additional context**

**Comment by tomweber-sas** [comment]
I'll have Jared look at this. He wrote the proc generation code. Also, I wonder if this is related to #194?

**Comment by tomweber-sas** [comment]
@ngrajales1 Did Jared get up with you on this one? Is it addressed? Seems like it was something about needing a way to identify the proc doesn't support the plot statement?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
I followed the steps to add this proc and also see that plots=all is being generated at runtime which causes a failure, as this statement doesn't appear valid for this proc. @jld23 will need to address this as I'm not familiar enough with these procs and that generation code to know how this is supposed to be addresses correctly.

Thanks,
Tom

**Comment by ngrajales1** [comment]
I talked to @jld23 and here is the following solution. The sasStat library assumes that all stat procedures produces a plot. The STDIZE procedure does not produce a plot so to address the issue, I needed to go into the sasdecorator.py file and edit line 29 to inlcude the stdize procedure in the if logic statement. After that it should work! To verify I output the dataset into a saslib and then assigned it to a SAS data object. I then pulled the first 5 values to verify

**Comment by tomweber-sas** [comment]
Thanks for following up!

I just talked w/ Jared today and I think that the saspy.sasdecorator.procDecorator.doc_convert method for generating the method need an optional parameter so you (a user) can override the default for the product group if the proc you're adding is different. And, of course, document this and what the default for each product group is. That way, anyone who adds a proc like this can see what the default is, and based upon the SAS doc for that specific proc, can override this if necessary at method creation when the particular proc it doesn't follow the default behavior for that product. 

Then the underlying code (that the user shouldn't have to worry about) will already handle the case. It has that ability to handle it now, but there's no way currently for the end user to specify that this particular proc is opposite of the default, such that it triggers that non-default code gen. An end user shouldn't have to know to go to line 29 and hack in another hard coded proc name :) 

Jared's gonna fix this and will post when he's got it addressed. Thanks for helping outwith this!
Tom

**Comment by tomweber-sas** [comment]
This hasn't been fixed in years and no one has mentioned it. Jared, if you ever fix it, great, but it isn't an issue that anyone seems worried about.
