### ISSUE TITLE
Issue installing first time

### ISSUE THREAD

**Issue by rspain1** [sassoftware/saspy#242]
I'm not sure if this is a bug, but I am trying to install saspy for the first time and running into some issues. We have SAS installed in a terminal server environment, which may be the issue. All of our users are non-administrators on this server. I installed jupyter notebook/saspy/sas kernel all with my administrator account.

Windows Server 2012 
SAS 9.4 TS1M4
saspy 3.1.0

I can run the following below in Python with my administrator account with no issues.
import saspy
sas = saspy.SASsession(cfgname='winlocal')

cars = sas.sasdata('cars', libref='sashelp')
cars.head()

Here is my "sas" output on my admin account.
Access Method         = IOM
SAS Config name       = winlocal
WORK Path             = E:\SASwork\_TD35576_RHWAPP684A_\Prc2\
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 3.1.0
Teach me SAS          = False
Batch                 = False
Results               = HTML
SAS Session Encoding  = wlatin1
Python Encoding value = windows-1252
SAS process Pid value = 35576

When I try this with a non administrator account I get the error below when I try and run 
sas = saspy.SASsession(cfgname='winlocal')

Pandas module not available. Setting results to HTML
Java Error:
log4j:WARN No appenders could be found for logger (com.sas.services.connection).
log4j:WARN Please initialize the log4j system properly.
com.sas.services.connection.FatalConnectionFactoryException: The application could not find a command to launch a SAS Workspace Server.
	at com.sas.services.connection.ClusterEnvelope.getConnection(ClusterEnvelope.java:238)
	at com.sas.services.connection.AggregationKernel.doGetConnection(AggregationKernel.java:242)
	at com.sas.services.connection.ConnectionFactoryKernel.getConnection(ConnectionFactoryKernel.java:325)
	at com.sas.services.connection.ConnectionFactoryShell.getConnection(ConnectionFactoryShell.java:69)
	at com.sas.services.connection.ConnectionFactoryShell.getConnection(ConnectionFactoryShell.java:51)
	at pyiom.saspy2j.main(saspy2j.java:193)
Caused by: org.omg.CORBA.NO_IMPLEMENT: The application could not find a command to launch a SAS Workspace Server.  vmcid: 0x0  minor code: 0  completed: No
	at com.sas.iom.orb.brg.Engine.flowLaunchServer(Engine.java:2807)
	at com.sas.iom.orb.brg.Engine.flow(Engine.java:690)
	at com.sas.iom.orb.brg.Engine.initClient(Engine.java:655)
	at com.sas.iom.orb.brg.ORBImpl.uri_to_object(ORBImpl.java:119)
	at com.sas.services.connection.ClusterEnvelope.createObject(ClusterEnvelope.java:291)
	at com.sas.services.connection.ClusterEnvelope.getConnection(ClusterEnvelope.java:76)
	... 5 more

We failed in getConnection
The application could not find a command to launch a SAS Workspace Server.
Subprocess failed to start. Double check your settings in sascfg_personal.py file.

Attempted to run program D:\SAS94TS1M2\SASPrivateJavaRuntimeEnvironment\9.4\jre\bin\java.exe with the following parameters:['D:\\SAS94TS1M2\\SASPrivateJavaRuntimeEnvironment\\9.4\\jre\\bin\\java.exe', '-classpath', 'D:\\SAS94TS1M2\\SASDeploymentManager\\9.4\\products\\deploywiz__94230__prt__xx__sp0__1\\deploywiz\\log4j.jar;D:\\SAS94TS1M2\\SASDeploymentManager\\9.4\\products\\deploywiz__94230__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;D:\\SAS94TS1M2\\SASDeploymentManager\\9.4\\products\\deploywiz__94230__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;D:\\SAS94TS1M2\\SASDeploymentManager\\9.4\\products\\deploywiz__94230__prt__xx__sp0__1\\deploywiz\\sas.core.jar;D:\\Python37\\lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '49281', '-stdoutport', '49282', '-stderrport', '49283', '-zero', '-lrecl', '1048576', '']

If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
D:\SAS94TS1M2\SASPrivateJavaRuntimeEnvironment\9.4\jre\bin\java.exe -classpath "D:\SAS94TS1M2\SASDeploymentManager\9.4\products\deploywiz__94230__prt__xx__sp0__1\deploywiz\log4j.jar;D:\SAS94TS1M2\SASDeploymentManager\9.4\products\deploywiz__94230__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;D:\SAS94TS1M2\SASDeploymentManager\9.4\products\deploywiz__94230__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;D:\SAS94TS1M2\SASDeploymentManager\9.4\products\deploywiz__94230__prt__xx__sp0__1\deploywiz\sas.core.jar;D:\Python37\lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 49281 -stdoutport 49282 -stderrport 49283 -zero -lrecl 1048576  

No SAS process attached. SAS process has terminated unexpectedly.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-5e29acc31ef9> in <module>
----> 1 sas = saspy.SASsession(cfgname='winlocal')

d:\python37\lib\site-packages\saspy\sasbase.py in __init__(self, **kwargs)
    375 
    376         # validate encoding
--> 377         pyenc = sas_encoding_mapping[self.sascei]
    378         if pyenc is not None:
    379            if self._io.sascfg.encoding != '':

KeyError: 'No SAS process attached. SAS process has terminated unexpectedly.'

I found many hits with the same kind of errors but I am unable to try and fix the issue on my own. Any suggestions? Please let me know if you need any other information from me and I will try and provide it. 

Thanks!
Robert

**Comment by FriedEgg** [comment]
Looking at your log, notice the following

```
Caused by: org.omg.CORBA.NO_IMPLEMENT: The application could not find a command to launch a SAS
```

This means that your SAS installation was likely not standard, and for one reason or another, the SAS executable was not linked in your system registry.  To correct this see the troubleshooting guide, number 5.

https://sassoftware.github.io/saspy/troubleshooting.html

**Comment by rspain1** [comment]
Thanks for the quick reply FriedEgg.

A few more things I tried today/yesterday.

FYI - Here is my registry setting for HKEY_CLASSES_ROOT\CLSID{440196D4-90F0-11D0-9F41-00A024BB830C}\LocalServer32  

D:\SAS94TS1M2\SASFoundation\9.4\SAS.EXE -config D:\SAS94TS1M2\SASFoundation\9.4\sasv9.cfg -objectserver -nologo -noterminal -noprngetlist 
Which looks correct to me.

If I need to /regserver, I think all SAS sessions need to be closed to do this so I will have to wait to do this on the weekend if needed.

I tried the javaparms option and kept receiving invalid syntax on my administrator account where it was previously working correctly before. I also tried different variations of the command by adding quotes around the paths and commands with no luck.

Here is the winlocal option below, sorry for formatting is slightly off.
winlocal = {'java'      : 'D:\\SAS94TS1M2\\SASPrivateJavaRuntimeEnvironment\\9.4\\jre\\bin\\java.exe',
            'encoding'  : 'windows-1252',
            'classpath' : cpW
			'javaparms' : '-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=D:\\SAS94TS1M2\\SASFoundation\\9.4\\SAS.EXE -config D:\\SAS94TS1M2\\SASFoundation\\9.4\\sasv9.cfg -objectserver -nologo -noterminal -noprngetlist'
            }

**Comment by tomweber-sas** [comment]
Hey @rspain1, were you able to try using the /regserver for the user accounts over the weekend?
A couple other observations. 
1) you installed this with your admin account, and it worked, right? No javaparms needed.
2) the error for the user accounts: "The application could not find a command to launch a SAS Workspace Server". is specific about the command in the registry. So that is the problem to fix for this error.
3) The case that worked, had the work library on drive E, but you have SAS installed on D. Is that right, or is there more than one install? 
Whe you try to use the javaparms with what you have in your registry (which works when you don't put it in the javaparms?), what error are you gettting (you said invalid syntax)? Maybe that would shed some light too. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Looking to close stale issues. Did you get this working? Do you still need any help with this? I'll close this assuming so, since I haven't heard back, but you can always reopen or open a new one for any other issues!

Thanks,
Tom
