### ISSUE TITLE
install saspy 

### ISSUE THREAD

**Issue by sgibbs2018** [sassoftware/saspy#244]
**Describe the bug**

**To Reproduce**
1. Go to 'https://anaconda.org/conda-forge/saspy'
2. Click on 'Conda Install...'
3. Scroll down to either 
conda install -c conda-forge saspy 
conda install -c conda-forge/label/cf201901 saspy 
Perform install on Linux server
conda install -c conda forge saspy
Collecting package metadata: done
Solving environment: failed
PackagesNotFoundError: The following packages are not available from current channels:
- forge

**Expected behavior**
expected to install 

Question - does SAS have to be installed on the SAS server for this to work? 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Redhat Version is 7.2 (Maipo) 
 - SAS Version: [e.g. 9.4M3] - none installed on this server 
I do see with the conda list:
sas_kernel                2.2.0                    py37_0    anaconda
saspy                     3.1.0                      py_0    anaconda

**Additional context**
Is this a non issue and the real issue is that it is not finding environment variables? 
Solving environment: failed

**Comment by tomweber-sas** [comment]
Hmm, I;m not really that familiar with installing from conda, I just use pip. But I tried this on a windows system I have anaconda installed on. I saw similar behavior, so I just tried 'conda install saspy' and that worked. I don't believe it has anything to do with saspy, but rather with the conda environment and something about conda-forge. Here's what I saw:
```
(base) C:\Users\tomuser\Anaconda3>conda install -c conda forge saspy
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - forge

Current channels:

  - https://conda.anaconda.org/conda/win-64
  - https://conda.anaconda.org/conda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



(base) C:\Users\tomuser\Anaconda3>conda install saspy
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - saspy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.6.14               |           py37_0         2.1 MB
    saspy-3.1.0                |             py_0         121 KB
    ------------------------------------------------------------
                                           Total:         2.2 MB

The following NEW packages will be INSTALLED:

  saspy              pkgs/main/noarch::saspy-3.1.0-py_0

The following packages will be UPDATED:

  conda                                       4.6.11-py37_0 --> 4.6.14-py37_0


Proceed ([y]/n)? n


CondaSystemExit: Exiting.


(base) C:\Users\tomuser\Anaconda3>
```

And, looking at the -c option it shows:
```
Channel Customization:
  -c CHANNEL, --channel CHANNEL
                        Additional channel to search for packages. These are
                        URLs searched in the order they are given (including
                        file:// for local directories). Then, the defaults or
                        channels from .condarc are searched (unless
                        --override-channels is given). You can use 'defaults'
                        to get the default packages for conda. You can also
                        use any name and the .condarc channel_alias value will
                        be prepended. The default channel_alias is
                        http://conda.anaconda.org/.
```
I'm not sure if that's exactly right as is, or if you have to set something up in anaconda so that gets resolved right or what? 

Can you try it without the -c conda-forge? Also, about having to have SAS on the machine, no, you don't. That wouldn't have anything to do with it installing or not either. You can connect to remote SAS servers with saspy. Here's the instructions for installing and configuring:
https://sassoftware.github.io/saspy/install.html

Thanks,
Tom

**Comment by sgibbs2018** [comment]
Hi Tom,

Thanks so much! Running conda install saspy did the trick!!

Have a Happy Fourth!
Thanks, Sandy

(base) [root@machine ~]# conda install saspy
Collecting package metadata: done
Solving environment: done
## Package Plan ##
  environment location: /opt/anaconda3
  added / updated specs:
    - saspy

The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    certifi-2019.3.9           |           py37_0         155 KB
    conda-4.7.5                |           py37_0         3.0 MB
    conda-package-handling-1.3.10|           py37_0         259 KB
    saspy-3.1.0                |             py_0         121 KB
    ------------------------------------------------------------
                                           Total:         3.5 MB

The following NEW packages will be INSTALLED:
  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.3.10-py37_0

The following packages will be UPDATED:
  conda                    conda-forge::conda-4.6.14-py37_0 --> pkgs/main::conda-4.7.5-py37_0
The following packages will be SUPERSEDED by a higher-priority channel:
  certifi                                       conda-forge --> pkgs/main
  saspy                                            anaconda --> pkgs/main
Proceed ([y]/n)? y
Downloading and Extracting Packages
_libgcc_mutex-0.1    | 3 KB      | #################################################################################################################### | 100%
conda-package-handli | 259 KB    | #################################################################################################################### | 100%
certifi-2019.3.9     | 155 KB    | #################################################################################################################### | 100%
saspy-3.1.0          | 121 KB    | #################################################################################################################### | 100%
conda-4.7.5          | 3.0 MB    | #################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by tomweber-sas** [comment]
Awesome! And thanks, I did :) Hope you had a good 4th too.

Thanks,
Tom
