### ISSUE TITLE
Separate SAS license?

### ISSUE THREAD

**Issue by Tagar** [sassoftware/saspy#245]
We're an existing SAS customer. 

Would would love to try `saspy`.. 

Do we need a separate license just to run Python code with `saspy`? 

Would we be able to connect to a remote SAS box and run that code there?
(instead of running it locally that would requires installing SAS locally too)

Thank you.

**Comment by tomweber-sas** [comment]
Hey, no, there's no license for saspy, it's completely open and free. Yes it can connect in a number of different ways to various SAS instances, both local and remote. I'm happy to help you get up and running.

First, it would be good to read through the install/configure doc which walks through the different access methods and what they can connect to. https://sassoftware.github.io/saspy/install.html

Basically, there's one that works on linux (local or remote) to a SAS install. There's also an (actually 2) IOM access method which let you connect to a local SAS on windows or any workspace server on any platform it's running on, from either windows or linux (or Mac). There integration for SAS/Grid as well, so IOM to a grid can have saspy work routed to specific LSF queues and stuff like that. That makes IT happy :)

Take a look at the config doc, and don't worry if that makes it seem complicated; it's not, it's just there there's a lot a ways to get a SAS, so this has a lot of possibilities. Once you narrow down what you're connecting to, the final config is pretty simple. 

Then, if you want me to help walk you though configuring it, I'm happy to do that. You might just be able to do it on your own if you have the info you need and know how you're trying to connect.

Thanks,
Tom

**Comment by Tagar** [comment]
@tomweber-sas thank you for prompt response ! 

That sounds great.

I just discussed with a colleage of mine .. one follow up question is if we can connect to a SAS instance running on Solaris?
The idea is to install `saspy` on one of the servers where we run Python notebooks (a Linux server), and connect to a remote SAS servers (majority of our SAS servers are still Solaris, but we will fully migrate to Linux perhaps within 1-2 years).

Thank you!

**Comment by tomweber-sas** [comment]
Well, this is possible, but again, it depends upon what exactly the 'SAS Server' is. Is this a deployment where it's workspace server with object spawner and metadata? Or just a plain SAS install where you are invoking SAS directly on that (those) box(es)?
Workspace server will be via IOM. plain SAS would be STDIO over SSH.

Tom

**Comment by Tagar** [comment]
That's response I got from a colleague of mine :-) 

![image](https://user-images.githubusercontent.com/3013418/60283565-afafee80-98c6-11e9-8313-9df57e32aa0a.png)

We will give SASpy a try! 

Thank you

**Comment by tomweber-sas** [comment]
Hey, just doing some house cleaning. I'm going to close this, but if you need anything, just open up this or another!

Thanks,
Tom
