### ISSUE TITLE
SASPY autocfg_winlocal not working

### ISSUE THREAD

**Issue by drdatascience101** [sassoftware/saspy#246]
I am trying to run saspy but I get the same error even though I have tried to setup the configuration several different ways:

`import saspy
saspy

sas = saspy.SASsession(cfgfile = "C:/Users/user/AppData/Local/Programs/Python/Python37/Lib/site-packages/saspy/sascfg_personal.py")
Using SAS Config named: autogen_winlocal
The OS Error was:
The system cannot find the file specified

SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:/users/user/appdata/local/programs/python/python37/lib/site-packages/saspy/java/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '51726', '-stdoutport', '51727', '-stderrport', '51728', '-zero', '-lrecl', '1048576', '']

If no OS Error above, try running the following command (where saspy is running) manually to see what is wrong:
java -classpath "C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\log4j.jar;C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\sas.core.jar;C:/users/user/appdata/local/programs/python/python37/lib/site-packages/saspy/java/saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 51726 -stdoutport 51727 -stderrport 51728 -zero -lrecl 1048576  

No SAS process attached. SAS process has terminated unexpectedly.
Traceback (most recent call last):

  File "<ipython-input-1-ca89b5d8ee8d>", line 4, in <module>
    sas = saspy.SASsession(cfgfile = "C:/Users/user/AppData/Local/Programs/Python/Python37/Lib/site-packages/saspy/sascfg_personal.py")

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\saspy\sasbase.py", line 377, in __init__
    pyenc = sas_encoding_mapping[self.sascei]

KeyError: 'No SAS process attached. SAS process has terminated unexpectedly.'`

I also tried with `autocfg.main()` which results in the same error

Running the command line prompt yields:

`C:\Users\user>java -classpath "C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\log4j.jar;C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\sas.core.jar;C:/users/user/appdata/local/programs/python/python37/lib/site-packages/saspy/java/saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 51726 -stdoutport 51727 -stderrport 51728 -zero -lrecl 1048576"
'java' is not recognized as an internal or external command,
operable program or batch file.`

Please advise.

**Comment by drdatascience101** [comment]
I also added the appropriate strings to the environment variables and also ;.DLL to the system path

**Comment by FriedEgg** [comment]
This error is stating that it cannot find Java in your system path.  You can either amend you path to include the location of java or update the saspy configuration to have the full path to your java.exe

**Comment by drdatascience101** [comment]
How do I find the location of Java (if it exists on the machine)?

**Comment by FriedEgg** [comment]
Assuming, based on your previous notes here, that you have SAS installed on your machine where you are attempting to use SASPy then you have java installed as part of your SAS installation.  The default Windows path would be: C:\Program Files\SASHome\SASPrivateJavaRuntime\9.4\jre\bin\java.exe

**Comment by drdatascience101** [comment]
What is the name of my saspy configuration file and where should it be located? I have updated the system environment path to include the `java.exe` full path and will see if this works but if not then I will have to amend the configuration file?

**Comment by drdatascience101** [comment]
What is the syntax for adding java path to `sascfg_personal.py`?

Here is my path:

C:\Users\SADIQZ1>path
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\sas_home\SASFoundation\9.4\core\sasexe;C:\sas_home\SASFoundation\9.4\ets\sasexe;C:\sas_home\Secure\ccme4;C:\sas_home\SASFoundation\9.4\core\sasext;C:\Users\SADIQZ1\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\SADIQZ1\AppData\Local\Programs\Python\Python37\;C:\Users\SADIQZ1\AppData\Local\Microsoft\WindowsApps;"C:\sas_home\SASPrivateJavaRuntimeEnvironment\9.4\jre\bin\java.exe;";

Contents of sascfg_personal.py:

SAS_config_names=["autogen_winlocal"]

SAS_config_options = {
	"lock_down": False,
	"verbose"  : True
	}

cpW  =  "C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cpW += ";C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cpW += ";C:/users/sadiqz1/appdata/local/programs/python/python37/lib/site-packages/saspy/java/saspyiom.jar"

autogen_winlocal = {
	"java"      : "java",
	"encoding"  : "windows-1252",
	"classpath" : cpW
	}

import os
os.environ["PATH"] += ";C:\\sas_home\\SASFoundation\\9.4\\core\\sasext"

**Comment by drdatascience101** [comment]
I have updated the sascfg_personal.py file to include the full path for java as suggested. I have also added the java path to system environment variables. However, the problem persists. 

Even when I `cd` to the exact location of `sascfg_personal.py` error persists:

`os.chdir(r'C:\Users\SADIQZ1\AppData\Local\Programs\Python\Python37\Lib\site-packages\saspy')
sas = saspy.SASsession(config_name = ['autogen_winlocal'])
Using SAS Config named: autogen_winlocal
The OS Error was:
The system cannot find the file specified

SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program C:\sas_home\SASPrivateJavaRuntimeEnvironment\9.4\jrin\java.exe with the following parameters:['C:\\sas_home\\SASPrivateJavaRuntimeEnvironment\\9.4\\jre\x08in\\java.exe', '-classpath', 'C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\sas_home\\SASDeploymentManager\\9.4\\products\\deploywiz__94528__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\users\\sadiqz1\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '52862', '-stdoutport', '52863', '-stderrport', '52864', '-zero', '-lrecl', '1048576', '']

If no OS Error above, try running the following command (where saspy is running) manually to see what is wrong:
C:\sas_home\SASPrivateJavaRuntimeEnvironment\9.4\jrin\java.exe -classpath "C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\log4j.jar;C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\sas_home\SASDeploymentManager\9.4\products\deploywiz__94528__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\users\sadiqz1\appdata\local\programs\python\python37\lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 52862 -stdoutport 52863 -stderrport 52864 -zero -lrecl 1048576  

No SAS process attached. SAS process has terminated unexpectedly.
Traceback (most recent call last):

  File "<ipython-input-4-693121dbdd29>", line 2, in <module>
    sas = saspy.SASsession(config_name = ['autogen_winlocal'])

  File "c:\users\sadiqz1\appdata\local\programs\python\python37\lib\site-packages\saspy\sasbase.py", line 377, in __init__
    pyenc = sas_encoding_mapping[self.sascei]

KeyError: 'No SAS process attached. SAS process has terminated unexpectedly.'`

**Comment by drdatascience101** [comment]
The error is arising from `C:\sas_home\SASPrivateJavaRuntimeEnvironment\9.4\jrin\java.exe` I believe... this should be `C:\sas_home\SASPrivateJavaRuntimeEnvironment\9.4\jre\bin\java.exe`

How can I fix that path? Where is it located? It is not the path specificied in my `sascfg_personal.py` file

**Comment by tomweber-sas** [comment]
@drdatascience101 , sorry, I was out on vacation last week. Thanks @FriedEgg for helping out!
This current issue seems like it's being caused by single '\' in the path which are interpreted as escape sequences for certain characters on windows.  Try using double backslashes in your path '\\' or mark the string raw with an 'r' prefix: r'C:\this\that' 
You can see that \b is being escaped as 0x08 in the error message:
```
following parameters:['C:\sas_home\SASPrivateJavaRuntimeEnvironment\9.4\jre\x08in\java.exe', '-classpath
```
Fix up the path and see if that solves this for you.

thanks,
Tom

**Comment by drdatascience101** [comment]
Where? I have referenced several files in this thread.

**Comment by drdatascience101** [comment]
The path was generated by the autoconfig module provided by SAS, however I can try to fix it if you tell me which file I am supposed to modify?

**Comment by drdatascience101** [comment]
The `sascfg_personal.py` file is compiled using `\\` to represent the characters, should that not handle the raw_string problem that you are suggesting?

**Comment by tomweber-sas** [comment]
I was addressing the last post you made in this thread. You stated that you edited your sascfg_personal.py file to specify the full path to your java.exe, since simply having 'java' was found. You said that using that file you put the path in got the same error about java not being found, because the path was botched up:
```
The error is arising from C:\sas_home\SASPrivateJavaRuntimeEnvironment\9.4\jrin\java.exe I believe... this should be C:\sas_home\SASPrivateJavaRuntimeEnvironment\9.4\jre\bin\java.exe
```
I don't know what file that is, nor do I know what's in it; you didn't show it. I speculated that you have single backslashes in the path you edited since what should be jre\bin was jrin because of the \b being escaped for a backspace, which accounts for jrin.

If you aren't sure what config file you are using, if you have multiple of them, you can submit the following to see which one is being used.
```
>>> import saspy
>>> saspy
<module 'saspy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\saspy\\__init__.py'>
>>> saspy.sasbase.SAScfg
<module 'saspy.sascfg_personal' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\saspy\\sascfg_personal.py'>
>>>
```
This seems pretty clear as to the problem, but again, I can't see what you have in your config file. Maybe you can show it here so I can see what's really in it?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Did you fix your path to java? Are you up and running? Need anything else?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Cleaning up stale issues. I'm assuming you've addresses your Java path and are up and running? I'll close this issue. If you still need anything at all, just reopen this, or open a new one for other issues!

Thanks!
Tom
