### ISSUE TITLE
Reading  sas7bdat files without SAS installation

### ISSUE THREAD

**Issue by srikanthbojja** [sassoftware/saspy#249]
I have a SAS dataset and I am trying to do some data exploration/visualization on the dataset in python. I don't have access to local/remote installation of SAS. I am wondering if I can use saspy to load the SAS dataset into pandas dataframe.

i tried the pandas.read_sas way and it works. Is there such a possibility to read sasdatasets  via saspy

**Comment by cjdinger** [comment]
Hi, currently saspy works only with a SAS installation, and it uses SAS to read SAS data sets.  We appreciate that you would like to read SAS data without having a SAS install present.  If/when that changes, we'll be sure to let you know.

**Comment by tomweber-sas** [comment]
Hey @srikanthbojja , I'm afraid the short answer is no, saspy connects to SAS, wherever it is, and it's SAS that does all the work processing data. saspy doesn't process SAS Data Sets on it's own.
I do find it amazingly coincidental and fortuitous that you asked this exact question today :) This topic has come up here recently, and I hope you don't mind me asking, but I'm very curious as to the how/why of having SAS datasets, but having no access to SAS anywhere to connect to to do any processing of them. Do you mind telling me your situation? 

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Hey, I'm gonna close this, as there's nothing I can do to address this. If you have anything else, just let me know!

Thanks,
Tom
