### ISSUE TITLE
pygments dependency not respected in virtualenv

### ISSUE THREAD

**Issue by imatlab-helper** [sassoftware/saspy#25]
I don't understand the problem here, but saspy won't install in a fresh virtualenv because the pygments package is missing. Despite it being listed in the ```install_requirements``` in the ```setup.py```, it does not trigger a dependency installation. In python 3.5 on ubuntu 14.04, ```pip install saspy``` fails with:
```
Collecting saspy
  Using cached saspy-2.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k1_nkvcf/saspy/setup.py", line 24, in <module>
        from saspy import __version__
      File "/tmp/pip-build-k1_nkvcf/saspy/saspy/__init__.py", line 16, in <module>
        from saspy.sasbase     import *
      File "/tmp/pip-build-k1_nkvcf/saspy/saspy/sasbase.py", line 61, in <module>
        from saspy.sasstat import *
      File "/tmp/pip-build-k1_nkvcf/saspy/saspy/sasstat.py", line 17, in <module>
        from saspy.sasproccommons import SASProcCommons
      File "/tmp/pip-build-k1_nkvcf/saspy/saspy/sasproccommons.py", line 18, in <module>
        from saspy.sasresults import SASresults
      File "/tmp/pip-build-k1_nkvcf/saspy/saspy/sasresults.py", line 17, in <module>
        from saspy.SASLogLexer import SASLogStyle, SASLogLexer
      File "/tmp/pip-build-k1_nkvcf/saspy/saspy/SASLogLexer.py", line 16, in <module>
        from pygments.lexer import RegexLexer
    ImportError: No module named 'pygments'
```
The problem is fully resolved by installing pygments first via pip and then installing saspy.

**Comment by jld23** [comment]
I think the issue is with pip and that pygments is expected to be built before saspy. Here is an issue that seems to have the same behavior: https://github.com/pypa/pip/issues/25

**Comment by jwodder** [comment]
No, this is a bug in saspy's `setup.py`, which tries to import `saspy` when run, which ultimately causes Python to try to import `pygments` even though pip can't tell that `pygments` needs to be installed until after it's run `setup.py`.  See https://packaging.python.org/single_source_version/ for various ways to get the version number correctly.

**Comment by jld23** [comment]
@jwodder If I understand your comment correctly, I'm using an import of the version in line 24 of setup.py that is ultimately calling pygments even thought is necessarily installed yet. This corresponds to Item 6 in the link you included in your comment.

If I've understood correctly, do you have a recommendation for which pattern I should adopt?
Thank you for helping resolve this issue!

**Comment by imatlab-helper** [comment]
Much appreciated, thank you!
