### ISSUE TITLE
Typo in file sasiocom.py

### ISSUE THREAD

**Issue by JustinNeumann** [sassoftware/saspy#252]
Version 3.1.2.: In line 432 of sasiocom.py you type "val" but you actually mean "value". The inclusion of this code part in the submit statement (any prompt included) results in an error. Get back if you need clarification.

**Comment by tomweber-sas** [comment]
Great catch! Thanks for letting me know. If you want to d a PR for that, feel free, else I'm happy to fix it and push it out there!

Thanks,
Tom

**Comment by JustinNeumann** [comment]
Please do it yourself, I never did a PR before😹

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Tom Weber <notifications@github.com>
Gesendet: Monday, August 12, 2019 4:03:31 PM
An: sassoftware/saspy <saspy@noreply.github.com>
Cc: JustinNeumann <justin.neumann@live.de>; Author <author@noreply.github.com>
Betreff: Re: [sassoftware/saspy] Typo in file sasiocom.py (#252)


Great catch! Thanks for letting me know. If you want to d a PR for that, feel free, else I'm happy to fix it and push it out there!

Thanks,
Tom

**Comment by tomweber-sas** [comment]
No trouble! Done. Thanks again for finding this and letting me know!
Tom
