### ISSUE TITLE
sd2df not working on missing value and cannot recover back

### ISSUE THREAD

**Issue by shaokangchen** [sassoftware/saspy#255]
Use sd2df to convert data from SAS sever to python.
My code for the conversion:
c = sas.submit("""
                proc sql;
                    create table tmp as
                    select DIM_CODES_KEY, code, code_type, invalid_date, date_from, date_to
                    from CODES;
                """)
HTML(c['LST'])
new_res = sas.sd2df(table='TMP',libref='WORK')
print(new_res)

If the first time I run the code not including the invalid_date, it works fine. But once that field is included, it generate errors. But even I remove the invalid_date field in the Proc sql again, the sd2df will not work anymore if it sees an error before. From the server side, the file _saspy_sd2df.sas7bdat is not updated.

The field invalid_date is Datetime20. format, but not all the rows has values. When this field is concluded in the conversion, saspy reported the following errors:
TypeError Traceback (most recent call last) <ipython-input-10-54d2ccddc8f3> in <module> ----> 1 new_res = sas.sd2df(table='TMP',libref='WORK') 2 print(new_res) C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py in sd2df(self, table, libref, dsopts, method, **kwargs) 933 """ 934 dsopts = dsopts if dsopts is not None else {} --> 935 return self.sasdata2dataframe(table, libref, dsopts, method, **kwargs) 936 937 def sd2df_CSV(self, table: str, libref: str = '', dsopts: dict = None, tempfile: str = None, tempkeep: bool = False, C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py in sasdata2dataframe(self, table, libref, dsopts, method, **kwargs) 1013 return None 1014 else: -> 1015 return self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs) 1016 1017 def _dsopts(self, dsopts): C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in sasdata2dataframe(self, table, libref, dsopts, method, **kwargs) 596 df = self.sasdata2dataframeCSV(table, libref, dsopts=dsopts, **kwargs) 597 else: --> 598 header, rows = self.read_sasdata(table, libref, dsopts=dsopts) 599 df = pd.DataFrame.from_records(rows, columns=header) 600 C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in read_sasdata(self, table, libref, dsopts) 468 rows = [] 469 while not recordset.EOF: --> 470 rows.append([meta[x.Name]['CONVERT'](x.Value) for x in recordset.Fields]) 471 recordset.MoveNext() 472 C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in <listcomp>(.0) 468 rows = [] 469 while not recordset.EOF: --> 470 rows.append([meta[x.Name]['CONVERT'](x.Value) for x in recordset.Fields]) 471 recordset.MoveNext() 472 C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in <lambda>(x) 308 col_info['CONVERT'] = lambda x: self._sb.SAS_EPOCH + datetime.timedelta(days=x) 309 elif col_info['FORMAT_NAME'] in self._sb.sas_datetime_fmts: --> 310 col_info['CONVERT'] = lambda x: self._sb.SAS_EPOCH + datetime.timedelta(seconds=x) 311 # elif FIXME TIME FORMATS 312 else: TypeError: unsupported type for timedelta seconds component: NoneType .

If I remove that time field from the conversion, it seems sd2df does not recover from the last error and reports the following error:
com_error Traceback (most recent call last) <ipython-input-12-54d2ccddc8f3> in <module> ----> 1 new_res = sas.sd2df(table='TMP',libref='WORK') 2 print(new_res) C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py in sd2df(self, table, libref, dsopts, method, **kwargs) 933 """ 934 dsopts = dsopts if dsopts is not None else {} --> 935 return self.sasdata2dataframe(table, libref, dsopts, method, **kwargs) 936 937 def sd2df_CSV(self, table: str, libref: str = '', dsopts: dict = None, tempfile: str = None, tempkeep: bool = False, C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py in sasdata2dataframe(self, table, libref, dsopts, method, **kwargs) 1013 return None 1014 else: -> 1015 return self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs) 1016 1017 def _dsopts(self, dsopts): C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in sasdata2dataframe(self, table, libref, dsopts, method, **kwargs) 596 df = self.sasdata2dataframeCSV(table, libref, dsopts=dsopts, **kwargs) 597 else: --> 598 header, rows = self.read_sasdata(table, libref, dsopts=dsopts) 599 df = pd.DataFrame.from_records(rows, columns=header) 600 C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in read_sasdata(self, table, libref, dsopts) 455 export = EXPORT.format(tgt=TARGET, tbl=tablepath, dopt=dsopts) 456 self.workspace.LanguageService.Submit(export) --> 457 meta = self._schema(TARGET) 458 459 # Connect RecordSet object to ADODB connection with params: C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in _schema(self, table, libref) 300 301 schema = self.adodb.OpenSchema(self.SCHEMA_COLUMNS, criteria) --> 302 schema.MoveFirst() 303 304 metadata = {} C:\ProgramData\Anaconda3\lib\site-packages\win32com\client\dynamic.py in MoveFirst(self) com_error: (-2147352567, 'Exception occurred.', (0, 'ADODB.Recordset', 'Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.', 'C:\\WINDOWS\\HELP\\ADO270.CHM', 1240645, -2146825267), None)

**Comment by shaokangchen** [comment]
Thank you very much Tom, that is a very quick response. I just started using the SASpy, it is good to know those convenient way of function calls. I will try your fix. Thank you.

Regards
Kang

**Comment by shaokangchen** [comment]
Thank you both Tom and Harry. I will update the SASPy package.

Regards
Kang

**Comment by shaokangchen** [comment]
Thank you very much Tom. It does fix the sd2df() and works fine for me. I
am not sure if the reverse function df2sd() needs to change accordingly or
not. It seems in python data the unfilled numbers will be assigned a string
value, but if you run df2sd() to convert it back to SAS, it generates
TypeError as following:

TypeError Traceback (most recent call last)

<ipython-input-9-799f1f258080> in <module>----> 1 new_data = sas.df2sd(new_res)
C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py in
df2sd(self, df, table, libref, results, keep_outer_quotes,
embedded_newlines, LF, CR, colsep)    889         :return: SASdata
object    890         """--> 891         return
self.dataframe2sasdata(df, table, libref, results, keep_outer_quotes,
embedded_newlines, LF, CR, colsep)    892     893     def
dataframe2sasdata(self, df: 'pd.DataFrame', table: str = '_df',
libref: str = '',
C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py in
dataframe2sasdata(self, df, table, libref, results, keep_outer_quotes,
embedded_newlines, LF, CR, colsep)    923             return None
924         else:--> 925             self._io.dataframe2sasdata(df,
table, libref, keep_outer_quotes, embedded_newlines, LF, CR, colsep)
 926     927         if self.exist(table, libref):
C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in
dataframe2sasdata(self, df, table, libref, keep_outer_quotes,
embedded_newlines, LF, CR, colsep)    638             for i, col in
enumerate(row):    639                 func =
formats[df.columns[i]]--> 640                 vals.append(func(col))
 641     642             sql_values.append('values({})'.format(',
'.join(vals)))
C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py in
<lambda>(x)    629                 length =
df[name].map(str).map(len).max()    630                 definition =
"'{}'n char({})".format(name, length)--> 631
formats[name] = lambda x: "'{}'".format(x.replace("'", "''")) if
pd.isnull(x) is False else 'NULL'    632     633
columns.append(definition)
TypeError: an integer is required (got type str)


Regards

Kang

**Comment by tomweber-sas** [comment]
I've not been able to replicate this traceback. Can you show me the code you're running that is getting this? Can you replicate this with my test case? Can you recreate it in a stand alone case I can run if not with that test case?

I am seeing something odd with the reverse with my simple test case, but it's not the traceback. I'm still looking into that. I'm also not sure how the error is happening, It's hard to be sure of exactly what this traceback is really showing, but it seems the error is:
```
631 formats[name] = lambda x: "'{}'".format(x.replace("'", "''")) if pd.isnull(x) is False else 'NULL'    
TypeError: an integer is required (got type str)
```
But, I don't see what would be expecting an int instead of a string. So, I'm not sure what's really happening. Especially since I'm not seeing this particular error. Both x.replace and pd.isnull take strings. even the name key of the dict can be an int or a string.

Maybe showing the data frame you're trying to use and that data drames dtypes output too, to see what it's types and colnames are.

Thanks!
Tom

**Comment by shaokangchen** [comment]
Thank you Tom. I think I kind of found the problem.
My data is SAS looks like this:
DIM_keys,    Datetime20.       Datetime20.
1     01DEC2011:00:00:00 31DEC5999:00:00:00
2     01DEC2011:00:00:00 31DEC5999:00:00:00
3     01DEC2011:00:00:00 31DEC5999:00:00:00
4     01DEC2011:00:00:00 31DEC5999:00:00:00

When I run the sas.sd2df, the python data frame looks like this

     DIM_CODES_KEY  DATE_FROM              DATE_TO
0               1.0 2011-12-01  5999-12-30 00:00:00
1               2.0 2011-12-01  5999-12-30 00:00:00
2               3.0 2011-12-01  5999-12-30 00:00:00
3               4.0 2011-12-01  5999-12-30 00:00:00

The following are the columnInfo():

	Member   Num  Variable        Type    Len    Pos   Format

0      WORK.TMP 2.0   DATE_FROM      Num      8.0   8.0   DATETIME20.
1      WORK.TMP 3.0   DATE_TO        Num      8.0   16.0  DATETIME20.
2      WORK.TMP 1.0   DIM_CODES_KEY  Num      8.0   0.0

It seems the two datatime20. are treated differently.

If I run the sas.df2sd(), it works fine with date_from and I can see
the date is converted back to datetime20. with minutes and seconds.
But for date_to, it will generate the error as

TypeError: an integer is required (got type str).

I am not so sure how data format is kept in python, but it seems treat
the DIM_key as float and date_time and date_to as int. df2sd may not
be consistent with sd2df in some way.

Hopefully this info is helpful for you.


Regards

Kang

**Comment by tomweber-sas** [comment]
Thanks, yes, I think that's will be helpful, and that it is data specific. I looked at this when you posted it last week and I saw an issue with the year being so far in the future 5999. I got pulled off on another issue and didn't have a chance to finish my investigation, but I wanted to let you know I'll work to track this down this week.
Thanks!
Tom

**Comment by tomweber-sas** [comment]
Well, I was able to address this and make it behave the same as in the other access methods. So now, all cases behave the same. SAS supports dates with years that high, but pandas doesn't. So, you get NAT for these on the python side, but the transfers back and forth work right and keep the datetime datatypes. 

I've pushed this fix to master. Can you get it from there and see if you see the same behavior on your side?

Here's my simple test case:

```
7                                                          The SAS System                        11:04 Wednesday, September 11, 2019

53         ;*';*";*/;quit;run;
54         data b; format d Datetime20.;
55           do x =1 to 10;
56             d = x;
57             z = x;
58             if d = 5 then d = .;
59             if d = 6 then d = .;
60             if d > 6 then d = 119999999998;
61             /* if d > 6 then d = 9998; */
62             if x > 5 then z = .;
63             output;
64           end;
65         run;

NOTE: The data set WORK.B has 10 observations and 3 variables.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


66         ;*';*";*/;quit;run;

>>>
>>>
>>> workat = sas.sasdata('b', results='text')
>>> workat.head(10)
                                                           The SAS System                    11:04 Wednesday, September 11, 2019   1

                                               Obs                       d     x    z

                                                 1      01JAN1960:00:00:01     1    1
                                                 2      01JAN1960:00:00:02     2    2
                                                 3      01JAN1960:00:00:03     3    3
                                                 4      01JAN1960:00:00:04     4    4
                                                 5                       .     5    5
                                                 6                       .     6    .
                                                 7      25AUG5762:21:19:58     7    .
                                                 8      25AUG5762:21:19:58     8    .
                                                 9      25AUG5762:21:19:58     9    .
                                                10      25AUG5762:21:19:58    10    .

>>>
>>> dft = workat.to_df()
>>> dft.ftypes
d    datetime64[ns]:dense
x           float64:dense
z           float64:dense
dtype: object
>>>
>>>
>>>
>>> dft
                    d     x    z
0 1960-01-01 00:00:01   1.0  1.0
1 1960-01-01 00:00:02   2.0  2.0
2 1960-01-01 00:00:03   3.0  3.0
3 1960-01-01 00:00:04   4.0  4.0
4                 NaT   5.0  5.0
5                 NaT   6.0  NaN
6                 NaT   7.0  NaN
7                 NaT   8.0  NaN
8                 NaT   9.0  NaN
9                 NaT  10.0  NaN
>>>
>>>
>>> rt = sas.df2sd(dft, results='text')
>>> rt.head(12)
                                                           The SAS System                    11:04 Wednesday, September 11, 2019   5

                                            Obs    d                              x    z

                                              1    1960-01-01T00:00:01.000000     1    1
                                              2    1960-01-01T00:00:02.000000     2    2
                                              3    1960-01-01T00:00:03.000000     3    3
                                              4    1960-01-01T00:00:04.000000     4    4
                                              5                             .     5    5
                                              6                             .     6    .
                                              7                             .     7    .
                                              8                             .     8    .
                                              9                             .     9    .
                                             10                             .    10    .

>>> rt.contents()
                                                           The SAS System                    11:04 Wednesday, September 11, 2019   6

                                                       The CONTENTS Procedure

                            Data Set Name        WORK._DF                      Observations          10
                            Member Type          DATA                          Variables             3
                            Engine               V9                            Indexes               0
                            Created              09/11/2019 11:39:02           Observation Length    24
                            Last Modified        09/11/2019 11:39:02           Deleted Observations  0
                            Protection                                         Compressed            NO
                            Data Set Type                                      Sorted                NO
                            Label
                            Data Representation  WINDOWS_64
                            Encoding             wlatin1  Western (Windows)


                                                 Engine/Host Dependent Information

    Data Set Page Size          65536
    Number of Data Set Pages    1
    First Data Page             1
    Max Obs per Page            2715
    Obs in First Data Page      10
    Number of Data Set Repairs  0
    ExtendObsCounter            YES
    Filename                    C:\Users\dbitest2\AppData\Local\Temp\SAS Temporary Files\_TD3336_RDCESX51082_\Prc2\_df.sas7bdat
    Release Created             9.0401M6
    Host Created                X64_S08R2
    Owner Name                  BUILTIN\Administrators
    File Size                   128KB
    File Size (bytes)           131072


                                             Alphabetic List of Variables and Attributes

                                     #    Variable    Type    Len    Format         Informat

                                     1    d           Num       8    E8601DT26.6    E8601DT26.6
                                     2    x           Num       8
                                     3    z           Num       8

>>>
```

before the fix, I get the following failure trying to df2sd():

```
>>> workat = sas.sasdata('b', results='text')
>>> workat.head(10)
                                                           The SAS System                    10:56 Wednesday, September 11, 2019   1

                                               Obs                       d     x    z

                                                 1      01JAN1960:00:00:01     1    1
                                                 2      01JAN1960:00:00:02     2    2
                                                 3      01JAN1960:00:00:03     3    3
                                                 4      01JAN1960:00:00:04     4    4
                                                 5                       .     5    5
                                                 6                       .     6    .
                                                 7      25AUG5762:21:19:58     7    .
                                                 8      25AUG5762:21:19:58     8    .
                                                 9      25AUG5762:21:19:58     9    .
                                                10      25AUG5762:21:19:58    10    .

>>>
>>>
>>> dft = workat.to_df()
>>> dft.ftypes
d     object:dense
x    float64:dense
z    float64:dense
dtype: object
>>>
>>>
>>>
>>> dft
                     d     x    z
0  1960-01-01 00:00:01   1.0  1.0
1  1960-01-01 00:00:02   2.0  2.0
2  1960-01-01 00:00:03   3.0  3.0
3  1960-01-01 00:00:04   4.0  4.0
4                 None   5.0  5.0
5                 None   6.0  NaN
6  5762-08-24 21:19:58   7.0  NaN
7  5762-08-24 21:19:58   8.0  NaN
8  5762-08-24 21:19:58   9.0  NaN
9  5762-08-24 21:19:58  10.0  NaN
>>>
>>> rt = sas.df2sd(dft, results='text')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py", line 891, in df2sd
    return self.dataframe2sasdata(df, table, libref, results, keep_outer_quotes, embedded_newlines, LF, CR, colsep)
  File "C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py", line 925, in dataframe2sasdata
    self._io.dataframe2sasdata(df, table, libref, keep_outer_quotes, embedded_newlines, LF, CR, colsep)
  File "C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py", line 640, in dataframe2sasdata
    vals.append(func(col))
  File "C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasiocom.py", line 631, in <lambda>
    formats[name] = lambda x: "'{}'".format(x.replace("'", "''")) if pd.isnull(x) is False else 'NULL'
TypeError: an integer is required (got type str)
>>>
```

**Comment by shaokangchen** [comment]
Thank you very much Tom. I will update the SASpy and give it a try.

Regards
Kang

**Comment by tomweber-sas** [comment]
Yes, that is my observation also. Pandas data frames store timestamps as NumPy datetime64 data types. This type has a valid range as follows:
```
>>> pd.Timestamp.min
Timestamp('1677-09-21 00:12:43.145225')
>>> pd.Timestamp.max
Timestamp('2262-04-11 23:47:16.854775807')
```
So any dates above that (or below the 1677...), end up throwing the following error:
```
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 5960-01-01 00:00:01
```

So, when I import SAS data into a Dataframe, and I set the columns which should be datetimes to datetime64, I use the coerce attribute so that instead of failing to create the dataframe, it will succeed with a valid datetime column, but the out of range values will be missing (NAT).

The COM access method didn't have this logic in it, so what was happening was that the column was not being created as a timestamp column, but rather an object, and that object didn't simply have string values,, but rather datetime.datetime() objects as values. or simply None for missing.

I added the logic to COM so it does the same as all the other access methods, creating a valid timestamp column with the datetime values, which will then be created again correctly when sent back to SAS, as datetime types (well, floating point doubles in SAS with a datetime format).

This does, however, limit the datetime ranges to those which are valid in pandas dataframes.

So, is this ok? Or is there some other behavior you need?
I don't currently have any kind of logic to support out of range dates in pandas to still be converted back to valid date ranges in SAS. Dataframe dtypes of Object, I have to assume, are to become Character values in SAS. Object is a catch all in pandas, but also is what 'string' is and generally can only really mean Char as opposed to Num (Float, with or without a datetime format associated w/ it) when importing into a SAs data set.

Let me know what you think especially if you have an idea about a way to work around the pandas limitation.

Thanks!
Tom

**Comment by shaokangchen** [comment]
Thank you Tom. Since the timestamp in Pandas does not support a larger
time, I am fine with your current solution.

Regards
Kang

**Comment by tomweber-sas** [comment]
Thanks Kang. I suppose we can close this then? 
If you need these future dates to be transferred between SAS and Pandas for production work (as opposed to this was just to see if years that far worked), I can probably help you figure out some code (python or SAS, or a combination) to get you a workaround. I haven't had time to play with it as of yet, but I'm sure something could be done outside of saspy itself to get you what you need, if you really need it. 

Thanks!
Tom

**Comment by shaokangchen** [comment]
Thanks Tom. It is fine to close this issue.

Regards
Kang

**Comment by tomweber-sas** [comment]
Thanks Kang, just let me know if you need anything else!
Tom
