### ISSUE TITLE
How to share session between saspy and cell magics?

### ISSUE THREAD

**Issue by jasonphillips** [sassoftware/saspy#26]
This library is enormously useful for cases when I want to write in Python but switch to SAS for certain heavy lifting segments -- but I'm running into one workflow issue when attempting to combine the object-based saspy methods with the cell magics approach.

My goal is to do something like this, in a series of cells in one notebook:

```python
# start a session
import saspy
import pandas as pd
from IPython.display import HTML

sas = saspy.SASsession(cfgname='ssh')
```

 Later, load something into the SAS session:

```python
sas_dataset = sas.df2sd(something_in_pandas, 'mydata')
```

Now, instantiate cell magics so that I can submit SAS statements directly:

```python
%load_ext saspy.sas_magic
```

Do something useful in SAS (hello world example here):

```python
%%SAS

proc print data=WORK.mydata; run;
```

But the issue is that the cell magics extension, when loaded, creates a new SAS session on the other end, separate from the one created with the direct `saspy.SASsession` call, which means that my work library and other instantiated data are not available to me in any %SAS cells.

I can of course get around this by using the more explicit syntax:

```python
c = sas.submit("""
  ... sas code here
""")
HTML(c['LST'])
```

But that isn't quite as elegant for a single notebook trading off tasks between python and SAS. Is there a way to force a shared session between both, or a reason to prevent that?  

Ideally, an existing session could simply be passed through into the magics when loaded. This line is where the new session is created:

https://github.com/sassoftware/saspy/blob/master/saspy/sas_magic.py#L36

Although as far as I can tell from API docs, the `load_ext` call in iPython doesn't allow arguments, so I'm not sure how passing in an already instantiated SAS session would be done in this case.

**Comment by jasonphillips** [comment]
I found a solution that works well for me. The `%load_ext` invocation doesn't allow arguments, but cell magics do, on the same line; so I modified the `%%SAS` magic to check for an object name following its invocation, and if it is a SASsession instance, use that session to submit the code.

Check the commit here: https://github.com/jasonphillips/saspy/commit/225df5eccb102fd32bd6cbbb32ad8e895709c6a7

Usage (in place of the invocation I wrote above):

```python
%%SAS sas

proc print data=WORK.mydata; run;
```

Where, in this case, `sas` is the existing session instantiated somewhere above in the notebook by calling `saspy.SASsession()` manually. This approach actually lets you potentially manage more than one session with different workspaces and decide which one a cell will use.

The only downside I currently see is that the initial `%load_ext` call still instantiates a new session that I never end up using. If this approach makes sense to more than myself, I could start up a PR, which would require also updating the other cell magic and the documentation.

**Comment by tomweber-sas** [comment]
Hey, in general, this sounds fine. I'll take a closer look when I get a chance. You certainly need to be able to share a single session when submitting code via both methods. Out of curiosity, would the submit method be 'acceptable' in place of a magic if it just displayed the results automatically? It would be easy to set a session attribute to modify the submit method, so you could have it return the DICTionary (the default), display the LST (like most other methods), display the LOG, or display BOTH. Could add that option to the submit method too, So, you could have something like this:

sas=saspy.SASsession()
sas.submit_results('LST')

sas.submit('proc print data=WORK.mydata; run;')  # this will display the results, like sasdata.head() would
sas.submit('libname _all_ list;', 'LOG')                         # this will display the LOG; don't need print(...['LOG'}) 

This way, the single line would give you the results w/out having to print() or HTML() the dictionary key for the cases where you just want the results displayed, like most other methods.

**Comment by jld23** [comment]
I think making this change makes sense and if we move a couple of lines from the __init__ to the SAS method we can key off of the `self.lst_len` to see if a session has already been established.

The open question is, **should two cell magics with no specified session object use the same SAS session or should each be different?**  The current behavior is they share a single session.

Modifying the SAS cell magic to take an optional SAS session object and use it if provided is a PR I would support.

Jared

**Comment by jasonphillips** [comment]
@tomweber-sas 

The submit method would certainly work fine with a few tweaks to the output as you suggested. That at least cleans up the need to assign a temporary variable and then manually select the LST key. I do like the magics approach just for aesthetic reasons as I read through a notebook (though I'm also aware that the goal of saspy is to reduce the need for "direct" SAS calls and stick to more of the pythonic implementations where available).

@jld23 

I may go ahead and give the PR a shot this weekend, checking through the automated tests as well to see where I'll need an addition to reflect the new option. I would personally lean towards leaving the current behavior if no session is specified, so I'd probably create the session once when needed, then default back to it for future calls that don't specify.

**Comment by jld23** [comment]
That should great! Thanks for your interest and contribution.

Jared

**Comment by jld23** [comment]
@jasonphillips,
Modified your code slightly to achieve consistency with the current behavior but be able to call an existing SAS session. I've included the code if you want to incorperate it and create a PR.

Jared

```
    def __init__(self, shell):
        super(SASMagic, self).__init__(shell)
        self.lst_len = -99  # initialize the length to a negative number to trigger function
        self.mva = None
        if self.lst_len < 0 and type(self.mva) == SASsession :
            self._get_lst_len()

    @ipym.cell_magic
    def SAS(self, line, cell):
        mva = self.mva
        if len(line) and line in self.shell.user_ns:  # session supplied
            _mva = self.shell.user_ns[line]
            print(str(type(_mva)))
            if type(_mva) == SASsession:
                mva = _mva
            else:
                return 'Invalid SAS Session object supplied'
        elif len(line) and not line in self.shell.user_ns:  # string supplied but not a session
            return 'Invalid SAS Session object supplied'
        else:  # no string should default to last session called
            try:
                if mva is None:
                    mva = SASsession()
                    self.mva = mva  # save the session for reuse
                else:
                    mva = self.mva
            except:
                return "this shouldn't happen"
        saveOpts="proc optsave out=__jupyterSASKernel__; run;"
        restoreOpts="proc optload data=__jupyterSASKernel__; run;"
        if len(line)>0:  # Save current SAS Options
            mva.submit(saveOpts)

        if line.lower()=='smalllog':
            mva.submit("options nosource nonotes;")

        elif line is not None and line.startswith('option'):
            mva.submit(line + ';')

        res = mva.submit(cell)
        dis = self._which_display(res['LOG'], res['LST'])

        if len(line)>0:  # Restore SAS options 
            mva.submit(restoreOpts)

        return dis
```

**Comment by jasonphillips** [comment]
So, I'd like to start moving on this in the coming days as other things finally left my plate, but I was wanting to first set up the appropriate tests for clear expectations of the change; however, at the moment I haven't worked out which components of the Jupyter integration have existing tests... am I correct to say that there aren't any tests for the cell magic at present? Or perhaps I missed them on first read-through.
 
(Beyond that, it looks as if the Session tests currently expect a live connection to SAS, making them "integration" tests more or less. I'd be interested in pursuing some isolated tests using mocking with something like [`unittest.mock.patch()`](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch) so that it's easier to test expectations without a live connection, checking only to see that the correct SAS code would have been sent without a server needing to be present. And likewise on the sasdata tests, perhaps some fixtures for the SAS responses from `sashelp` libraries instead of actually pulling them live. Generally I'm more comfortable testing code in isolation and not worry about the particularities of my local stack beyond the module; thoughts welcome on that direction.)

**Comment by tomweber-sas** [comment]
Closing this as #54 was merged.
