### ISSUE TITLE
Issue with SASdata.head in Jupyter

### ISSUE THREAD

**Issue by stomioka** [sassoftware/saspy#261]
I generated a SAS dataset using `SASsession.submit`, then used `SASsession.sasdata` to make it available in saspy. SASdata.head works without any error/warning but the dataset is not displayed correctly in Jupyter Notebook.  `SASdata.head()` tries to print all variables on the screen, but the value in each cell does not wrap appropriately.

**Screenshots**
![image](https://user-images.githubusercontent.com/33785239/66419387-0bb00600-e9d2-11e9-8869-9791ec5752f8.png)

**Expectation**
I would expect that the output is similar to pd.head()
![image](https://user-images.githubusercontent.com/33785239/66419668-79f4c880-e9d2-11e9-8c1f-4cd0e0c63bba.png)

**To Reproduce**
```python
from IPython.display import HTML
import saspy
sas1=saspy.SASsession(results='HTML')
l=sas1.submit('''
    data baseball;
        set sashelp.baseball;
    run;
''')
print(l['LOG'])
test = sas1.sasdata('baseball', libref='work')
test.head()
```

**Desktop:**
 - OS: Windows Server 2016 Datacenter
 - SAS Version: 9.4 (TS1M6)
 - SASPy Version: 3.1.4

**Comment by tomweber-sas** [comment]
Hey, yes that's an old bug in Jupyter Notebook, been there for for a long time, but never fixed that I'm aware of, as they went on to Jupyter L:ab. This works correctly in Lab, as well as in previous versions of Notebook. There have been a number of issues on this in the past: #97, #140 and I opened the following with jupyter notebook: https://github.com/jupyter/notebook/issues/3413.

Can you use jupyter Lab? It's the new standard for jupyter going forward. I can't fix it in saspy, as it's the html rendering in the notebook code itself, in jupyter. The older version of notebook worked - this was a regression bug that was introduced.

Tom

**Comment by stomioka** [comment]
Thanks Tom. I can use Jupyter Lab.
