### ISSUE TITLE
Find correct path to saspyiom.jar

### ISSUE THREAD

**Issue by wonderfreda** [sassoftware/saspy#267]
I tried to export a df to sas format using the following code. The output data.sas7bdat is truncated at 23 rows while the original df has over 400k rows. 

import saspy
#sas = saspy.SASsession(cfgname='default')
sas = saspy.SASsession()
sas.saslib('sav', path='mypath')
sas_names = sas.df2sd(df, table='data', libref='sav')
sas.disconnect()

The log of this code above is the followings:

Using SAS Config named: default
SAS Connection established. Subprocess id is 46739

28   libname sav    'mypath'  ;
NOTE: Libref SAV was successfully assigned as follows: 
      Engine:        V9 
      Physical Name: 

'This method is only available with the IOM access method'

In addition to the truncated output, the code took a while to run, over 3min in wall time. I wonder if this is related or a separate issue. 
CPU times: user 9.76 s, sys: 1.95 s, total: 11.7 s
Wall time: 3min 12s

Any input of how to solve this? Thank you very much! 

PS: I am running Python 3 on JuypterLab
 - writing to SAS 9.4TS Level 1M6
 - SASPy Version: Version 2.0

**Comment by wonderfreda** [comment]
Hi Tom,

Thanks a lot for the quick response. I was running saspy on juypter on a cloud service so I don't have full access to the upgrade function, hence I switched to run on local windows environment:

![image](https://user-images.githubusercontent.com/30054031/66948297-742a6300-f022-11e9-84a3-3c43ecdfccd5.png)

I have read various error report on saspy for winlocal setup, and did the following to the sascfg.py file:

![image](https://user-images.githubusercontent.com/30054031/66948501-d4b9a000-f022-11e9-88f7-3b4f4a336286.png)

And I have added sasext to the environment:
![image](https://user-images.githubusercontent.com/30054031/66948557-f3b83200-f022-11e9-81aa-fe3c5f30adfc.png)

And lastly, I verified that my saspy is version 3.1.6.

Could you please help me to understand why it didn't work? Much appreciated!

**Comment by tomweber-sas** [comment]
Hey, sure. That error is that the saspyiom.jar file isn't being found by java - basically number 1 here:
https://sassoftware.github.io/saspy/troubleshooting.html#classpath-problems

So, the classpaths you have in your sasccfg_personal file, did you edit those to make sure they are correct on your machine? The example file shows realistic patht, so you have a better idea of what you're looking for, but they are not, by definition valid paths on any given system. You have to edit that to be correct for your machine. 

I don't think saspyiom.jar happens to be in the path listed. Double check the paths for the rest of the jars too, from the SAS install. Even if you have SAS in the usual place, which is what the examples show, that last part w/ the numbers won't nexecrraily be right even if the rest is:

```
C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94472__prt__xx__sp0__1\\deploywiz\\
```
the _94472_ in those paths is likly not what your paths have even if yours is installed in 
C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\

Tom

**Comment by wonderfreda** [comment]
I believe so. I changed the cpW in the sascfg_personal.py (and sascfg.py) to reflect the numbers I see in the folder path:

![pic2](https://user-images.githubusercontent.com/30054031/66958263-ce80ef00-f035-11e9-98ec-3c1132f731a9.PNG)

And I saved and restarted the PC and kernel, but still got the same error:
![image](https://user-images.githubusercontent.com/30054031/66958344-00925100-f036-11e9-81e8-2f515a12a7b0.png)

Thank you for looking into it!

**Comment by tomweber-sas** [comment]
Ok, though the error is saying it can't find the saspyiom.jar really. Is that path correct? 
If you are using anaconda, are you really running from that install, or a user install where saspy hasn't been installed in that environment? I get a lot of confusion w/ people using anaconda on windows, and not being in the place they think they are, or the environment only works from an anaconda shell, but not from a regular shell ...
 
And, what version of Java are you running? That could have something to do with it too. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Oh, I see you're running java from the SAS install; that should be ok. Didn't see that when I asked.
So, C:\\ProgramData\\Anaconda3\ is a system install of acaconda, though many people end up with packages they install in their User directory, C:\Users\userid\...   I don't know the rest of the path cuz I install only in the system one so there's no confusion. But, if you installed saspy and it's in your user directory, the path would be different than what is in the config.

**Comment by tomweber-sas** [comment]
just type in the following to see where you're running it from:
import saspy
saspy

```
>>> import saspy
>>> saspy
<module 'saspy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\saspy\\__init__.py'>>>>
```
In this case, it's installed in :  C:\ProgramData\Anaconda3\lib\\site-packages, cuz that's where I did install it.

**Comment by wonderfreda** [comment]
I ran it and the path shown is:

![image](https://user-images.githubusercontent.com/30054031/66964095-8b2d7d00-f043-11e9-9b34-15522cd27792.png)

**Comment by tomweber-sas** [comment]
Exactly. That's the user location that modules can get installed in as opposed to the system location. So, change the path to the saspyiom.jar to that instead of that system location, where it isn't, and you'll probably be good to go. 😀
Tom

**Comment by wonderfreda** [comment]
Excellent! I added a line in the sascfg_personal.py for cpW+ reflecting the user location and now it's running. Thanks a lot for your help!

**Comment by tomweber-sas** [comment]
Great! Let me know if there's anything else you need!
Tom
