### ISSUE TITLE
Views are not chunked and error handling not correct

### ISSUE THREAD

**Issue by fdegier** [sassoftware/saspy#270]
Hi,

Thank you for providing the package, it helps a lot with getting data from SAS using Python. However with my limited SAS knowledge I ran into a few issues that I would classify as bugs, I tried to describe them properly, hope it makes sense and you are able to help.

**Describe the bug**
The bug is two-fold: 

_Chunking_
Assume that we want to retrieve data in chunks of 1000 rows, we would specify this using `firstobs` and `obs` for `engine=BASE`.  From the documentation it makes sens that `obs` is the windows size, however this results in errors saying `obs > firstobs` so it appears that `obs` actually behaves as `endobs`. 

The following code would give back rows 1001 till 2000 meaning its the second chunk of 1000 rows.

```python
sas.saslib(libref=libref, engine=engine, options='ACCESS=READONLY', path=sas_path)
dsopts = {'firstobs': 1001, 'obs': 2000}
data = sas.sasdata(table=table, libref=libref, dsopts=dsopts)
```
This works fine if the table is actually a table, but when the table is a view it does not work due to a `where` clause being used in the view, disabling the use of `obs` and `firstobs`.

_Error handling_
When code runs and it encounter a SAS error in the notes, the rest of the code fails with: 
```ERROR - invalid literal for int() with base 10: 'vn=VARNUMS= vl=VARLIST= vt=VARTYPE= i=1 _ERROR_=1 _N_=1'```

Which is caused by: 
```python
File "/usr/local/lib/python3.7/site-packages/saspy/sasioiom.py", line 1740, in sasdata2dataframeCSV
    lrecl = int(l2[0])
```

**Expected behavior**
_Chunking_
Automatically handling `firstobs` and `obs` for views to represent the same behaviour as on tables.

_Error handling_
A proper error message parsed from SAS instead of a Python error related to `int()` failing.

**Desktop (please complete the following information):**
 - OS: Linux (docker: python:3.7.4-stretch)
 - SASPy Version: 3.1.6

**Comment by fdegier** [comment]
If you want I can create a PR for the error handling but the chunking I would greatly appreciate your help.

**Comment by tomweber-sas** [comment]
If you want to create a PR, that's great. I haven't had a chance to look into this yet, but will as soon as I can. Had a flurry of issues this week after a big lul earlier. Keeping me busy :)
Thanks,
Tom

**Comment by tomweber-sas** [comment]
Ok, I've looked at this some. There's a couple things here to address. First, you've got it right about using firstobs and obs (lastobs really; that always confuses me to at first too). So yes, you can work through blocks of the data at will.

Second is handling the error better when the submitted code fails. I don't get a nice return code from running code in SAS, so I have to try to handle these cases individually in every method for any code I ever submit. So, can you show me the code you ran and the error output. I will see where and how to try to make that better.

Now, even if I returned a better error, it still didn't work to do what you were trying to do. At first I though you describing that if a view has a where clause, then SAS doesn't let you use obs/firstobs, and that's why it failed. I tried this out a little and I see that this isn't specifically the case. But I also see a couple of issues, and some differences between data step views and proc sql views, so can you also tell me which kind of view you're using? That may be part of this too.

I see a couple bugs already in my code due to some of this. The first is in head(), where I'm actually using obs as a row count, not as 'lastobs'; can't believe this hasn't been reported or noticed. If you have firstobs set for your data object, I need to be adding obs= to that to specify as obs, but I am currently just using the parm to head (which defaults to 5), So the following fails when it should produce rows 100-105). and the one after that show those 5 rows should have shown 105 rows. I'll fix that so it's right.

```
>>> cars = sas.sasdata('cars','sashelp', results='text')
>>> cars
Libref  = sashelp
Table   = cars
Dsopts  = {}
Results = text

>>> cars.head()
                                                           The SAS System                         15:28 Friday, October 18, 2019   1

                                       Drive                   Engine                                 MPG_
 Obs Make  Model          Type  Origin Train     MSRP  Invoice  Size  Cylinders Horsepower MPG_City Highway Weight Wheelbase Length

   1 Acura MDX            SUV    Asia  All    $36,945  $33,337   3.5      6         265       17       23    4451     106      189
   2 Acura RSX Type S 2dr Sedan  Asia  Front  $23,820  $21,761   2.0      4         200       24       31    2778     101      172
   3 Acura TSX 4dr        Sedan  Asia  Front  $26,990  $24,647   2.4      4         200       22       29    3230     105      183
   4 Acura TL 4dr         Sedan  Asia  Front  $33,195  $30,299   3.2      6         270       20       28    3575     108      186
   5 Acura 3.5 RL 4dr     Sedan  Asia  Front  $43,755  $39,014   3.5      6         225       18       24    3880     115      197
>>> cars.dsopts={'firstobs' : 100}
>>> cars
Libref  = sashelp
Table   = cars
Dsopts  = {'firstobs': 100}
Results = text

>>> cars.head()    # this gets none when it should have been 5

>>> cars.head(105)  # this is what should have come out above


                                                           The SAS System                         15:28 Friday, October 18, 2019   2

                                                                                                              M
                                                                   D                         E       H        P
                                                                   r                         n   C   o        G         W
                                                                   i                         g   y   r    M   _         h
                                                                   v                  I      i   l   s    P   H         e
                                                             O     e                  n      n   i   e    G   i    W    e    L
                                  M                          r     T                  v      e   n   p    _   g    e    l    e
            M                     o                   T      i     r        M         o      S   d   o    C   h    i    b    n
     O      a                     d                   y      g     a        S         i      i   e   w    i   w    g    a    g
     b      k                     e                   p      i     i        R         c      z   r   e    t   a    h    s    t
     s      e                     l                   e      n     n        P         e      e   s   r    y   y    t    e    h

    100  Chrysler  300M Special Edition 4dr         Sedan   USA  Front   $33,295   $30,884  3.5  6  255  18  27  3650  113  198
    101  Chrysler  Sebring Limited convertible 2dr  Sedan   USA  Front   $30,950   $28,613  2.7  6  200  21  28  3448  106  194
    102  Chrysler  Town and Country LX              Sedan   USA  Front   $27,490   $25,371  3.3  6  180  19  26  4068  119  201
    103  Chrysler  Town and Country Limited         Sedan   USA  Front   $38,380   $35,063  3.8  6  215  18  25  4331  119  201
    104  Chrysler  Crossfire 2dr                    Sports  USA  Rear    $34,495   $32,033  3.2  6  215  17  25  3060   95  160
    105  Chrysler  Pacifica                         Wagon   USA  Rear    $31,230   $28,725  3.5  6  250  17  23  4675  116  199
>>> 
```

The other problem this has exposed is the difference in views. The obs() method applies your dsopts= when it gets the count, which it should, and that works right for datasets and for data step views, but doesn't work for proc sql views. So that's another bug I need to figure out how to fix. Need to spend more time tracking this down completely. Using those same views as above, one data step the other sql, they work except when using the dsopts on the sql one.

```
 68? proc sql;select count(*) from a;quit;
                                                                       The SAS System                                                                                       14:32 Friday, October 18, 2019 239
                                                                          --------
                                                                               102
NOTE: View WORK.A.VIEW used (Total process time):
      real time           0.14 seconds
      cpu time            0.08 seconds

NOTE: There were 102 observations read from the data set SASHELP.CARS.
      WHERE msrp>40000;
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.15 seconds
      cpu time            0.09 seconds


 69? proc sql;select count(*) from sa;quit;
                                                                       The SAS System                                                                                       14:32 Friday, October 18, 2019 240
                                                                          --------
                                                                               102
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.17 seconds
      cpu time            0.16 seconds


 76? proc sql;select count(*) from  a(firstobs=100 obs=120);quit;
                                                                       The SAS System                                                                                       14:32 Friday, October 18, 2019 241
                                                                          --------
                                                                                 3
NOTE: View WORK.A.VIEW used (Total process time):
      real time           0.11 seconds
      cpu time            0.08 seconds

NOTE: There were 102 observations read from the data set SASHELP.CARS.
      WHERE msrp>40000;
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.12 seconds
      cpu time            0.09 seconds

proc sql;select count(*) from sa(firstobs=100 obs=120);quit;

 77?
ERROR: Unable to process SAS data set options for SQL view WORK.SA.
NOTE: The SAS System stopped processing this step because of errors.
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.06 seconds
      cpu time            0.06 seconds


```

I'm gonna need to spend some more time on this to flush out any other issues that might be hiding in here.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
@fdegier the problems I described above, were not pervasive, and were limited to head() tali() and obs(). I have fixes for those I've been working on. However, I'd like to see the code you were using that got the errors you reported. It doesn't necessarily look like it was either of those 3 that you got an error from, but I don't see the code you ran so I don't know exactly where you got that error.
Can you show that code so I can see if there's more that I need to address with this?

Thanks,
Tom

**Comment by fdegier** [comment]
Hi Tom,

Thanks for your reply, I just ran the code again using the latest version of saspy. 

The code used is:
```python
sas.saslib(libref=libref, engine=engine, options='ACCESS=READONLY', path=sas_path)
dsopts = {'firstobs': 1001, 'obs': 2000}
data = sas.sasdata(table="D********E", libref="D****A", dsopts=dsopts)
```

Which returns the following message (* used to anonymize):
```
ERROR: Unable to process SAS data set options for SQL view D****A.D********E.\nNOTE: Argument 1 to function ATTRN(0,'LRECL') at line 87 column 9 is invalid.\nNOTE: Argument 1 to function ATTRN(0,'NVARS') at line 87 column 36 is invalid.\nLRECL= .\nVARNUMS= .\nVARLIST=\nERROR: Invalid DO loop control information, either the INITIAL or TO expression is missing or the BY expression is missing, zero, or invalid.
```

If I run the code without the dsopts it works, however its 300m rows so its too big to pull at once.

Given that the message actually specifies the error, it could be parsed and raised as an error.

**Comment by tomweber-sas** [comment]
Hey @fdegier , so, the thing is that none of those 3 lines can produce that error. It would have to be something like a sd2df method or a few others. I'm expecting you would be using the sd2df* to do what it sounds like you were trying. But I don't see any other code or actual output from running the code. 

But, I have dug into this further and found cases where sd2df* methods, when using sql views, fail, and thus get various tracebacks in python, as the expected output isn't there in the log. Hopefully, what you are seeing is related to at least one of these things I've found and fixed.   

I do have all of the fixes at master to address the errors I described above that I found in head/tail/obs. and these in sd2df*.  

Can you get the code from master and see if any of this fixes your case? And, can you show the actual run of your code with the output? And, if you're using a view, what is the view? You had mentioned a where clause, but I don't see anything about that in those 3 lines of code either. The problems I found are just from things I tried, so I don't know if they're the same as what you have or not.

Thanks,
Tom

**Comment by fdegier** [comment]
Hi Tom,

You are right, its caused by `to_df_CSV()` which triggers the code I described in my first post, sorry if this was unclear.

I'm running it via Airflow, this is the error as logged by Airflow:
```
2019-10-22 19:55:38,052] {{logging_mixin.py:95}} INFO - SAS Connection established. Subprocess id is 322
[2019-10-22 19:55:38,053] {{logging_mixin.py:95}} INFO - 
[2019-10-22 19:55:38,153] {{logging_mixin.py:95}} INFO - Start reading table: *****.
[2019-10-22 19:55:38,254] {{logging_mixin.py:95}} INFO - 3                                                          The SAS System                            21:55 Tuesday, October 22, 2019

20         
21         libname *****. BASE  '******************' ACCESS=READONLY;
NOTE: Libref *****. refers to the same physical library as *****.
NOTE: Libref *****. was successfully assigned as follows: 
      Engine:        BASE 
      Physical Name: ******************
[2019-10-22 19:55:39,259] {{logging_mixin.py:95}} INFO - Using dsopts: {'firstobs': '1', 'obs': '1000000'}
[2019-10-22 19:55:40,667] {{taskinstance.py:1051}} ERROR - invalid literal for int() with base 10: 'vn=VARNUMS= vl=VARLIST= vt=VARTYPE= i=1 _ERROR_=1 _N_=1'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/airflow/dags/operators/sas.py", line 28, in execute
    multiple_files=self.multiple_files
  File "/usr/local/airflow/dags/utils/sas.py", line 106, in extract
    tmp = data.to_df_CSV()
  File "/usr/local/lib/python3.7/site-packages/saspy/sasdata.py", line 1068, in to_df_CSV
    return self.to_df(method='CSV', tempfile=tempfile, tempkeep=tempkeep, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/saspy/sasdata.py", line 1056, in to_df
    return self.sas.sasdata2dataframe(self.table, self.libref, self.dsopts, method, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/saspy/sasbase.py", line 1133, in sasdata2dataframe
    return self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/saspy/sasioiom.py", line 1499, in sasdata2dataframe
    return self.sasdata2dataframeCSV(table, libref, dsopts, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/saspy/sasioiom.py", line 1740, in sasdata2dataframeCSV
    lrecl = int(l2[0])
ValueError: invalid literal for int() with base 10: 'vn=VARNUMS= vl=VARLIST= vt=VARTYPE= i=1 _ERROR_=1 _N_=1'
[2019-10-22 19:55:40,673] {{taskinstance.py:1082}} INFO - Marking task as FAILED.
```

If I print `ll`, the entire message is as following (after clean-up and anonymization):
```log
proc sql; create view sasdata2dataframe as select * from ***.**** (firstobs=1 obs=1000000 ); NOTE: SQL view WORK.SASDATA2DATAFRAME has been defined.
ERROR: Unable to process SAS data set options for SQL view DMT_SCHA.DNF_02_FARMACIE. ERROR: Unable to process SAS data set options for SQL view ***.****.

NOTE: Argument 1 to function ATTRN(0,'LRECL') at line 87 column 9 is invalid. NOTE: Argument 1 to function ATTRN(0,'NVARS') at line 87 column 36 is invalid. LRECL= . VARNUMS= . VARLIST= ERROR: Invalid DO loop control information, either the INITIAL or TO expression is missing or the BY expression is missing, zero, or invalid. d=0 var=  lrecl=. nvars=. lr=LRECL= vn=VARNUMS= vl=VARLIST= vt=VARTYPE= i=1 _ERROR_=1 _N_=1 NOTE: Mathematical operations could not be performed at the following places. The results of the operations have been set to  missing values. Each place is given by: (Number of times) at (Line):(Column). 1 at 87:9    1 at 87:36  NOTE: The SAS System stopped processing this step because of errors.
```

**Comment by tomweber-sas** [comment]
Ok, thanks, that is what I would have expected. So then the fixes at Master will likely address this. Have you tried that yet?

**Comment by fdegier** [comment]
With the master it works, perfect! Thank you. 
However with a larger table (300m rows) it used to be fast to use the `.obs()` method, now it takes much longer.

**Comment by tomweber-sas** [comment]
Great! for the fixed part :)

So is that table for the obs() case really a sql view? I'm wondering if it really didn't run before, and got an error in SAS, but the obs() methods still returned a value; that was a bug I fixed. Or, if there's something else different/wrong? 

SAS doesn't always guarantee it can tell you the number of observations; even for SAS members. Certainly not for Access Engines; database tables. When forced to give up the number, there can be cases (like having these options; where clauses, firstobs, obs) where the only way to do so is to read the table, with those things applied, and count the rows. I'm guessing this is one of those cases. BUT, again, did it really get the correct number before without reading and now it's reading? Or was this a case with the bug, where it (SAS) couldn't, and didn't return the number, but I (my obs method) incorrectly didn't notice that and, incorrectly (bug that's now fixed), returned a number.

If you are able to run both the before and after; code before master, and master, then you can run that obs() and print out the log to see the SAS code and it it really worked in the previous case.

Or, if you can provide me the definition of the SASdata object you're using; is it a view? Data step or sql? what dataset options are you using? Then I can see  about doing that myself and seeing if I can determine what's happening.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
So, I've played around with this some. Maybe enough to have a different idea of how to implement this. 
So, I have 3 different ways I've gotten the number of obs, so far. 
1) data step function nobs; this works the least of the time, and I never ended up using it.
2) proc sql, slect count(*) ...; this works more of the time, but fails for the sql views. (saspy obs())
3)  create data step view, then proc sql;select count(*) from view; this works even for sql view (saspy at master)

So, 1 doesn't even matter. 2 is what's been in saspy all along and is fast (as it can be), when it works. 3 works even when 2 doesn't but takes (some amount) longer than 2 most all of the time (from what I've seen so far). 

I hate to make everything take longer, just so the odd case that doesn't run will run. So, I'm thinking of adding a force=[**False** | True] parm to obs(). False is default.

When False, run proc sql smae as always. If that fails, you can say True and then I'll wrap it w/ the data step view and run proc sql and you'll get the obs, but it'll take as long as it takes.

What's you opinion on this?

Here's an example:
```
# given this view: proc sql;create view chris as select * from x.chris;quit;

# obs() works with this by default
>>> chris = sas.sasdata('chris')
>>> chris.obs()
50000

# with the where clause this fails to get the obs without the extra work
>>> chris.dsopts={'where' : 'TOTAL_VALUE_PER_SQ_FT > 100'}
>>> chris.obs()
The number of obs was not able to be determined. You can specify obs(force=True) to force it to be calculated
>>> chris.obs(force=True)
30452
>>>

# here both cases run, but the True takes longer, so we don't want that by default
>>> chris.dsopts={}
>>> chris.obs(force=False)
50000
>>> chris.obs(force=True)
50000
>>>
```

with the force=True it ran, and it took a little time to calculate. But, when obs() actually worked, with force=False, it didn't take the extra time, 

So, I've pushed this to master for you to try out with your cases. Can you give it a try and see if things behave better for you, and if you even hit the case that would require True?

Thanks,
Tom

**Comment by fdegier** [comment]
Hi Tom,

I don't recall seeing the `.count()` fail due to obs, it was only after that when I used `obs` to chunk the data that it would fail. I just tested this and in fact:

```python
def obs(self):
	"""
    return the number of observations for your SASdata object
    """
 	code = "proc sql;select count(*) format best32. into :lastobs from "+ self.libref + ".'" + self.table + "'n " + self._dsopts() + ";%put lastobs=&lastobs 	lastobsend=;\nquit;"

```
Gives the result within seconds, and:

```python
def obs(self):
	"""
    return the number of observations for your SASdata object
    """
	code  = "%let lastobs=-1;\n"
	code  += "data sasdata2dataframe / view=sasdata2dataframe; set "+ self.libref + ".'" + self.table + "'n " + self._dsopts() +";run;\n"
	code += "proc sql;select count(*) format best32. into :lastobs from sasdata2dataframe;"
```
takes 1 hour.

**Comment by fdegier** [comment]
Please also note that `.contents()` does not take into account the `obs` issue, see the following:

```python
varcat = l2[2].split("\n", nvars)
print(varcat)
```
Out:
```log
[2019-10-24 12:24:49,750] {{logging_mixin.py:95}} INFO - ['ERROR: The option OBS= cannot be used with the SPD Engine-only options STARTOBS= or ENDOBS= for file
```

**Comment by tomweber-sas** [comment]
So, with the new code, you get the error saying this?
```
The number of obs was not able to be determined. You can specify obs(force=True) to force it to be calculated
```
And if you set force=True it takes an hour to get the value?

I need to see what this data set it that you are trying to access. Can you run the following code, with whatever the libref and data set name you are using?

```
print(sas.submit("""
libname YOURLIBREF list;
proc contents data=YOURLIBREF.YOURTABLENAME;run;
""")['LOG'])
```
It would really help me if I can see the code you're running, the results that running that code produces and the SAS log for the session after you run that code. you can submit 
```
print(sas.saslog()) 
```
to get the log.

Assuming your SASsession is named 'sas' (it could be anything), and your SASdata object is named data1, can you run the following also so I can see the output:

```
import saspy
sas = saspy.SASsession(...)
sas

data1 = sas.sasdata(...)
data1
```

Thanks,
Tom

**Comment by fdegier** [comment]
Chunking of views works perfect now, thanks! :D
