### ISSUE TITLE
how to configure EG7.1 on the  remote desktop

### ISSUE THREAD

**Issue by westcliffe** [sassoftware/saspy#277]
I read issue #171 and still didn't figure out how to configure SAS EG on remote desktop.

My issue is EG7.1 located in Remote Desktop ( windows server 2008 R;  Host Name for remote desktop : ABC-SASTOOL)

Here is for personal sascfg:

SAS_config_names=['winiomwin']
SAS_config_options = {'lock_down': False,
                      'verbose'  : True
                     }

cpW  =  "H:\\My Documents\\D_Cam\\Project\\Jar\\sas.svc.connection.jar"
cpW += ";H:\\My Documents\\D_Cam\\Project\\Jar\\log4j.jar"
cpW += ";H:\\My Documents\\D_Cam\\Project\\Jar\\sas.security.sspi.jar"
cpW += ";H:\\My Documents\\D_Cam\\Project\\Jar\\sas.core.jar"
#cpW += ";C:\\wherever\\I\\put\\these\\jars\\saspyiom.jar"
cpW += ";H:\\My Documents\\D_Cam\\Project\\Jar\\saspyiom.jar"

winiomwin  = {'java'    : 'java',
            'iomhost'   :'WIL-ENTSAS##.***.com',
            'iomport'   : 8591,
            'encoding'  : 'windows-1252',
            'appserver' : 'Analytics - Workspace Server',  
            'classpath' : cpW
            }

Still can't connect. My questions:
 how to put remote desktop connection (host name or ip address)?

the usename and pass word is the same for remote server and EG server. how to input?

Thanks
Qing

**Comment by tomweber-sas** [comment]
Can you show me what you are getting when you try to connect? What error are you seeing? It sounds like you are saying you're trying to connect saspy to EG, but that isn't what it does. It can connect to the same workspace servers that the EG client connects to. Is that what you are trying to do? Assuming that's so, can you verify the host and port that EG is using to get at the workspace server? 
Thanks,
Tom

**Comment by westcliffe** [comment]
Morning, Tom,
Thanks for your quick response. 

i run proc iomoperate on EG and get spawner server object info.  machine name is for iomhost. 

Foundation repository (A0000001.A5XAV222)

    Object Spawner - WIL-METASASPRD4 (A5XAV222.AU000002)
        Server class : IOM Spawner
        Spawnable server component : Operating System Services - WIL-METASASPRD4.&&&.com
        Operator port : 8581
        PortBank port : 8801
        PortBank port : 8811
        PortBank port : 8821
        Machine name : WIL-METASASPRD4.&&&.com


error:


  File "C:\Anaconda3\Lib\site-packages\saspy\sasbase.py", line 439, in __init__
    raise SASIONotSupportedError(self.sascfg.mode, alts=['IOM'])

SASIONotSupportedError: Cannot use STDIO I/O module on Windows. Try the following: IOM

**Comment by tomweber-sas** [comment]
Ok, the spawner machine is the correct one for IOMHOST. And the port number needs to be the port it's listening on for workspace server connections; the default being 8591, like you have. You can also run the other IOMOPERATE query looking for 'Workspace' to verify that, if need be.

But, this error shows that you are not using the configuration you show in the first post above. This error is what you get if you end up using the sascfg.py examples file on windows. If you have the current version of saspy, the following will show you what config file saspy will use and what possible ones there are in the search path. Can you run this and see? It doesn't seem to be picking up the one you show above. You can put that file in a directory in the search path, or you can specify the path directly on the SASsession(cfgfile='path') too.

```
import saspy
saspy
saspy.SAScfg
saspy.list_configs()
```

Thanks,
Tom

**Comment by westcliffe** [comment]
Tom,

i double chekced port by PROC IOMOPERATE with FILTER="- Workspace" and port is 8591. 
after submit the code:

import saspy
import pandas as pd
from IPython.display import HTML
saspy
sas=saspy.SASsession(cfgfile='C:Anaconda3/Lib/site-packages/personal_sascfg.py')
saspy.SAScfg
saspy.list_configs()

the result in log:


  File "<ipython-input-40-8a0b4c9c7d40>", line 5, in <module>
    sas=saspy.SASsession(cfgfile='C:Anaconda3/Lib/site-packages/personal_sascfg.py')

  File "C:\Anaconda3\Lib\site-packages\saspy\sasbase.py", line 410, in __init__
    self.sascfg            = SASconfig(**kwargs)

  File "C:\Anaconda3\Lib\site-packages\saspy\sasbase.py", line 130, in __init__
    SAScfg = self._find_config(cfg_override=kwargs.get('cfgfile'))

  File "C:\Anaconda3\Lib\site-packages\saspy\sasbase.py", line 250, in _find_config
    raise SASConfigNotFoundError(cfg_expand)

SASConfigNotFoundError: Configuration path C:Anaconda3/Lib/site-packages/personal_sascfg.py does not exist.

**Comment by westcliffe** [comment]
Tom,
please discard last post. i put wrong path. after corrected. the log showed :

SAS process has terminated unexpectedly. RC from wait was: 4294967290
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'H:\\My Documents\\D_Cam\\Project\\Jar\\sas.svc.connection.jar;H:\\My Documents\\D_Cam\\Project\\Jar\\log4j.jar;H:\\My Documents\\D_Cam\\Project\\Jar\\sas.security.sspi.jar;H:\\My Documents\\D_Cam\\Project\\Jar\\sas.core.jar;H:\\My Documents\\D_Cam\\Project\\Jar\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '60311', '-stdoutport', '60312', '-stderrport', '60313', '-appname', "'Analytics - Workspace Server'", '-iomhost', 'WIL-METASASPRD4.bbtnet.com', '-iomport', '8591', '-user', 'c46850', '-lrecl', '1048576', '']

No SAS process attached. SAS process has terminated unexpectedly.
Traceback (most recent call last):

  File "<ipython-input-44-58d769b069f2>", line 2, in <module>
    saspy.SASsession(cfgfile='C:/Anaconda3/Lib/site-packages/personal_sascfg.py')

  File "C:\Anaconda3\Lib\site-packages\saspy\sasbase.py", line 480, in __init__
    pyenc = sas_encoding_mapping[self.sascei]

KeyError: 'No SAS process attached. SAS process has terminated unexpectedly.'

**Comment by westcliffe** [comment]
EG 7.1 configuration detail: 
![image](https://user-images.githubusercontent.com/45299382/72098171-ec37ba80-32eb-11ea-89ad-b7e18fcd621b.png)

**Comment by tomweber-sas** [comment]
ok, gotcha. So, I'm not seeing an IOM error there at all. I'm not convinced java is starting up correctly, so it could be an issue with the class path or something. You didn't appear to get the rest of the error message saying to try to run that command directly to see if there's a better error message. That usualy comes out, but here's the command to try. Can you run this from a command prompt from wherever you're running saspy?
```
java -classpath "H:\My Documents\D_Cam\Project\Jar\sas.svc.connection.jar;H:\My Documents\D_Cam\Project\Jar\log4j.jar;H:\My Documents\D_Cam\Project\Jar\sas.security.sspi.jar;H:\My Documents\D_Cam\Project\Jar\sas.core.jar;H:\My Documents\D_Cam\Project\Jar\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 59110 -stdoutport 59111 -stderrport 59112 -appname "Analytics - Workspace Server" -iomhost WIL-METASASPRD4.bbtnet.com -iomport 8591, -user c46850 -lrecl 1048576
```

BTW, why would the saspyiom.jar you'tr pointing to not be 
"C:\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar"? That's the jar that's part of the saspy install. Did you actually copy it to that other directory with the IOM client jars? That's something that would be a problem sometime if you upgrade saspy and that jar doesn't match with the rest of the code in the newer version.
That could be the problem too if that jar isn't really there either. 

And, if you put your sascfg_personal.py in C:\Anaconda3\Lib\site-packages\saspy\ then you won't need to specify it on the SASsession() method, it'll find it and use it from there.

Tom

**Comment by tomweber-sas** [comment]
Also, the EG info, I don't see anything in there that is relevant. I think I saw you said you verified the port, as well as the host, so that's really all that's needed. And, as I'm not seeing an IOM errors related to the wrong host or port, I'm still thinking it's java not coming up. Depending upon the problem and timing of that, I don't always get a good error message back, which is why the usual message, that you didn't get, saying to run the java command manually and we should get the real error that way.

Here's an example error with that rest of the message near the end (I try to put the command you can just cut-n-paste).

'If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:'

```
sas = saspy.SASsession(cfgname='winlocal', classpath=cp)

Java Error:
java.lang.NoClassDefFoundError: com/sas/util/ChainedExceptionInterface
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sas.util.ChainedExceptionInterface
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 19 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"

Subprocess failed to start. Double check your settings in sascfg_personal.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\java\\sas.svc.connection.jar;C:\\java\\log4j.jar;C:\\jars\\sas.security.sspi.jar;C:\\jars\\saspyiom.jar',
'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '59110', '-stdoutport', '59111', '-stderrport', '59112', '-zero', '']

If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
java -classpath "C:\java\sas.svc.connection.jar;C:\java\log4j.jar;C:\jars\sas.security.sspi.jar;C:\jars\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 59110 -stdoutport 59111 -stderrport 59112 -zero

No SAS process attached. SAS process has terminated unexpectedly.
```

**Comment by westcliffe** [comment]
i deleted copied saspyiom.jar and modified path to point the "C:\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar".   after run java in command prompt. the result showed below 
![image](https://user-images.githubusercontent.com/45299382/72105634-ee097a00-32fb-11ea-8c8c-00e80fef89fa.png)
 looks still is sas configuration issue. I need to ask help company's admin.

**Comment by westcliffe** [comment]
there were 3 folders which all had the same 4 java files. I used  deploywiz_94420_***
![image](https://user-images.githubusercontent.com/45299382/72106822-1c885480-32fe-11ea-951b-ade59f7f2a4a.png)

**Comment by tomweber-sas** [comment]
ok, hang on. So that error is what you should get; the connection refused java error. Because, saspy isn't waiting for the java process to connect; That shows that java IS coming up without a serious classpath problem. And that the saspyiom jar was found and tried to run. 
The three folders with the jars are probably updates or hotfixes, so that's not troublesome either.

So, there's still no real error that is pointing me at anything next. What environment are you running this in? Notebook, command line, some IDE?

Would a web-ex work? I can set that up. Might see something myself that I'm not coming up with.
BTW, what version of java and of saspy are you running? I see SAS is a 9.4 version, so we should be good there.

**Comment by westcliffe** [comment]
I run on Spyder. SAS EG7.1 was installed remote desktop. there is different java version between remote desktop and local., version 6 in remote desktop, version 8 in local. 
![image](https://user-images.githubusercontent.com/45299382/72114080-72fe8e80-3310-11ea-865c-d4d682d6bc30.png)

**Comment by tomweber-sas** [comment]
Java 6 is too old and won't work, but java 8 is fine. Which one are you using?

**Comment by tomweber-sas** [comment]
Ok, we took this offline via webex and got the configuration set up and connected to the same workspace server as EG was connecting to. All is well and up and running. :) 
going ahead and closing.
Tom
