### ISSUE TITLE
Starting SASpy with winlocal and memsize max

### ISSUE THREAD

**Issue by optidatascience** [sassoftware/saspy#278]
**Describe the bug**
Having issues starting saspy with IOM winlocal and specify memsize = max. It always defaults to the sas cfg file that our environment has a limitation per user. I can use command line "sas.exe -memsize max" to start sas with no memory constraint

**To Reproduce**
Here is my config file for winlocal
```
winlocal = {'java'      : 'java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW,
            'options'   : ['-memsize=max'],
            }
```

and start session command, 
`sas = saspy.SASsession(cfgfile='../_Config/sascfg.py',cfgname='winlocal')
`
No issue to start SAS session. However, when I run 
`sas.submit('proc options option=MEMSIZE value;run;')
`
```
SAS (r) Proprietary Software Release 9.4  TS1M2

Option Value Information For SAS Option MEMSIZE
    Value: **4294967296**
    Scope: SAS Session
    How option value set: Config File
    Config file name:
            E:\Program Files\SASHome\SASFoundation\9.4\nls\en\sasv9.cfg

NOTE: PROCEDURE OPTIONS used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

```
**Expected behavior**
I have 96G installed on the sas server, but still it memory shows 4G and it loads the default sas config

**Desktop (please complete the following information):**
 - OS: Windows Server 2012
 - SAS Version: 9.4
 - SASPy Version: 3.1.8

Thank you for helping!

**Comment by optidatascience** [comment]
I also tried to use the config below and it doesn't help 

```
winlocal = {'java'      : 'H:\\Download\\Java\\jre1.8.0_51\\bin\\java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW,
            'options'   : ['-memsize=max'],
            'javaparms' : ["-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=E:\\Program Files\\SASHome\\SASFoundation\\9.4\\sas.exe"]
            }
```

And this one below throws errors when start SAS sessions

```
winlocal = {'java'      : 'H:\\Download\\Java\\jre1.8.0_51\\bin\\java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW,
            'javaparms' : ["-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=E:\\Program Files\\SASHome\\SASFoundation\\9.4\\sas.exe -memsize=max"]
            }
```

**Comment by tomweber-sas** [comment]
Hey, yes, the IOM protocol doesn't provide a way for me to override, or provide, options at startup. It's designed to be used starting up SAS servers, like Workspace servers, where they only use the configuration for the server, so the user starting them can reconfigure them on the fly. Using it with a stand alone install on your PC is a special case (no metadata, object spawner, workspace server...), but it still doesn't provide a way to provide startup options. And, memsize is a startup only option.

So, I'm guessing you can't just change the value to MAX in the config file; don't have permission or something? That would be the way to do this. But, if you can't, then can you copy the config file to one you can edit and then try your idea about using the javaparms, but add
-config your\path\to\your\config\file 
on that after the SAS command? Like how you tried with -memsize.
I haven't tried that, but I think it ought to work.

Tom

**Comment by tomweber-sas** [comment]
BTW, that's why the 'options' parm isn't available for IOM, only STDIO. In the STDIO access method, I do start SAS myself, like on the command line, So I can specify start up options that way.

**Comment by tomweber-sas** [comment]
Here's an example for the javaparms that has config and the other options you might need. Of course, your paths would be different.
```
'-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd="C:\\PROGRA~1\\SASHome\\SASFOU~1\\9.4\\SAS.EXE" -config "C:\\PROGRA~1\\SASHome\\SASFOU~1\\9.4\\sasv9.cfg" -objectserver -nologo -noinal -noprngetlist'
```

**Comment by optidatascience** [comment]
Hi Tom, 

Thank you for the quick reply! I don't have permission to change sas cfg file so that's reason looking for other possibilities... I've tried your suggestion and it doesn't work. The error is that you can't add any options after /path/to/sas.exe
`
-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd
`
I think there might be some other java parameters similar to above that you can set to point to a new config file.. but I am not familiar with SAS Foundation Java classes, so don't know which one to set..

**Comment by tomweber-sas** [comment]
ugh. Well, that's too bad. I don't know any of that off the top of my head either. But, I will investigate this more and see if I can come up with a workaround. 
Tom

**Comment by tomweber-sas** [comment]
Is this 'your' machine? Or rather, would you be allowed to edit the registry where this startup command is. Maybe not if you aren't allowed to edit the sascfg file. But, if you can, you can specify the same thing there, which should work. 

![image](https://user-images.githubusercontent.com/17710182/72171739-96254e80-33a1-11ea-836b-17f866fcc0e5.png)

I'll keep checking to see if there are other parms where we can specify these, But, the registry entry is the startup command, so changing the config file there would work. If you can edit it.

Thanks,
Tom

**Comment by optidatascience** [comment]
There are many instances when I put sasv9.cfg in search.. It is a Win Server that are shared by many users. I don't think I am able to change all of them, and I also wouldn't give all user access to full memory :P

**Comment by tomweber-sas** [comment]
Hey, I did verify this works. I think maybe you may not have had the quotes all right or something?
The 'sascmd' is a string of the whole thing, sas.exe plus all the -options. So there is not other option needed; they whole commnad like IS the string value of ...sascmd=' sas.exe -config ... -whatever'

I just ran with this in my config and verified it uses the config file pointed to. Can you give this another try? You have to get those goofy windows paths right.

```
'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE -config "C:\PROGRA~1\SASHome\SASFOU~1\9.4\sasv9.cfg" -objectserver -nologo -noterminal -noprngetlist']
```

**Comment by optidatascience** [comment]
Finally I got it to work. 
`
'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd="E:\\Program Files\\SASHome\\SASFoundation\\9.4\\sas.exe" -config "H:\_Config\sasv9.cfg"']`

The trick is there is no "=" after the options.. I was using `-config="H:\_Config\sasv9.cfg"`

Thank you for your help, Tom!

**Comment by optidatascience** [comment]
And by the way, you can also use `-memsize max` too. :)

**Comment by tomweber-sas** [comment]
Sweet! Well that's good to know now, that you can get startup options to it that way!
Very good.

**Comment by tomweber-sas** [comment]
So, we can close this one then? You're all good?

**Comment by optidatascience** [comment]
Yes, totally! Thank you!
