### ISSUE TITLE
Write out sas7bdat file

### ISSUE THREAD

**Issue by biojerm** [sassoftware/saspy#280]
Hey Tom, 

Is there an easy way to write out *.sas7bdat files using saspy?

Right now i am using the sas.submit and it is a little tedious.  I assume I missed it somewhere in the docs.

Thanks,
Jeremy

**Comment by tomweber-sas** [comment]
Hey @biojerm, can you give me an example of what you're doing? I'm not sure I quite understand.
Thanks,
Tom

**Comment by biojerm** [comment]
@tomweber-sas  sorry for the confusion,  I wrote this little function that takes in a pandas dataframe and will write the dataframe into a sas dataset in the sas7bdatformat.

```
def df2sas7bdat(df, file_name, out_path):
    sas = saspy.SASsession(cfgname='mycfg')
    sas_ds = sas.df2sd(df, file_name)  # push dataframe to sas session
    sas.submit(f"libname myDf '{os.path.normpath(out_path)}';"
               f"data myDf.{file_name};"
               f"set {file_name};"
               "run;"
               )
```

However the only way I found to write out the dataset was to supply the SAS commands and execute them via a `sas.submit`.  Is there a better way to do this?

**Comment by tomweber-sas** [comment]
If I read this right, you're just trying to have the SAS datasets written to a particular library (directory on disk)? df2sd writes out .sas7bdat files to disk; that's what a SAS dataset is. Given what I see, try this instead and see if this is what you really want. 

Assign the libref to that location, then specify that libref in sd2df; done.

```
# given: df (data frame), file_name (SAS data set name; tablename), out_path (SAS library; OS directory)

# create SAS session
sas = saspy.SASsession(cfgname='mycfg')

# assign libref  (this generates and assignes the libref via a libname statement
sas.saslib("myDf", path=os.path.normpath('/u/sastpw/'))

#write df to SAS dataset in the library you wanted it in: sd2df(df, table=file_name, libref='mydf')
sas_ds = sas.df2sd(df, file_name, "myDf")  # push dataframe to sas session
```

Is that it?
Tom

**Comment by biojerm** [comment]
Yup this is what I was trying to do but in a silly way.  Thanks!

**Comment by tomweber-sas** [comment]
No problem, I'm good with these easy ones too :)

**Comment by jinwzhang** [comment]
Great question and anwsers. I had work on this issue over weeks.  A little suggest is the save to sas7bdat method could be added into the df2sd(). E.g. df2sd(df, table=file_name, libref, save=True) OR just to_sas7bdat() like to_csv() does.

**Comment by jinwzhang** [comment]
Hi Tom,

I just tried this method you metioned but seems has no effect, the file did not created, and no error hints. Does it works for remote connection?

>>> sas = saspy.SASsession()
Using SAS Config named: ssh
SAS Connection established. Subprocess id is 23981
>>> sas.saslib(libref='ods', path='/sasdata/ods_data')

17   
18   libname ods    '/sasdata/ods_data'  ;
NOTE: SUCCESSFULLY ASIGNED TO“ODS”，AS FOLLOWING: 
       engine:        V9 
       physical name: /sasdata/ods_data
19   
20   
>>> cars = sas.sd2df('cars', 'sashelp')
>>> sas_df = sas.df2sd(cars, 'tst_cars', 'ods')
(End but no file found)

**Comment by jinwzhang** [comment]
also tried
>>> test = sas.sd2df('test_cars', 'ods')
The SAS Data Set ods.test_cars does not exist

**Comment by jinwzhang** [comment]
>>> test = sas.sd2df('tst_cars', 'ods')
The SAS Data Set ods.test_cars does not exist

**Comment by tomweber-sas** [comment]
Hey, well, I'd need to see more info to have some idea of what may be going on. Can you show the log after running
sas_df = sas.df2sd(cars, 'tst_cars', 'ods')
print(sas.saslog())

Do you have permission to write to that directory? And, can you submit the SAS session object so I can see what version,. access method,. ... you have? for instance:
```
>>> sas
Access Method         = IOM
SAS Config name       = iomj
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /sastmp/SAS_workDFCA00000F23_tom64-5/SAS_work178300000F23_tom64-5/
SAS Version           = 9.04.01M4D11092016
SASPy Version         = 3.3.5
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 3875
```

**Comment by jinwzhang** [comment]
Hey Tom,

After checked the log, I found it was due to the user authencating issue. After changing my config ssh host as the following to the r/w user, sas file created, thank you so much!

ssh48      = {'saspath' : '/opt/sas94/SASHome/SASFoundation/9.4/bin/sas_en',
            'ssh'     : '/usr/bin/ssh',
            'host'    : 'odsuser@XX.XXX.XXX.48',
            'encoding': 'latin1',
            'options' : ["-fullstimer"]
            }

**Comment by tomweber-sas** [comment]
Hey that's great. Yes, looking at the log after running something that doesn't seem to work is the first thing to do! Glad that's working!
Tom
