### ISSUE TITLE
saslib self.nosub  issue

### ISSUE THREAD

**Issue by camccaul** [sassoftware/saspy#282]
When trying to establish libname using sas.saslib receive the following error, 
--> 540         if self.nosub:
    541             print(code)
    542         else:

AttributeError: 'str' object has no attribute 'nosub'

This is the code I submitted
sas.saslib('mydata', 'BASE', "'C:\Users\Documents\python'")

using saspy 2.1.7, python 3.6.3

**Comment by tomweber-sas** [comment]
Hey, no problem, V2.1.7 is over 2 years old. Any chance of getting a current version of saspy and giving it another try? There have been hundreds of enhancements over that time. 
The error seems strange too, as it's implying the SASsession object (self in this code), is a string, so it doesn't seem there's really a connection. I'd have to see more code and output to tell what's happening. If you submit your SASsession object (sas) it should display info about itself, if it is a SASsession object.

Tom

**Comment by tomweber-sas** [comment]
One of the enhancements over that time is also that you don't have to try to add extra quotes to the path; I do that for you now (I know your path is windows, and mine linux, but that doesn't mater):

```
>>> sas.saslib('mydata', 'BASE', '/u/sastpw')

44
45   libname mydata BASE  '/u/sastpw'  ;
NOTE: Libref MYDATA was successfully assigned as follows:
      Engine:        BASE
      Physical Name: /u/sastpw
46
47
>>> sas.saslib('mydata', 'BASE', "/u/sastpw")

49
50   libname mydata BASE  '/u/sastpw'  ;
NOTE: Libref MYDATA was successfully assigned as follows:
      Engine:        BASE
      Physical Name: /u/sastpw
51
52
>>>
```

**Comment by camccaul** [comment]
Thanks for the quick response, I will see what we can do about getting an upgrade, but for now this is what we have to work with.

I tried the single quotes no luck... single quotes, getting the following error 
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
These are the steps and results I have been running and results, am I missing something?
1 import saspy
2 import pandas as pd
1 saspy

<module 'saspy' from '/trvapps/anaconda/anaconda-5.0/lib/python3.6/site-packages/saspy/__init__.py'>

1 sas=saspy.SASsession
2 sas
saspy.sasbase.SASsession

1 sas.saslib('mydata', 'BASE', 'C:\Users\camccaul\Documents\python')

  File "<ipython-input-6-acda8f18e0e7>", line 1
    sas.saslib('mydata', 'BASE', 'C:\Users\camccaul\Documents\python')
                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by tomweber-sas** [comment]
Ah, there we are. That's why 'sas' is a string, not a SASsession object.  SASsession is a method, so you need:

sas=saspy.SASsession()

Do you have saspy configured? https://sassoftware.github.io/saspy/install.html#configuration
If so, then adding the parenthesis should get you an actually connection to a SAS session. Then you can start using it. If not, then you need to configure saspy so it knows where SAS is and how you want it to connect to it.

Tom

**Comment by tomweber-sas** [comment]
Oh, that the unicode exception you're getting is because on windows you either have to use double backslashes or tag the string as raw:
```
'c:\\dir1\\dir2'
or
r'c:\dir1\dirs'
```

**Comment by tomweber-sas** [comment]
Hey, were you able to establish a connection and get a valid SASsession object?
```
sas=saspy.SASsession()
sas
```

**Comment by camccaul** [comment]
Thanks for the help, we are up and running, also requested upgrade to current version of saspy...

Thanks again

**Comment by tomweber-sas** [comment]
That's good new :)  Should we close this? You can always open it up again, or open another if you have other issues!

Thanks,
Tom

**Comment by camccaul** [comment]
Yes, this can be closed.

Thanks,
