### ISSUE TITLE
Localhost i hosts file

### ISSUE THREAD

**Issue by jingmeb** [sassoftware/saspy#285]
Hello!

Is there anyway of configuring saspy such as that localhost doesn’t need to be added to the hosts file?

**Comment by tomweber-sas** [comment]
Hey, I'm sorry I haven't responded. I'm out west skiing. I'll be back in the office Monday. Is it an IOM local connection you're having trouble with?  Is it number 6 under https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors ?
If so, that's an IOM requirement that I can't control on my side.
Tom

**Comment by jingmeb** [comment]
Exactly! Ok, thanks!
