### ISSUE TITLE
Get data from wrds in Jupyter notebook, but the data doesn't exist in work library 

### ISSUE THREAD

**Issue by slucyp** [sassoftware/saspy#287]
I try to query data from wrds through saspy and download the data, as shown in the following code:

```
%%SAS 
%let wrds = wrds.wharton.upenn.edu 4016;options comamid = TCP remote=WRDS;
signon username=myusername password=mypassword;
​
/*Downloading quarterly call report data*/
rsubmit;
libname bank "/wrds/bank/sasdata/commercial"; run; /*find the file directory on wrds*/
​
/****** extract control variale data**/
​data work.control; set bank.call200112; loan=rcfd1400; deposits=rcfd2200; assets=rcfd2170; 
keep rssd9001 date loan deposits assets; run; 
proc download data=work.control out=work.control ; run;
endrsubmit;
```

The SAS log shows that work.control has been created

> NOTE: There were 8998 observations read from the data set BANK.CALL200112.
NOTE: The data set WORK.CONTROL has 8998 observations and 7 variables.
NOTE: DATA statement used (Total process time):
      real time           0.44 seconds
      cpu time            0.19 seconds
      32   proc download data=work.control out=work.control status = N; run;
NOTE: Download in progress from data=WORK.CONTROL to out=WORK.CONTROL
NOTE: 503888 bytes were transferred at 604182 bytes/second.
NOTE: The data set WORK.CONTROL has 8998 observations and 7 variables.
NOTE: Downloaded 8998 observations of 7 variables.
NOTE: The data set WORK.CONTROL has 8998 observations and 7 variables.
NOTE: PROCEDURE DOWNLOAD used (Total process time):
      real time           0.96 seconds
      cpu time            0.04 seconds
      NOTE: Remote submit to WRDS complete.
66         
67         
68         ods html5 (id=saspy_internal) close;ods listing;
69         

But then when I try to fetch the data from work library, I get nothing
`fcm = sas.sd2df(table='control',libref='work')`

returns

> The SAS Data Set work.control does not exist

Any ideas or suggestions about what is wrong here?

Thanks a lot!

**Comment by tomweber-sas** [comment]
Ah, you had me there for a minute.  I was fixated on the SAS Connect and comamid=TCP; took me back 30 years,  lol. 
Yeah,  you're using that magic; %%SAS
So you can either add you're SASsession object to that (you using two different SAS sessions, is why it's not there),  or use the sas.submit or submitLOG or submitLST methods.  Either way,  when you are using these same session,  the table will be there for you. 

%%SAS sas
Code

That will use your 'sas' session for submitting that code so it's in the same session. 

Tom

**Comment by slucyp** [comment]
Ha! Thanks so much for your quick reply! Yes, that's the thing! I then successfully see the tables using both methods, it took me so much time trying to figure it out, and your comments just like those "AHA" moment! I was kind of amazed by the fact that when using sas.submit command, the whole block of sas codes just run behind the scene, with the data generated exactly as in SAS, while the object generated by this method only records the log and result! I  previously thought that the data might be stored in the object and I have call to get the data, but this seems much better and easy! Thanks again!

**Comment by tomweber-sas** [comment]
Awesome, I' love it when the answers work out that easy! Glad that's all working for you, and thanks!
I'll close this one, and just let me know if you need anything else!
Tom
