### ISSUE TITLE
error occured in SAS during sasdata2dataframe. Trying to return the saslog instead of a data frame.

### ISSUE THREAD

**Issue by saumya123-alt** [sassoftware/saspy#291]
>>> saspy
<module 'saspy' from '/Users/XXXXX/opt/anaconda3/lib/python3.7/site-packages/saspy/__init__.py'>
>>> sas
Access Method         = SSH
SAS Config name       = ssh
SAS Config file       = /Users/XXXXX/Desktop/sascfg.py
WORK Path             = /home/devo/c5050xxxx/SAS_workA857000063E2_pr3-xxxx-lapxxx.xxx.xxxx.com/
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 3.3.4
Teach me SAS          = False
Batch                 = False
Results               = text
SAS Session Encoding  = utf-8
Python Encoding value = utf-8
SAS process Pid value = 25570

>>> sastab= sas.sasdata('sasdata', results='text')
Table WORK.sasdata does not exist. This SASdata object will not be useful until the data set is created.
>>> cars=sas.sasdata2dataframe(table='cars',libref='sashelp')
error occured in SAS during sasdata2dataframe. Trying to return the saslog instead of a data frame.

**Comment by tomweber-sas** [comment]
What was in the log?

**Comment by tomweber-sas** [comment]
Just do 'print(cars)' as cars was the log that was returned instead of the dataframe, since there was an error. 
Since your using SSH, the most likely thing is that you can't establish the socket connection from SAS to the port on your client. But, we should see that in the log to know for sure. If that's the case, you just need to use the rtunnel (and tunnel some other cases), to specify a port to use across the SSH tunnel. See the doc on these config def options here: https://sassoftware.github.io/saspy/install.html#stdio-over-ssh
You just pick some unused port(s) and the connections will then go through the existing SSH tunnel instead of trying to go over new socket connections.
But, Let's see what the error is so we aren't just guessing.
Tom

**Comment by saumya123-alt** [comment]
Log :
283  filename sock socket 'EXIHYD-IM-021:53176' lrecl=1 recfm=f encoding=binary;
284  data _null_; set sashelp.'cars'n ;
285  format 'MSRP'n best32.; format 'Invoice'n best32.; format 'EngineSize'n best32.; format 'Cylinders'n best32.; format
285! 'Horsepower'n best32.; format 'MPG_City'n best32.;
286  format 'MPG_Highway'n best32.; format 'Weight'n best32.; format 'Wheelbase'n best32.; format 'Length'n best32.; file sock; put
286! 'Make'n '02'x;
287  put 'Model'n '02'x; put 'Type'n '02'x; put 'Origin'n '02'x; put 'DriveTrain'n '02'x; put 'MSRP'n '02'x; put 'Invoice'n '02'x;
287! put 'EngineSize'n '02'x; put 'Cylinders'n '02'x; put 'Horsepower'n '02'x; put 'MPG_City'n '02'x;
288  put 'MPG_Highway'n '02'x; put 'Weight'n '02'x; put 'Wheelbase'n '02'x; put 'Length'n '01'x; run;
NOTE: Unable to connect to host EXIHYD-IM-021. Check validity of host name.
ERROR: Host name EXIHYD-IM-021 not found.
NOTE: The SAS System stopped processing this step because of errors.
NOTE: DATA statement used (Total process time):
      real time           0.04 seconds
      user cpu time       0.00 seconds
      system cpu time     0.01 seconds
      memory              553.75k
      OS Memory           8608.00k
      Timestamp           04/10/2020 09:49:02 AM
      Step Count                        21  Switch Count  0
      Page Faults                       0
      Page Reclaims                     30
      Page Swaps                        0
      Voluntary Context Switches        30
      Involuntary Context Switches      0
      Block Input Operations            0
      Block Output Operations           0

**Comment by tomweber-sas** [comment]
ok, so your client machine how name isn't found from the SAS server:

NOTE: Unable to connect to host EXIHYD-IM-021. Check validity of host name.
ERROR: Host name EXIHYD-IM-021 not found.

Try using the rtunnel option, as it just uses the existing SSH tunnel instead of having to do a separate socket connection.

**Comment by tomweber-sas** [comment]
Sorry, for sd2df, that uses tunnel, not rtunnel. Just specify both and you are covered for whatever method you use. most use tunnel, but some rtunnel. Just depends upon the direction of the connection.

**Comment by saumya123-alt** [comment]
So could you please help me to get rtunnel and tunnel info?

**Comment by tomweber-sas** [comment]
Yes, it's in the link I posted a couple posts ago: https://sassoftware.github.io/saspy/install.html#stdio-over-ssh

```
tunnel -
(Optional: integer) Certain methods of saspy require opening a local port and accepting a 
connection and data streamed from the SAS instance to saspy. If the remote SAS server would not 
be able to reach ports on your client machine due to a firewall or other security configuration, you 
may pass a port number to used for SAS to connect to on the remote side, which will be forwarded 
to the local side (using the -R ssh option) so that the remote SAS server can connect using this port.

rtunnel -
(Optional: integer) Certain methods of saspy require opening a remote port and allowing a 
connection to be made and data streamed to the SAS server from saspy; the Reverse of the tunnel 
case. In these cases, saspy needs to provide a port for the SAS server to use to accept a connection 
so data can be streamed to the SAs server. This is simply the reverse of the tunnel case, where SAS 
creates the socket and saspy connects. This will use the -L ssh option so that the saspy can connect 
to the remote SAS server on this port.

ssh      = {'saspath' : '/opt/sasinside/SASHome/SASFoundation/9.4/bin/sas_u8',
            'ssh'     : '/usr/bin/ssh',
            'host'    : 'remote.linux.host',
            'tunnel'  : 9911
            'rtunnel' : 9912
           }
```

So, you just pick some port(s) that's not in use and set them like above on your configuration definition. On real linux you can use the netstat command to see what ports are in use. I guess that works on a Mac?
netstat -tpan
is what I usually run.
The way this works is that ssh is already a socket connection from one machine to the other, using port 22 (by default you can set port= to use a different port than 22, but no need), and it allows you to use that existing connection to 'tunnel' other socket connections through, as if those other connections were local (localhost) connections.

So, when you use  'tunnel'  : 9911 (or whatever port), SAS thinks it's connecting to localhost:9911, not  'EXIHYD-IM-021:port_number'. Same for the reverse case where saspy tries to connect to SAS over a socket: 'rtunnel'  : 9912 means saspy connects to localhost:9912 not 'SAS.machine.whaterve.com:port_number'. 

So any issue with DNS, like you got, or even if there is a firewall between the two where they aren't allowed to connect to a random port, is midigated, as the connections are tunneled through the existing ssh socket connections. ssh handles distributing the different packets to the correct connections on either side.

That make sense? Just put some port numbers in there and give it a try. Here's a reference for port numbers, just FYI in case.

Tom

**Comment by tomweber-sas** [comment]
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by saumya123-alt** [comment]
First thing if I am putting like;
             'tunnel'  : 9911
            'rtunnel' : 9912
            }
Then its giving below error while  
sas = saspy.SASsession(cfgfile='/Desktop/sascfg.py'),
File "/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/folders/pr/w_hplw1j7bl0vj2yj97_dd5mv3j_2t/T/tmpg96m_c8j/sascfg003.py", line 103
    'rtunnel' : 9001

if I am giving a comma like 
            'tunnel'  : 9911,
            'rtunnel' : 9912
            } 
I am getting connected.
but while i am trying below code i am geting below error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/saspy/sasbase.py", line 1379, in sasdata2dataframe
    return self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/saspy/sasiostdio.py", line 1733, in sasdata2dataframe
    newsock[0].shutdown(socks.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected

**Comment by saumya123-alt** [comment]
*****
but while I am trying below code I am getting below error.

cars=sas.sasdata2dataframe(table='cars',libref='sashelp')

**Comment by tomweber-sas** [comment]
Sorry, yes, you have to have commas between those items; that's a typo on my part.
Can you show the SAS log from the last case that had the error?

**Comment by tomweber-sas** [comment]
@saumya123-alt are you up for a Web-Ex? I can set that up. That way I can see what's going on there and quickly figure out (usually) what's going on. This is on you Mac, right? I just don't have one to be able to try this out.

**Comment by saumya123-alt** [comment]
Ya sure, Please share your webex details.

**Comment by saumya123-alt** [comment]
@tomweber-sas Please share your webex details and inform me when to join

**Comment by tomweber-sas** [comment]
Sorry, I had finished for the day. Is there a time on Monday that works best for you? Happy to set it up for then.
Tom

**Comment by saumya123-alt** [comment]
@tomweber-sas  Ya sure, Just tell me Monday which time (PST/IST) with your WebEx details I will be there on time.

**Comment by tomweber-sas** [comment]
Does 10:00 PST work. That's 1:00 EST for me.

**Comment by saumya123-alt** [comment]
Okay, I will be on time.Please shares your WebEx details.

**Comment by saumya123-alt** [comment]
@tomweber-sas https://appleinc.webex.com/meet/saumyaranjan_biswal
this my Webex, either you can join.

**Comment by tomweber-sas** [comment]
Since you're ready, I'll join your now

**Comment by saumya123-alt** [comment]
okay,sure

**Comment by saumya123-alt** [comment]
thanks alot @tomweber-sas 
Its working fine now
import saspy
>>> 
>>> 
>>> sas = saspy.SASsession(cfgfile='/Users/saumya.rb/Desktop/sascfg.py')
Using SAS Config named: iomlinux
SAS Connection established. Subprocess id is 4252

>>> cars=sas.sasdata2dataframe(table='cars',libref='sashelp')
>>> 
>>> 
>>> cars.describe()
                MSRP        Invoice  EngineSize   Cylinders  Horsepower    MPG_City  MPG_Highway       Weight   Wheelbase      Length
count     428.000000     428.000000  428.000000  426.000000  428.000000  428.000000   428.000000   428.000000  428.000000  428.000000
mean    32774.855140   30014.700935    3.196729    5.807512  215.885514   20.060748    26.843458  3577.953271  108.154206  186.362150
std     19431.716674   17642.117750    1.108595    1.558443   71.836032    5.238218     5.741201   758.983215    8.311813   14.357991
min     10280.000000    9875.000000    1.300000    3.000000   73.000000   10.000000    12.000000  1850.000000   89.000000  143.000000
25%     20334.250000   18866.000000    2.375000    4.000000  165.000000   17.000000    24.000000  3104.000000  103.000000  178.000000
50%     27635.000000   25294.500000    3.000000    6.000000  210.000000   19.000000    26.000000  3474.500000  107.000000  187.000000
75%     39205.000000   35710.250000    3.900000    6.000000  255.000000   21.250000    29.000000  3977.750000  112.000000  194.000000
max    192465.000000  173560.000000    8.300000   12.000000  500.000000   60.000000    66.000000  7190.000000  144.000000  238.000000

**Comment by tomweber-sas** [comment]
Great! And you should have access to everything in that workspace server, same as you would from EG. (we switched to IOM access methods after seeing that it's a production environment being connected to).
Want to close this now? If you need anything reopen or create a new one for anything else!

Thanks!
Tom

**Comment by saumya123-alt** [comment]
Thanks again,
 Yes we can close this one now.
have a good day tom

**Comment by neocsbee** [comment]
@tomweber-sas I have the same error but my log looks clean. I am seeing that Windows defender firewall is stopping the dataframe from getting returned for Python to receive it. Both the machines are inside the firewall, so I am confused as to why this should happen.

Any ideas how to resolve this?

**Comment by tomweber-sas** [comment]
Hey @neocsbee can you open a new issue and put your information in it? I'll need to see your config, and the code you are submitting along with all of it's output, and see what error you're getting where.

Thanks!
Tom

**Comment by neocsbee** [comment]
Okay, will do.
