### ISSUE TITLE
STDIO SSH download error, upload works (OSX related?)

### ISSUE THREAD

**Issue by matthew-a-dunlap** [sassoftware/saspy#292]
Hello!

I've run into another issue using saspy in my Django project running currently on my Mac. I'm able to upload files and run sas code. But afterwards when I use saspy to download those files I run into a socket error.

```
Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/madunlap/Documents/GitHub/hsis-sas-merge/hsis_sas_merge/views.py", line 63, in index
    download_folder_from_sas_helper(folder_name, sas_conn)
  File "/Users/madunlap/Documents/GitHub/hsis-sas-merge/hsis_sas_merge/views.py", line 120, in download_folder_from_sas_helper
    sas_conn.download(settings.MEDIA_ROOT + "/testtemp", full_folder_path + "/" + entry, True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/saspy/sasbase.py", line 1116, in download
    log = self._io.download(localfile, remotefile, overwrite, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/saspy/sasiostdio.py", line 1364, in download
    newsock[0].shutdown(socks.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected
```

After the error, a file is created and there are some contents (variable headers) but the size is too short and there is no actual data. Looking at the sas7bdat file in a hex editor after the first kb or so its all zeroes.

I have `tunnel`/`rtunnel` set correctly, and confirmed the machine running SAS can be connected to from my machine on those ports. Am I missing something obvious or did I run into another OSX compatibility issue?

Thanks again for all the help thus far!

p.s. I'm not sure its relevant but I noticed that even though saspy upload is working for me, the log starts with a connection error

```
{'Success': True, 
'LOG': "channel 3: open failed: connect failed: Connection refused\r

58   
59            filename saspydir '/tmp/hsis_upload/data/nc06road.dta' recfm=F encoding=binary lrecl=1 permission='';
60            filename sock socket ':9911' server reconn=0 recfm=S encoding=binary lrecl=4096;
61   
62            data _null_; nb = -1;
63            infile sock nbyte=nb;
64            file saspydir;
65            input;
66            put _infile_;
67            run;
NOTE: TCP/IP XX Access Method Listen portno is 9911.
NOTE: The infile SOCK is:
      Local Host Name=localhost.localdomain,
      Local Host IP addr=::1,Listen Portno=9911,
      Client Hostname,Client IP addr,Lrecl=4096,
      Recfm=Stream

NOTE: The file SASPYDIR is:
      Filename=/tmp/hsis_upload/data/nc06road.dta,
      Owner Name=odum,Group Name=odum,
      Access Permission=-rw-rw-r--,
      Last Modified=15Apr2020:17:36:27

NOTE: TCP/IP XX Access Method has connected to client at IP addr 127.0.0.1 .
NOTE: 5863 records were read from the infile SOCK.
      The minimum record length was 2255.
      The maximum record length was 4096.
NOTE: 24013007 records were written to the file SASPYDIR.
NOTE: DATA statement used (Total process time):
      real time           19.88 seconds
      user cpu time       1.76 seconds
      system cpu time     0.71 seconds
      memory              323.34k
      OS Memory           11428.00k
      Timestamp           04/15/2020 05:36:47 PM
      Step Count                        5  Switch Count  737
      Page Faults                       0
      Page Reclaims                     119
      Page Swaps                        0
      Voluntary Context Switches        5152
      Involuntary Context Switches      2141
      Block Input Operations            0
      Block Output Operations           46928
      
68   
69            filename saspydir;
NOTE: Fileref SASPYDIR has been deassigned.
70            filename sock;
NOTE: Fileref SOCK has been deassigned.
71   
72   
73   
74   
75   "}
```

**Comment by tomweber-sas** [comment]
Hey Matthew, any chance of a Web-Ex (I can set that up) to get to the bottom of this? That would probably be a lot quicker then me asking you questions to post back to ...
The other user on the original MacOS issue saw something similar to this, but as it turned out, he was trying to connect to a workspace server in a production system and needed to be using the IOM access method instead of STSIO. so we switched to that, after getting the current version of saspy,  but didn't figure out what that error was. This is different but similar and it could very well be something specific to Mac, but I don't have enough info to know that either way yet.
I'm available anytime today, so if that works, just let me know when.
Tom

**Comment by tomweber-sas** [comment]
Also, just to address what you posted above, I think that error you see in the log for your successful upload is the tail end of whatever you ran before the upload, which I'm guessing is the download that failed. Showing the code you ran, along with the output is always helpful :)
The sock.shutdown line that got the exception happens in 2 different places in these methods. In an error case, and a non-error case. I've added code to catch this exception in the error case so that it continues and returns the log like it would have. This is at master, so if you grab master, and run this, it may provide some insight.

**Comment by matthew-a-dunlap** [comment]
@tomweber-sas Thanks for the quick reply! I have a deadline coming up for this so I ended up working around this issue. I have to get back to it, let me touch base when that is over. 

That being said, I did try the code off of master and it looks to blow up the "same" as before:
```
downloading from /sasdata/output/doi1033563FK2ABQF9V/nc15veh.sas7bdat
downloading to /Users/madunlap/Documents/hsis_django_downloads/testtemp/nc15veh.sas7bdat
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/madunlap/virt/hsis-sas-merge/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/madunlap/virt/hsis-sas-merge/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/madunlap/virt/hsis-sas-merge/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/madunlap/Documents/GitHub/hsis-sas-merge/hsis_sas_merge/views.py", line 64, in index
    download_folder_from_sas_helper(folder_name, sas_conn)
  File "/Users/madunlap/Documents/GitHub/hsis-sas-merge/hsis_sas_merge/views.py", line 122, in download_folder_from_sas_helper
    sas_conn.download(settings.MEDIA_ROOT + "/testtemp/"+ entry, full_folder_path + "/" + entry, True)
  File "/Users/madunlap/virt/hsis-sas-merge/lib/python3.7/site-packages/saspy/sasbase.py", line 1116, in download
    log = self._io.download(localfile, remotefile, overwrite, **kwargs)
  File "/Users/madunlap/virt/hsis-sas-merge/lib/python3.7/site-packages/saspy/sasiostdio.py", line 1376, in download
    newsock[0].shutdown(socks.SHUT_RDWR)
```

Its hard for me to share the full code, the download line I'm using is:
```
sas_conn.download(settings.MEDIA_ROOT + "/testtemp/"+ entry, full_folder_path + "/" + entry, True)
```
I've been using the same saspy session for all my commands, not closing it until things are done.

**Comment by tomweber-sas** [comment]
Sure, just let me know when you have time. If that's the code at master, then that's the success path where I shut down and close the sockets. So, that make no sense whatsoever. UNLESS, the python socket code for MacOS, doesn't work like it does on real linux, which, given they are completely missing numbers of lower level methods, seem all too likely. I can't make that line of code (in either the error or success case) ever cause an exception. I can fail to connect, and take other exceptions, and the code behaves as expected. I was hoping it was the error case I added code to, so we could see why. 
Let me know when you have time to look at this. We can try a few things to see what's going on.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
This seemed to maybe be another issue w/ MacOS python not really matching up with Linux python, but we never get further. 

Closing up old, idle issues. if you still need something on this, you can reopen it. If you need anything else, feel free to open a new issue.
Thanks!
Tom
