### ISSUE TITLE
Where clause not working

### ISSUE THREAD

**Issue by amckiern** [sassoftware/saspy#30]
Hi,

I am trying to use _sasdata2dataframe_ to query a sas table for some data. 

I have added a dictionary with a 'where' clause but no matter what filter I put in, I still seem to get all 5000 observations back in the dataframe. For instance:

`results = sas.sasdata2dataframe(table='wip_tbl', libref='fabvw_cl', dsopts={'where':'waferqty > 24'})`

In this case the table is in the library "_fabvw_cl_", the table is called "_wip_tbl_" and I am looking for all rows where the "wafer quantity" (_waferqty_) is greater than 24. 

I have also tried queries on text columns and datetime columns and they are not working for me either. 

Has anyone else had similar problems?

Thanks.

**Comment by tomweber-sas** [comment]
I will take a look at that. I can believe I might not be applying the where in the data frame conversion code. My bad if so. Do you know which access method you're using?

**Comment by tomweber-sas** [comment]
I see you're using the IOM access method because this is already supported in STDIO. Don't know how I didn't get that into IOM too, but I didn't, although I will. I'll let you know when I have this done and pushed out.  Sorry bout that.

**Comment by tomweber-sas** [comment]
Ok, pushed support for this to master for IOM access method. Let me know if this solves your issue or if you still have any other problems. 
Tom

**Comment by amckiern** [comment]
It's not beyond the bounds of belief that I could be doing something stupid!

I am using IOM, specifically "winiomlinux" to connect from python on windows to a linux server running sas.

**Comment by amckiern** [comment]
Thanks a lot, that seemed to work.

I have a related question on the "where" clause. I have tried this code:

`r = s.sd2df('moves_tbl', 'fabvw_cl', {'where':'trackouttime>="04may2017 00:00"dt'})`

Hpwever I get the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AMcKiern\AppData\Local\Continuum\Anaconda2\envs\py3\lib\site-packages\saspy\sasbase.py", line 676, in sd2df
    return self.sasdata2dataframe(table, libref, dsopts, **kwargs)
  File "C:\Users\AMcKiern\AppData\Local\Continuum\Anaconda2\envs\py3\lib\site-packages\saspy\sasbase.py", line 715, in sasdata2dataframe
    return self._io.sasdata2dataframe(table, libref, dsopts, **kwargs)
  File "C:\Users\AMcKiern\AppData\Local\Continuum\Anaconda2\envs\py3\lib\site-packages\saspy\sasioiom.py", line 1121, in sasdata2dataframe
    if ll['LST'][0] == "\ufeff":
IndexError: string index out of range

The _trackouttime_ column is a datetime column in the _moves_tbl_. Have I done something wrong with the datetime I supplied? It seemed to work fine on another table I tried.

Thanks.

**Comment by amckiern** [comment]
Related to the previous comment, this is what the data step looks like from the sas log:

718        data _null_; set fabvw_cl.moves_tbl(where=(trackouttime>="04may2017 00:00"dt) );
719         file _tomods1; put 'LOTID'n '09'x 'AREA'n '09'x 'LOCATION'n '09'x 'PARTID'n '09'x 'PARTNAME'n '09'x 'STAGE'n '09'x
719      ! 'SORTINGORDER'n '09'x 'CURPRCDID'n '09'x 'RECPID'n '09'x 'LOTTYPE'n '09'x 'STATE'n '09'x 'EQPTYPE'n '09'x 'EQPID'n '09'x
719      ! 'ENGINEER'n '09'x 'CURMAINQTY'n best32. '09'x 'CURSUBQTY'n best32. '09'x 'MAINMATTYPE'n '09'x 'SUBMATTYPE'n '09'x
719      ! 'WAFERQTY'n best32. '09'x 'DIEQTY'n best32. '09'x 'PRIORITY'n '09'x 'FABPROCESS'n '09'x 'SHORTFABPROCESS'n '09'x
719      ! 'GENERIC'n '09'x 'STRATEGY'n '09'x 'WAFERSIZE'n '09'x 'TRACKINTIME'n best32. '09'x 'TRACKOUTTIME'n best32. '09'x
719      ! 'TRACKINUSER'n '09'x 'TRACKOUTUSER'n '09'x 'QUEUETIME'n best32. '09'x 'NEXTPRODAREA'n '09'x 'NEXTLOCATION'n '09'x
719      ! 'NEXTSTAGE'n '09'x 'NEXTSTAGESORTORDER'n '09'x 'WORKCENTRE'n '09'x 'DUMMYTRACKOUT'n '09'x 'limerickFabProcess'n '09'x
719      ! 'layerTally'n '09'x 'IPDPROCESS'n ;
720         run;


Sorry about the formatting...

**Comment by jld23** [comment]
@amckiern
You can check the SAS code to elminate that part of the equation
something like this should be equivalent:
```
 t = s.submit("""
data foo;
    set fabvw_cl.moves_tbl;
    where trackouttime>="04may2017 00:00"dt;
run;
""")
print(t['LOG'])
```

**Comment by amckiern** [comment]
@jld23 
Thanks for that. It turns out there was no recent data in that table.

I thought it would just return an empty dataframe if no data is found, rather than raising an exception.

I should say that I think it's great that SAS are making the platform available to python!

**Comment by tomweber-sas** [comment]
@amckiern I believe that your where clause is working ok. I think it's just resulting in zero rows to return. I will add a check in the code for this, so you get something better than a traceback. I've verified this with the following program. Just creating some datetime values and query them as you were. They work fine unless my constraint results in no rows then I get that same traceback. 

```
import saspy
sas = saspy.SASsession()
ll = sas.submit('data a;do x=1 to 100;format x datetime.;output;end;run;')
print(ll['LOG'])
d1 = sas.sasdata('a')
d1.head()
d1.dsopts={'where': 'x > "1960-01-01 00:00:03"dt'}
d1.head()
df = d1.to_df()
df.head()
df2 = sas.sasdata2dataframe('a', dsopts={'where': 'x > "1960-01-01 00:00:03"dt'})
df2.head()
df2 = sas.sasdata2dataframe('a', dsopts={'where': 'x < "1956-01-01 00:00:03"dt'})
```

**Comment by tomweber-sas** [comment]
Ah, sorry, just saw you got to the same conclusion. Yes I will clean it up so you don't get a traceback. It should be giving you a clean, although empty, data frame back and a note that there were no rows returned.

**Comment by amckiern** [comment]
Thanks @tomweber-sas! Much appreciated.

**Comment by tomweber-sas** [comment]
Ok, cleaned up and pushed to master. It does return an empty data frame. The STDIO access method was already doing this, so it was ok. I just needed to clean up that check for the utf8 bom in the IOM case, which was not in STDIO. Now they both come back with a clean data frame.

Glad you're liking this, and keep letting us know if you see any other glitches. We'll clean them up! Thanks for helping!
