### ISSUE TITLE
issue with creating libname using saspy in python 3.8 using a centos7 machine

### ISSUE THREAD

**Issue by snehak0991** [sassoftware/saspy#301]
Hi,

My goal is to save a pandas dataframe as a sas7bdat file in a target directory using saspy. I am trying to create a libname with saspy.saslib function but I get the below error repeatedly. My saspy connection seems to be working. I am not sure what is the issue here.

error: NOTE: Library MYLIB does not exist.

code:
sas = saspy.SASsession(cfgname='iomwin', omruser='username',omrpw='mypassword)
sas.saslib('mylib',path='my linux path')

the linux directory path is like: /home/username/projectname/Data

Please help!

**Comment by tomweber-sas** [comment]
Hey, well you can certainly do that. So what is the output from running that code? Can you run it and show the output? I believe that the saslib method displays the log. You can submit print(sas.saslog()) to see the whole log too. Also, please submit your SASsession object (sas) to display info for me too please.

**Comment by snehak0991** [comment]
Hi My code is as below:

import saspy
import pandas as pd
sas = saspy.SASsession(cfgname='iomwin', omruser='myusername',omrpw='*******')
	sas.saslib('mylib',path='/home/skrishnan/CommercialDataPull/GPS/src/Data')
	print(sas.saslog())

the saslog is as below:
SAS Connection established. Subprocess id is 24548
5                                                          The SAS System                              16:08 Thursday, June 25, 2020

24
25         libname mylib    '/home/skrishnan/CommercialDataPull/GPS/src/Data'  ;
NOTE: Library MYLIB does not exist.
26
27
28
6                                                          The SAS System                              16:08 Thursday, June 25, 2020

29
1                                                          The SAS System                              16:08 Thursday, June 25, 2020

NOTE: Copyright (c) 2016 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software 9.4 (TS1M5)
      Licensed to **********, Site *******.
NOTE: This session is executing on the X64_SR12R2  platform.



NOTE: Updated analytical products:

      SAS/STAT 14.3
      SAS/IML 14.3
      SAS/QC 14.3

NOTE: Additional host information:

 X64_SR12R2 WIN 6.3.9600  Server

NOTE: SAS Initialization used (Total process time):
      real time           0.01 seconds
      cpu time            0.01 seconds

NOTE: The autoexec file, C:\SAS\Config\Lev1\SASApp\WorkspaceServer\autoexec.sas, was executed at server initialization.
1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any validmemname=extend pagesize=max nosyntaxcheck; ods graphics on;
3
4          ;*';*";*/;
5
2                                                          The SAS System                              16:08 Thursday, June 25, 2020

6
7          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
8
3                                                          The SAS System                              16:08 Thursday, June 25, 2020

9          ;*';*";*/;
10         data _null_; length x $ 4096;
11                        x = resolve('%sysfunc(pathname(work))');  put 'WORKPATH=' x 'WORKPATHEND=';
12                        x = resolve('&SYSENCODING');              put 'ENCODING=' x 'ENCODINGEND=';
13                        x = resolve('&SYSVLONG4');                put 'SYSVLONG=' x 'SYSVLONGEND=';
14                        x = resolve('&SYSJOBID');                 put 'SYSJOBID=' x 'SYSJOBIDEND=';
15                        x = resolve('&SYSSCP');                     put 'SYSSCP=' x 'SYSSCPEND=';
16                     run;

WORKPATH=M:\WORKSPACES94\skrishnan\SAS Temporary Files\_TD1896_PAPP84SAS01_\Prc2 WORKPATHEND=
ENCODING=wlatin1 ENCODINGEND=
SYSVLONG=9.04.01M5P09132017 SYSVLONGEND=
SYSJOBID=1896 SYSJOBIDEND=
SYSSCP=WIN SYSSCPEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds


17
18
19         ;*';*";*/;
20
4                                                          The SAS System                              16:08 Thursday, June 25, 2020

21
22         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
23
5                                                          The SAS System                              16:08 Thursday, June 25, 2020

24         ;*';*";*/;
25         libname mylib    '/home/skrishnan/CommercialDataPull/GPS/src/Data'  ;
NOTE: Library MYLIB does not exist.
26
27         ;*';*";*/;
28
6                                                          The SAS System                              16:08 Thursday, June 25, 2020

29
30         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
31

SAS Connection terminated. Subprocess id was 24548

**Comment by tomweber-sas** [comment]
Ok. So that directory doesn't exist, or perhaps you don't have permission to access it?
```
25 libname mylib '/home/skrishnan/CommercialDataPull/GPS/src/Data' ;
NOTE: Library MYLIB does not exist.
26
```
That's the error from SAS when that libname statement is submtted.
If you were expecting to have it created for you, I believe there's an option you have to set when running on Windows or Linux (MVS you just specified disp=new on the libname). I googled it and apparently you have set
```
options dlcreatedir;
```
Before you submit the libname statement. So, you can do that with a submit statement, it you could add that to the autoexec key in your configuration definition so it's submitted for you every time you make s connection, so you don't have to manually submit it.

Try that and see if it fixes it, if that's what the problem is. I think the dir just doesn't exist.

**Comment by snehak0991** [comment]
Hi,

The directory "/home/skrishnan/CommercialDataPull/GPS/src/Data" exists and I have access to create files in the folder as well. I have tried that and it works.

**Comment by tomweber-sas** [comment]
Wait. In you log the paths are Windows paths. Where is this running? Can you submit your sas object so I can see that output? If your running Windows SAS, unix paths don't work.

**Comment by tomweber-sas** [comment]
Are you running python on a Linux client, connecting to a remote window machine where SAS is running, but want the SAS data set to end up back on your client Linux box?
Sorry, I'm on my phone trying to help, and maybe I've missed some of the info.
Tom

**Comment by snehak0991** [comment]
I am running the python program on a linux machine, but my guess is, the sas server being connected is on a windows machine. I and trying to get more information this. I will post as soon as I get more information. 

Thank you so much for looking into it so quickly!

**Comment by snehak0991** [comment]
so I just got confirmation that the sas server is a windows vm and I am trying to connect to it from my linux machine using iomwin protocol

**Comment by tomweber-sas** [comment]
Yes, looking at the log, SAS is running on some windows machine. So you won't get a libname statement to assign to a directory on your Linux client, unless that dir is mounted to window, which I doubt. So, if you want a SAS data set, from a pandas df, then you will want to just create the data set in the work library, as that's the easiest, then download it to your client.
```
sas.df2sd(df, 'sd')
sas.download('/home/.../liux/path', sas.workpth+'sd')
```
Hope i tyoed that all ok. So, create the dataset from the data frame using df2sd, them download it to your client in that directory.
Make sense?

**Comment by snehak0991** [comment]
Thanks got it. I will try that!

**Comment by tomweber-sas** [comment]
Yeah, I didn't type it all the way right. I'll blame phone 😎
So data frame named df. Data set in work: work.sd.
Download takes local file path, remote file path.
So that should do it.

**Comment by tomweber-sas** [comment]
Check the updates, I didn't get it right the first time
sas.df2sd(df, 'sd')
sas.download('/home/.../liux/path', sas.workpath+'sd.sas7bdat') #need the full file path here

**Comment by tomweber-sas** [comment]
ok, I logged in so I could give you a decent example:

```
>>> sas = saspy.SASsession(cfgname='iomjwin')
SAS Connection established. Subprocess id is 935

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to cp1252 based upon the SAS session encoding value of wlatin1.

>>> sas
Access Method         = IOM
SAS Config name       = iomjwin
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD17296_d10a626_\Prc2\
SAS Version           = 9.04.01M4P11142016
SASPy Version         = 3.3.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = cp1252
SAS process Pid value = 17296


>>> df = sas.sd2df('cars','sashelp')
>>> df.head()
    Make           Model   Type Origin DriveTrain   MSRP  Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  Wheelbase  Length
0  Acura             MDX    SUV   Asia        All  36945    33337         3.5        6.0         265        17           23    4451        106     189
1  Acura  RSX Type S 2dr  Sedan   Asia      Front  23820    21761         2.0        4.0         200        24           31    2778        101     172
2  Acura         TSX 4dr  Sedan   Asia      Front  26990    24647         2.4        4.0         200        22           29    3230        105     183
3  Acura          TL 4dr  Sedan   Asia      Front  33195    30299         3.2        6.0         270        20           28    3575        108     186
4  Acura      3.5 RL 4dr  Sedan   Asia      Front  43755    39014         3.5        6.0         225        18           24    3880        115     197
>>> type(df)
<class 'pandas.core.frame.DataFrame'>

# crearte work.sd from the dataframe named df
>>> sd1 = sas.df2sd(df, 'sd')
>>> sas.list_tables()
[('SASDATA2DATAFRAME', 'VIEW'), ('SD', 'DATA')]

# look at the local filesystem, the dataset doesn't exist yet
>>> import os
>>> os.lstat('./sd.sas7bdat')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: './sd.sas7bdat'

# now download the data set to the current directory
>>> res = sas.download('.', sas.workpath+'sd.sas7bdat')

# and now you see it's there
>>> os.lstat('./sd.sas7bdat')
os.stat_result(st_mode=33188, st_ino=7210772, st_dev=64768, st_nlink=1, st_uid=894, st_gid=100, st_size=196608, st_atime=1593132213, st_mtime=1593132235, st_ctime=1593132235)


#fwiw, look at it on the server to compare
>>> sas.file_info(sas.workpath+'sd.sas7bdat')
{'File Size (bytes)': '196608', 'RECFM': 'V', 'Filename': 'C:\\Users\\sastpw\\AppData\\Local\\Temp\\SAS Temporary Files\\_TD17296_d10a626_\\Prc2\\sd.sas7bdat', 'LRECL': '32767', 'Create Time': '25Jun2020:20:41:24', 'Last Modified': '25Jun2020:20:41:24'}
>>>
```

Hope that helps,
Tom

**Comment by snehak0991** [comment]
Hi Tom,

Thanks for this example. I tried the sas.download method and was not able to download the sas dataset in the working directory or specific directory. please see below my code and the log:

df = pd.DataFrame.from_dict({'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']})
sas = saspy.SASsession(cfgname='iomwin', omruser='myusername',omrpw='*****')
sd = sas.df2sd(df)
sas.download('.',sas.workpath+'sd.sas7bdat')
print(sas.lastlog())
os.lstat('./sd.sas7bdat')

Log:
15                                                         The SAS System                              17:53 Thursday, June 25, 2020

82         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
82       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
83
84         filename _spfinfo clear;
NOTE: Fileref _SPFINFO has been deassigned.
85
86
87         ods html5 (id=saspy_internal) close;ods listing;
88
16                                                         The SAS System                              17:53 Thursday, June 25, 2020

89
Traceback (most recent call last):
  File "BDM_Commercial_DataPull_GPS.py", line 627, in <module>
    main()
  File "BDM_Commercial_DataPull_GPS.py", line 361, in main
    os.lstat('./sd.sas7bdat')
FileNotFoundError: [Errno 2] No such file or directory: './sd.sas7bdat'

**Comment by tomweber-sas** [comment]
Hey, I don't see any output from any of those commands. download returns a dictionary w/ whether it was successful or not and the log; what did that have in it? And I can't see anything that shows if the df2sd worked; can you show if that was successful?. I don't see any of the saslog that shows any of those steps either. So I have no information from this to know what happened. 
Would you like to jump on a Web-Ex and I can walk you through how to do this and see what is happening? I can set that up.

Thanks,
Tom

**Comment by snehak0991** [comment]
Hi Tom,

I had used the lastlog command yesterday. Sorry about that. Please see below code and the complete log:
Code:
df = pd.DataFrame.from_dict({'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']})
	sas = saspy.SASsession(cfgname='iomwin', omruser='myusername',omrpw='*******')
	sd = sas.df2sd(df)
	sas.download('.',sas.workpath+'sd.sas7bdat')
	print(sas.saslog())
	os.lstat('./sd.sas7bdat')
SAS Log:
SAS Connection established. Subprocess id is 22445
1                                                          The SAS System                                09:41 Friday, June 26, 2020

NOTE: Copyright (c) 2016 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software 9.4 (TS1M5)
      Licensed to *********, Site ****.
NOTE: This session is executing on the X64_SR12R2  platform.



NOTE: Updated analytical products:

      SAS/STAT 14.3
      SAS/IML 14.3
      SAS/QC 14.3

NOTE: Additional host information:

 X64_SR12R2 WIN 6.3.9600  Server

NOTE: SAS Initialization used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

NOTE: The autoexec file, C:\SAS\Config\Lev1\SASApp\WorkspaceServer\autoexec.sas, was executed at server initialization.
1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any validmemname=extend pagesize=max nosyntaxcheck; ods graphics on;
3
4          ;*';*";*/;
5
2                                                          The SAS System                                09:41 Friday, June 26, 2020

6
7          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
8
3                                                          The SAS System                                09:41 Friday, June 26, 2020

9          ;*';*";*/;
10         data _null_; length x $ 4096;
11                        x = resolve('%sysfunc(pathname(work))');  put 'WORKPATH=' x 'WORKPATHEND=';
12                        x = resolve('&SYSENCODING');              put 'ENCODING=' x 'ENCODINGEND=';
13                        x = resolve('&SYSVLONG4');                put 'SYSVLONG=' x 'SYSVLONGEND=';
14                        x = resolve('&SYSJOBID');                 put 'SYSJOBID=' x 'SYSJOBIDEND=';
15                        x = resolve('&SYSSCP');                     put 'SYSSCP=' x 'SYSSCPEND=';
16                     run;

WORKPATH=M:\WORKSPACES94\myusername\SAS Temporary Files\_TD696_PAPP84SAS01_\Prc2 WORKPATHEND=
ENCODING=wlatin1 ENCODINGEND=
SYSVLONG=9.04.01M5P09132017 SYSVLONGEND=
SYSJOBID=696 SYSJOBIDEND=
SYSSCP=WIN SYSSCPEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


17
18
19         ;*';*";*/;
20
4                                                          The SAS System                                09:41 Friday, June 26, 2020

21
22         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
23
5                                                          The SAS System                                09:41 Friday, June 26, 2020

24         data '_df'n;
25         length  'col_1'n 8 'col_2'n $1;
26         infile datalines delimiter='03'x  DSD STOPOVER;
27         input @;
28         if _infile_ = '' then delete;
29         input 'col_1'n 'col_2'n ;
30         ;
31         datalines4;
6                                                          The SAS System                                09:41 Friday, June 26, 2020

NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds

NOTE: The data set WORK._DF has 4 observations and 2 variables.

37         ;;;;
38
7                                                          The SAS System                                09:41 Friday, June 26, 2020

39         ;*';*";*/;
40         run;
41
42         ;*';*";*/;
43
8                                                          The SAS System                                09:41 Friday, June 26, 2020

44
45         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
46
9                                                          The SAS System                                09:41 Friday, June 26, 2020

47         ;*';*";*/;
48         data _null_; e = exist("'_df'n");
49         v = exist("'_df'n", 'VIEW');
50          if e or v then e = 1;
51         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


52
53
54         ;*';*";*/;
55
10                                                         The SAS System                                09:41 Friday, June 26, 2020

56
57         %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
58
11                                                         The SAS System                                09:41 Friday, June 26, 2020

59         ;*';*";*/;
60         data _null_; e = exist("user.'_df'n");
61         v = exist("user.'_df'n", 'VIEW');
62          if e or v then e = 1;
63         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 0
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


64
65
66         ;*';*";*/;
67
12                                                         The SAS System                                09:41 Friday, June 26, 2020

68
69         %put E3969440A681A2408885998500000005;
E3969440A681A2408885998500000005
70
13                                                         The SAS System                                09:41 Friday, June 26, 2020

71         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
71       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
72         ;*';*";*/;
73         filename _spfinfo 'M:\WORKSPACES94\skrishnan\SAS Temporary Files\_TD696_PAPP84SAS01_\Prc2\sd.sas7bdat';
74         %put FILEREF_EXISTS=%sysfunc(fexist(_spfinfo)) FILE_EXTEND=;
FILEREF_EXISTS=0 FILE_EXTEND=
75
76         ;*';*";*/;
77         ods html5 (id=saspy_internal) close;ods listing;
78
14                                                         The SAS System                                09:41 Friday, June 26, 2020

79
80         %put E3969440A681A2408885998500000007;
E3969440A681A2408885998500000007
81
15                                                         The SAS System                                09:41 Friday, June 26, 2020

82         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
82       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
83         ;*';*";*/;
84         filename _spfinfo clear;
NOTE: Fileref _SPFINFO has been deassigned.
85
86         ;*';*";*/;
87         ods html5 (id=saspy_internal) close;ods listing;
88
16                                                         The SAS System                                09:41 Friday, June 26, 2020

89
90         %put E3969440A681A2408885998500000008;
E3969440A681A2408885998500000008
91

**Comment by tomweber-sas** [comment]
Oh, I didn't see that before. You didn't provide a table name for the dataset on the df2sd method. So you didn't create work.sd. that's why the download didn't succeed.. I still don't see any output from that code. It would have told you so. Either provide a table name on df2sd, and specify that name in the download, or specify the default name that was used which was _df. So, work._df.

**Comment by snehak0991** [comment]
Hi Tom,

Did you mean like this:

sd = sas.df2sd(df,table='df')
	sas.download('.',sas.workpath+'sd.sas7bdat','work.df')
I didn't quite get on how to mention the table name in the download statement.

**Comment by tomweber-sas** [comment]
great!
Yes, in SAS a data set is referred to as libname.membername (libname.tablename; whichever). While on the filesystem it's the pytsical name of the file in the directory. So, 'work.sd' in SAS is 'M:\WORKSPACES94\myusername\SAS Temporary Files_TD696_PAPP84SAS01_\Prc2\sd.sas7bdat', in this case above, on the filesystem.
If that addressed this issue, we can close it. You can open another issue for anything else you may need.

Thanks!
Tom

**Comment by snehak0991** [comment]
Hi Tom,

Thanks for the explanation. I just had one final follow up question. I am able to save the sas7bdat file in the current working directory but when I try to mention another specific directory the download doesn't happen.

sd = sas.df2sd(df,table='df')
sas.download('/home/skrishnan/CommercialDataPull/GPS/src/Data',sas.workpath+'work.df.sas7bdat')

log:
SAS Connection established. Subprocess id is 10755
1                                                          The SAS System                                11:29 Friday, June 26, 2020

NOTE: Copyright (c) 2016 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software 9.4 (TS1M5)
      Licensed to ********, Site *****.
NOTE: This session is executing on the X64_SR12R2  platform.



NOTE: Updated analytical products:

      SAS/STAT 14.3
      SAS/IML 14.3
      SAS/QC 14.3

NOTE: Additional host information:

 X64_SR12R2 WIN 6.3.9600  Server

NOTE: SAS Initialization used (Total process time):
      real time           0.01 seconds
      cpu time            0.01 seconds

NOTE: The autoexec file, C:\SAS\Config\Lev1\SASApp\WorkspaceServer\autoexec.sas, was executed at server initialization.
1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any validmemname=extend pagesize=max nosyntaxcheck; ods graphics on;
3
4          ;*';*";*/;
5
2                                                          The SAS System                                11:29 Friday, June 26, 2020

6
7          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
8
3                                                          The SAS System                                11:29 Friday, June 26, 2020

9          ;*';*";*/;
10         data _null_; length x $ 4096;
11                        x = resolve('%sysfunc(pathname(work))');  put 'WORKPATH=' x 'WORKPATHEND=';
12                        x = resolve('&SYSENCODING');              put 'ENCODING=' x 'ENCODINGEND=';
13                        x = resolve('&SYSVLONG4');                put 'SYSVLONG=' x 'SYSVLONGEND=';
14                        x = resolve('&SYSJOBID');                 put 'SYSJOBID=' x 'SYSJOBIDEND=';
15                        x = resolve('&SYSSCP');                     put 'SYSSCP=' x 'SYSSCPEND=';
16                     run;

WORKPATH=M:\WORKSPACES94\skrishnan\SAS Temporary Files\_TD16656_PAPP84SAS01_\Prc2 WORKPATHEND=
ENCODING=wlatin1 ENCODINGEND=
SYSVLONG=9.04.01M5P09132017 SYSVLONGEND=
SYSJOBID=16656 SYSJOBIDEND=
SYSSCP=WIN SYSSCPEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds


17
18
19         ;*';*";*/;
20
4                                                          The SAS System                                11:29 Friday, June 26, 2020

21
22         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
23
5                                                          The SAS System                                11:29 Friday, June 26, 2020

24         data 'df'n;
25         length  'col_1'n 8 'col_2'n $1;
26         infile datalines delimiter='03'x  DSD STOPOVER;
27         input @;
28         if _infile_ = '' then delete;
29         input 'col_1'n 'col_2'n ;
30         ;
31         datalines4;
6                                                          The SAS System                                11:29 Friday, June 26, 2020

NOTE: DATA statement used (Total process time):
      real time           0.01 seconds
      cpu time            0.00 seconds

NOTE: The data set WORK.DF has 4 observations and 2 variables.

37         ;;;;
38
7                                                          The SAS System                                11:29 Friday, June 26, 2020

39         ;*';*";*/;
40         run;
41
42         ;*';*";*/;
43
8                                                          The SAS System                                11:29 Friday, June 26, 2020

44
45         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
46
9                                                          The SAS System                                11:29 Friday, June 26, 2020

47         ;*';*";*/;
48         data _null_; e = exist("'df'n");
49         v = exist("'df'n", 'VIEW');
50          if e or v then e = 1;
51         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


52
53
54         ;*';*";*/;
55
10                                                         The SAS System                                11:29 Friday, June 26, 2020

56
57         %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
58
11                                                         The SAS System                                11:29 Friday, June 26, 2020

59         ;*';*";*/;
60         data _null_; e = exist("user.'df'n");
61         v = exist("user.'df'n", 'VIEW');
62          if e or v then e = 1;
63         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 0
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


64
65
66         ;*';*";*/;
67
12                                                         The SAS System                                11:29 Friday, June 26, 2020

68
69         %put E3969440A681A2408885998500000005;
E3969440A681A2408885998500000005
70
13                                                         The SAS System                                11:29 Friday, June 26, 2020

71         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
71       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
72         ;*';*";*/;
73         filename _spfinfo 'M:\WORKSPACES94\skrishnan\SAS Temporary Files\_TD16656_PAPP84SAS01_\Prc2\work.df.sas7bdat';
74         %put FILEREF_EXISTS=%sysfunc(fexist(_spfinfo)) FILE_EXTEND=;
FILEREF_EXISTS=0 FILE_EXTEND=
75
76         ;*';*";*/;
77         ods html5 (id=saspy_internal) close;ods listing;
78
14                                                         The SAS System                                11:29 Friday, June 26, 2020

79
80         %put E3969440A681A2408885998500000007;
E3969440A681A2408885998500000007
81
15                                                         The SAS System                                11:29 Friday, June 26, 2020

82         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
82       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
83         ;*';*";*/;
84         filename _spfinfo clear;
NOTE: Fileref _SPFINFO has been deassigned.
85
86         ;*';*";*/;
87         ods html5 (id=saspy_internal) close;ods listing;
88
16                                                         The SAS System                                11:29 Friday, June 26, 2020

89
90         %put E3969440A681A2408885998500000008;
E3969440A681A2408885998500000008
91

SAS Connection terminated. Subprocess id was 10755

End Log

Am I doing something wrong in specifying the directory path where the dataset should be saved?

Thanks in advance!

**Comment by tomweber-sas** [comment]
yes, you can specify any local directory, that exists and you can write to. But in the log I see that the file didn't exist:
```
73 filename spfinfo 'M:\WORKSPACES94\skrishnan\SAS Temporary Files_TD16656_PAPP84SAS01\Prc2\work.df.sas7bdat';
74 %put FILEREF_EXISTS=%sysfunc(fexist(_spfinfo)) FILE_EXTEND=;
FILEREF_EXISTS=0 FILE_EXTEND=
```
There's no other info available, since there's nothing else submitted to see anything about what's going on. I have no guesses why you got this. Nothing here to let me see what's going on. 
Can you do a call, so I can walk you through how to look at this?

**Comment by tomweber-sas** [comment]
I've still never see the results of submitting your SASsession object, like below (so I could get that info). So, what version of saspy are you running?

```
>>> sas
Access Method         = IOM
SAS Config name       = iomjwin
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD59888_d10a626_\Prc2\
SAS Version           = 9.04.01M4P11142016
SASPy Version         = 3.3.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = cp1252
SAS process Pid value = 59888
```

**Comment by snehak0991** [comment]
Hi Tom,

Yes we can do a quick call. What time would you prefer?

Thanks!

**Comment by tomweber-sas** [comment]
can you join this now? https://sas.webex.com/join/Tom.Webersas.com

**Comment by snehak0991** [comment]
Access Method         = IOM
SAS Config name       = iomwin
SAS Config file       = /home/skrishnan/.virtualenvs/vbase3/lib/python3.8/site-packages/saspy/sascfg_personal.py
WORK Path             = M:\WORKSPACES94\skrishnan\SAS Temporary Files\_TD17652_PAPP84SAS01_\Prc2\
SAS Version           = 9.04.01M5P09132017
SASPy Version         = 3.3.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = windows-1252
SAS process Pid value = 17652

My SAS object

**Comment by tomweber-sas** [comment]
Ah, cool 3.3.7, so that's good then

**Comment by tomweber-sas** [comment]
looked at it on web-ex. Was just a typo:
73 filename spfinfo 'M:\WORKSPACES94\skrishnan\SAS Temporary Files_TD16656_PAPP84SAS01\Prc2\work.df.sas7bdat';
should be
73 filename spfinfo 'M:\WORKSPACES94\skrishnan\SAS Temporary Files_TD16656_PAPP84SAS01\Prc2\df.sas7bdat'

then it worked.;

**Comment by snehak0991** [comment]
Thanks for all the help Tom! Closing the issue.
