### ISSUE TITLE
SAS | SAS DATA SET | SASPY I DATA TYPE of the COLUMN

### ISSUE THREAD

**Issue by Narendra5005** [sassoftware/saspy#303]
hello - what's the best way to validate the data types of the sas data set's columns?

**Comment by tomweber-sas** [comment]
Not sure on'validate', but you can see what the columns are using either the columnInfo() or contents() methods of the SASdata object.

Can you describe what you mean by 'validate' them?

Thanks,
Tom

**Comment by Narendra5005** [comment]
any quick example with a proc sql query or any other way pls?

Say I have a table SALARY with the COLUMN as EMPLOYEE ... 

I tried few ways but unable to fetch the exact data type

**Comment by tomweber-sas** [comment]
Are you asking how to programmatically check the type (Num or Char) of a given variable (column) of a SAS data set?

**Comment by Narendra5005** [comment]
yes Tom

**Comment by tomweber-sas** [comment]
ok, so there's more than one way, but how about this, for starters. the columnInfo() method returns a concise set of info for the columns,  and in a pandas dataframe bydefault. So, to check a single column you could code the following; I'll use the cars dataset for a working example.
```
>>> cars = sas.sasdata('cars','sashelp')
>>> cars
Libref  = sashelp
Table   = cars
Dsopts  = {}
Results = Pandas

# this will returna dataframe you can query, if you know how to mess with the dataframe that way
>>> cars.columnInfo()
          Member  Num     Variable  Type  Len  Pos    Format            Label
0   SASHELP.CARS    9    Cylinders   Num    8   24       NaN              NaN
1   SASHELP.CARS    5   DriveTrain  Char    5  147       NaN              NaN
2   SASHELP.CARS    8   EngineSize   Num    8   16       NaN  Engine Size (L)
3   SASHELP.CARS   10   Horsepower   Num    8   32       NaN              NaN
4   SASHELP.CARS    7      Invoice   Num    8    8  DOLLAR8.              NaN
5   SASHELP.CARS   15       Length   Num    8   72       NaN      Length (IN)
6   SASHELP.CARS   11     MPG_City   Num    8   40       NaN       MPG (City)
7   SASHELP.CARS   12  MPG_Highway   Num    8   48       NaN    MPG (Highway)
8   SASHELP.CARS    6         MSRP   Num    8    0  DOLLAR8.              NaN
9   SASHELP.CARS    1         Make  Char   13   80       NaN              NaN
10  SASHELP.CARS    2        Model  Char   40   93       NaN              NaN
11  SASHELP.CARS    4       Origin  Char    6  141       NaN              NaN
12  SASHELP.CARS    3         Type  Char    8  133       NaN              NaN
13  SASHELP.CARS   13       Weight   Num    8   56       NaN     Weight (LBS)
14  SASHELP.CARS   14    Wheelbase   Num    8   64       NaN   Wheelbase (IN)

# now, let's only pick the one column - could just navigate the dataframe above to get to the column you want too
>>> cars.dsopts={'keep':'Make'}
>>> cars.columnInfo()
         Member  Num Variable  Type  Len  Pos
0  SASHELP.CARS    1     Make  Char   13   80
>>> df = cars.columnInfo()
>>> df['Type'][0]
'Char'
>>>
>>> df['Type'][0] == 'Char'
True
>>> df['Type'][0] == 'Num'
False
>>>
```

Thats one way you can get at the variable type programmatically. If you know how to navigate the DF, thenyou can just get the whole result and look. Getting only one column back inthe second case, and cheking it is easy if you just want to know about a particular column.

Is this what you are looking for?

Tom

**Comment by Narendra5005** [comment]
Thanks for the detailed info Tom.. let me try and get back.. When I tried last time with dataframes, all varchars were coming as objects.. will try this

**Comment by Narendra5005** [comment]
Hi Tom,

I got a question, there is a SAS portal known as SAS RFW where users create a project and execute the flow. Is there a way to automate this through an api or a proc sql query for SAS EG. We want to avoid the interaction with the web RFW portal. Please let me know if you are aware of anything around this. Thank you

Regards
Narendra

**Comment by tomweber-sas** [comment]
Is SAS Risk and Finance Workbench what you are asking about? I had to google SAS RFW, and that's what the first hit was.
I'm afraid I don't know anything about that. I would think Tech Support would be the fastest way to get an answer on that.
Tom

**Comment by tomweber-sas** [comment]
Closing up old, idle issues. if you still need something on this, you can reopen it. If you need anything else, feel free to open a new issue.
Thanks!
Tom
