### ISSUE TITLE
Saspy on google collab or alternative?

### ISSUE THREAD

**Issue by jingmeb** [sassoftware/saspy#305]
We are trying to figure out a workflow for using SAS in a jupyter notebook where we can do code-review and version control in a seamless way.

So far Google Collab seems to have come the furthest, but doesn't support saspy - even when using it as a local runtime. 

Are there any plans for extending support for collaborative tools using SAS?

Best,
Jing

**Comment by tomweber-sas** [comment]
Hey Jing,

I had to look that up, as I haven't used that before. I read up enough in it that guess i see the issue. It's a cloud service, so remotely connecting back to your internal SAS servers would be the problem, right? I don't see any way to configure networking, or VPN from there. Is that how it's 'not supported' from your perspective?

I'm sorry, but I'm on vacation this week, till Monday the 13th. But, I have a phone and sometimes internet 😎
So I tried this and got the error I expect. Hope this screen shot comes through. 

![Screenshot_20200705-091346_Chrome](https://user-images.githubusercontent.com/17710182/86533705-ee489380-bea0-11ea-99bf-1fa173be7ffc.jpg)

Is this the problem then?

Thanks,
Tom

**Comment by jingmeb** [comment]
Yes - I think it is possible to run on your local computer (https://research.google.com/colaboratory/local-runtimes.html) but so far haven't seen anyone successfully run SASpy through this.

I think the primary use case here is that google collab has very good version control and commenting features - which Jupyter Notebooks/Jupyter Lab doesn't support natively quite yet.

**Comment by tomweber-sas** [comment]
The doc for local runtime sounds like it's your Python and Jupyter on your machine, so I would expect that to work same as normal. Fwiw, I also tried a remote IOM connection to a workspace server from there and that works if you can connect to the host from the internet. 

sas = saspy.SASsession(java='/usr/bin/java', iomhost=host, iomport=8591)

So, if you can connect to a workspace server from the internet, that will work. But, that's less likely. But it sounds like the local would work for you. 

Tom

**Comment by jingmeb** [comment]
Hi Tom!

Thanks for looking at this over the weekend on your vacation. Indeed, it seems to work!

Best,
Jing

**Comment by tomweber-sas** [comment]
That's cool! Then you are the proof, you didn't find out there 😎 
Good job!

**Comment by jingmeb** [comment]
:D 

So if Google Colab now offered SAS syntax highlighting - this could be the ideal SAS IDE...

Best,
Jing

**Comment by tomweber-sas** [comment]
I think this was resolved.
Closing up old, idle issues. if you still need something on this, you can reopen it. If you need anything else, feel free to open a new issue.
Thanks!
Tom
