### ISSUE TITLE
Error: We failed in get connection

### ISSUE THREAD

**Issue by abkmystery** [sassoftware/saspy#306]
I have followed all the instructions for installation, including adding the sspiauth directory to system PATH, and I still get the error below.

Thanks in advance!

We failed in get Connection
The native implementation module for the security package could not be found in the path.
SAS process has terminated unexpectedly. RC from wait was: 4294967290
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94498__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94498__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94498__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94498__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Users\\jinzha\\Appdata\\Local\\Continuum\\anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '63847', '-stdoutport', '63848', '-stderrport', '63849', '-zero', '-lrecl', '1048576', '']

Be sure the path to sspiauth.dll is in your System PATH

No SAS process attached. SAS process has terminated unexpectedly.

**Comment by tomweber-sas** [comment]
Hey, can you show me the config file you're using? Do you know what version if SAS you have installed on your machine, and which version of saspy you're installed?
Thanks,
Tom

**Comment by tomweber-sas** [comment]
Trying to clean up old, idle issues. This error is documented in number 3 at this section in the doc: https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors.
You need the path to the sspiauth.dll in your path. Did you already fix that and get running? 
Thanks,
Tom

**Comment by tomweber-sas** [comment]
If you get back to this and need more help, feel free to reopen, or if you need something new, just open another!
Thanks,
Tom

**Comment by jg-esri** [comment]
Hi there, I am getting this error but do have the dll location listed in my PATH variable. Were there any solutions to this issue?

**Comment by tomweber-sas** [comment]
Hey @jg-esri can you open an issue with whatever information you have on your problem? Can you provide the code you ran and all of the output so I can see what you are getting. What configuration are you using, what version of saspy/SAS? 
Thanks!
Tom
