### ISSUE TITLE
I have SAS University edition in Virtual box running in my mac. I am trying to connect saspy to this. Its unable to connect SASsession.

### ISSUE THREAD

**Issue by sribarrow** [sassoftware/saspy#307]
I get the below error. how to connect to my SAS running in virtualbox?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/saspy/sasbase.py", line 527, in __init__
    pyenc = sas_encoding_mapping[self.sascei]
KeyError: 'No SAS process attached. SAS process has terminated unexpectedly.'
```

**Comment by tomweber-sas** [comment]
Yes, UE is a closed system. It has saspy in it already, so you can use it from the jupyter notebook that is in it. There is not a way to use an external python to interface directly to the SAS that is inside UE. 

After the VM starts, you just go to localhost:10080 in your browser. That gives you the choice of either SAS Studio, or Jupyter. Choose Jupyter notebook and it brings up jupyter. Actually, Jupyter Lab in the latest UE versions. The version of saspy in it is bound to be pretty old. But you can upgrade it by running the following (whatever version you want; 3.3.7 is the latest currently), and then connect right to it:
```
! pip install saspy==3.3.7 --user

Collecting saspy==3.3.7
  Downloading https://files.pythonhosted.org/packages/58/63/025468523140fdfbc2d39944190fdd9d7e76b0bcc142d4bd26e0763f3a27/saspy-3.3.7.tar.gz (6.4MB)
    100% |████████████████████████████████| 6.4MB 1.9MB/s 
sas-kernel 2.2.0 has requirement metakernel>=0.18.0, but you'll have metakernel 0.12.4 which is incompatible.
Installing collected packages: saspy
  Found existing installation: saspy 3.1.6
    Uninstalling saspy-3.1.6:
      Successfully uninstalled saspy-3.1.6
  Running setup.py install for saspy ... done
Successfully installed saspy-3.3.7

import saspy
sas = saspy.SASsession()
sas

Using SAS Config named: default
SAS Connection established. Subprocess id is 15695

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to utf_8 based upon the SAS session encoding value of utf-8.
Access Method         = STDIO
SAS Config name       = default
SAS Config file       = /folders/myfolders/.local/lib/python3.5/site-packages/saspy/sascfg.py
WORK Path             = /tmp/SAS_work625600003D4F_localhost.localdomain/
SAS Version           = 9.04.01M6P11072018
SASPy Version         = 3.1.6
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 15695
```

I just did this in the version I have. I noticed the warning about the sas_kernel, so I just installed the current vcersion of that too and it got the newer metakernel it wanted. So it's up and running with the latest saspy and sas_kernel.
! pip install sas-kernel==2.2.0 --user

Can you run it that way and accomplish what you need?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Do you still need any help with this? Trying to close old, idle issues.
Thanks!
Tom

**Comment by sribarrow** [comment]
Hi Tom,

This was sorted, thank you.

Sri

**Comment by tomweber-sas** [comment]
Cool thanks!. As always, just open up another if you need anything else!
Tom

**Comment by sribarrow** [comment]
I defo will.

**Comment by sribarrow** [comment]
Thanks Tom. I sure will.
