### ISSUE TITLE
Typo in documentation for sascfg

### ISSUE THREAD

**Issue by amckiern** [sassoftware/saspy#31]
Hi, there is a typo in the documentation https://sassoftware.github.io/saspy/install.html.

In the _Remote_ section, _winiomwin_ is mentioned twice and I think one of those references should be to _winiomlinux_.

![image](https://cloud.githubusercontent.com/assets/8472772/25713449/99f57f54-30ec-11e7-8654-cfab09f24617.png)

Regards,
Adrian.

**Comment by tomweber-sas** [comment]
Ah yes, thanks. I have some other doc edits to do and I will clean up this one at the same time. Thanks!

**Comment by tomweber-sas** [comment]
That's fixed now. Thanks again.
