### ISSUE TITLE
Submit SAS code directly from Python session

### ISSUE THREAD

**Issue by bruceuser** [sassoftware/saspy#310]
Hi, I've used the SAS Kernel but am new to SASPy.  I did code similar to the code to Submit SAS code directly from Python session at https://sassoftware.github.io/saspy/getting-started.html#submit-sas-code-directly-from-python-session.  I picked the simplest code I could.

c = sas.submit("""
data one;
  input v1 v2 $;
  datalines;
1 att
2 ibm
3 aol
4 ama
;run;
proc print data=one; 
run;
""")
HTML(c['LST'])

I got the following results.

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-3fe3751af00c> in <module>
     11    run;
     12 """)
---> 13 HTML(c['LST'])

NameError: name 'HTML' is not defined

I most recently did this in a new session where all I had done prior to this code was the minimum.  This does connect me and I can do some basic stuff successfully.
import pandas
import saspy
sas = saspy.SASsession(cfgname='ssh')

Is there something I need to add to make HTML available?  I assume HTML is a method?

Thanks,
Bruce

**Comment by tomweber-sas** [comment]
Hey Bruce, yes, this is an easy one. You do need to 'define' HTML - the way this was originally in saspy, it would have been to import it:
```
from IPython.display import HTML
c = sas.submit(code)
HTML(c['LST'])
```
Then that would work. But, the current saspy has HTML defined w/in it so you don't have to do that import just use the saspy defined one:
```
c = sas.submit(code)
sas.HTML(c['LST'])
```
So that will work from your SASsession object. But the more current saspy has submitLOG() and submitLST() methods that you can use so now you don't even need to do that!
```
sas.submitLST(code)
```
And that will render the LST automatically!   submitLOG(code) renders the log for you.

And if you the code you submit may produce output, or not and you want the output, else the log (or maybe if there's an error then no output) you can add an option on submitLST(code, results=listorlog') which will render the LST if there is one, else render the log!

You can use results='listandlog' or results='logandlist' to render both, in whichever order you like too. 

I like the submitLOG and submitLST versions as it's much more convenient in an interactive session.

Try those and see what you like!
Tom

**Comment by bruceuser** [comment]
Hi Tom, this looks great!  I'm probably making some small error.

Submitted this in 1st cell:
# Initial library imports: SASPy and Pandas.
import pandas
import saspy
# Connect to a SAS session, ssh references a connection name specified in 
# the local SASPy configuration.
sas = saspy.SASsession(cfgname='ssh')

Got back this, so I know I got the connection:
SAS Connection established. Subprocess id is 108106

Submitted this in 2nd cell:
c = sas.submit("""
data one;
     input v1 v2 $;
     datalines;
   1 att
   2 ibm
   3 aol
   4 ama
   ;run;
   proc print data=one; 
   run;
""")

Submitted this in 3rd cell:
sas.submitLOG(code)

Got this:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-5a952f8f6cf2> in <module>
----> 1 sas.submitLOG(code)

AttributeError: 'SASsession' object has no attribute 'submitLOG'

Submitted in 4th cell:
sas.submitLST(code, results='listandlog')

Got this:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-e05d666d697c> in <module>
----> 1 sas.submitLST(code, results='listandlog')

AttributeError: 'SASsession' object has no attribute 'submitLST'

I bet it's something small that I'm just not seeing.

Thanks,
Bruce

**Comment by tomweber-sas** [comment]
These error:
AttributeError: 'SASsession' object has no attribute 'submitLOG'
is indicative of you not having the version of saspy that has these, that's all. 
if you submit your SASsession object, sas, it will display info regarding versions an such. 

```
tom64-5> python3.5
Python 3.5.6 (default, Nov 16 2018, 15:50:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession(cfgname='ssh')
SAS Connection established. Subprocess id is 27171

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to latin_1 based upon the SAS session encoding value of latin1.

>>> sas
Access Method         = SSH
SAS Config name       = ssh
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /sastmp/SAS_work25BE00000E76_tom64-4/
SAS Version           = 9.04.01M6D11072018
SASPy Version         = 3.3.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = latin1
Python Encoding value = latin_1
SAS process Pid value = 3702


>>>
```

So, if you just get the latest version, you'll have these newer methods. FWIW, the best way to get the newer version is to uninstall then install:
```
pip uninstall -y saspy
pip install saspy
```

was sas.HTML() available in the version you have?

**Comment by bruceuser** [comment]
Thanks, I installed the new version and verified that it's there.  I'm getting a different error now but suspect I'm closer to the answer.
Thanks!
Bruce

sas

Access Method         = SSH
SAS Config name       = ssh
SAS Config file       = /mnt/vol_edp_home/adap_home/m1bfg00/sascfg_personal.py
WORK Path             = /mnt/vol_adap_sas_swap/sas_m1bfg00/SAS_work278A0001F774_m1-adaprssas04p.frb.gov/
SAS Version           = 9.04.01M3P06242015
SASPy Version         = 3.3.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = latin1
Python Encoding value = latin1
SAS process Pid value = 128884

c = sas.submit("""
data one;
     input v1 v2 $;
     datalines;
   1 att
   2 ibm
   3 aol
   4 ama
   ;run;
   proc print data=one; 
   run;
""")
HTML(c['LST'])

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-9-3fe3751af00c> in <module>
     11    run;
     12 """)
---> 13 HTML(c['LST'])

NameError: name 'HTML' is not defined

c = sas.submit("""
data one;
     input v1 v2 $;
     datalines;
   1 att
   2 ibm
   3 aol
   4 ama
   ;run;
   proc print data=one; 
   run;
""")
sas.submitLST(code, results='logandlist')

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-c86c660cd552> in <module>
     11    run;
     12 """)
---> 13 sas.submitLST(code, results='logandlist')

NameError: name 'code' is not defined

**Comment by tomweber-sas** [comment]
NameError: name 'HTML' is not defined   is the same error you started with. You need to use sas.HTML()

you don't submit '---> 13 sas.submitLST(code, results='logandlist')' as is, 'code' is your SAS code you are trying to submit.

instead of running this
```
c = sas.submit("""
data one;
input v1 v2 $;
datalines;
1 att
2 ibm
3 aol
4 ama
;run;
proc print data=one;
run;
""")
sas.HTML(c['LST'])
```
which should work, you can use this instead
```
sas.submitLST("""
data one;
input v1 v2 $;
datalines;
1 att
2 ibm
3 aol
4 ama
;run;
proc print data=one;
run;
""")
```

Tom

**Comment by tomweber-sas** [comment]
Ok, at least you have this all working, now you just need to learn some python :)

So, sas.HTML() is used to render HTML, which is, in your case, what the LST is returning. The LOG isn't HTML, it's just text - a string. When you submit something in python that returns text to you, but you don't assign it to anything it displays as a string literal. If you want to see it 'rendered' so line-feeds are 'used' not displayed as backslash n  you print() strings. So HTML  the LST and print the LOG.

None of what you are seeing in the above cases is other than not yet understanding the methods and python. You should take a look at some of the examples here to get a better feel of saspy, and python's easy enough, so google a few things and just start playing with it.
https://github.com/sassoftware/saspy-examples/tree/master/SAS_contrib the first one to see is:
https://github.com/sassoftware/saspy-examples/blob/master/SAS_contrib/saspy_example_github.ipynb
it's a little old, but walks you through some things.

Here's some of that w/out saspy, just simple python showing the same kind of output and errors (FYI):
```
>>> x = 'hi\nthere\nho\nare\nyou'
>>> x
'hi\nthere\nho\nare\nyou'
>>> print(x)
hi
there
ho
are
you
>>>
>>> HTML(z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'HTML' is not defined
>>> anotherUnknownMethod(z)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'anotherUnknownMethod' is not defined
>>>
```

See, these are just normal error of the language and normal rendering of the objects by python.

You've got your saspy working, just need to lean some python and then saspy will make more sense and work like you expect too! 

Tom

**Comment by bruceuser** [comment]
Thanks Tom.  I am new to both Jupyter and Python.  So much to learn.  I will get to that as time allows.  In the meantime, I think the following is a good solution.

c = sas.submit("""
data one;
input v1 v2 $;
datalines;
1 att
2 ibm
3 aol
4 ama
;run;
proc print data=one;
run;
""")
sas.HTML(c['LST'])              # shows LST     
print(c['LOG'])                    # shows log

Unless you disagree, I think that is sufficient for now.  Thanks for all of your help.  I have learned a lot.

Bruce

**Comment by tomweber-sas** [comment]
Yes, you can do that. You'll figure out the others soon too! Hey, actually, I had an issue yesterday, that I think would be useful. They referenced an SGF video presentation, using this (University Edition - but you already have this running; so you're good to go). Here's the link. It's an intro to both python and saspy, so it's just what you need! I think it'll be a worth while thing to watch and try interactively on your system as then go through things.
https://www.youtube.com/watch?v=YL8xV0AOcMc&t=185s
BTW, don't be confused at how they use the term KERNEL - think PROCESS not kernel like Jupyter Kernel, cuz those are two different things. Give it a watch and try the code on your system as you go. It's a good intro that will help I think!
Tom

**Comment by bruceuser** [comment]
Thanks!  Will do.
Bruce

**Comment by bruceuser** [comment]
I'm sorry, one last question.  I run the following code but only get the log output.  I run sas.HTML(c['LST'])  in its own cell and it returns the LST.  Why wouldn't that work in the same cell with the other stuff?

c = sas.submit("""
   data one;
     input v1 v2 $;
     datalines;
   1 att
   2 ibm
   3 aol
   4 ama
   ;run;
   proc print data=one; 
   run;
   """)
   sas.HTML(c['LST'])     # show lst
   print(c['LOG'])        # show log

Thanks,
Bruce

**Comment by tomweber-sas** [comment]
That's a jupyter'ism. I'm general, if you submit multiple statements, in a single cell, that produce output, you only see that last output. Good idea to have one output per cell. There are ways to have more than one, but that's more complicated.

**Comment by bruceuser** [comment]
Thanks.  Something to add to the document I'm writing.

Thanks and have a great weekend.

**Comment by tomweber-sas** [comment]
@bruceuser I'm trying to close up old, idle issues. This looks like you're up and running. Can we close this one or is there anything you need with it? You can always open new issues for other things as needed, too.
Thanks,
Tom

**Comment by bruceuser** [comment]
Hi Tom, you can close this one out.  Thanks for all of your help.
Bruce

**Comment by tomweber-sas** [comment]
Cool. Just open another if you need anything else!
Tom
