### ISSUE TITLE
Issue applying labels to dataset from pandas dataframe

### ISSUE THREAD

**Issue by biojerm** [sassoftware/saspy#313]
II am having an issues applying the label below to a column when creating a sas7bdat dataset.

> "The subject's PTID. If the PTID has changed in the past, this is always the most recent value."

I am looping over .csv data files and .csv files containing mapping to the labels, using pandas to read the .csv and saspy to convert them to sas7bdat files.  The above label is being applied numerous times with other datasets/files (earlier in the loop), however on a few datasets saspy seems to 'hang'.  Using `pdb` I have manually changed the label to remove the single quote processing continues (until a few datasets later it 'hangs' again).  I know in #283 you mention surrounding labels in triple quotes, when quotes are in the label.  But I have not figured out how to do that when not manually defining the formats dict.  Below is the code I use to create the dictionary from two columns in a data frame:
`labels = pd.Series(lables_df["label"].values, index=labels_df["name"]).to_dict()`
 

Also what is very confusing is that in previous csv files the **same** label is applied (with single quote).
When I pause processing using `pdb` I appear to be stuck in the submit function( sasiostdio.py>submit() )

**Desktop (please complete the following information):**
```(Pdb) sas.session
Access Method         = STDIO
SAS Config name       = mycfg
SAS Config file       = /trials/LabDataOps/common/assay_code/io/lio/sas/lio_sascfg.py
WORK Path             = /tmp/SAS_workC9DF0000F689_statsrv/
SAS Version           = 9.04.01M2P07232014
SASPy Version         = 3.3.7
Teach me SAS          = False
Batch                 = True
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 63113```

**Additional context**
also saw the same issue in saspy 3.2

**Comment by tomweber-sas** [comment]
Hey Jeremy, can you show me the code you're running to assign the labels; the saspy code? I'll track this down! Maybe the SASLOG too, if it doesn't hang.
Thanks,
Tom

**Comment by biojerm** [comment]
Hey Tom,

I am essentially running this code to create the datset:

```        lib_path, file_name = self._sas_path_split(out_path)
        self.session.saslib("outlib", path=lib_path)
        self.session.df2sd(
            dataframe,
            table=file_name,
            libref="outlib",
            datetimes=datetimes,
            outfmts=fmts,
            labels=labels,
        ) 
```


I wrapped the creation of the sas session some code that allows it to be used in a context manager.  full Code below.  I'll email you the saslog, since it has info I don't want shared on github.

```
PACKAGE_DIR = os.path.dirname(os.path.abspath(__file__))
CFG_PATH = os.path.join(PACKAGE_DIR, "lio_sascfg.py")


class SasSession(ContextDecorator):
    def __init__(self, cfg_path=CFG_PATH):
        self.cfg_path = os.path.abspath(cfg_path)

    def __enter__(self):
        """Creates the sas connection within a context manager

        Returns:
            [SASsession] -- SASsession connection
        """
        cfg_path = self.cfg_path
        self.session = saspy.SASsession(
            cfgfile=cfg_path, cfgname="mycfg", options=["-nofmterr"]
        )
        self.session.set_batch(True)  # to reduce sas messages
        return self

    def __exit__(self, *exc):
        """Closes the SASsession when exiting the context manager"""
        self.session.endsas()

    def write(self, dataframe, out_path, datetimes={}, fmts={}, labels={}):
        """Write out a pandas dataframe to a sas7bdat object

        Arguments:
            dataframe {pandas df} -- Pandas dataframe of the data
            out_path {str} -- path including filename of the sasdataset

        Keyword Arguments:
            datetimes{dict} -- columns in sas dataset with time or date data.
                               Can have the value 'time' or 'date' as values
                           (default: {{}})
            fmts {dict} -- columns and sas formats to apply to the sas dataset
                           (default: {{}})
            labels {dict} -- Values to set as SASdataset lables.
                            column names are keys and labels as values of dict.
                            If labels have quotes in them use triple single
                            quote to wrap the text '''"it's here"'''
                           (default: {{}})
        """
        lib_path, file_name = self._sas_path_split(out_path)
        self.session.saslib("outlib", path=lib_path)
        self.session.df2sd(
            dataframe,
            table=file_name,
            libref="outlib",
            datetimes=datetimes,
            outfmts=fmts,
            labels=labels,
        )

    def _sas_path_split(self, file_path):
        """Breaks a path down into its path and filename components.

            When SAS reads in a file a directory is loaded an the files can be
            loaded without the extension.  This function splits the path and
            removed the extension to be sas compatable.

        Arguments:
            file_path {str} -- path to a file

        Returns:
            libpath {str} -- path to the directory
            fn {str} -- filename without extension
        """
        lib_path, file = os.path.split(file_path)
        fn, _ = os.path.splitext(file)
        return lib_path, fn
```

**Comment by tomweber-sas** [comment]
cool, I got it. I'll take a look this afternoon and see what I can see!

**Comment by tomweber-sas** [comment]
Got the log and was able to print() it out to read it. I think it's just that the label strings you're providing me don't conform to the SAS label rules: https://go.documentation.sas.com/?docsetId=lestmtsref&docsetTarget=n1r8ub0jx34xfsn1ppcjfe0u16pc.htm&docsetVersion=9.4&locale=en

Having an embedded single quote requires outer double quotes, while having whitespace requires no outer quoting, which is not the usual case for SAS syntax. Having other embedded quoting requites following other doc about SAS character constants (another link in that doc). 

For the label, I simply generate the label statement with the string you provide, since I won't be able to programmatically try to manipulate your string trying to get the rules right. 

I think if you simply added double quotes to that string itself you were trying to use that should fix it. So, for this case the SAS syntax needs to be:
45   label 'SUBJECT'n =”The subject's PTID. If the PTID has changed in the past, this is always the most recent value.”;
instead of
45   label 'SUBJECT'n =The subject's PTID. If the PTID has changed in the past, this is always the most recent value.;

so the dict for that column would be (needing a string containing both double and single quotes requires python triple quotes  around it):
```
{'subject' : '''"The subject's PID [...] value."'''}
```

Can you give that a try?  BTW I emailed back all of this w/ the log readable to see this more clearly.
Tom

**Comment by biojerm** [comment]
Thanks for looking into this Tom,


If I were to manually define all the labels (in my case I have 92) your solution above would work as it evaluates to

```
(Pdb) {'subject' : '''"The subject's PID [...] value."'''}
{'subject': '"The subject\'s PID [...] value."'}
```
With the right quotes in there.  However my issues is that:

**Comment by biojerm** [comment]
I might be able to do this 

```
(Pdb) labels['SUBJECT'] = repr(labels['SUBJECT'])
(Pdb) labels['SUBJECT']
'"The subject\'s PTID. If the PTID has changed in the past, this is always the most recent value."'
```
for labels with `'` in them.  will sas remove the escaping backslash? `\'` in the repr string or will it get `subject\'s` as the label?

**Comment by tomweber-sas** [comment]
This is why I'm not trying to do all this in my code, as I'll never get it right for ever user case :)

So, labels['SUBJECT'] is a string w/ a single quote in it. If that's the only problem case, would this just work:

labels['SUBJECT'] = '"'+labels['SUBJECT']+'"'
Or rather assigning it to wherever in the first place, just add the double quotes around it. 

You just need to wrap your string w/ double quotes. If there are other permutations of quoting in these strings, then again, it a matter of making it work w/ the SAS rules for labels. But, I kinda think that if you just add double quotes to your actual string you want to use, that will work.  It needs to be:
```
>>> labelstr = "The subject's PTID. If the PTID has changed in the past, this is always the most recent value."
>>> labelstr
"The subject's PTID. If the PTID has changed in the past, this is always the most recent value."
>>> print(labelstr)
The subject's PTID. If the PTID has changed in the past, this is always the most recent value.
>>>
>>> labelstr = '"'+"The subject's PTID. If the PTID has changed in the past, this is always the most recent value."+'"'
>>> labelstr
'"The subject\'s PTID. If the PTID has changed in the past, this is always the most recent value."'
>>> print(labelstr)
"The subject's PTID. If the PTID has changed in the past, this is always the most recent value."
>>> see the difference? you need the second
```

**Comment by biojerm** [comment]
Oh, I see now let me give it a try

**Comment by biojerm** [comment]
you are a genius, it work thanks!

**Comment by tomweber-sas** [comment]
And, sorry, but I haven't had a chance to go read all the rest of the rules. I don't know what you get is your string has double quotes init, or both??? I might be inclined to just do something like this to alleviate that; it's just a label, so:
label = '"'+label_string.replace('"', "'")+'"'
so that it only has single quotes inside the string, so that double quotes on the outside are always valid. Again, I 'm not sure the SAS rules on this, exactly, and what you would then have to do in Python if they didn't make sense there.

**Comment by tomweber-sas** [comment]
Ah, cool. Yes, looking at quoted quotes in a string is sometimes a bit of a black hole!

**Comment by tomweber-sas** [comment]
assuming we can close this? If you need anything else ...     
you know where to find me :)
