### ISSUE TITLE
Raise Errors when there are issues in the SAS job

### ISSUE THREAD

**Issue by biojerm** [sassoftware/saspy#319]
Hey Tom,

This is more of a 'how should I handle this situation?' question. 

I was using the new outencoding capabilities in saspy and noticed that when I was writing out some data, the datasets were truncated when I was converting them from UTF-8 to Latin9.  The creation of the dataset stopped when there was a character not encoded with in latin9, so SAS did not know what to do (totally reasonable because encoding makes everything more complicated 😆 ).  

I am not too worried about the fact that there are issues converting between encodings, because that is bound to happen.  What was unfortunate is that I was not alerted that there was an issue during dataset creation.  The dataset issue truncation happened a while back too when I need to escape some new line characters #313.  

I only noticed the issue because I wrote a check that there are equal numbers of rows in the pandas dataframe and sas dataset.  I am sure in the 'sas.saslog()' there is information about what is happening.  But I typically don't inspect the saslog unless I already know there is an issue. 

Do you have any suggestions on how to 'detect' these issues as they happen?  Normally I would expect a "SASDataSetError("Your dataset is all messed up %s", sas.lastlog()) or something to steer me in the right direction.

I don't know how much cross talk you have with the sas Kernel, so this may be impossible.  But I wanted to get your opinion.  We have a lot of shell scripts that watch the return value, so I can understand if the info you can get back is limited.

**Comment by tomweber-sas** [comment]
Hey Jeremy, yes, this can become a complicated situation. Let me try to address each this independently. Then we can address each specifically.

1) trying to write data out in an encoding that doesn't support the data is a problem. Can I see the log for this case? Did the table get created? or did it fail and not create it? If it failed to create the table, then the SASdata object returned from that would be 'None', such that checking that being returned or not would tell you if it failed. If it created the table, and didn't fail, then I'd have to see what was in the log to see what you can do.
if you are trying to implicitly replace an existing table (you already have a table named 'a' and you're doing df2sd with the same name 'a'), then if the step fails and the table isn't created (overwritten), then you would still get back a SASdata object for that existing table, as I don't know that isn't the 'new' table. In that case, you should del the exiting table you're trying to replace in the first place, then you will know if the new table was created or not. Or use a different name. You can even rename it after if it worked.

2) specific to df2sd, I do first validate that the data you're trying to sent to SAS does transcode from utf-8 to the SAS session encoding, as I have to do that in the code myself. If it doesn't then I fail . But in this case, where you add the option to tell SAS to take that and then transcode it to some other encoding; the error happens after me, in SAS. I suppose one thing I could do it to enhance my code to 'double' transcode, to what your final encoding will be and fail if it can't be supported by that encoding. 

3) checking the log to see if there were any issues. I do believe that checking the log to see what happened is something one should do, at least when doing something new, that you haven't already validated. There are so many possibilities in SAS for something to happen, especially when using new data you haven't used before or doing things with it you haven't done before, that looking at the log to see what happened, the first time you do something new (should be the same each time after, so you have to always do it once you validated the process) is something that should be done. 
I added a method, lastlog(), a while back to help with this, as the full session log (saslog()) can get big. so just trying to see the last thing that happened is cumbersome. However, the implementation was a bit simple and doesn't really work with sd2df and df2sd; I've been gonna work through enhancing it for those case, but haven't as of yet. Currently it's just the log from the last submit(), which is right for most methods, but df2sd and sd2df are more complicated and submit more than one block of code, and sometimes interact other then w/ submit(), so I'll need to manually aggregate all of the parts of log to provide the 'right' lastlog() for those methods. 
It seems about time I do that, then you can use lastlog() after these to easily see exacly what happened for that method.

4) saspy trying to analyse the logs to determine success or failure. So, this is a dubious thing that I've never bought into. I don't like the idea of saspy arbitrarily trying to assess failure or success of a method based upon trying to parse the log. There's too many possibilities for that to be accurate. If the following were truly definitive,   if 'ERROR:' in LOG'  then the user can code that one liner after anything they want to check for. But that's never been something I think I should be doing in here, as there are other possibility that could be failures, and having false positives would be even worse, where you could get code to run because I decided it didn't work. Since this is a programming environment, I think that providing the user a way to assess what happened is better than me trying to magically do it for them. Fixing lastlog() so you get the aggregates log for all of the logical steps that happen under the covers would certainly help this.

Sorry that's really long, but as I said, this is a complicates situation. So, can you show me the code/log for the case in question and then what do you think about any of these topics above? I will work on enhancing lastlog() for these 'composite' methods, which run more than one simple block of code, so you get back all of the pieces of the log for the method. That is certainly part of the solution. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
FYI, I've created an issue #320 to address having lastlog() actually show all of the log for what ended up being run by methods that do more than just one code submission. I think this will help a lot as far as being able to easily see or check for things in the log on a method per method basis. Doesn't solve everything but it'll be a lot better regarding all of this.

**Comment by biojerm** [comment]
Hey Tom here is a quick example I coded up

```
import saspy
import pandas as pd

# note that the ≥ character is not encoded in latin9
df = pd.DataFrame({"col1": ["abc", "≥", "def"]})
sample_labels = {
    "col1": "Adding this utf-8 char: ≥ results in None returned"
}

sas = saspy.SASsession(cfgname="sas_u8")

print(sas)


should_be_fine = sas.df2sd(df, "should_be_ok", labels=sample_labels)
latin9_encoded = sas.df2sd(df, "latin9_encoded", outencoding="latin9")
utf_in_label = sas.df2sd(
    df, "utf_in_label", outencoding="latin9", labels=sample_labels
)

print(f"should_be_fine has {should_be_fine.obs()} observation(s)")
print(f"latin9_encoded has {latin9_encoded.obs()} observation(s)")
print(
    f"When there is a UTF character in the label and the dataset is latin9"
    f" encoded, the return value is None correct? {(utf_in_label is None)}"
)

print(sas.saslog())

```

here is the output minus the log

```
$ python sas_sandbox.py
Access Method         = STDIO
SAS Config name       = sas_u8
SAS Config file       = /scratch/jlabarge/saspy_sandbox/sascfg_personal.py
WORK Path             = /tmp/SAS_work11A900019905_statsrv/
SAS Version           = 9.04.01M2P07232014
SASPy Version         = 3.5.0
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 104709


should_be_fine has 3 observation(s)
latin9_encoded has 1 observation(s)
When there is a UTF character in the label and the dataset is latin9 encoded, the return value is None correct? True

```

and the log itself:
```
1                                                          The SAS System                         08:52 Thursday, September 17, 2020

NOTE: Unable to open SASUSER.REGSTRY. WORK.REGSTRY will be opened instead.
NOTE: All registry changes will be lost at the end of the session.

WARNING: Unable to copy SASUSER registry to WORK registry. Because of this, you will not see registry customizations during this
         session.
NOTE: Copyright (c) 2002-2012 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software 9.4 (TS1M2 MBCS3170)
      Licensed to FRED HUTCHINSON CNCR RES CTR - SCHARP, Site 70230084.
NOTE: This session is executing on the Linux 4.4.104-18.44-default (LIN X64) platform.



NOTE: Updated analytical products:

      SAS/STAT 13.2
      SAS/IML 13.2

NOTE: Additional host information:

 Linux LIN X64 4.4.104-18.44-default #1 SMP Thu Jan 4 08:07:55 UTC 2018 (05a9de6) x86_64 openSUSE 42.2 (x86_64) VERSION = 42.2
      CODENAME = Malachite

NOTE: SAS initialization used:
      real time           0.03 seconds
      cpu time            0.01 seconds


NOTE: AUTOEXEC processing beginning; file is /usr/local/sas-9.4/SASFoundation/9.4/autoexec.sas.


NOTE: AUTOEXEC processing completed.

1    ;*';*";*/;
2    options svgtitle='svgtitle'; options validvarname=any validmemname=extend; ods graphics on;
3
4    ;*';*";*/;%put %upcase(e3969440a681a2408885998500000001);
E3969440A681A2408885998500000001
5    ;*';*";*/;
6    data _null_; length x $ 4096; file STDERR;
7                   x = resolve('%sysfunc(pathname(work))');  put 'WORKPATH=' x 'WORKPATHEND=';
8                   x = resolve('&SYSENCODING');              put 'ENCODING=' x 'ENCODINGEND=';
9                   x = resolve('&SYSVLONG4');                put 'SYSVLONG=' x 'SYSVLONGEND=';
10                  x = resolve('&SYSJOBID');                 put 'SYSJOBID=' x 'SYSJOBIDEND=';
11                  x = resolve('&SYSSCP');                     put 'SYSSCP=' x 'SYSSCPEND=';
12               run;
NOTE: The file STDERR is:
      Pipe command="<standard error>"
WORKPATH=/tmp/SAS_work982C0001A911_statsrv WORKPATHEND=
ENCODING=utf-8 ENCODINGEND=
SYSVLONG=9.04.01M2P07232014 SYSVLONGEND=
SYSJOBID=108817 SYSJOBIDEND=
SYSSCP=LIN X64 SYSSCPEND=


NOTE: 5 records were written to the file STDERR.
      The minimum record length was 25.
      The maximum record length was 55.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.02 seconds

13
14
15   ;*';*";*/;%put %upcase(e3969440a681a2408885998500000002);
E3969440A681A2408885998500000002
16   ;*';*";*/;
17   data _null_; file STDERR; put %upcase('col0REG=');
NOTE: The file STDERR is:
      Pipe command="<standard error>"
COL0REG=


NOTE: 1 record was written to the file STDERR.
      The minimum record length was 8.
      The maximum record length was 8.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

18                                  data _null_;
18 !                                             put %upcase('col0LOG=');run;
COL0LOG=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

19
20   ;*';*";*/;%put %upcase(e3969440a681a2408885998500000003);
E3969440A681A2408885998500000003
21   data 'should_be_ok'n;
22   length 'col1'n $3;
23   label 'col1'n =Adding this utf-8 char: ≥ results in None returned;
24   infile datalines delimiter='03'x  STOPOVER;
25   input @;
26   if _infile_ = '' then delete;
27   input 'col1'n ;
28    'col1'n = translate('col1'n, '0A'x, '01'x);
29    'col1'n = translate('col1'n, '0D'x, '02'x );
30   ;
31   datalines4;
NOTE: The data set WORK.SHOULD_BE_OK has 3 observations and 1 variables.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

35   ;;;;
36   ;*';*";*/;
37   run;
38
39   ;*';*";*/;%put %upcase(e3969440a681a2408885998500000004);
E3969440A681A2408885998500000004
40   ;*';*";*/;
41   data _null_; e = exist("'should_be_ok'n");
42   v = exist("'should_be_ok'n", 'VIEW');
43    if e or v then e = 1;
44   put 'TABLE_EXISTS=' e 'TAB_EXTEND=';run;
TABLE_EXISTS=1 TAB_EXTEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

45
46   ;*';*";*/;%put %upcase(e3969440a681a2408885998500000005);
E3969440A681A2408885998500000005
47   ;*';*";*/;
48   data _null_; e = exist("user.'should_be_ok'n");
49   v = exist("user.'should_be_ok'n", 'VIEW');
50    if e or v then e = 1;
51   put 'TABLE_EXISTS=' e 'TAB_EXTEND=';run;
TABLE_EXISTS=0 TAB_EXTEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

52
53   ;*';*";*/;%put %upcase(e3969440a681a2408885998500000006);
E3969440A681A2408885998500000006
54   data 'latin9_encoded'n(encoding="latin9");
55   length 'col1'n $3;
56   infile datalines delimiter='03'x  STOPOVER;
57   input @;
58   if _infile_ = '' then delete;
59   input 'col1'n ;
60    'col1'n = translate('col1'n, '0A'x, '01'x);
61    'col1'n = translate('col1'n, '0D'x, '02'x );
62   ;
63   datalines4;
NOTE: Data file WORK.LATIN9_ENCODED.DATA is in a format that is native to another host, or the file encoding does not match the
      session encoding. Cross Environment Data Access will be used, which might require additional CPU resources and might reduce
      performance.
ERROR: Some character data was lost during transcoding in the dataset WORK.LATIN9_ENCODED. Either the data contains characters that
       are not representable in the new encoding or truncation occurred during transcoding.
NOTE: The DATA step has been abnormally terminated.
NOTE: The SAS System stopped processing this step because of errors.
WARNING: The data set WORK.LATIN9_ENCODED may be incomplete.  When this step was stopped there were 1 observations and 1 variables.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds

67   ;;;;
68   ;*';*";*/;
69   run;
70
71   ;*';*";*/;%put %upcase(e3969440a681a2408885998500000007);
E3969440A681A2408885998500000007
72   ;*';*";*/;
73   data _null_; e = exist("'latin9_encoded'n");
74   v = exist("'latin9_encoded'n", 'VIEW');
75    if e or v then e = 1;
76   put 'TABLE_EXISTS=' e 'TAB_EXTEND=';run;
TABLE_EXISTS=1 TAB_EXTEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds

77
78   ;*';*";*/;%put %upcase(e3969440a681a2408885998500000008);
E3969440A681A2408885998500000008
79   ;*';*";*/;
80   data _null_; e = exist("user.'latin9_encoded'n");
81   v = exist("user.'latin9_encoded'n", 'VIEW');
82    if e or v then e = 1;
83   put 'TABLE_EXISTS=' e 'TAB_EXTEND=';run;
TABLE_EXISTS=0 TAB_EXTEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

84
85   ;*';*";*/;%put %upcase(e3969440a681a2408885998500000009);
E3969440A681A2408885998500000009
86   data 'utf_in_label'n(encoding="latin9");
87   length 'col1'n $3;
88   label 'col1'n =Adding this utf-8 char: ≥ results in None returned;
89   infile datalines delimiter='03'x  STOPOVER;
90   input @;
91   if _infile_ = '' then delete;
92   input 'col1'n ;
93    'col1'n = translate('col1'n, '0A'x, '01'x);
94    'col1'n = translate('col1'n, '0D'x, '02'x );
95   ;
96   datalines4;
NOTE: Data file WORK.UTF_IN_LABEL.DATA is in a format that is native to another host, or the file encoding does not match the
      session encoding. Cross Environment Data Access will be used, which might require additional CPU resources and might reduce
      performance.
ERROR: Some character data was lost during transcoding in the dataset WORK.UTF_IN_LABEL. Either the data contains characters that
       are not representable in the new encoding or truncation occurred during transcoding.
NOTE: The SAS System stopped processing this step because of errors.
WARNING: The data set WORK.UTF_IN_LABEL was only partially opened and will not be saved.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

100  ;;;;
101  ;*';*";*/;
102  run;
103
104  ;*';*";*/;%put %upcase(e3969440a681a2408885998500000010);
E3969440A681A2408885998500000010
105  ;*';*";*/;
106  data _null_; e = exist("'utf_in_label'n");
107  v = exist("'utf_in_label'n", 'VIEW');
108   if e or v then e = 1;
109  put 'TABLE_EXISTS=' e 'TAB_EXTEND=';run;
TABLE_EXISTS=0 TAB_EXTEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

110
111  ;*';*";*/;%put %upcase(e3969440a681a2408885998500000011);
E3969440A681A2408885998500000011
112  ;*';*";*/;
113  data _null_; e = exist("WORK.'should_be_ok'n");
114  v = exist("WORK.'should_be_ok'n", 'VIEW');
115   if e or v then e = 1;
116  put 'TABLE_EXISTS=' e 'TAB_EXTEND=';run;
TABLE_EXISTS=1 TAB_EXTEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

117
118  ;*';*";*/;%put %upcase(e3969440a681a2408885998500000012);
E3969440A681A2408885998500000012
119  ;*';*";*/;
120  %let lastobs=-1;
121  proc sql;
121!          select count(*) format best32. into :lastobs from WORK.'should_be_ok'n ;
121!                                                                                  %put lastobs=&lastobs lastobsend=;
lastobs=                               3 lastobsend=
122  quit;
NOTE: The PROCEDURE SQL printed page 1.
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds

123
124  ;*';*";*/;%put %upcase(e3969440a681a2408885998500000013);
E3969440A681A2408885998500000013
125  ;*';*";*/;
126  data _null_; e = exist("WORK.'latin9_encoded'n");
127  v = exist("WORK.'latin9_encoded'n", 'VIEW');
128   if e or v then e = 1;
129  put 'TABLE_EXISTS=' e 'TAB_EXTEND=';run;
TABLE_EXISTS=1 TAB_EXTEND=
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

130
131  ;*';*";*/;%put %upcase(e3969440a681a2408885998500000014);
E3969440A681A2408885998500000014
132  ;*';*";*/;
133  %let lastobs=-1;
134  proc sql;
134!          select count(*) format best32. into :lastobs from WORK.'latin9_encoded'n (encoding="latin9" );
134!                                                                                                        %put lastobs=&lastobs
134! lastobsend=;
NOTE: Data file WORK.LATIN9_ENCODED.DATA is in a format that is native to another host, or the file encoding does not match the
      session encoding. Cross Environment Data Access will be used, which might require additional CPU resources and might reduce
      performance.
lastobs=                               1 lastobsend=
135  quit;
NOTE: The PROCEDURE SQL printed page 2.
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds

136
137  ;*';*";*/;%put %upcase(e3969440a681a2408885998500000015);
E3969440A681A2408885998500000015
```

**Comment by biojerm** [comment]
re 1. hopefully the example above illustrates the behavior I am seeing.  I am not too worried about 'solving' this issue
for this particular dataset, because I have the checks in place already.  It is more for 'next time' when i see something 'new'.

re 2.  yeah something like this is what I was thinking where I could get some sort of signal that there was an issue.  In this  case encoding is causing the problem. But we have also had issues in the past where embedded new line characters cause issues that we don't notice right away (inspecting the logs has not been in my normal workflow).  That all being said, I may not want the system to implode if there are issues.  I know the `pandas.to_numeric` function has an 'errors' parameter where you can keep moving on without issue and default values being added (this gets into a case where you 'choose' default which could be concerning).
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html 

But pathlib.path.mkdir allows you to specify that if a directory exists that is not a problem and ignore FileExistsErrors
https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir

re 3 and 4
   That is good to know that inspecting the log is best practice.  I see how 'parsing' the logs could lead it false positives.  For my use case this can be challenging because I am often asked to develop code for a customer using datasets that are not static.  So when I develop my code, I have a subset or 'current' data in the dataset.  However, over time users add information to the dataset and my code is often used by the customer(not me). So what has happened in the past I my code works on the example dataset I was given, but as more information is added to my source datasets, customers may not 'know' there were issues for some time (if ever).  From experience I have seen issues arise because people copy and paste from Office products or use characters from foreign languages.  Also 'comment' fields are a free for all... 🤷‍♂️ .

I get there is no easy answer here where it sounds like you get limited information back from the SAS Kernel, and SAS has its own behaviors that we need to account for.  Also it makes total sense that you don't want to impose your choices on the user, because we all do different things and inevitably someone will object to any choice that was made.  

I will definitely start to inspect the saslogs more carefully in the future though.  Normally I have been ignoring it 🤦 .

**Comment by tomweber-sas** [comment]
Thanks Jeremy! That's a perfect example of why this is problematic for me to try to address in saspy code, as opposed to user code checking to see what happened. In the two cases with a character that can't transcode, both had the same 'ERROR:' message in the log. But one still created the data set, though missing some data. The other didn't create the data set. When I fix lastlog(), then in user code, knowing these different cases that may happen when you try to do this, you can easily check things after running this method, and determine if you think it ran like you expect.

They both had the exact same error message!, plus a warning that was different in each case:
```
SASdata was successfully returnd and represends a partial dataset:

ERROR: Some character data was lost during transcoding in the dataset WORK.LATIN9_ENCODED. Either the data contains characters that
       are not representable in the new encoding or truncation occurred during transcoding.
NOTE: The DATA step has been abnormally terminated.
NOTE: The SAS System stopped processing this step because of errors.
WARNING: The data set WORK.LATIN9_ENCODED may be incomplete.  When this step was stopped there were 1 observations and 1 variables.


SASdata was None because the data set was not created:

ERROR: Some character data was lost during transcoding in the dataset WORK.UTF_IN_LABEL. Either the data contains characters that
       are not representable in the new encoding or truncation occurred during transcoding.
NOTE: The SAS System stopped processing this step because of errors.
WARNING: The data set WORK.UTF_IN_LABEL was only partially opened and will not be saved.
```

This is where I can't parse the log for every possible thing that can be in it and then try to assess success or failure. That has to be left up to the user program. In my little dissertation above :) Number 3 is what I would say is the situation here. The user is writing code to take some data and write it to SAS but have it be transcoded into some other encoding, which will either work just fine, or could have a number of (potentially) negative outcomes. Having run this through and see that there are likely issues, coding up a check of the log from this method (once I give you all the log for what was run, correctly), you can check for these cases and determine, progamatically, whether you believe it to be a success or not. Maybe if you got 999 of 1000 rows translated correctly, you consider that ok; maybe you don't. But checking for the message about 'When this step was stopped there were ' would show that you didn't get all the rows you expect. Checking for 'was only partially opened and will not be saved' would identify it failed, of course returning None does that too. But, there could be other messages in the log that identify other situations for the code you ran. Those possibilities need to be check for by user code to make a determination.

I know this isn't what you (or anyone) wants, but me just looking for 'ERROR:' in the log and blindly failing isn't right at all. There are way too many possibilities for me to try to make determinations about. Coding this kind of thing is what I would expect in user code:

```
sd = sas.df2sd(...)

if not sd:
   raise # problem case to do something about
else:
   ll = sas.lastlog()
   if 'When this step was stopped there were ' in ll:   # we want to keep trucking in this case, maybe?
      print('missing some data, but that's ok?')
   elif 'ERROR:' in ll:
      raise # problem case to do something about
```

That's just an example, but there are just too many possibilities of things that can happen in SAS code, depending upon what you are doing, that when doing things that may have issues, checking to see what happened is on the program to do.

**Comment by biojerm** [comment]
yeah seeing that you have limited info from SAS, raising the 'correct' error would be impossible. I think having the user inspect `sas,lastlog()` might be the best option.  Thanks for the sample snippet.  I will make sure to do that in the future.

**Comment by tomweber-sas** [comment]
One of the things that's always been true w/ SAS is it doesn't simply give you a return code for everything you can submit. This whole issue is nothing new. That being the case, I still want to handle as much as I can in saspy, so users don't have to do extra work, when I can do it. This one happens to fall into the case where I can't always determine what happened and if it's ok or not.

Regarding number 2 above, was there something you think I can do with it to help, or some other options to add? Also, FYI, as of v3.5.0, I've changed the default for the embedded_newlines to True, so it is now being done by default so it can't go unnoticed. There were some other fixes there too to make that more solid as well. 

And, keep an eye on the other issue, fixing lastlog(). I'm working on that now and will post to it when I push code out. Hopefully you'll be able to add some simple checks in your code using that to see these different problems and catch them easily. 

Thanks!
Tom

**Comment by biojerm** [comment]
In that case for me what I am going to do is have some sort of check that looks something like:
```
ds = sas.df2sd(df,'whatever)

if ds is None:
    raise SomeError('No dataframe was created check saslog')

elif ds.obs() == df.shape()[0]:  # it could be index 1 i forget at the moment
    raise SomeOtherError(f'Not all records were written out' to sas dataset.  Only {ds.obs()} written, check saslog')

else:
    pass # move on with life (not even sure this is required)
```

So what I could see being valuable is having a flag that like 'strict'. 'check_output',  or 'coerce'  which when set (T/F) does the above checks before returning the ds.

Parsing the log would be too difficult, but having something say 'this does not look right' might be helpful.  Once again for me, and as the user this reasonably might be my problem.

**Comment by tomweber-sas** [comment]
Hey, I've pushed the branch 'lastlog' so you get all of the log for everything submitted for a given method. With that, 'parsing the log' is trivial, you can just add an elif to check for errors:

```
ds = sas.df2sd(df,'whatever')

if ds is None:
    raise SomeError('No dataframe was created check saslog')

elif ds.obs() == df.shape()[0]:  # it could be index 1 i forget at the moment
    raise SomeOtherError(f'Not all records were written out' to sas dataset.  Only {ds.obs()} written, check saslog')

elif 'ERROR:' in sas.lastlog()"  # some error was in the log, don't know if it really worked or not
    raise SomeLogERRORError(f'Found Errors in the log. Here it is to look at:\n {sas.lastlog()}')
```

I get the preference for having an option to have saspy check to see what happened. But it's still back to me failing or not based upon what I try to find in the log, which isn't really viable. There are too many possible things that could show up in the log for me to decide on (and we saw an ERROR when it actually succeeded; I don't know if you think that's ok or not ). I do verify whether the data set I try to create exists afterwards. that's definitive enough for me to check. I validate other things too, and will fail for any number of things that I can be sure of. But trying to assess the contents of the log isn't something I can do definitively. 

If you can, try that branch and see if checking the log after is as easy as I keep saying :) And, It's not like you have to do this for all methods. I think you're on one of the worst cases where you're explicitly doing something that's likely to fail for a known reason. just checking for that possible error after seems reasonable. A generic check for errors in the log, at any point where you have good reason to expect that it could fail, is a good thing to do. Now that you get the complete part of the log for the given method, that should be as easy as if 'ERROR"' in sas.lastlog()", or whatever other message you would expect to be in there for the expected failure case (or check that a specific message is Not in the log; if that means it worked).

**Comment by biojerm** [comment]
Cool, I'll check the branch out soon.  I had another priority come up, so I won't be able to get to it until this weekend-ish.

**Comment by tomweber-sas** [comment]
No problem, BTW, I've merged that branch into main,
