### ISSUE TITLE
sas.sasdata.to_df does not convert dates for tables with SPDE Engine

### ISSUE THREAD

**Issue by michaelbestlinkit** [sassoftware/saspy#328]
**Describe the bug**
I am using saspy to pull data from SAS and converting the resulting pandas data frame to parquet.
The tables I'm pulling are under different libraries which can use either an SPDE engine or a BASE engine.
Some of these tables have dates in them, which can be seen when you inspect the contents after getting the sasdata in the examples below. The problem is that when I pull data from tables that are using the SPDE engine, these dates get converted into a double. For the BASE engine, this behaviour does not occur.

**To Reproduce**
This is what I'm doing in python3.8.0. 
sas is my SAS session. I have kept out names and the dspopts dictionary, but this just filters some of the columns in these tables. I've tried using all three methods for to_df, they all result in the same bug.

```
sas.saslib(libref=base_df_libref,
           engine="BASE",
           options="ACCESS=READONLY",
           path=base_df_sas_path)

sas_result = sas.sasdata(table=base_df_table,
                         libref=base_df_libref,
                         dsopts=dsopts)
base_pd_df=sas_result.to_df(method="CSV")
```

You can see here that it correctly converts a SAS date into a date in Pandas

```
sas_result.contents()
Type  Format 
Num    DDMMYY10
Num    DDMMYY10

base_pd_df
       COLUMN1                     COLUMN2
0    1970-01-01                  2014-08-29
1     1970-01-01                  2014-08-29

```

With the SPDE engine the date is not converted correctly

```
sas.saslib(libref=spde_df_libref,
           engine="SPDE",
           options="ACCESS=READONLY",
           path=spde_df_sas_path)

sas_result = sas.sasdata(table=spde_df_table,
                         libref=spde_df_libref,
                         dsopts=dsopts)
spde_pd_df=sas_result.to_df(method="CSV")

```
You can see here that it does not correctly convert a SAS date into a date in Pandas

```
sas_result.contents()
Type  Format 
Num    DDMMYY10
Num    DDMMYY10

spde_pd_df
                COLUMN1             COLUMN2
0             17532.0                  17846.0
1              17532.0                  17846.0

```

**Expected behavior**

In spde_pd_df, we expect 17532.0 to be date 2008-01-01 and 17846.0  to correspond to date 2008-11-10, so a table like this:

```
spde_pd_df
                COLUMN1             COLUMN2
0             2008-01-01                 2008-11-10
1              2008-01-01                 2008-11-10
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
Access Method         = IOM
SAS Config name       = iomwin
SAS Config file       = .config/saspy/sascfg_personal.py
SAS Version           = 9.04.01M1P12042013
SASPy Version         = 3.5.3
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = windows-1252

Let me know what else I can provide to help fixing this problem.

**Comment by tomweber-sas** [comment]
Hey @michaelbestlinkit that is strange. Great job of providing clean use case showing this! The fist two things I'd like to see is a sas_result.contents() for each table. to see the formats that are defined on each of those for those columns. The other is the saslog( (if you have the latest saspy, lastlog() will show everything) for the sd2df()method. Also, I see you're using the CSV method. Does this happen for MEMORY or DISK too? That would be interesting to see too.
Thanks!
Tom

**Comment by michaelbestlinkit** [comment]
@tomweber-sas 
What is the best way of sharing these files with you without posting them online?

I'm using the CSV method, but I tried for MEMORY and DISK as well, this still happens.

**Comment by tomweber-sas** [comment]
No problem, you can just email that to me. tom.weber@sas.com

**Comment by michaelbestlinkit** [comment]
@tomweber-sas I've sent you an email, thanks for the support.

**Comment by tomweber-sas** [comment]
Great, thanks. And, yes I see the problem in the log. On the step where I'm trying to gather the formats, so I can convert things correctly, it's getting an SPDE specific err, so I 'm not getting the formats; thus not converting the doubles to datetimes for the ones w/ the data/time/datatime formats.

So, let me go see why exactly, and if I can deal with this this so that I can get the formats.


422        data _null_; set work._n_u_l_l_ DMT_VRZN.'DNF_VERZEKERDEN_MUTATIE'n (startobs=1 endobs=100000 obs=0 );put 'FMT_CATS=';
ERROR: The option OBS= cannot be used with the SPD Engine-only options STARTOBS= or ENDOBS= for file
       DMT_VRZN.DNF_VERZEKERDEN_MUTATIE.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Ok, I have a fix for this pushed to github. Can you pull from there to test it out? It's in the default branch, main (used to be master), so you can install from there via pip using the following command:
pip install git+https://git@github.com/sassoftware/saspy.git

**Comment by michaelbestlinkit** [comment]
I will test it today or tomorrow, I'll let you know as soon as I can whether it works now

**Comment by michaelbestlinkit** [comment]
@tomweber-sas I can confirm that the main branch converts the dates correctly. Thanks for fixing it so quickly.


I also found that calling `sas_result.head()` for data in the SPDE Engine results in the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/saspy/sasdata.py", line 218, in head
    df   = self._returnPD(code, '_head')
  File "/usr/local/lib/python3.8/dist-packages/saspy/sasdata.py", line 164, in _returnPD
    raise ValueError("Internal code execution failed: " + errorMsg)
ValueError: Internal code execution failed: ERROR: The option OBS= cannot be used with the SPD Engine-only options STARTOBS= or ENDOBS= for file 
```
I will open a new ticket for this issue.
