### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by mshin254** [sassoftware/saspy#331]
Hi,

 

I've been trying to configure the saspy package to no avail.

Due to covid, I had to move everything to virtual desktop and am trying to re-install saspy on this machine.

I used the same host/port as before, but it seems to be not working anymore.

 

The virtual machine is on window and the sas server is sitting on a unix server.

So I tried using the winiomlinux method (same as before) to configure the package and I keep getting the following error:

 

---------Error 1---------

Please enter the name of the SAS Config you wish to run. Available Configs are: ['winiomlinux', 'winlocal', 'iomcom'] winiomlinux

We failed in getConnection

An exception was thrown while receiving the requirements status from the peer.

 

SAS process has terminated unexpectedly. RC from wait was: 4294967290

SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

 

---------Error 2---------

Please enter the name of the SAS Config you wish to run. Available Configs are: ['winiomlinux', 'winlocal', 'iomcom'] winiomlinux

We failed in getConnection

The application could not log on to the server "caxxxxxx.net:8561". No server is available at that port on that machine.

 

SAS process has terminated unexpectedly. RC from wait was: 4294967290

SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

---------End--------

 

I went through the guide for past couple days and used proc iomoperate functions in SAS to grab the machine/port numbers.

Any guidance would be appreciated.

Thanks.

**Comment by tomweber-sas** [comment]
Ok, so it appears you have 3 configuration definitions in your config file: ['winiomlinux', 'winlocal', 'iomcom'] 
Can you show me them? Though I guess you're only trying the one named winiomlinux? What configuration did you have before that worked? Can you show me that. I'm guessing you are trying to connect to a workspace server using IOM? Is your client machine on the network that your workspace server is on, so it can see it? What version of saspy are you using. 
That first error I haven't seen before, but the second is straight forward that the host/port aren't right. Did you change something between those two cases? 
If a web-ex is ok, I can set that up so we can quickly see what's going on.
Tom

**Comment by mshin254** [comment]
desktop os: windows
SAS os: linux
SAS version: 9.4
SASPy version:

Can you show me them? 
winiomlinux = {'java': 'java',
                         'iomhost': 'caxxxxxx.net',
                         'iomport': 8591,
                         'omruser': xxx,
                         'omrpw': xxx}

Though I guess you're only trying the one named winiomlinux? 
yes

What configuration did you have before that worked? Can you show me that.
I used the below one exactly on the new saspy and it gives the same error as above.
winiomlinux = {'java': 'java',
                         'iomhost': 'caxxxxxx.net',
                         'iomport': yyy,
                         'encoding': 'latin1',
                         'classpath': cpW,
                         'omruser': xxx,
                         'omrpw': xxx}

I'm guessing you are trying to connect to a workspace server using IOM? Is your client machine on the network that your workspace server is on, so it can see it? 
not sure what this means. I have SAS EG on the virtual machine on windows and the SAS grid is on the unix server

What version of saspy are you using.
3.5.3

That first error I haven't seen before, but the second is straight forward that the host/port aren't right. Did you change something between those two cases?
first one I used the proxy list for the metadata server and the second one is the setting i've used before

**Comment by tomweber-sas** [comment]
Ok, that helps, thanks. So, with 3.5.3, you no longer need that classpath like you did in the old case; and you don't have it in your new config, so that's good. The first errror now makes more sense, since you were pointing at the metadata server, so no telling what kind of error that can cause. The second error is more straight forward, that there's not a listening object spawner at the host/port. Or, it is maybe that you can't get to that host from your client? Are you able to see that host address from your client? Can you access it with anything else? Do you use EG to connect to the workspace server? Is the machine you're on in the network? or do you need to be VPN'd in or anything?

**Comment by mshin254** [comment]
it is maybe that you can't get to that host from your client? 
I'm not sure. It worked before previously.

Are you able to see that host address from your client? 
I can see the host address when I use the iom operate to figure out the iomhost and iomport

Can you access it with anything else? 
I'm not sure. only thing I tried was EG and saspy

Do you use EG to connect to the workspace server?
yes, I connect to the EG using the metadata server

Is the machine you're on in the network? 
I would assume that they are on the same company network since I can access it through EG

or do you need to be VPN'd in or anything?
I don't need to VPN anything other than using my id/pw

**Comment by tomweber-sas** [comment]
ok, so you can connect w/ EG. Good, yes, I missed that in the previous post. So, when you look at the host/port for the connection to that workspace server, in EG, is it the exact same host and port? Not the profile in EG, which points at the metadata server, but the connection info for the appserver EG is connected to.

**Comment by tomweber-sas** [comment]
I don't see any output from that proc. there's nothing there.
The host/port I was asking about in EG is in the properties for the actual workspace server you are connected to. In EG, if you look at the properties of the server you're connected to (right click on it and click properties), it will show you the host and port.
![image](https://user-images.githubusercontent.com/17710182/96477793-e967df80-1204-11eb-9992-2f0259aabbf2.png)
Inthis case it says 'local', because I don't have an actual deployment to connect to. You would see something like 'SASApp Prod - Workspace Server' as the server name. The properties of that server would then show the host and port (object spawner host, workspace server port), but again, I am not connected to a real deployment so that aren't filled in like they will be for you
![image](https://user-images.githubusercontent.com/17710182/96478082-41064b00-1205-11eb-82d2-135ea035fc38.png)

**Comment by mshin254** [comment]
I see.
I used your method to get the host name and the port.
port is still the same but the host name had a different number.
I used the host/port from the properties but am still getting the same error.

We failed in get Connection.
The application could no log on to the server "caxxx###.net:port". No sever is available at that port on that machine.


---sas properties---
type: server
protocol: IOM
host name: caxxxx###.net
port: xxxx
Encription level: everything
Encryption algorithm: XXX (not sure if this is sharable)
grid launched: yes

**Comment by tomweber-sas** [comment]
Can you connect to a web-ex or teams meeting? I can provide a link, then I can maybe see what I need to help figure this out.

**Comment by mshin254** [comment]
if you can provide web-ex meeting, I think I can log on through the web application.

**Comment by tomweber-sas** [comment]
https://sas.webex.com/join/Tom.Webersas.com

**Comment by tomweber-sas** [comment]
To follow up, after working on this offline, this is currently disabled at the site, and there is some interaction already happening to see how to allow this w/in the existing security requirements of the company. I guess we can close this issue and just keep up on email as this continues?
Tom

**Comment by tomweber-sas** [comment]
Hey @mshin254, just checking to see if there's anything I can do with this? Seems your IT folks are working with someone here to see about allowing this. Do you want to keep this open, or close it until there's some kind of resolution? I don't thing there's anything I can do at this point.

Thanks,
Tom

**Comment by mshin254** [comment]
Hi Tom, 

I think we can close this issue. 
Thank you for your help.
Please keep me posted on the progress if you can.

**Comment by tomweber-sas** [comment]
Actually, I'm not aware of who, here, you're folks are 'working with'. I just saw in that one email from one of your folks that said they were already working with SAS. But it didn't say who or what they were actually doing. No one here has contacted me about this. FYI. Tom
