### ISSUE TITLE
Issue with partitioning

### ISSUE THREAD

**Issue by michaelbestlinkit** [sassoftware/saspy#345]
**Describe the bug**
We have recently found an issue with our code and want your take on why this is happening and what are the right steps to fix this. 
Currently we are pulling data from SAS, and we are doing so in chunks of 10m records, since some of these tables are quite big.

For most tables, the chunking mechanism pulls in data correctly, 10m rows at a time, and then later get aggregated into one big table in spark.
The problem occurs when we have a `where` clause in our query. We noticed recently that if there is more than one chunk, the separated data does not always get pulled in correctly, so even though we get number of rows we would expect, we get duplicate and missing rows from the original table in sas.
Looking at the logs, to me it seems the issue is that each time we are running the where statement on each chunk, we are not getting the same ordering of the data.

My question is, should we expect this?
Is this a behaviour on sas or saspys end, or are we not using saspy correctly?

And what is the right way to fix this? 
Should we be storing an intermediate table that pulls all the data at once, perhaps order it, and take chunks from that? Or is there a function in saspy that would do something like this for us?

We have been pulling chunks of 10m rows for a while. It seems that previously either our sas server or saspy did not like bigger chunks,  but it seems that now 30m rows seem to work fine. Since 30m rows is bigger than the data filtered with the where, increasing the chunk size does remove this problem. While this is a solution to our problem, we would like to if there is something faulty with our scripts.

**To Reproduce**
```
    # For one our tables, we have the following sas_query_opts
    'dsopts': {
      'where': 'VERRICHTING_SOORT_CODE in ("54", "02")',
      'keep': [
        "VERANTWOORDING_JAAR", "VERANTWOORDING_MAAND", "SCHADEREGEL_ZORGKOSTEN_TYPE_CODE", "VERRICHTING_SOORT_CODE",
        "KOSTENSOORT_CODE", "ZVL_AGB_CODE", "ZVL_NAAM", "VERRICHTING_INGANG_DTM", "VERRICHTING_EIND_DTM",
        "ZORGPRODUCT_BR", "SCHADE_UITKERINGSREGEL_ID", "VERRICHTING_SUB_CODE", "VERRICHTING_OMS",
        "UITKERINGSREGEL_UITVOER_BDG", "AANTAL_VRT_BR", "VERZEKERDE_BRN_PERSOON_ID", "VZD_POSTCODE",
        "DBC_SPECIALISME_CODE", "DBC_SPECIALISME_OMS_BR", "DOT_DIAGNOSE_CODE", "DECLARATIECODE_BR", "SCHADE_NOTA_ID",
        "IDENTIFICATIE_PRESTATIE_GEGEVEN", "VERRICHTING_GENEESMIDDEL_ID", "SOORT_DUUR_GENEESMIDDEL_CODE",
        "DURE_GNM_INDICATIE_CODE", "DBC_ZORGTYPE_CODE", "SCHADEREGEL_CATEGORIE_CODE", "SCHADE_CORRECTIE_IDC"
      ]
    }

    def _determine_chunks(total_rows: int) -> (int, int):
        chunk_size = int(10 * 10 ** 6)
        if total_rows < chunk_size:
            chunk_size = total_rows
            chunks = 1
        else:
            chunks = int(total_rows // chunk_size) + 1
        return chunks, chunk_size

    def get_sas_data(self, i: int, chunk_size: int, table: str, **sas_query_opts: object) -> saspy.SASdata:
        dsopts = None
        offset = ((i * chunk_size) + 1)
        endobs = ((i + 1) * chunk_size)
        if self.engine == 'BASE':
            dsopts = {'firstobs': offset, 'obs': endobs, **sas_query_opts}
        elif self.engine == 'SPDE':
            dsopts = {'startobs': offset, 'endobs': endobs, **sas_query_opts}
        else:
            print('Invalid sas_engine format specified, exiting')
            raise KeyError
        result = self.sas_session.sasdata(table=table, libref=self.libref, dsopts=dsopts)
        try:
            result.contents()
        except ValueError as E:
            print(f"Tried to load table from SAS. Error: {str(E)}")
            raise ConnectionError
        return result

    def extract_table(self, table, parquet_engine, output_path, sas_query_opts):
        total_rows = self.sas_session.sasdata(table=table, libref=self.libref).obs()
        chunks, chunk_size = self._determine_chunks(total_rows) # This returns the number of chunks that we will need, the          chunk size is either a specified size, or the total number of rows if the total is smaller than the chunk size.
        for i in range(chunks):
            result = self.get_sas_data(i, chunk_size, table, **sas_query_opts)
            tmp = self.sas_to_pandas(result)
            self.export_file(tmp, output_file, parquet_engine)
```

Running the `extract_table` function for our table with where results in three parquet files. 

**Expected behavior**
I would expect to get a table without repeated values, meaning I wouldn't have worried about the ordering of the data.

OS: Ubuntu 18.04
Access Method         = IOM
SAS Config name       = iomwin
SAS Config file       = /usr/local/airflow/.config/saspy/sascfg_personal.py
WORK Path             = F:\SASWork\_TD117224_APP0844_\Prc2\
SAS Version           = 9.04.01M1P12042013
SASPy Version         = 3.6.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = windows-1252
SAS process Pid value = 117224

**Additional context**
The data that I'm trying to read is a view of another table. 
I've sent you by email the log files from what I've run.

**Comment by tomweber-sas** [comment]
Hey @michaelbestlinkit, yes, this is disconcerting. I also got your email with the logs; thanks so much for that, it really helps!
I have played with this a bit and I do see what is happening. The where clause is being applied (by SAS) prior to the fisrobs/obs. So, that would really cause lots of duplicates, and not be correct at all for what you are trying to accomplish. I tried this using the where statement, in the datastep, rather than the where= data set option, to see if the obs options would be applied first in that case, then the where= subordinate to that, since it's a statement in the datastep , not a data set option. That didn't change the behavior, unfortunately.

One quick thing that you can do to make this work correctly, for what you're trying to do, is create a view with the obs options, and then use that as your data set with the where= data set option. Just recreate the view with the firstobs/obs for each chunck (creating a view doesn't take any time or resources, it's just a logical thing), and then apply the where and keep dsopts to that table for the extract. Here's some psuedo code for that, which I'm not 100% sure is exactly right, for you code, but I think you'll get the gist.
```
below I changed/ added these:
            dsopts = '(firstobs={} obs={})'.format(offset, endobs)
            dsopts = '(startobs={} endobs={}_..format(offset, endobs)
        ll = sas.submit("data chunck / view=chunk; set {}.{} {};run;".format(
             self.libref, table, dsopts))
        result = self.sas_session.sasdata(table=chunk,                      dsopts=**sas_query_opts)

the idea is to create a view with the obs options, then assign your SASdata object to that, with the where= and keep=
applied to it (subordinate to the obs values), then you should be getting the correct rows from each chunk.


    def get_sas_data(self, i: int, chunk_size: int, table: str, **sas_query_opts: object) -> saspy.SASdata:
        dsopts = None
        offset = ((i * chunk_size) + 1)
        endobs = ((i + 1) * chunk_size)
        if self.engine == 'BASE':

            dsopts = '(firstobs={} obs={})'.format(offset, endobs)
            #dsopts = {'firstobs': offset, 'obs': endobs, **sas_query_opts}
        elif self.engine == 'SPDE':

            dsopts = '(startobs={} endobs={})'.format(offset, endobs)
            #dsopts = {'startobs': offset, 'endobs': endobs, **sas_query_opts}
        else:
            print('Invalid sas_engine format specified, exiting')
            raise KeyError

        ll = sas.submit("data chunck / view=chunk; set {}.{} {};run;".format(
             self.libref, table, dsopts))
        result = self.sas_session.sasdata(table=chunk,                      dsopts=**sas_query_opts)
        #result = self.sas_session.sasdata(table=table, libref=self.libref, dsopts=dsopts)
        try:
            result.contents()
        except ValueError as E:
            print(f"Tried to load table from SAS. Error: {str(E)}")
            raise ConnectionError

```
Again, I haven't run this, so there might be some syntax error, and I'm not 100% sure of the 'dsopts=**sas_query_opts' part being correct; that should be adding the where=and keep=, so if that' snot exactly right, at least you know what it's supposed to be.

Let me know if that all makes sense and if my solution works. Here's the bit of code I was trying, to see this happening, just FYI:
```
data a; do x=1 to 100; y = mod(x,10);output;end;run;
proc print data=a (firstobs=1 obs=10 where=(y=0));run;


data b/view=b;set a(firstobs=1 obs=10);run;
data chunk / view=chunk; set b(where=(y=0));run;
proc print data=chunk;run;


proc print data=a (firstobs=1 obs=10 where=(y=0));run;
proc print data=b (firstobs=1 obs=10 where=(y=0));run;
proc print data=b (                  where=(y=0));run;
```

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Well, coming back to this, the better answer, I missed yesterday, would be for you to just have the where clause applied in the dsopts when you run the .obs() method to get the number of rows. This way your 'relative obs numbers' for each chuck would be relative to the result set of the where clause. That would be the real answer to this. I think you're just missing that one thing and what you have would be correct. Would it just be as simple as this change to your code (haven't run it to see, but this would be the idea; might need other tweaks to the code other than just this):
```
    def extract_table(self, table, parquet_engine, output_path, sas_query_opts):
        total_rows = self.sas_session.sasdata(table=table, libref=self.libref, dsopts=sas_quey_opts).obs()
        #total_rows = self.sas_session.sasdata(table=table, libref=self.libref).obs()
```
With the example code I had above, there were 100 rows in the table but 10 rows w/ the where applied. So you would be chunking 10 rows not 100 and it would be the right result you're looking for.

Should have seen this to begin with. Should be a simple fix to the code you have.
Tom

**Comment by michaelbestlinkit** [comment]
Hi @tomweber-sas. Thanks for the support. So far we have tested a mix of both of your recommendations. 
We are looking at using the following code, it's a mix of our code, we've changed it so that we write to a temp view in work since that is the only place we have write permissions.

```
    #sas_query_opts has where and keep statements
    def extract_table(self, table, parquet_engine, output_path, sas_query_opts):
        # If 'where' is not in sas_query_opts, return 1 ("True"  in SAS); and remove the 'where' key
        where = sas_query_opts.get('where', 1)
        sas_query_opts.pop('where', None)

        # If 'keep' is not in sas_query_opts, return an empty list; and remove the 'keep' key
        keep = sas_query_opts.get('keep', [])
        sas_query_opts.pop('keep', None)

        temp_lib = "WORK"
        temp_view = "table_view"

        # Create a view that subsets the data according to the where/keep statements
        query = f"data {temp_lib}.{temp_view}/view={temp_lib}.{temp_view}; " \
                f"set {self.libref}.{table}(where=({where}) keep={' '.join(keep)}); run;"
        view = self.sas_session.submit(query)
        total_rows = self.sas_session.sasdata(table=temp_view, libref=temp_lib).obs()
        chunks, chunk_size = self._determine_chunks(total_rows)

        for i in range(chunks):
           # For each chunk, get data
            result = self.get_sas_data(i, chunk_size, temp_view, temp_lib, **sas_query_opts)
            tmp = self.sas_to_pandas(result)
```

This seems to work so fine with the tests we have run, we still want to try it on some more tables and see what happens. I'll update you when we have made a final decision on this.

**Comment by tomweber-sas** [comment]
Hey, I'm going to close this out. It's figured out and you have a couple ways to code things to work as expected. Basically, obs numbers are relative to the post where clause result set, not the pre where clause data. If you need anything else , on this or anything, just reopen this or create a new one!
Thanks,
Tom
