### ISSUE TITLE
Having an issue running sas1 =saspy.SASsession() 

### ISSUE THREAD

**Issue by khsruns** [sassoftware/saspy#349]
I'm trying to run sas1 =saspy.SASsession() and have it start a local SAS session. I've set the following in the sascfg_personal.py file:

default  = {'saspath'  : 'C:\\Program Files\\SASHome\\SASFoundation\\9.4\\'
            }
and am getting this error:

Using SAS Config named: default
---------------------------------------------------------------------------
SASIONotSupportedError                    Traceback (most recent call last)
<ipython-input-4-fa67af7fae98> in <module>
----> 1 sas1 =saspy.SASsession()

~\Anaconda3\lib\site-packages\saspy\sasbase.py in __init__(self, **kwargs)
    493                 self._io = SASsessionSTDIO(sascfgname=self.sascfg.name, sb=self, **kwargs)
    494             else:
--> 495                 raise SASIONotSupportedError(self.sascfg.mode, alts=['IOM'])
    496         elif self.sascfg.mode == 'IOM':
    497             self._io = SASsessionIOM(sascfgname=self.sascfg.name, sb=self, **kwargs)

SASIONotSupportedError: Cannot use STDIO I/O module on Windows. Try the following: IOM

Not sure what I'm doing wrong.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SAS Version: 9.4M6
 - SASPy Version: 3.6.1

**Comment by tomweber-sas** [comment]
Hey, no problem. This is because on a windows client, you need to use the IOM access method, not STDIO. You'll need java and just a little different configuration. See the IOM doc here, and specifically the 'Local' section since SAS is on that same windows machine as your Python process: https://sassoftware.github.io/saspy/install.html#local
Give that a try and if you have any issues, just post back. I'll keep this open till I hear back from you :)
Tom

**Comment by khsruns** [comment]
That’s where I’m a little confused.  I set the following:

winlocal = {'java'      : 'C:\\Program Files (x86)\\Java\\jre1.8.0_271\\bin\\java.exe',
            'encoding'  : 'windows-1252',
            }

but still get the same error.

**Comment by tomweber-sas** [comment]
Ah, then it's not picking up that change. So, it's not finding the sascfg_personal.py you coded that in. Did you read this section? : https://sassoftware.github.io/saspy/install.html#sascfg-personal-py

You can run this code to see what config file is being used, and what configs are in the paths it searches.
```
>>> import saspy
>>> saspy.SAScfg
'/opt/tom/github/saspy/saspy/sascfg_personal.py'
>>> saspy.list_configs()
['/opt/tom/github/saspy/saspy/sascfg_personal.py', '/r/sanyo.unx.sas.com/vol/vol810/u81/sastpw/.config/saspy/sascfg_personal.py']
>>>
```
That's on Linux, but you'll see the windows paths you have. I would get this file right and have it in the correct path, but you can actually specify the file itself, if you don't have it in a place it's already found (that doc tells you where). And, you can actually override any of these config options on the SASsession() method too, so you can just specify them there to see if it's working. The other thing is having the sspiauth.dll path (again, in the doc provided earlier). 

```
sas = saspy.SASsession(cfgfile='path to your sascfg_personal.pyfile')

sas = saspy.SASsession(java='C:\\Program Files (x86)\\Java\\jre1.8.0_271\\bin\\java.exe',  encoding = 'windows-1252', ...)
```

**Comment by khsruns** [comment]
I reread https://sassoftware.github.io/saspy/install.html#sascfg-personal-py which helped.  I also found that I needed to restart Jupiter Notebook so it recognized the updates to sascfg_person.py.  I have it working now.  Thanks.

**Comment by tomweber-sas** [comment]
That's great, glad that's all it was. And, yes, once a module is imported, changing the file on disk won't affect what's already loaded in the existing process, so restarting is the thing to do. I'll close this, but just let me know if you need anything else!
Thanks,
Tom
