### ISSUE TITLE
IOM connection to SAS fails with the following error:

### ISSUE THREAD

**Issue by GarrettAllred** [sassoftware/saspy#35]
None of the requested encryption algorithms are supported by both peers: AES
SAS process has terminated unexpectedly. RC from wait was: 4294967290
SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

Fix:
Add the following entries to your sascfg.py file. They point to the jar files that contain the client side encryption support:
cpW += ";C:\Program Files\SASHome\SASVersionedJarRepository\eclipse\plugins\sas.rutil_904400.1.0.20160824190000_v940m4\sas.rutil.nls.jar"

cpW += ";C:\Program Files\SASHome\SASVersionedJarRepository\eclipse\plugins\sas.rutil_904400.1.0.20160824190000_v940m4\sas.rutil.jar"

cpW += ";C:\Program Files\SASHome\SASVersionedJarRepository\eclipse\plugins\sastpj.rutil_6.1.0.0_SAS_20121211183517\sastpj.rutil.jar"

**Comment by jld23** [comment]
@GarrettAllred I don't see a copy of the error in your text. Can you add it and then we can try and help you resolve the issue.

**Comment by tomweber-sas** [comment]
Good job tracking that down. I will add this to the config doc and the sascfg.py templates. Thanks @GarrettAllred !

**Comment by tomweber-sas** [comment]
I have added the information about adding these jars to your classpath when using encryption with IOM to both the configuration doc, and in the templates in sascfg.py.
Going ahead and closing.
Tom
