### ISSUE TITLE
The application could not create a tunnel to the server "127.0.0.1:55517".

### ISSUE THREAD

**Issue by yabwon** [sassoftware/saspy#354]
**Describe the bug**
After downloading  and setting up latest SASpy (3.3.7) attempt to connect to the local SAS (9.4M6) returns the following error:

~~~~
We failed in getConnection
The application could not create a tunnel to the server "127.0.0.1:55517".
SAS process has terminated unexpectedly. RC from wait was: 4294967290
~~~~

Even tough the connection is not setup, the SAS session is started (what can be checked in the Task Manager).

The `[C:\...\]sas.exe /regserver` was executed too.

Thanks in advance for help. Details are below.

**The code executed in Python:**

~~~~
import os
#print(os.environ["PATH"])
os.environ["PATH"] += "C:\\Program Files\\SASHome\\SASFoundation\\9.4\\core\\sasext;"
print(os.environ["PATH"])

import saspy

saspy

sas = saspy.SASsession(cfgname='winlocal')
~~~~

**The Python's log is:**

~~~~
import os
#print(os.environ["PATH"])
os.environ["PATH"] += "C:\\Program Files\\SASHome\\SASFoundation\\9.4\\core\\sasext;"
print(os.environ["PATH"])

import saspy

saspy

sas = saspy.SASsession(cfgname='winlocal')
C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Oracle\Product\12.2.0.1\Client\jdk\bin;C:\oracle\product\12.2.0.1\client\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\MicroStrategy\Desktop\DataServices\180_77\64-bit\bin\server;C:\Program Files (x86)\SSH Communications Security\SSH Tectia\SSH Tectia AUX;C:\Program Files (x86)\SSH Communications Security\SSH Tectia\SSH Tectia AUX\Support binaries;C:\Program Files (x86)\SSH Communications Security\SSH Tectia\SSH Tectia Broker;C:\Program Files (x86)\SSH Communications Security\SSH Tectia\SSH Tectia Client;C:\ProgramData\Oracle\Java\javapath;C:\windows\SysWOW64\;C:\windows\SysWOW64\Wbem;C:\windows\SysWOW64\WindowsPowerShell\v1.0;C:\Program Files (x86)\Common Files\ThinPrint;C:\Program Files\Common Files\ThinPrint;C:\Program Files\MiKTeX 2.9\miktex\bin\x64;C:\Program Files\SASHome\SASFoundation\9.4\core\sasexe;C:\Program Files\SASHome\SASFoundation\9.4\ets\sasexe;C:\Program Files\SASHome\Secure\ccme4;C:\Program Files\SASHome\x86\SASFoundation\9.4\ets\sasexe;C:\Program Files\SASHome\x86\Secure\ccme4;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Common Files\ThinPrint\;C:\Users\bj22705\AppData\Local\Microsoft\WindowsApps;C:\Program Files\SASHome\SASFoundation\9.4\core\sasext;
We failed in getConnection
The application could not create a tunnel to the server "127.0.0.1:55517".
SAS process has terminated unexpectedly. RC from wait was: 4294967290
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\iomclient\\sas.svc.connection.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\iomclient\\log4j.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\iomclient\\sas.security.sspi.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\iomclient\\sas.core.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-internal-api.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-omgapi.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-orb.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\pfl-basic.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\pfl-tf.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil_904600.0.0.20181017190000_v940m6\\sas.rutil.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil.nls_904600.0.0.20181017190000_v940m6\\sas.rutil.nls.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sastpj.rutil_6.1.2.0_SAS_20180917093823\\sastpj.rutil.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '55501', '-stdoutport', '55502', '-stderrport', '55503', '-zero', '-lrecl', '1048576', '']

Be sure the path to sspiauth.dll is in your System PATH

No SAS process attached. SAS process has terminated unexpectedly.
Invalid response from SAS on inital submission. printing the SASLOG as diagnostic

Traceback (most recent call last):

  File "<ipython-input-1-1049c4baf857>", line 10, in <module>
    sas = saspy.SASsession(cfgname='winlocal')

  File "C:\ProgramData\Anaconda3\lib\site-packages\saspy\sasbase.py", line 527, in __init__
    pyenc = sas_encoding_mapping[self.sascei]

KeyError: 'No SAS process attached. SAS process has terminated unexpectedly.'

~~~~

**The `sascfg_personal.py` file is:**

~~~~
SAS_config_names=['winlocal']

SAS_config_options = {'lock_down': False,
                      'verbose'  : True,
                      'prompt'   : True
                     }
SAS_output_options = {'output' : 'html5'}


# build out a local classpath variable to use below for Windows clients   CHANGE THE PATHS TO BE CORRECT FOR YOUR INSTALLATION
cpW  =  "C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\iomclient\\sas.svc.connection.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\iomclient\\log4j.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\iomclient\\sas.security.sspi.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\iomclient\\sas.core.jar"

# These jars provide CORBA support for Java 10+ which no longer provides CORBA itself.  CHANGE THE PATHS TO BE CORRECT FOR YOUR INSTALLATION
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-internal-api.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-omgapi.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-orb.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\pfl-basic.jar"
cpW += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\thirdparty\\pfl-tf.jar"

# And, if you've configured IOM to use Encryption, you need these client side jars.  CHANGE THE PATHS TO BE CORRECT FOR YOUR INSTALLATION
cpW += ";C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil_904600.0.0.20181017190000_v940m6\\sas.rutil.jar"
cpW += ";C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil.nls_904600.0.0.20181017190000_v940m6\\sas.rutil.nls.jar"
cpW += ";C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sastpj.rutil_6.1.2.0_SAS_20180917093823\\sastpj.rutil.jar"

winlocal = {'saspath'   : 'C:\\Program Files\\SASHome\\SASFoundation\\9.4',
            'java'      : 'java',
            'encoding'  : 'utf-8',
            'autoexec'  : 'C:\\SAS_WORK\\autoexec.sas',
            'classpath' : cpW
            }

~~~~

**Desktop:**
 - OS: Microsoft Windows [Version 10.0.17763.1577]
 - SAS Version: 9.4M6
 - SASPy Version: 3.3.7
 - Java Version: 1.8.0_261, Java(TM) SE Runtime Environment (build 1.8.0_261-b12), Java HotSpot(TM) Client VM (build 25.261-b12, mixed mode)
 - Python Version: 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
 - IPython Version: 7.4.0

**Comment by tomweber-sas** [comment]
Hey Bart, first let me say great job providing me info I need to help you! Second, I don't recall seeing that specific IOM error message before, so I don't know the answer just yet. There are a few things that aren't quite right, or aren't necessary, so let's first eliminate those; I don't really expect a change, but ...

In your configuration definition, 'saspath' isn't valid for IOM, though it ought to be ignored. The 'autoexec' option doesn't take a file (it isn't a replacement for SAS's actual autoexec), but rather a string of code to be submitted automatically for you after the session is established (and SAS has already processed it's autoexec file). So, you could simply change it to:
```
'autoexec'  : "%include 'C:\\SAS_WORK\\autoexec.sas';",
```
And, since V3.3.3 (I think) the classpath has no longer been been necessary. I was finally allowed to include the jars in the saspy repo (which is where you're pointing at them), and saspy will build that out itself. So you don't need any of that in your config file. Since you're using a local connection, you wouldn't need the encryption jars either. So, first thing I'd like to try to to clean that up and see what happens. None of those things seem like they would cause this error, but let's eliminate them anyway.

Can you just change your config def to this and let's see what we see.
```
winlocal = {'java'      : 'java',
            'encoding'  : 'utf-8',
            'autoexec'  : "%include 'C:\\SAS_WORK\\autoexec.sas';",
            }
```
Thanks!
Tom

**Comment by tomweber-sas** [comment]
Assuming none of these 'clean up' changes make a difference. My next thought would go to things like your /ect/hosts file and what localhost and or 127.0.0.1 are set to or if there's some kind of network redirect going on. Like I said, I haven't seen this exact IOM error, but it's right in line with some others documented here: https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors
If fact, when we figure this one out, I 'll add it to that list :) But, lets see what happens with the changes above, and then go down the next path after that, in case something changes.

Thanks,
Tom

**Comment by yabwon** [comment]
I used exactly this:

~~~~
winlocal = {'java'      : 'java',
            'encoding'  : 'utf-8',
            'autoexec'  : "%include 'C:\\SAS_WORK\\autoexec.sas';",
            }
~~~~

and the output and errors didn't change a bit.

I'll check the `hosts` file and will let you know.

Bart

**Comment by yabwon** [comment]
Adding:

~~~~
127.0.0.1 localhost
~~~~

the `hosts` file didn't help too...

B

**Comment by tomweber-sas** [comment]
Ok, so next would be checking what's in your registry as the start up command that IOM is trying to use. Number 5 in that list of IOM errors has the info, though I know that' snot the error you're getting. It could be that what is actually trying to be started isn't really sas.exe with the right parms. Can you check what's in your registry for the following key:
from the doc:
If you get this error: The application could not log on to the server. The server process did not start. And you have what seems to be the correct start up command in your registry; key=HKEY_CLASSES_ROOTCLSID{440196D4-90F0-11D0-9F41-00A024BB830C}LocalServer32. 

If you're open to a web-ex or teams meeting, let me know, Maybe I can see something that's not apparent?
Tom

**Comment by yabwon** [comment]
The `[C:\...\]sas.exe /regserver` was one of the first executed.

**Comment by tomweber-sas** [comment]
And the contents of that key? To be sure it did what it was supposed to do?

**Comment by yabwon** [comment]
```
C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE -config C:\PROGRA~1\SASHome\SASFOU~1\9.4\sasv9.cfg -objectserver -nologo -noterminal -noprngetlist
```

**Comment by tomweber-sas** [comment]
thanks, yeah, that looks right. So, what happens when you double click a .sas file? That should be doing the same thing as what I'm doing (or close enough); trying to fire up SAS via IOM using that command.

**Comment by yabwon** [comment]
it opens SAS EG (I have it too) with the code

**Comment by tomweber-sas** [comment]
Well, that's the kind of thing this registry deal is about. So, it's windows, maybe you have to reboot a couple times :)

The command you showed above says it should be starting SAS, not EG. So, the next thing to try, would be the workaround for that problem (number4/5) which is to add the command to use to the javaparms config option. Lets try that and see if that works, then we can figure out what the deal is with you having SAS as the registry command, but it using EG.

Try adding the following to your config:
```
'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd="C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE -config C:\PROGRA~1\SASHome\SASFOU~1\9.4\sasv9.cfg -objectserver -nologo -noterminal -noprngetlist']
```
Tom

**Comment by tomweber-sas** [comment]
You know, I may be off base with that registry key being EG or SAS. I'm not 100% on that. The default app to open a filetype may be independent of that key. But, trying the javaparms is still something to see.

**Comment by yabwon** [comment]
After adding this line to the `sascfg_personal.py` the error in Python's log (console) went to:

```
Java Error:
log4j:WARN No appenders could be found for logger (com.sas.services.connection).
log4j:WARN Please initialize the log4j system properly.
com.sas.services.connection.FatalConnectionFactoryException: The application could not log on to the server. The server process did not start.
        at com.sas.services.connection.ClusterEnvelope.getConnection(ClusterEnvelope.java:248)
        at com.sas.services.connection.AggregationKernel.doGetConnection(AggregationKernel.java:242)
        at com.sas.services.connection.ConnectionFactoryKernel.getConnection(ConnectionFactoryKernel.java:325)
        at com.sas.services.connection.ConnectionFactoryShell.getConnection(ConnectionFactoryShell.java:69)
        at com.sas.services.connection.ConnectionFactoryShell.getConnection(ConnectionFactoryShell.java:51)
        at pyiom.saspy2j.main(saspy2j.java:198)
Caused by: org.omg.CORBA.COMM_FAILURE: The application could not log on to the server. The server process did not start.  vmcid: 0x0  minor code: 0  completed: No
        at com.sas.iom.orb.brg.Engine.flowLaunchServer(Engine.java:3058)
        at com.sas.iom.orb.brg.Engine.flow(Engine.java:711)
        at com.sas.iom.orb.brg.Engine.initClient(Engine.java:676)
        at com.sas.iom.orb.brg.ORBImpl.uri_to_object(ORBImpl.java:114)
        at com.sas.services.connection.ClusterEnvelope.createObject(ClusterEnvelope.java:394)
        at com.sas.services.connection.ClusterEnvelope.getConnection(ClusterEnvelope.java:86)
5 more
Caused by: java.io.IOException: Cannot run program "C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE -config C:\PROGRA~1\SASHome\SASFOU~1\9.4\sasv9.cfg -objectserver -nologo -noterminal -noprngetlist -nologo -noterminal -noxcmd -objectserver -objectserverparms protocol=bridge": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.sas.iom.orb.brg.Engine.flowLaunchServer(Engine.java:3036)
10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
14 more

We failed in getConnection
The application could not log on to the server. The server process did not start.
```

That is very strange, because the command: `C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE -config C:\PROGRA~1\SASHome\SASFOU~1\9.4\sasv9.cfg` run on `CMD` starts sas perfectly well.

**Comment by tomweber-sas** [comment]
Ug, missing a quote in there; that's my bad. Need the double quote after sas.exe. I got the same error and it worked w/ the trailing " to wrap the command correctly.

```
'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd="C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE" -config C:\PROGRA~1\SASHome\SASFOU~1\9.4\sasv9.cfg -objectserver -nologo -noterminal -noprngetlist']
```

**Comment by yabwon** [comment]
Adding the `''` did help, but the "tuneling" error is still here... it only changed from `... "127.0.0.1:55517"` to `..."127.0.0.1:63163"`

**Comment by tomweber-sas** [comment]
Yeah, ok. That confirms the registry entry; same thing and same problem. I would expect the port number to change each time, as it's an ephemeral port it's getting. Makes me wonder if there some firewall or something constraining the connection to the port. I'm surprised at the error talking about tunneling. Do you have firewall software running on your pc? I'm wondering if something like that could be causing the problem. 

Googled a little on the port range and the first thing would be to see your port range (I have to think a port you get is in the range). This following command shows the range on Win. See what this shows for you.

And see if you have a firewall turned on. If so, can you try turning it off and trying this to see if that's causing the error? I'll ping Tech Support here to see if they have other ideas about this error. I only see one hit on it and it's not helpful. 

Unfortunately, it appears everything you have set up is right. So it seems like something else getting in the way. I just haven't seen this one before.
```
U:\tkpython2>netsh int ipv4 show dynamicport tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 49152
Number of Ports : 16384


U:\tkpython2>python
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 49152+16384
65536
>>>
```

**Comment by yabwon** [comment]
My output for the `netsh int ipv4 show dynamicport tcp` is the same.

Output for `netsh firewall show state` is:

```
Firewall status:
-------------------------------------------------------------------
Profile                           = Domain
Operational mode                  = Disable
Exception mode                    = Enable
Multicast/broadcast response mode = Enable
Notification mode                 = Enable
Group policy version              = Windows Defender Firewall
Remote admin mode                 = Enable

Ports currently open on all network interfaces:
Port   Protocol  Version  Program
-------------------------------------------------------------------
27472  TCP       Any      (null)
32111  TCP       Any      (null)

IMPORTANT: Command executed successfully.
However, "netsh firewall" is deprecated;
use "netsh advfirewall firewall" instead.
For more information on using "netsh advfirewall firewall" commands
instead of "netsh firewall", see KB article 947709
at https://go.microsoft.com/fwlink/?linkid=121488
```

**Comment by tomweber-sas** [comment]
Thanks. I've emailed a contact w/ Tech Support who knows way more about IOM and it's errors than I do. Hoping he has an idea. So does that show that there isn't a firewall (Operation mode = Disable), if effect? Or just not one that command knows about? I'm not familiar with that command; nor the other, just googled it to see how to get the port range on windows. I'm better on Linux.

**Comment by yabwon** [comment]
Don't know what does it mean... I'm not good on networks and firewalls...

**Comment by tomweber-sas** [comment]
Well, I heard back from TS, and they hadn't heard of this happening in this environment before. But, here's his comments:

"I wouldn’t rule out Windows firewall. I’d also check if they have SAS_IOM_PROXYLIST environment variable set on that machine as well. Maybe they are using http tunneling for other remote SAS servers and it is affecting the local connection?"

So, can you check, or do you know, if you have that SAS_IOM_PROXYLIST environment variable set? And again, see if windows firewall or some other firewall is running? Do you have an IT dept or sys admin who would be able to look into this on your system? This isn't a usual error and you have everything set up right, as far as I can tell. something's blocking or redirecting the connection, even though it's a local internal connection.

**Comment by tomweber-sas** [comment]
Hey, well, this is maybe getting close. I was able to create that error by setting that:

```
>>> os.environ['SAS_IOM_PROXYLIST']='https://www.sas.com'
>>> os.environ['SAS_IOM_PROXYLIST']
'https://www.sas.com'
>>>
>>> import saspy; sas = saspy.SASsession(cfgname='winlocal'); sas
We failed in getConnection
The application could not create a tunnel to the server "127.0.0.1:54243".
SAS process has terminated unexpectedly. RC from wait was: 4294967290



>>> del(os.environ['SAS_IOM_PROXYLIST'])
>>> os.environ['SAS_IOM_PROXYLIST']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'SAS_IOM_PROXYLIST'
>>> import saspy; sas = saspy.SASsession(cfgname='winlocal'); sas
SAS Connection established. Subprocess id is 37100

Access Method         = IOM
SAS Config name       = winlocal
SAS Config file       = C:\ProgramData\Anaconda3\lib\site-packages\saspy\sascfg_personal.py
WORK Path             = C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD17980_d10a626_\Prc2\
SAS Version           = 9.04.01M5P09132017
SASPy Version         = 3.6.2
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = cp1252
SAS process Pid value = 17980


>>>
```

**Comment by yabwon** [comment]
You nailed it! Thank you!

**Comment by yabwon** [comment]
I think it looks like nice example for `IOM specific errors` number 7 :-)

**Comment by tomweber-sas** [comment]
For sure. And yes, definitely number 7 in the troubleshooting guide!

Assuming you need that for other cases, just adding 

import os
del(os.environ['SAS_IOM_PROXYLIST'])

into your sascfg_personal.py, along with this so it';s there automatically
os.environ["PATH"] += "C:\\Program Files\\SASHome\\SASFoundation\\9.4\\core\\sasext;"

will make this work w/ saspy, but not keep you from having problem with whatever you needed it for, and it will be automatic when you bring up saspy.

Gotta shout out to our TS folks, as they figured this one out!

Thanks for stick with me on this trying to figure it out!
Tom

**Comment by yabwon** [comment]
Thanks for help, solution, and possibility to learn something new!

All the best
Bart

**Comment by tomweber-sas** [comment]
Me too - learning something new. Always the goal :)
I've updated the doc, you can see number 7 out there now, and I'll go ahead and close this.

Let me know if you need anything else!
Tom
