### ISSUE TITLE
SASPY on Google Colab 

### ISSUE THREAD

**Issue by johnbde** [sassoftware/saspy#357]
I am trying to run sas on Google Colab. I am using the following code -
```
import saspy
saspy.SAScfg
saspy.list_configs()

```
sas = saspy.SASsession(cfgfile='/usr/local/lib/python3.6/dist-packages/saspy/sascfg.py')
 
 It throws this error - 
Using SAS Config named: default The OS Error was: No such file or directory SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file. Attempted to run program /opt/sasinside/SASHome/SASFoundation/9.4/bin/sas_u8 with the following parameters:['/opt/sasinside/SASHome/SASFoundation/9.4/bin/sas_u8', '-nodms', '-stdio', '-terminal', '-nosyntaxcheck', '-pagesize', 'MAX', '']

I tried this solution #305   but not sure about the config.
 
What's iomhost and iomport here? I am running on my laptop and don't have access to any server. Can it still be possible? 
`sas = saspy.SASsession(java='/usr/bin/java', iomhost=host, iomport=8591)
`

**Comment by tomweber-sas** [comment]
Hey, so where are you running Colab? In the cloud or on your own machine? Where is the SAS you are trying to connect to? Have you looked at the configuration instructions, which are how you tell saspy where SAS is and how to connect to it? https://sassoftware.github.io/saspy/install.html#configuration

I can help you get going, assuming you can get to SAS from where you're running. 
Thanks,
Tom

**Comment by johnbde** [comment]
I'm running colab in cloud. I'm trying to run SAS in the colab in cloud. SAS isn't installed on my machine. Is it the problem? Can it connect to SAS Cloud for Academics? I've included configuration code in the post

**Comment by tomweber-sas** [comment]
So, yes, you have to have some SAS deployment somewhere to connect to. You can use saspy to connect to SAS On Demand for Academics (is that what you mean by SAS Studio for Academics?). There's some basic doc for that here: https://support.sas.com/ondemand/saspy.html and, of course, the real saspy doc has more details (there's a link to that in there).
You have to configure saspy so it knows where SAS is, what kind of deployment and how to connect to it. That's all in the config doc,  but the simple instructions are the link above.
So, as long as you can get at the On Demand hosts from wherever you're running (you aren't locked down behind some firewall), then you can connect to those SAS workspace servers in that environment from saspy.
Do you already have an account for ODA?
