### ISSUE TITLE
unable to establish connection with SAS Grid from Linux box

### ISSUE THREAD

**Issue by simontao01** [sassoftware/saspy#362]
I used the same IOM configuration/credential and IOM host:8591 as of successfully running from local Windows to connect with SAS Grid, but failed if run from Linux box after installing saspy. The error is weird, the same IOM host doesn't exist on SAS Grid - is this caused by the Java files within saspy or needs to install client SAS on Linux box?

**Comment by tomweber-sas** [comment]
I'm going to need to see more info to know the answer. Can you show me your configurations and show me the code being run with the output/error it produces?

**Comment by simontao01** [comment]
Could you send to my work email: zhu.yong.tao@citi.com, we cannot send what you require to personal email, thanks.

Best regards,

Simon

________________________________

**Comment by tomweber-sas** [comment]
This turned out to be a proxy issue. The Grid has a proxy server you have to go through to get to it. This had been set up on windows by IT but nothing was done on the linux machine. We tracked it down and set it up on linux and now it connects as expected. The proxy SAS doc is here, for reference: https://go.documentation.sas.com/?cdcId=bicdc&cdcVersion=9.4&docsetId=bisecag&docsetTarget=p0tbh3vv7cetrbn1jw6fhxb8hp9r.htm&locale=en
So, this one is resolved :)
Tom

**Comment by simontao01** [comment]
Hi Tom,

Thanks for your kind help to solve the connection issue. One more question for running saspy is the SASsession() sounds continue to run after SAS script run through, the icon on Jupyter Notebook and PyCharm display still running without ending, but it doesn't end after I add sasend() after SASsession() as online said, do you know how to do to end the SAS process?

import saspy
SAS =SASsession()

demo = SAS.submit(''' SAS script''')

endsas()



Best regards,

Simon

________________________________

**Comment by tomweber-sas** [comment]
Just from looking at what you have below, you didn't use the endsas() method from the SASsession object.

SAS.endsas()  # is the endsas method of saspy

endsas() # is a non-existant method - didn't this give an error that it didn't know what this method was?

**Comment by simontao01** [comment]
Yes, I think you are right, it's method of SAS session, thanks.

Best regards,

Simon

________________________________

**Comment by simontao01** [comment]
Hi Tom,

Do you think we can connect using STDIO SSH to SAS Grid on Linux system from our Linux box? Thanks.

Best regards,

Simon

________________________________

**Comment by tomweber-sas** [comment]
Well, STDIO over SSH can connect to SAS on another Linux machine. So yes. Now whether you have access to do so, and whether or not your IT folks want you doing that is another thing, or two. That has nothing to so with saspy. But, if you can, you will be just starting up your own SAS sessions form the SAS deployment on those machines. not connecting to the defined Workspace servers, and bypassing any of the Grid infrastructure and policies that are in place for that whole system. I think we talked about this on the phone, if I'm remembering right.

**Comment by simontao01** [comment]
Oh, directly turn around saspy is not my job, that's for IT guy. What I've seen within saspy there also has STDIO over SSH access method available, I wonder maybe I can try that one because my manager wants to use Functional/team ID instead of my personal ID and password, I found STDIO works with passwordless SSH, and SAS Grid is set up on Linux system...

Best regards,

Simon

________________________________

**Comment by tomweber-sas** [comment]
Yes, if you have passwordless ssh access to the machine where SAS is installed, then it will work. That's what it's designed for.
