### ISSUE TITLE
Not able to connect to SAS from Jupyter notebook

### ISSUE THREAD

**Issue by budigi369** [sassoftware/saspy#366]
Trying to connect to SAS from Jupyter notebook using saspy. However, I am keep hitting this error. I have proper drivers added to classpath. Not sure what I am missing. Any help would be appreciated.

Java Error:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/sas/services/connection/ConnectionFactoryException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: com.sas.services.connection.ConnectionFactoryException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more

SAS Connection failed. No connection established. Staus=(8388, 256)  Double check your settings in sascfg_personal.py file.

**Comment by tomweber-sas** [comment]
Can I see what your configuration is? I'm not sure what you mean by 'proper drivers added to classpath.'. You shouldn't need a classpath if you're using a current version of saspy.

**Comment by budigi369** [comment]
thank you.
This is what I meant. 
cpL  = "/myjars/"
cpL  = "/myjars/sas.svc.connection.jar"
cpL += ":/myjars/log4j.jar"
cpL += ":/myjars/sas.security.sspi.jar"
cpL += ":/myjars/sas.core.jar"
cpL += ":/myjars/sas.rutil.jar"
cpL += ":/myjars/sas.rutil.nls.jar"
cpL += ":/myjars/sastpj.rutil.jar"
cpL += ":/mnt/miniconda/lib/python3.7/site-packages/saspy/java/saspyiom.jar"

**Comment by tomweber-sas** [comment]
what version of saspy do you have? Can you remove the classpath from your config definition and try it?
https://sassoftware.github.io/saspy/install.html#attn-as-of-saspy-version-3-3-3-the-classpath-is-no-longer-required
I assume in your config def it has 'classpath':'cpL' ?  Just remove that or comment it out.

**Comment by budigi369** [comment]
Sorry I am not very familiar with SAS/SASPY. I am using sascfg_personal.py. Are you suggesting to get rid of all paths mentioned in the above from sascfg_personal.py?

**Comment by tomweber-sas** [comment]
can you show me your sascfg_personal.py? Yes, in there you set the classpath. But you don't need to and I expect that's causing the problem. Do you know what version of saspy you have?

**Comment by budigi369** [comment]
saspy version 3.6.5. 

I am trying to connect to different workspace servers. Ex: 
Workspace_server = {'java'   : '/usr/bin/java',
            'iomhost'   : ['server 1', 'server 2'],
            'iomport'   : 9197,
            'encoding'  : 'latin1',
            'encryptionPolicy' : 'required',
            'encryptionContent' : 'all'
            }

I have taken out cpl parameter in this. Am I doing it right? I have yet to test though. Please guide me.

**Comment by tomweber-sas** [comment]
Ok, that's a current version, so you don't need the classpath. I don't have 'encryptionPolicy' or 'encryptionContent'  as configuration definition keys? Where did you come up with those? https://sassoftware.github.io/saspy/install.html#remote

This configuration definition you have is configured to get at a remote workspace server. Assuming the hosts and port you provide are correct, this seems fine; do you know what the correct values are? Try it and lets see what you get.

**Comment by budigi369** [comment]
Now SAS connection is working. Thank you for your suggestions. Much appreciated

**Comment by tomweber-sas** [comment]
Great! Is there anything else you need now? Or should we close this issue?

**Comment by budigi369** [comment]
I am closing this issue now.
