### ISSUE TITLE
Connect Jupyter Notebook to SAS University Virtual Application 

### ISSUE THREAD

**Issue by platikanova** [sassoftware/saspy#367]
Hello, 
I would like to run some SAS codes on my local computer, as opposed to the Jupyter Notebook option on the virtual machine. However, I don't seem to find a solution. The specific request requires me to connect to WRDS and pull out data from there using a SAS codes. Can you please help me establish the link between my Jupyter Notebook on my hard disk and the SAS Virtual machine. 
![wrds_sas](https://user-images.githubusercontent.com/51383135/110190647-a2316280-7e24-11eb-910c-32f6beae440a.GIF)
Thank you in advance, 
Best,
Petya

**Comment by tomweber-sas** [comment]
University Edition is a closed, self contained VM. You can't connect to it from outside. It has jupiter inside it, so you can use that from the url, localhost:10080. 
There is another option where you can use your own python install, which is SAS ODA. This isn't the first, best link, but you can Google that. https://support.sas.com/ondemand/saspy.html
This is what I found quickly from my phone right now. 
Tom

**Comment by platikanova** [comment]
Thank you very much, Tom! I will try your solution.
Have a lovely weekend,
Best,
Petya

De: Tom Weber <notifications@github.com>
Enviado el: sábado, 6 de marzo de 2021 20:14
Para: sassoftware/saspy <saspy@noreply.github.com>
CC: Platikanova , Petya <petya.platikanova@esade.edu>; Author <author@noreply.github.com>
Asunto: Re: [sassoftware/saspy] Connect Jupyter Notebook to SAS University Virtual Application (#367)


University Edition is a closed, self contained VM. You can't connect to it from outside. It has jupiter inside it, so you can use that from the url, localhost:10080.
There is another option where you can use your own python install, which is SAS ODA. This isn't the first, best link, but you can Google that. https://support.sas.com/ondemand/saspy.html
This is what I found quickly from my phone right now.
Tom

**Comment by tomweber-sas** [comment]
I dug up a couple links for SAS ODA. Here's the main link: https://www.sas.com/en_us/software/on-demand-for-academics.html
and here's the registration instructions: https://www.sas.com/en_us/software/on-demand-for-academics.html
The link I sent above, is then the instructions for connecting saspy to a workspace server in this environment, after you have credentials to use after signing up.

**Comment by platikanova** [comment]
Thanks, Tom. Following the link for your early reply, I could see it the SAS on Demand. It is working now. Thanks again!!
Have a lovely day,
Petya

De: Tom Weber <notifications@github.com>
Enviado el: lunes, 8 de marzo de 2021 16:52
Para: sassoftware/saspy <saspy@noreply.github.com>
CC: Platikanova , Petya <petya.platikanova@esade.edu>; Author <author@noreply.github.com>
Asunto: Re: [sassoftware/saspy] Connect Jupyter Notebook to SAS University Virtual Application (#367)


I dug up a couple links for SAS ODA. Here's the main link: https://www.sas.com/en_us/software/on-demand-for-academics.html
and here's the registration instructions: https://www.sas.com/en_us/software/on-demand-for-academics.html
The link I sent above, is then the instructions for connecting saspy to a workspace server in this environment, after you have credentials to use after signing up.

**Comment by tomweber-sas** [comment]
Awesome, that's great! I'll close this, but just let me know if you need anything else!
Thanks,
Tom
