### ISSUE TITLE
Pulling a dataset from SAS library into Python creates an empty dataset

### ISSUE THREAD

**Issue by obewanjacobi** [sassoftware/saspy#377]
**Describe the bug**

I created a dataset in SAS and saved it to a library. This dataset has one column that was transformed using a SAS format that I also created. The SAS format converted numeric values to their actual labels based on an "error_code" table that I had also made in my SAS project. 

Once the data was created in SAS and saved to a library, I attempted to pull it using SASPy in Spyder for further analysis. I used code similar to the following:

````
import saspy
import pandas
sas = saspy.SASsession(cfgname='SERVER')

error_codes = sas.sasdata('COMBINED_ERROR_CODES', libref='LIBRARYNAMEHERE')
````

When attempting to turn this into a pandas dataframe using `.to_df()` I got an empty dataset (which I know it is not). Then to check things out I tried doing `error_codes.head()` and got the following error: `ValueError: Internal code execution failed: ERROR: The format $ERROR_CODE_FORMAT was not found or could not be loaded.`

The issue here is that I had no idea that this was a problem from the `.sasdata()` call, it simply returned an empty dataset. This next part may be creeping into an additional request, but I think ideally if it can't find the format for the values, then it should just return the raw values themselves (at least that's what I would expect). 

**To Reproduce**
1. create dataset in SAS that has a formatted column using a user created format
2. save it to a SAS library
3. attempt to pull that same dataset into Python using the `.sasdata()` call. 

**Expected behavior**

I would expect to at the very least get some data back, not an entirely empty dataset. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SAS Version: SASEg with SAS Version 9.4
 - SASPy Version: 3.6.6

**Comment by tomweber-sas** [comment]
Hey, I can help with this. So, first off, sasdata() doesn't return any data, it just defines a SASdata object in python, which just represents a data set that's in the SAS session.  So, there's nothing it would know other than if that table doesn't exist, and it will tell you that if that's the case. So, it wouldn't be till you tried to access that table and do something with it (to_df() or head(), ...) that there would be an issue since the format isn't found in SAS.
Can you submit print(sas.saslog()) so we can see the errors that happened in SAS when you tried to access the table?
This sounds' like it's an error in SAS that I can't do anything about, but I'll reserve judgment on that till I know a little more and see the log, at least. Do you have the format catalog that has the user defined format that table needs, to be able to be accessed? That's gonna be the real answer, but let's see what were actually getting and go from there.
Thanks,
Tom

**Comment by obewanjacobi** [comment]
Hi Tom, thanks for the help! That all makes sense. You'll have to forgive my for my ignorance in SAS, I'm still learning the ropes, which is why I'm excited to use SASPy instead, lol.

So to be exact the code I've run is below:
````
import saspy
import pandas
sas = saspy.SASsession(cfgname='SERVERNAMEHERE')

error_codes = sas.sasdata('COMBINED_ERROR_CODES', libref='LIBRARYNAMEHERE').to_df()

print(sas.saslog())
```` 

and the only output I get is:

````
40                                                         The SAS System                                 15:10 Tuesday, May 4, 2021

237        
238        %put E3969440A681A2408885998500000017;
E3969440A681A2408885998500000017
239        
````

**Comment by tomweber-sas** [comment]
ok, though the whole log should have been printed. Let's try this:
```
import saspy
import pandas
sas = saspy.SASsession(cfgname='SERVERNAMEHERE')
sas

error_codes = sas.sasdata('COMBINED_ERROR_CODES', libref='LIBRARYNAMEHERE')
error_codes

error_codes.head()

print(sas.saslog())
```

**Comment by obewanjacobi** [comment]
I don't know if it's a byproduct of Spyder or what, but whenever I try to print the log the only thing returned is that little snippet I sent you before.

**Comment by tomweber-sas** [comment]
Ah, I was wondering what interface you were using. Can you use a command line to try running that? Or, try
print(sas.saslog().replace(chr(12), chr(10))
I thought I had that everywhere, but maybe there still a case. I'm thinking spyder can't handle the FormFeed char.

**Comment by obewanjacobi** [comment]
`print(sas.saslog().replace(chr(12), chr(10))` actually printed what I would have expected. The log output is below:

````
1                                                          The SAS System                               09:39 Wednesday, May 5, 2021

NOTE: Copyright (c) 2002-2012 by SAS Institute Inc., Cary, NC, USA. 
NOTE: SAS (r) Proprietary Software 9.4 (TS1M3) 
      Licensed to HUMANA INC, Site 70130518.
NOTE: This session is executing on the AIX 7.1 (AIX 64) platform.



NOTE: Updated analytical products:
      
      SAS/STAT 14.1
      SAS/ETS 14.1
      SAS/IML 14.1

NOTE: Additional host information:

IBM AIX AIX 64 1 7 00F9E6294C00 

You are running SAS 9. Some SAS 8 files will be automatically converted 
by the V9 engine; others are incompatible.  Please see 
http://support.sas.com/rnd/migration/planning/platform/64bit.html

PROC MIGRATE will preserve current SAS file attributes and is 
recommended for converting all your SAS libraries from any 
SAS 8 release to SAS 9.  For details and examples, please see
http://support.sas.com/rnd/migration/index.html


This message is contained in the SAS news file, and is presented upon
initialization.  Edit the file "news" in the "misc/base" directory to
display site-specific news and information in the program log.
The command line option "-nonews" will prevent this display.




NOTE: SAS Initialization used (Total process time):
      real time           0.01 seconds
      user cpu time       0.00 seconds
      system cpu time     0.00 seconds
      memory              9075.81k
      OS Memory           10144.00k
      Timestamp           05/05/2021 09:39:14 AM
      Step Count                        0  Switch Count  88
      Page Faults                       0
      Page Reclaims                     115
      Page Swaps                        0
      Voluntary Context Switches        315
      Involuntary Context Switches      17
      Block Input Operations            0
      Block Output Operations           0
      
NOTE: The autoexec file, /sasapps/sas_config/Lev6/SASHPS/WorkspaceServer/autoexec.sas, was executed at server initialization.
1          ;*';*";*/;
2          options svgtitle='svgtitle'; options validvarname=any validmemname=extend pagesize=max nosyntaxcheck; ods graphics on;
3          
4          ;*';*";*/;
5          

2                                                          The SAS System                               09:39 Wednesday, May 5, 2021

6          
7          %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
8          

3                                                          The SAS System                               09:39 Wednesday, May 5, 2021

9          ;*';*";*/;
10         data _null_; length x $ 4096;
11                        x = resolve('%sysfunc(pathname(work))');  put 'WORKPATH=' x 'WORKPATHEND=';
12                        x = resolve('&SYSENCODING');              put 'ENCODING=' x 'ENCODINGEND=';
13                        x = resolve('&SYSVLONG4');                put 'SYSVLONG=' x 'SYSVLONGEND=';
14                        x = resolve('&SYSJOBID');                 put 'SYSJOBID=' x 'SYSJOBIDEND=';
15                        x = resolve('&SYSSCP');                     put 'SYSSCP=' x 'SYSSCPEND=';
16                     run;

WORKPATH=/saswork/SAS_work297A018B01AC_isbsas37/SAS_workCA6E018B01AC_isbsas37 WORKPATHEND=
ENCODING=latin1 ENCODINGEND=
SYSVLONG=9.04.01M3P06242015 SYSVLONGEND=
SYSJOBID=25887148 SYSJOBIDEND=
SYSSCP=AIX 64 SYSSCPEND=
NOTE: DATA statement used (Total process time):
      real time           0.04 seconds
      user cpu time       0.00 seconds
      system cpu time     0.01 seconds
      memory              1081.65k
      OS Memory           12704.00k
      Timestamp           05/05/2021 09:39:15 AM
      Step Count                        1  Switch Count  52
      Page Faults                       0
      Page Reclaims                     379
      Page Swaps                        0
      Voluntary Context Switches        184
      Involuntary Context Switches      4
      Block Input Operations            0
      Block Output Operations           0
      

17         
18         
19         ;*';*";*/;
20         

4                                                          The SAS System                               09:39 Wednesday, May 5, 2021

21         
22         %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
23         

5                                                          The SAS System                               09:39 Wednesday, May 5, 2021

24         ;*';*";*/;
25         %let engine=BAD;
26         proc sql;
26       !          select distinct engine into :engine from sashelp.VLIBNAM where libname = 'DATASPRX';
26       !                                                                                              ;%put engstart=&engine
26       ! engend=;
engstart=BASE     engend=
27         quit;
NOTE: The PROCEDURE SQL printed page 1.
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.07 seconds
      user cpu time       0.01 seconds
      system cpu time     0.01 seconds
      memory              5251.46k
      OS Memory           17828.00k
      Timestamp           05/05/2021 09:39:15 AM
      Step Count                        2  Switch Count  42
      Page Faults                       0
      Page Reclaims                     573
      Page Swaps                        0
      Voluntary Context Switches        165
      Involuntary Context Switches      12
      Block Input Operations            0
      Block Output Operations           0
      

28         
29         ;*';*";*/;
30         

6                                                          The SAS System                               09:39 Wednesday, May 5, 2021

31         
32         %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
33         

7                                                          The SAS System                               09:39 Wednesday, May 5, 2021

34         ;*';*";*/;
35         data _null_; e = exist("DATASPRX.'COMBINED_ERROR_CODES'n");
36         v = exist("DATASPRX.'COMBINED_ERROR_CODES'n", 'VIEW');
37          if e or v then e = 1;
38         te='TABLE_EXISTS='; put te e;run;

TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.01 seconds
      user cpu time       0.00 seconds
      system cpu time     0.01 seconds
      memory              783.43k
      OS Memory           14752.00k
      Timestamp           05/05/2021 09:39:16 AM
      Step Count                        3  Switch Count  32
      Page Faults                       0
      Page Reclaims                     115
      Page Swaps                        0
      Voluntary Context Switches        86
      Involuntary Context Switches      10
      Block Input Operations            0
      Block Output Operations           0
      

39         
40         
41         ;*';*";*/;
42         

8                                                          The SAS System                               09:39 Wednesday, May 5, 2021

43         
44         %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
45         

9                                                          The SAS System                               09:39 Wednesday, May 5, 2021

46         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
46       ! ods graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: _TOMODS1
47         ;*';*";*/;
48         data _head ; set DATASPRX.'COMBINED_ERROR_CODES'n (obs=5 ); run;

ERROR: The format $ERROR_CODE_FORMAT was not found or could not be loaded.
NOTE: The SAS System stopped processing this step because of errors.
WARNING: The data set WORK._HEAD may be incomplete.  When this step was stopped there were 0 observations and 3 variables.
NOTE: DATA statement used (Total process time):
      real time           0.04 seconds
      user cpu time       0.00 seconds
      system cpu time     0.01 seconds
      memory              1361.43k
      OS Memory           23204.00k
      Timestamp           05/05/2021 09:39:16 AM
      Step Count                        4  Switch Count  27
      Page Faults                       0
      Page Reclaims                     283
      Page Swaps                        0
      Voluntary Context Switches        84
      Involuntary Context Switches      6
      Block Input Operations            0
      Block Output Operations           0
      

49         
50         ;*';*";*/;
51         ods html5 (id=saspy_internal) close;ods listing;
52         

10                                                         The SAS System                               09:39 Wednesday, May 5, 2021

53         
54         %put E3969440A681A2408885998500000005;
E3969440A681A2408885998500000005
55         
````

**Comment by obewanjacobi** [comment]
I think the key here is the 

````
ERROR: The format $ERROR_CODE_FORMAT was not found or could not be loaded.
NOTE: The SAS System stopped processing this step because of errors.
WARNING: The data set WORK._HEAD may be incomplete.  When this step was stopped there were 0 observations and 3 variables.
````

So does this mean that user defined formats have no way of working in SASpy?

**Comment by tomweber-sas** [comment]
Perfect. I'll try to find where I am missing that replace(), cuz I thought I had caught all of those. And, yes, that was the 'second thing' in my first post that you didn't quite know what I was talking about. 

So, it's got nothing to do with saspy; it's not working in SAS! SAS is unable to process that file because the format isn't available. That was the question about having the format catalog with that format in it, so you SAS can read that data set.

You don't know about the format catalog, so do you know where this table came from? Who created it? There will be a format catalog somewhere available to the SAS process that creates this table. The SAS session you're connected to with saspy, needs that catalog available so it can read that data set. Once you know where that format catalog is, you can ad it to the format search path in SAS so that it will be found and then you (SAS itself) can access that data set.

Not that this will help you yet, but this will be helpful once we find the catalog (adding it for later):
https://go.documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/lesysoptsref/p1fvn6rwmpf1njn1whkud1hmsc97.htm

Make sense, at least conceptually, so far? Can you get any info about where this table came from? Where the catalog is?
Tom

**Comment by obewanjacobi** [comment]
So the table that's building this format is actually made by me in my SAS project that builds the datasets that I'm writing to a library to read into python. So in terms of flow it goes like this:
I build the dataset that created the format -> the data I want to read into python is built and organized in SAS using that format -> this new dataset is written to a SAS library for me to read into python using SASpy

Does all that make sense? I understand the concept of this format catalog, but I believe it would be wasteful almost to add this cheeky little format I built to some important catalog for my company, especially seeing as how I really only need it for this project right now. So maybe the best answer is to not use a format at all in SAS and build out my own transformation later in python to do the reformatting there.

**Comment by tomweber-sas** [comment]
No, there's nothing about it that you have to add to a company place. You just need that catalog w/ the format is to be in the search path. A Catalog is just a different type of SAS file (data, view, catalog, ...). So, you can just create it in the work library if you want, and it'll be found; that's part of the link I added, so I'd be able to find the doc :)
You got time for a teams meeting, and we can walk through this w/ screen share and see what you're doing and get it working.
Shouldn't be hard now that you're the one creating the format. I think it's like, proc format ... and then we should be good. (yeah, more than that, but still ...)
Tom

**Comment by obewanjacobi** [comment]
Ok so I did some research and looked into the `proc format library` statement. And to save the catalog to the work library, I did `library=work` and hen finished the `proc format` statement. So I've run that, recreated the dataset saved to the library I want to pull it from in python, but python still appears to be unable to pull in the dataset because of the format. Now that this catalog exists, is there something I need to add to the `.sasdata()` function call?

My apologies if these questions seem trivial, like I said before I'm still learning the ropes of SAS.

**Comment by tomweber-sas** [comment]
So, what's the log show now after doing that? Sounds like the right things to do. Again, saspy doesn't know anything about any of this; it's SAS that either can or can't process the data.

**Comment by obewanjacobi** [comment]
Just for the sake of not leaving anything out, below is the log that was output by SAS:

````
1          %_eg_hidenotesandsource;
5          %_eg_hidenotesandsource;
33         
34         
35         /* --------------------------------------------------------------------
36            Manipulates the incoming data into the correct format for PROC
37            FORMAT to use as a CNTLIN data set.
38            -------------------------------------------------------------------- */
39         TITLE; FOOTNOTE;
40         DATA WORK._EG_CFMT;
41             LENGTH label $ 20;
42             SET WORK.ERROR_CODE (KEEP=ERROR_CODE ERROR_DESC RENAME=(ERROR_CODE=start ERROR_DESC=label)) END=__last;
43             RETAIN fmtname "error_code_format" type "C";
44         
45             end=start;
46         
47             OUTPUT;
48         
49             IF __last = 1 THEN
50               DO;
51                 hlo = "O";
52                 label = "Other";
53                 OUTPUT;
54               END;
55         RUN;

NOTE: There were 4 observations read from the data set WORK.ERROR_CODE.
NOTE: The data set WORK._EG_CFMT has 5 observations and 6 variables.
NOTE: DATA statement used (Total process time):
      real time           0.03 seconds
      user cpu time       0.00 seconds
      system cpu time     0.00 seconds
      memory              1381.03k
      OS Memory           23456.00k
      Timestamp           05/06/2021 03:11:33 PM
      Step Count                        45  Switch Count  84
      Page Faults                       0
      Page Reclaims                     189
      Page Swaps                        0
      Voluntary Context Switches        316
      Involuntary Context Switches      37
      Block Input Operations            0
      Block Output Operations           0
      

56         
57         /* --------------------------------------------------------------------
58            Creates a new format based on the data values contained within the
59            source data set.
60            -------------------------------------------------------------------- */
61         PROC FORMAT LIBRARY=WORK CNTLIN=WORK._EG_CFMT;
NOTE: Format $ERROR_CODE_FORMAT is already on the library WORK.FORMATS.
NOTE: Format $ERROR_CODE_FORMAT has been output.
62         RUN;

NOTE: PROCEDURE FORMAT used (Total process time):
      real time           0.01 seconds
      user cpu time       0.00 seconds
2                                                          The SAS System                                14:49 Thursday, May 6, 2021

      system cpu time     0.00 seconds
      memory              708.81k
      OS Memory           22940.00k
      Timestamp           05/06/2021 03:11:33 PM
      Step Count                        46  Switch Count  30
      Page Faults                       0
      Page Reclaims                     70
      Page Swaps                        0
      Voluntary Context Switches        58
      Involuntary Context Switches      11
      Block Input Operations            0
      Block Output Operations           0
      
NOTE: There were 5 observations read from the data set WORK._EG_CFMT.

63         
64         /* --------------------------------------------------------------------
65            Now that the new SAS format has been created, we want to tidy up by
66            deleting the WORK data set
67            -------------------------------------------------------------------- */
68         PROC SQL;
69             DROP TABLE WORK._EG_CFMT;
NOTE: Table WORK._EG_CFMT has been dropped.
70         QUIT;
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.00 seconds
      user cpu time       0.00 seconds
      system cpu time     0.00 seconds
      memory              43.31k
      OS Memory           22424.00k
      Timestamp           05/06/2021 03:11:33 PM
      Step Count                        47  Switch Count  28
      Page Faults                       0
      Page Reclaims                     1
      Page Swaps                        0
      Voluntary Context Switches        61
      Involuntary Context Switches      5
      Block Input Operations            0
      Block Output Operations           0
      

71         
72         
73         
74         
75         %_eg_hidenotesandsource;
89         
90         
91         %_eg_hidenotesandsource;
94      
````

**Comment by tomweber-sas** [comment]
That's some code that was run in EG, when you created the dataset w/ the user defined format?

**Comment by obewanjacobi** [comment]
Correct

**Comment by tomweber-sas** [comment]
So, then, are you adding that format into the format catalog in the SAS session you're using from saspy, so it can be found and used? The work library is a local/transient thing for each different SAS session. No 2 EG sessions, or saspy session, or any client use the same SAS session, So whatever you did in EG isn't there in another connection.

**Comment by tomweber-sas** [comment]
Well, that's the code you just showed; the proc format. It's just that it writes the format to the work library, which only exists in that SAS session, and goes away every time, so you have to run that code every time you use the format; creating the data or reading the data. If you wrote the format to a permanent library (once ever), then you would simply add that library/catalog to the format search and it would be found and used w/out you having to create it every time you needed it.
But, to just try it out, submit that data step and proc format in your saspy session before trying to access the dataset with that format and see it that works as expected. Look at the SAS log to see what really happened.

**Comment by obewanjacobi** [comment]
I think I'm a little confused on what's getting run and where. So I build the dataset in SAS EG that I want to read into python using saspy. I am also building the format and saving it to the work library in SAS EG. But above you seem to indicate that I should run this stuff in the saspy session, is that correct? If I understand correctly, these are 2 different sessions, even though I'm logged in as myself in both places. So if I need to run the format statement in saspy, what exactly would that look like since it's based on another dataset from SAS EG?

Apologies if I'm way misunderstanding here. I just want to make sure I follow you correctly, and that I haven't been handling all of this incorrectly from the start.

**Comment by tomweber-sas** [comment]
Hey, no problem. It's all SAS stuff, and if you're not clear on it, then it can be confusing. Can you do a teams meeting, or webex, I can set that up? It'll be a lot easier/quicker to get you going that way.

**Comment by obewanjacobi** [comment]
Issue closed after help from Tom. Thanks again!
