### ISSUE TITLE
Usage of iomclient jars in Julia package

### ISSUE THREAD

**Issue by nucklass** [sassoftware/saspy#387]
Hello! 
I'm looking to author and [register](https://github.com/JuliaRegistries/General) a package to interface SAS with the Julia programming language, in the same vein as saspy.  As it sits the four iomclient jars are a necessary dependency for this to happen, and I'm keen to have a pathway for users to obtain these when it's not possible to obtain the jars from a sas installation, ie when using SAS ODA. I understand that the jars have their own license and I wanted to clarify permissions/usage rights of them before publicly posting the Julia package. Would I be in violation of any terms if I included code to optionally download these four jars, or perhaps saspy in it's entirety, from the saspy repo as part of a build step?
Thanks!

**Comment by tomweber-sas** [comment]
hey @nucklass, that sounds like an interesting project. I can't give you an answer to this off the top of my head, but I will contact our legal department and find out what they say. I can imagine a couple possibilities, but let me check with them before speculating.
Thanks,
Tom

**Comment by nucklass** [comment]
Thanks Tom!
Let me know if you need any more information or anything else.
Best, 
Nick

**Comment by tomweber-sas** [comment]
No problem. I've sent what I need to the right person in legal, with my suggestion. So just have to wait to hear back and I'll let you know what they think.

**Comment by tomweber-sas** [comment]
Hey, just a quick update. I head back from my first query, and didn't get a viable answer. So, I set up a call for Tuesday morning w/ Legal to discuss it and see if there's something we can come up with. I'll let you know what comes of that after. Sorry this is taking a while, but this one isn't under my control.

Thanks,
Tom

**Comment by nucklass** [comment]
Thank you for the update Tom. Also, no problem on the wait. I understand legal matters can take a bit of time to resolve.

Thanks,
Nick

**Comment by tomweber-sas** [comment]
Hey @nucklass , I talked with Legal yesterday and we discussed all of this. There were a number of possibilities, and not all of them could pan out. We did come up with an acceptable use case for ODA users, as they have no way (necessarily) to acquire those jars for connecting to ODA, from your code.

Having you package our jars in your code, effectively redistributing them as part of your code base, is NOT an acceptable case. That would be the easiest, of course, but against our licensing, and you already know that as you’re asking this in the first place 😊

The next possibility is to document that the users could download the jars from our download site. We have other things on this download site like this, and to download from there you must have a SAS profile (just a login, an ODA user can still create this w/out having SAS) and accept the terms of the licensing agreement. At the moment, these jars are not on that site, but I could go through the hoops to get them there, but that would also take some time. However, this would be in compliance w/ licensing for both the jars and the ODA use case.

The other case, which can be used today, is to document that for the ODA case, if you don’t have a SAS install to get the jars from, then you can install SASPy, and then just use the jar files from that; point the classpath for your Julia code to those jars. This still requires compliance with the licensing agreement which is in the SASPy repo. Like any open source project that has a license file in the repo, compliance is implied. So, this gives you a way for your users to use these jars for an ODA case, basically, like they have using SASPy to ODA (that was the driving force for getting these jars into my repo, as opposed to on the download site). So, if you document something like the following in your instructions, then you can have users working immediately for your use case.

```
Get the required jar files from your SAS installation, or, if you are using ODA and don't have your
own SAS installation, you can install SASPy, and point at the jar files in that local install. You must
still comply with he licensing agreement in the SASPy repo as well as your ODA licensing agreement.
```
If that works for you, then we should be all set. If you rather we have the jars on the download site and document how to get them from there (one link), that will take a little time, but it is an acceptable case, per Legal, as that was my other choice too, if I had not been allowed to put them in my repo. But, again, that will take me some amount of time to do, but I'm happy to do it if needed..

Thanks for being patient with this. After the initial 'no', I still wanted to have a conversation about it to work through the possibilities. Luckily that panned out :)

Let me know what you think,
Tom

**Comment by nucklass** [comment]
Thanks for the update and the hard work on this, Tom. For now, I agree that the 3rd option of including documentation on downloading SASpy and pointing to the included jars, makes the most sense. I would be interested in having a single click download of those jars in the future, but for now I think good docs will work. I’ll try to get the package posted in the next week or so with updated docs. I think we are just about good to close this unless you have any last thoughts. Thanks!

**Comment by tomweber-sas** [comment]
That sounds cool. As for the one click, it more one link to document. The end user would still need to go to that link to download the jars. They would need a SAS Profile (login), which they would already if using ODA, and they need to click through the licensing agreement to be able to download the jars. So, it wouldn't be something you automate, but still instructions for them to do. But, just one link to go to. 
To get these on the download site, I still have to go through the whole process, but I already expect that it would get approved, as Legal is usually the part that takes the most effort. So, let me know if that changes anything in your mind. It would take a couple weeks, I'm guessing. Kinda depends, could be other hurdles, but I doubt it.

If you want to close this, and open another, or reopen this, if you want to pursue the download, that works for me. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
seems like we can close this and if you you want to pursue the download stuff, you can reopen this or open another. Curious to to see your project :)
Tom
