### ISSUE TITLE
Missing Notes in the sas_session.submit()[LOG]

### ISSUE THREAD

**Issue by damjankrstajic** [sassoftware/saspy#388]
Here is a simple SAS code
--Begin SAS code--
data weight_club;
  input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
  Loss=StartWeight-EndWeight;
  datalines;
1023 David Shaw red 189 165
1049 Amelia Serrano yellow 145 124
1219 Alan Nance red 210 192
1246 Ravi Sinha yellow 194 177
1078 Ashley McKnight red 127 118
;
run;
--End SAS code--

which when executed in SAS Studio reports the following LOG
-- Begin of LOG--
 
 1          OPTIONS NONOTES NOSTIMER NOSOURCE NOSYNTAXCHECK;
 72         
 73         data weight_club;
 74           input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
 75           Loss=StartWeight-EndWeight;
 76           datalines;
 
 NOTE: Invalid data for EndWeight in line 78 6-11.
 RULE:      ----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0                     
 78         1049 Amelia Serrano yellow 145 124
 IdNumber=1023 Name=David Shaw red 189 Team=165 StartWeight=1049 EndWeight=. Loss=. _ERROR_=1 _N_=1
 NOTE: Invalid data for EndWeight in line 80 6-9.
 80         1246 Ravi Sinha yellow 194 177
 IdNumber=1219 Name=Alan Nance red 210 Team=192 StartWeight=1246 EndWeight=. Loss=. _ERROR_=1 _N_=2
 NOTE: LOST CARD.
 82         ;
 IdNumber=1078 Name=Ashley McKnight red Team=127 StartWeight=118 EndWeight=. Loss=. _ERROR_=1 _N_=3
 NOTE: SAS went to a new line when INPUT statement reached past the end of a line.
 NOTE: Missing values were generated as a result of performing an operation on missing values.
       Each place is given by: (Number of times) at (Line):(Column).
       2 at 75:19   
 NOTE: The data set WORK.WEIGHT_CLUB has 2 observations and 6 variables.
 NOTE: DATA statement used (Total process time):
       real time           0.00 seconds
       user cpu time       0.00 seconds
       system cpu time     0.00 seconds
       memory              697.28k
       OS Memory           29352.00k
       Timestamp           07/10/2021 01:45:34 PM
       Step Count                        24  Switch Count  2
       Page Faults                       0
       Page Reclaims                     192
       Page Swaps                        0
       Voluntary Context Switches        10
       Involuntary Context Switches      0
       Block Input Operations            0
       Block Output Operations           264
       
 
 82         ;
 83         run;
 84         
 85         
 86         OPTIONS NONOTES NOSTIMER NOSOURCE NOSYNTAXCHECK;
 98         
--End of LOG--

However when I execute the same code with syspy as below I do not get the "NOTE: " statements
--Begin of syspy code--
import saspy
import pandas as pd

sas_session = saspy.SASsession()
sas_session

c = sas_session.submit("""
data weight_club;
  input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
  Loss=StartWeight-EndWeight;
  datalines;
1023 David Shaw red 189 165
1049 Amelia Serrano yellow 145 124
1219 Alan Nance red 210 192
1246 Ravi Sinha yellow 194 177
1078 Ashley McKnight red 127 118
;
run;
""",
results="TEXT")
print("LOG ")
print(c["LOG"])

sas_session.endsas()

--ENd of syspy code--

I also tried executing "print(sas_session.saslog())" but I don't see notes. 

Is there a way of seeing the same LOG as when executed from SAS Studio?

Thanks in advance
DK

**Comment by tomweber-sas** [comment]
Hey, given you're using c=submit(...), the print(c['LOG']) is what will display the LOG from what you submitted. The print("LOG") just prints the string LOG. You can also use submitLOG(...) which displays the log for you so you don't have to issue the print after running it.

Running your code I get this:

```
>>> c = sas.submit("""
... data weight_club;
... Loss=StartWeight-EndWeight;
... input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
... Loss=StartWeight-EndWeight;
... datalines;
... 1023 David Shaw red 189 165
... 1049 Amelia Serrano yellow 145 124
... 1219 Alan Nance red 210 192
... 1246 Ravi Sinha yellow 194 177
... 1078 Ashley McKnight red 127 118
... ;
... run;
... """,
... results="TEXT")
>>> print(c["LOG"])

21
22
23   data weight_club;
24   input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
25   Loss=StartWeight-EndWeight;
26   datalines;
NOTE: Invalid data for EndWeight in line 28 6-11.
RULE:----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0
28   1049 Amelia Serrano yellow 145 124
IdNumber=1023 Name=David Shaw red 189 Team=165 StartWeight=1049 EndWeight=. Loss=. _ERROR_=1 _N_=1
NOTE: Invalid data for EndWeight in line 30 6-9.
30   1246 Ravi Sinha yellow 194 177
IdNumber=1219 Name=Alan Nance red 210 Team=192 StartWeight=1246 EndWeight=. Loss=. _ERROR_=1 _N_=2
NOTE: LOST CARD.
32   ;
IdNumber=1078 Name=Ashley McKnight red Team=127 StartWeight=118 EndWeight=. Loss=. _ERROR_=1 _N_=3
NOTE: SAS went to a new line when INPUT statement reached past the end of a line.
NOTE: Missing values were generated as a result of performing an operation on missing values.
      Each place is given by: (Number of times) at (Line):(Column).
      2 at 25:17
NOTE: The data set WORK.WEIGHT_CLUB has 2 observations and 6 variables.
NOTE: DATA statement used (Total process time):
      real time           0.13 seconds
      cpu time            0.03 seconds

32   ;
33   run;
34
35
>>>
``` 
I don't see any output, including LOG from that other print. What output do you get? How are you running Python? In some IDE? Is there something about where you're running that is not displaying output? 

Thanks,
Tom

**Comment by damjankrstajic** [comment]
Thanks Tom. I execute the Python code from a command line (Linux).  
Please find attached my code and stdout from the following command.

$ ./problematic_example.py 1>stdout.txt

As you will see, the Notes are not printed.

$ python3 --version
Python 3.6.3

and I am using SAS OnDemand for Academics.

If you need any more info, please do not hesitate to contact me.

Thanks in advance.
DK

Quoting Tom Weber ***@***.***>:

> Hey, given you're using c=submit(...), the print(c['LOG']) is what  
> will display the LOG from what you submitted. The print("LOG") just  
> prints the string LOG. You can also use submitLOG(...) which  
> displays the log for you so you don't have to issue the print after  
> running it.
>
> Running your code I get this:
>
> ```
>>>> c = sas.submit("""
> ... data weight_club;
> ... Loss=StartWeight-EndWeight;
> ... input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
> ... Loss=StartWeight-EndWeight;
> ... datalines;
> ... 1023 David Shaw red 189 165
> ... 1049 Amelia Serrano yellow 145 124
> ... 1219 Alan Nance red 210 192
> ... 1246 Ravi Sinha yellow 194 177
> ... 1078 Ashley McKnight red 127 118
> ... ;
> ... run;
> ... """,
> ... results="TEXT")
>>>> print(c["LOG"])
>
> 21
> 22
> 23   data weight_club;
> 24   input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
> 25   Loss=StartWeight-EndWeight;
> 26   datalines;
> NOTE: Invalid data for EndWeight in line 28 6-11.
> RULE:----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0
> 28   1049 Amelia Serrano yellow 145 124
> IdNumber=1023 Name=David Shaw red 189 Team=165 StartWeight=1049  
> EndWeight=. Loss=. _ERROR_=1 _N_=1
> NOTE: Invalid data for EndWeight in line 30 6-9.
> 30   1246 Ravi Sinha yellow 194 177
> IdNumber=1219 Name=Alan Nance red 210 Team=192 StartWeight=1246  
> EndWeight=. Loss=. _ERROR_=1 _N_=2
> NOTE: LOST CARD.
> 32   ;
> IdNumber=1078 Name=Ashley McKnight red Team=127 StartWeight=118  
> EndWeight=. Loss=. _ERROR_=1 _N_=3
> NOTE: SAS went to a new line when INPUT statement reached past the  
> end of a line.
> NOTE: Missing values were generated as a result of performing an  
> operation on missing values.
>       Each place is given by: (Number of times) at (Line):(Column).
>       2 at 25:17
> NOTE: The data set WORK.WEIGHT_CLUB has 2 observations and 6 variables.
> NOTE: DATA statement used (Total process time):
>       real time           0.13 seconds
>       cpu time            0.03 seconds
>
> 32   ;
> 33   run;
> 34
> 35
>>>>
> ```
> I don't see any output, including LOG from that other print. What  
> output do you get? How are you running Python? In some IDE? Is there  
> something about where you're running that is not displaying output?
>
> Thanks,
> Tom
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sassoftware/saspy/issues/388#issuecomment-878279580



Using SAS Config named: oda
SAS Connection established. Subprocess id is 6253

LOG 

5                                                          The SAS System                       Wednesday, July 14, 2021 06:27:00 PM

24         
25         
26         data weight_club;
27         input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
28         Loss=StartWeight-EndWeight;
29         datalines;
RULE:      ----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0                     
31         1049 Amelia Serrano yellow 145 124
IdNumber=1023 Name=David Shaw red 189 Team=165 StartWeight=1049 EndWeight=. Loss=. _ERROR_=1 _N_=1
33         1246 Ravi Sinha yellow 194 177
IdNumber=1219 Name=Alan Nance red 210 Team=192 StartWeight=1246 EndWeight=. Loss=. _ERROR_=1 _N_=2
35         ;
IdNumber=1078 Name=Ashley McKnight red Team=127 StartWeight=118 EndWeight=. Loss=. _ERROR_=1 _N_=3
35         ;
36         run;
37         
38         
39         
40         

6                                                          The SAS System                       Wednesday, July 14, 2021 06:27:00 PM

41         
SAS Connection terminated. Subprocess id was 6253

**Comment by tomweber-sas** [comment]
Ah, that's helpful, to see the code and output. And knowing you're connecting to ODA. So, SAS has about a billion options, which control all kinds of things, some being output. Seeing your output, I assumed you have 'options nonotes' set. And seeing now that you're connected to ODA, I was able to try it myself and see the same thing. If you want to see the notes, you can change the option, as below, and then you will see the notes like I did w/ a default SAS install that I posted before.

```
tom64-5> python3.5
Python 3.5.6 (default, Nov 16 2018, 15:50:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession()
Please enter the name of the SAS Config you wish to run. Available Configs are: ['default', 'SASgrid', 'http', 'httptest', 'ssh', 'sshtun', 'sshrtun', 'httpfred', 'grid', 'tdi', 'tdi_cn', 'tdi_cn8', 'tdilat', 'oda', 'iomj', 'sdssas_cn', 'sdssas_u8', 'iomc', 'iomjwin', 'winiomj', 'winiomjwin', 'winlocal', 'gridiom', 'wingridiom', 'zos', 'zos2', 'winzos', 'winzos2', 'sshtest', 'sshloc', 'sdssas', 'saskr', 'vb010', 'vb015', 'pune', 'notpune', 'iomkr', 'httpviya', 'kevin', 'issue176', 'httpjason', 'itviya', 'carrie1', 'console', 'iomcom', 'iomcom_loc', 'iom4', 'm5bug', 'spre34', 'sshprob', 'vbviya', 'vbviyaxx', 'vbviyapp', 'alex', 'dotat', 'dotav', 'dotap', 'dotas', 'odadev', 'mahesh', 'viya_cn', 'procpy', 'procpy_cn', 'tdiexe7', 'tdiexe6', 'biff', 'sshsax', 'chris', 'wilbram', 'sso', 'SGF_Viya', 'dotat_cn'] oda
SAS Connection established. Subprocess id is 29478

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to utf_8 based upon the SAS session encoding value of utf-8.

>>> sas
Access Method         = IOM
SAS Config name       = oda
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /saswork/SAS_workB93200013D72_odaws04-usw2.oda.sas.com/SAS_work7C0D00013D72_odaws04-usw2.oda.sas.com/
SAS Version           = 9.04.01M6P11072018
SASPy Version         = 3.7.2
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 81266


>>> c = sas.submit("""
... data weight_club;
... Loss=StartWeight-EndWeight;
... input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
... Loss=StartWeight-EndWeight;
... datalines;
... 1023 David Shaw red 189 165
... 1049 Amelia Serrano yellow 145 124
... 1219 Alan Nance red 210 192
... 1246 Ravi Sinha yellow 194 177
... 1078 Ashley McKnight red 127 118
... ;
... run;
... """,
... results="TEXT")
>>>
>>> print(c["LST"])

>>> print(c["LOG"])

5                                                          The SAS System                       Wednesday, July 14, 2021 06:37:00 PM

24
25
26         data weight_club;
27         Loss=StartWeight-EndWeight;
28         input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
29         Loss=StartWeight-EndWeight;
30         datalines;
RULE:      ----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0
32         1049 Amelia Serrano yellow 145 124
Loss=. EndWeight=. StartWeight=1049 IdNumber=1023 Name=David Shaw red 189 Team=165 _ERROR_=1 _N_=1
34         1246 Ravi Sinha yellow 194 177
Loss=. EndWeight=. StartWeight=1246 IdNumber=1219 Name=Alan Nance red 210 Team=192 _ERROR_=1 _N_=2
36         ;
Loss=. EndWeight=. StartWeight=118 IdNumber=1078 Name=Ashley McKnight red Team=127 _ERROR_=1 _N_=3
36         ;
37         run;
38
39
40
41

6                                                          The SAS System                       Wednesday, July 14, 2021 06:37:00 PM

42
>>> sas.submitLOG('proc options option=notes;run;')

7                                                          The SAS System                       Wednesday, July 14, 2021 06:37:00 PM

45         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
45       ! ods graphics on / outputfmt=png;
46
47         proc options option=notes;run;
    SAS (r) Proprietary Software Release 9.4  TS1M6

 NONOTES           SAS does not write notes to the SAS log.
48
49
50         ods html5 (id=saspy_internal) close;ods listing;
51

8                                                          The SAS System                       Wednesday, July 14, 2021 06:37:00 PM

52
>>>
```
So, just set options notes; and you will then see notes in the log:
```
>>> sas.submitLOG('options notes;')

9                                                          The SAS System                       Wednesday, July 14, 2021 06:37:00 PM

55         ods listing close;ods html5 (id=saspy_internal) file=_tomods1 options(bitmap_mode='inline') device=svg style=HTMLBlue;
55       ! ods graphics on / outputfmt=png;
56
57         options notes;
58
59
60         ods html5 (id=saspy_internal) close;ods listing;
61

10                                                         The SAS System                       Wednesday, July 14, 2021 06:37:00 PM

62
>>> sas.submitLOG("""
... data weight_club;
... Loss=StartWeight-EndWeight;
... input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
... Loss=StartWeight-EndWeight;
... datalines;
... 1023 David Shaw red 189 165
... 1049 Amelia Serrano yellow 145 124
... 1219 Alan Nance red 210 192
... 1246 Ravi Sinha yellow 194 177
... 1078 Ashley McKnight red 127 118
... ;
... run;
... """,
... results="TEXT")

11                                                         The SAS System                       Wednesday, July 14, 2021 06:37:00 PM

65
66
67         data weight_club;
68         Loss=StartWeight-EndWeight;
69         input IdNumber 1-4 Name $ 6-24 Team $ StartWeight EndWeight;
70         Loss=StartWeight-EndWeight;
71         datalines;

NOTE: Invalid data for EndWeight in line 73 6-11.
RULE:      ----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0
73         1049 Amelia Serrano yellow 145 124
Loss=. EndWeight=. StartWeight=1049 IdNumber=1023 Name=David Shaw red 189 Team=165 _ERROR_=1 _N_=1
NOTE: Invalid data for EndWeight in line 75 6-9.
75         1246 Ravi Sinha yellow 194 177
Loss=. EndWeight=. StartWeight=1246 IdNumber=1219 Name=Alan Nance red 210 Team=192 _ERROR_=1 _N_=2
NOTE: LOST CARD.
77         ;
Loss=. EndWeight=. StartWeight=118 IdNumber=1078 Name=Ashley McKnight red Team=127 _ERROR_=1 _N_=3
NOTE: SAS went to a new line when INPUT statement reached past the end of a line.
NOTE: Missing values were generated as a result of performing an operation on missing values.
      Each place is given by: (Number of times) at (Line):(Column).
      3 at 68:17   2 at 70:17
NOTE: The data set WORK.WEIGHT_CLUB has 2 observations and 6 variables.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      user cpu time       0.01 seconds
      system cpu time     0.00 seconds
      memory              528.18k
      OS Memory           14760.00k
      Timestamp           07/14/2021 06:42:05 PM
      Step Count                        4  Switch Count  2
      Page Faults                       0
      Page Reclaims                     115
      Page Swaps                        0
      Voluntary Context Switches        8
      Involuntary Context Switches      0
      Block Input Operations            0
      Block Output Operations           264


77         ;
78         run;
79
80
81
82

12                                                         The SAS System                       Wednesday, July 14, 2021 06:37:00 PM

83
>>>
```

**Comment by damjankrstajic** [comment]
Great! It works. I justed added "options notes;" as the first line of my SAS code in python and now I can see the Notes. Thanks a lot!!!!

**Comment by tomweber-sas** [comment]
No problem, I like these easy ones :)
