### ISSUE TITLE
No output without ODS (HTML or Pandas)

### ISSUE THREAD

**Issue by bobburnham** [sassoftware/saspy#40]
This is fantastically cool. I think I have found one issue in sasiostdio.py, but I am afraid I cannot track down the cause yet.

I have a test script that looks like this:

    import saspy
    
    sas = saspy.SASsession(cfgname='default')
    sas.set_results('text')
    sas.set_batch('True')
    
    print(sas)
    
    sas_code = """
    data test_data;
      do x = 1 to 10;
        y = x * 2;
        output;
      end;
      run;
    proc print data=test_data noobs uniform;
      var x y;
      run;
    proc contents data=test_data;
      run;
    """
    
    results_dict = sas.submit(sas_code)
    
    for key in results_dict.keys():
        print(key)
        print(results_dict[key])
		
When I comment out the `sas.set_results` line then I get the expected results back in HTML format. This code will execute properly, and the LOG will indicate the proper number of observations had been printed, but the LST will be empty.

The SAS object looks like this:

    Access Method         = STDIO
    SAS Config name       = default
    WORK Path             = /scratch/[directory on my server]/
    SAS Version           = 9.04.01M0P06192013
    Teach me SAS          = False
    Batch                 = True
    Results               = text
    SAS Session Encoding  = LATIN1
    Python Encoding value = LATIN1

I am running SAS on Linux:

NOTE: This session is executing on the Linux 3.10.0-514.2.2.el7.x86_64 (LIN X64) platform.

**Comment by tomweber-sas** [comment]
Huh, I see that too. I'm not sure why yet, either. I get the proc contents output, but not the proc print output. If I switch the order of the procs, I still only get contents output but not print. If I change contents to print (print sashelp.class); so two proc prints), I get both of the proc print outputs. So, it's not like you only get the last one or something like that.
I will look into this and let you know; very strange. If you only have the proc print, I assume you get the output?

**Comment by bobburnham** [comment]
Tom,

Wow, that is interesting.  Actually, the order does not seem to matter on my system. For example, let's say that I add a few more PROC PRINTs and a PROC MEANS too:

    sas_code ="""
    data test_data;
      do x = 1 to 10;
        y = x * 2;
        output;
      end;
      run;
    proc print data=sashelp.class;
      run;
    proc means data=test_data;
      var x y;
      run;
    proc print data=test_data noobs uniform;
      var x y;
      run;
    proc contents data=test_data;
      run;
    """
	
My theory was that there had to be some timing issue and that the log was returning first, including `logcodeo`, and that the loop was closing before it could read results from STDIN, but that does not seem to be the case.  If I pipe the exact same code through `sas -stdio` then it returns in the expected order.

I'm going to keep looking, but thanks for confirming that you see the same thing.

Bob

**Comment by tomweber-sas** [comment]
Yeah, breaking out of the loop before getting it all would seem a suspect, but I haven't seen that logic fail yet. And, the output would then show up in the next result you get back, which it doesn't.  And, you would get the print if you got the contents,(when print was first). I just ran this and got all of the three reults:
```
sas_code = """
data test_data;
  do x = 1 to 10;
    y = x * 2;
    output;
  end;
  run;
proc contents data=test_data;
  run;
proc print data=test_data ;
  run;
proc print data=sashelp.class ;
  run;
"""
```
So, there's something I'm missing here. I will track it down. It could be a bug even. Just fixed an ODS bug from another issue found using saspy. So, it's possible, though I'm mot gonna speculate till I dig in and see what I find.

And, now you're original case is working 3 times in a row. Must be me somehow. I'll track it down.

**Comment by bobburnham** [comment]
Thanks Tom!

**Comment by bobburnham** [comment]
I had thought that it might be related to this line:

`lst = self.stdout.read1(4096).decode(self.sascfg.encoding)`

I ran PROC OPTIONS on my system, and sure enough BUFSIZE was set to this:

`BUFSIZE=0         Specifies the size of a buffer page for output SAS data sets.`

I was very impressed that saspy respected a `sasv9.cfg` file in the directory when I set the BUFSIZE option to match saspy:

`BUFSIZE=4K`

Unfortunately that did not seem to make any difference, but I'm wondering if that is the type of system level variable that would explain what we are seeing.

**Comment by tomweber-sas** [comment]
So, I have to say, huh, huh, huh?
I looked back at what I ran; I'm running python command line on a linux shell. I thought I saw what you were saying, but looking back, the proc print is actually there in each case. I think it blended in with the contents output on the console, and I 'saw' what I was expecting to see -  what you described. 
Are you running line mode, or in jupyter? not that it should matter. 
Of course, I'm running the latest code. What version are you running. If you get the latest code (pull from github, not pip as there are some changes in the repo that aren't in the latest pip install). And, I don't know of any recent changes that would account for this.
Do you still see this? As I look through the terminal session, I don't actually see a case where the output is missing. 
Sorry for the confusion, but it's actually all running right for me, as it turns out. I can't make it fail.

**Comment by tomweber-sas** [comment]
Here's my original run. Can you send your log, with the saspy version? 
pip list
will show that.

```
>>> import saspy
>>> sas = saspy.SASsession(cfgname='tdi')
SAS Connection established. Subprocess id is 2274

>>> sas.set_results('text')
>>> sas.set_batch('True')
>>>
>>> print(sas)
Access Method         = STDIO
SAS Config name       = tdi
WORK Path             = /usr/tmp/SAS_work602A000008E2_tom64-3/
SAS Version           = 9.04.01M4P11092016
Teach me SAS          = False
Batch                 = True
Results               = text
SAS Session Encoding  = UTF-8
Python Encoding value = utf-8

>>> sas_code = """
... data test_data;
...   do x = 1 to 10;
...     y = x * 2;
...     output;
...   end;
...   run;
... proc print data=test_data noobs uniform;
...   var x y;
...   run;
... proc contents data=test_data;
...   run;
... """
>>>
>>>
>>> print(sas_code)

data test_data;
  do x = 1 to 10;
    y = x * 2;
    output;
  end;
  run;
proc print data=test_data noobs uniform;
  var x y;
  run;
proc contents data=test_data;
  run;

>>> results_dict = sas.submit(sas_code)
>>> for key in results_dict.keys():
...     print(key)
...     print(results_dict[key])
...
LOG

27
28
29   data test_data;
30     do x = 1 to 10;
31       y = x * 2;
32       output;
33     end;
34     run;
NOTE: The data set WORK.TEST_DATA has 10 observations and 2 variables.
NOTE: DATA statement used (Total process time):
      real time           0.07 seconds
      cpu time            0.01 seconds

35   proc print data=test_data noobs uniform;
36     var x y;
37     run;
NOTE: There were 10 observations read from the data set WORK.TEST_DATA.
NOTE: The PROCEDURE PRINT printed page 1.
NOTE: PROCEDURE PRINT used (Total process time):
      real time           0.03 seconds
      cpu time            0.00 seconds

38   proc contents data=test_data;
39     run;
NOTE: The PROCEDURE CONTENTS printed page 2.
NOTE: PROCEDURE CONTENTS used (Total process time):
      real time           0.02 seconds
      cpu time            0.00 seconds

40
41
42
LST
                                                           The SAS System                            14:23 Tuesday, May 30, 2017   1

                                                               x     y

                                                               1     2
                                                               2     4
                                                               3     6
                                                               4     8
                                                               5    10
                                                               6    12
                                                               7    14
                                                               8    16
                                                               9    18
                                                              10    20

                                                           The SAS System                            14:23 Tuesday, May 30, 2017   2

                                                       The CONTENTS Procedure

               Data Set Name        WORK.TEST_DATA                                           Observations          10
               Member Type          DATA                                                     Variables             2
               Engine               V9                                                       Indexes               0
               Created              05/30/2017 14:24:04                                      Observation Length    16
               Last Modified        05/30/2017 14:24:04                                      Deleted Observations  0
               Protection                                                                    Compressed            NO
               Data Set Type                                                                 Sorted                NO
               Label
               Data Representation  SOLARIS_X86_64, LINUX_X86_64, ALPHA_TRU64, LINUX_IA64
               Encoding             utf-8  Unicode (UTF-8)


                                                 Engine/Host Dependent Information

                        Data Set Page Size          65536
                        Number of Data Set Pages    1
                        First Data Page             1
                        Max Obs per Page            4061
                        Obs in First Data Page      10
                        Number of Data Set Repairs  0
                        Filename                    /usr/tmp/SAS_work602A000008E2_tom64-3/test_data.sas7bdat
                        Release Created             9.0401M4
                        Host Created                Linux
                        Inode Number                2362849
                        Access Permission           rw-r--r--
                        Owner Name                  sastpw
                        File Size                   128KB
                        File Size (bytes)           131072


                                             Alphabetic List of Variables and Attributes

                                                    #    Variable    Type    Len

                                                    1    x           Num       8
                                                    2    y           Num       8

```

**Comment by bobburnham** [comment]
Hi again Tom,

Wow, that is interesting, but I'm glad to hear that it is working on your end. There is probably something in my configuration that is different and that I need to track down.  I will download the GitHub version tomorrow, but yes I am running the pip version via the command line.

I am attaching my program and the output (stdout & stderr) below.

Thanks again.  This is a very cool direction for SAS and I appreciate the assistance.

[sas-session.txt](https://github.com/sassoftware/saspy/files/1039855/sas-session.txt)
[output.txt](https://github.com/sassoftware/saspy/files/1039856/output.txt)

**Comment by bobburnham** [comment]
Some progress!! Check out this code:

    sas_code = """
    proc printto file=stdout;
      run;
    data measurements;
      do x = 1 to 100;
        y = x * 2;
        section = mod(x,2);
        output;
      end;
    run;
    proc print data=measurements;
      run;
    proc freq data=measurements;
      table section;
      run;
    """

Adding a call to PROC PRINTTO with STDOUT as the file destination fixes the problem and all of the output is returned exactly as expected. I am not sure that makes sense, because where else would the output be directed to that I would need to set it to STDOUT? But hey, it is nice to have a workaround!

**Comment by tomweber-sas** [comment]
I would check your SAS config and autoexec to see if there's something in there that's redirecting the output. Or, is this a script and maybe it's being redirected in it somehow? I've never seen this before, and it works everywhere I've seen it run without having to do anything special like this. Very strange indeed.

**Comment by bobburnham** [comment]
Yes, I strongly suspect this has something to do with how things are configured on my end.

Thanks for the help.  I will close the issue and let you know if I find anything else out.

**Comment by bobburnham** [comment]
Just one last follow up. I just tried linking this to SAS 9.4TS1M4 and it worked as expected. This may have been an issue with 9.4TS1M0 that has been corrected.

Bob

**Comment by tomweber-sas** [comment]
No kidding? Well, maybe I'll try to dig up that version and see if I see the same thing, when I get a chance.
I'm glad you're up and running on the newer version. And thanks for letting me know!
