### ISSUE TITLE
Is it possible to connect without a sascfg_personal.py

### ISSUE THREAD

**Issue by yobdoy** [sassoftware/saspy#410]
Hi @tomweber-sas 

I can connect just fine using a sascfg_personal.py, just wondering if there is any documentation on doing it without using an external file, and just specify the iomlinux, SAS_Config_names, username and password args directly in the saspy.SASsession statement.

Let me know if you need a vendor case opened

Thanks in advance and best regards,

**Comment by tomweber-sas** [comment]
Hey @yobdoy, yes, in fact you can do that already. On the SASsession() method, you can provide overrides to any of the keys in your existing configuration. And, building upon that capability, you can override all of them, and in that way, effectively provide the configuration definition dynamically. But there's one other trick for this to work; which I've provided for by way of the config file 'lookthrough' that I use and the order of figuring out the access method. In the doc it describes how I find the config file to use; you can have more then one, and they can be in various directories. Failing to find any config anywhere, I fall back to the example sascfg.py file in the install of saspy. This is what worked for UE (University Edition), as the only available config def (listed in  SAS_config_names) was 'default' and that was configured w/ the correct path for UE.

So, if you have no config file, then I will use the 'default' (by default, haha), from sascfg.py, which isn't what you want, but when you provide the actual config def, even for a different Access Method (STDIO is the last one to be used if there are no keys which identify another Access Method: ssh, java, url/io, ...) then your dynamic config def will be honored as is with no other prompting or requirements. You can code individual parameters, just like when you override individual parms, but you can also just create a dictionary and pass that in as **kwargs; which looks a little cleaner:

```
>>> import saspy
>>> iomj     = {'java'      : '/usr/bin/java',
...             'authkey'   : 'saspy1',
...             'iomhost'   : 'localhost',
...             'iomport'   : 8591,
...             }
>>>
>>> sas = saspy.SASsession(**iomj)
SAS Connection established. Subprocess id is 14841

>>> sas
Access Method         = IOM
SAS Config name       = default
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg.py
WORK Path             = /sastmp/SAS_work09E6000039E7_tom64-5/SAS_work56C0000039E7_tom64-5/
SAS Version           = 9.04.01M7D08052020
SASPy Version         = 3.7.5
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 14823

# or, type them in here

>>> sas2 = saspy.SASsession( java = '/usr/bin/java', authkey = 'saspy1', iomhost = 'localhost', iomport = 8591)
SAS Connection established. Subprocess id is 14880

>>> sas2
Access Method         = IOM
SAS Config name       = default
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg.py
WORK Path             = /sastmp/SAS_work09E6000039E7_tom64-5/SAS_work7FA3000039E7_tom64-5/
SAS Version           = 9.04.01M7D08052020
SASPy Version         = 3.7.5
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 14823


>>>
```
So what you see above would work from a fresh install of saspy, never having created a sascfg_personal.py file. I use this in a number of ways here internally as well. So it's an 'on purpose' use case I support, though, no, I haven't documented it. It's just Python so anyone how understands what's going on would know to do that, but I find it easier with most users for them to follow the doc so I can help them when they have something wrong. 

Hope that is what you are looking for!
Tom
