### ISSUE TITLE
unable to connect SAS with saspy

### ISSUE THREAD

**Issue by angusxu458** [sassoftware/saspy#411]
**Describe the bug**
i want to connect SAS in jupyter notebook with sas_kernel, while some problem encountered with saspy.SASsession() on windows10.

**To Reproduce**
```python
import saspy
sas = saspy.SASsession()
```

**Desktop (please complete the following information):**
 - OS: windows10
 - SAS Version: SAS TS level 1M3
 - SASPy Version: saspy3.7.5

**Additional context**
this is my sascgf_personal.py
```python
SAS_config_names=["autogen_winlocal"]

SAS_config_options = {
	"lock_down": False,
	"verbose"  : True
	}

autogen_winlocal = {
	"java"      : "java",
	"encoding"  : "windows-1252",
	'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd="C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE"',
					'-Dlog4j.configurationFile=']
	}

import os
os.environ["PATH"] += ";C:\\Program Files\\SASHome\\SASFoundation\\9.4\\core\\sasext"
```
the output info
```python
Using SAS Config named: autogen_winlocal
Pandas module not available. Setting results to HTML
We failed in getConnection
The security package failed while authenticating a user.
SAS process has terminated unexpectedly. RC from wait was: 4294967290
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program java with the following parameters:['java', '-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd="C:\\PROGRA~1\\SASHome\\SASFOU~1\\9.4\\SAS.EXE"', '-Dlog4j.configurationFile=', '-classpath', 'C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\saspyiom.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\iomclient\\log4j-1.2-api-2.12.1.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\iomclient\\log4j-api-2.12.1.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\iomclient\\log4j-core-2.12.1.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\iomclient\\sas.security.sspi.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\iomclient\\sas.core.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\iomclient\\sas.svc.connection.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\iomclient\\sas.rutil.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\iomclient\\sas.rutil.nls.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\iomclient\\sastpj.rutil.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-internal-api.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-omgapi.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-orb.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\thirdparty\\pfl-basic.jar;C:\\ProgramData\\Anaconda3\\envs\\mysas\\lib\\site-packages\\saspy\\java\\thirdparty\\pfl-tf.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '50702', '-stdoutport', '50703', '-stderrport', '50704', '-zero', '-lrecl', '1048576', '']

Be sure the path to sspiauth.dll is in your System PATH

No SAS process attached. SAS process has terminated unexpectedly.
Invalid response from SAS on inital submission. printing the SASLOG as diagnostic
```
while i run the `java ...` command in cmd alone it comes
```
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at pyiom.saspy2j.main(saspy2j.java:175)
Exception in thread "main" java.lang.NullPointerException
        at pyiom.saspy2j.main(saspy2j.java:184)
``` 
thx

**Comment by tomweber-sas** [comment]
Hey, I'm on vacation this afternoon, and just on my phone, so I may miss something here, but the error is
```
The security package failed while authenticating a user.
```
Which isn't exactly the message I've seen before. Normally an error like this is about not having that sspiauth.dll file path, but you have that in the config. That path is valid? And the file's there? I'm guessing so.
That still leaves me unsure of exactly what's the problem.
The socket failure you get running the command alone is correct and shows that, at least, Java and the classpsth are found and correct enough to get that far; it's gonna fall at that point cuz saspy isn't listing on the socket for it to connect.Assuming what's in your config is correct,, what version of java do you have. the only piece jumping out at me at the moment.
Tom

**Comment by angusxu458** [comment]
sspiauth.dll is located at that dir
![image](https://user-images.githubusercontent.com/12888562/135672680-ebf4161c-b1da-49a0-8de6-14b86aae6a87.png)
my java version is java8 jdk1.8.0_201

> Hey, I'm on vacation this afternoon, and just on my phone, so I may miss something here, but the error is
> 
> ```
> The security package failed while authenticating a user.
> ```
> 
> Which isn't exactly the message I've seen before. Normally an error like this is about not having that sspiauth.dll file path, but you have that in the config. That path is valid? And the file's there? I'm guessing so. That still leaves me unsure of exactly what's the problem. The socket failure you get running the command alone is correct and shows that, at least, Java and the classpsth are found and correct enough to get that far; it's gonna fall at that point cuz saspy isn't listing on the socket for it to connect.Assuming what's in your config is correct,, what version of java do you have. the only piece jumping out at me at the moment. Tom

**Comment by tomweber-sas** [comment]
Ok, that Java should be good. So, does the user you're logged in as have permission to run SAS and access those directories and such. The error isn't that it can't get at the security package, which is the usual one, but that it can't authenticate you. Again I haven't seen that specified error before, so can you that specific issue?

**Comment by angusxu458** [comment]
hi tomwerber,
i use the cmd in administrator mode, thus it should be any permission problem i think.

**Comment by tomweber-sas** [comment]
What happens when you run it as the user you're logged on as, instead of Administrator mode? Can it authenticate the user then?

Also, googling the error, I see a TS track that identifies this being a possible error for not having locahost=127.0.0.1 in your etc/hosts file. See this note here:https://support.sas.com/kb/55/227.htmlI've always seen a different error for that case, but I've also never seen this error, so it's certainly worth a look. Can you see what's in your host file?

Thanks,
Tom

**Comment by angusxu458** [comment]
HI tom,

Thanks very much so far. It does something wrong in my etc/hosts file that it was edited by navicat.
I have fixed it under your suggestion.  Both saspy and sas_kernel works well in jupyter notebook now.

Best regards

**Comment by tomweber-sas** [comment]
That's great! Seems I missed this specific error when documenting this problem in the troubleshooting guide (number 6 here: https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors). That has the link to the same TS note, and this errror: 
```
The application could not log on to the server “localhost:0”. Integrated Windows authentication failed.
```
But, right there in the TS note it shows the error you got, as another possibility. I hadn't seen anyone get that error before. I'll update my troubleshooting guide entry with this error too, so it will be found there. I would have figured it out to begin with :)

Since you're working now, I'll close this. If you need anything else, feel free to reach out again.

Thanks!
Tom
