### ISSUE TITLE
How to make sure saspy connection is encrypted?

### ISSUE THREAD

**Issue by yobdoy** [sassoftware/saspy#413]
Hi @tomweber-sas 

Quick question, related to my previous inquiries.  I was able to get saspy installed and running from databricks, to the point where it tries to connect to our server but then it fails because the firewall is not open.

Before opening up the firewall, the databricks team needs reassurance that when we establish a connection to our SAS server from SASPy the connection will be encrypted.

Is there some additional config that needs to be done to explicitly turn this on? (Databricks team is asking for things like certificates, turning on SSL/TSL, etc -sorry if these don't make sense, I'm only repeating what they said-)

Best regards,

**Comment by tomweber-sas** [comment]
Ok, so IOM. Is the workspace server you're connecting to configured for encryption? Is so, then that would be what would be doing the encryption between the client and that server. There's no encryption in the python process, just between the iOM client and the IOM server (Workspace server). But, that's what's going across the wire.

**Comment by yobdoy** [comment]
Thanks Tom, 

So then, encryption must be configured in the server.  

Is there any documentation specifying how to check if the server I'm connecting to is encrypted?  Or how to check via saspy or Enterprise Guide if the server we're connecting to is configured to accept only encrypted connections?  (or even running a command on the server, I could ask the SAS admins here to check that).

Thanks, just trying to understand what evidence we can send the d.b. guys so they can open the firewall.

Best regards,
