### ISSUE TITLE
Can't connect Windows Client with SAS Linux Server

### ISSUE THREAD

**Issue by luizcbarros** [sassoftware/saspy#415]
**Describe the bug**
I use an EG client machine on Windows that accesses the SAS server on Linux.
On this machine I have Anaconda installed and through Jupyter I try to access SAS but I can't connect, I'm using the “winiomlinux” configuration in the sascfg_personal.py file, I tested ports 8561 and 8591.

**To Reproduce**
Configuration used:

winiomlinux = {'java' : 'java',
                         'iomhost' : ‘XXXXXXX.net’,
                         'iomport': 8561,
                         'appserver' : 'SASApp'
                         }

I've already used PROC IOMOPERATE, the Machine name of the Object Spawner is the same as the Workspace Server.

Using port 8591 gives the error:” We failed in getConnection
The application could not log on to the server "XXXXXXX.net:8591". No server is available at that port on that machine.”

Using port 8561 gives the error: "The client has connected to the SAS Metadata Server (v1.0) when it is intended to connect to the SAS Workspace Server."

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SAS Version: [e.g. 9.4M6]
 - SASPy Version: [e.g. 3.7.5]

Commands  described below:
proc iomoperate;
    list types;
run;

proc iomoperate
  uri="iom://omrhost.abc.xyz.com:8561;Bridge;USER=omruserid,PASS=omrpasswd";
  list DEFINED FILTER="Object";
quit;

Object Spawner - XXXXXXX
        Server class : IOM Spawner
        Spawnable server component : Operating System Services - XXXXXXXXX
        Spawnable server component : SASApp - Pooled Workspace Server
        Spawnable server component : SASApp - Stored Process Server
        Spawnable server component : SASApp - Workspace Server
        Operator port : 8581
        PortBank port : 8801
        PortBank port : 8811
        PortBank port : 8821
        Machine name : XXXXXXX.net

proc iomoperate
  uri="iom://omrhost.abc.xyz.com:8561;Bridge;USER=omruserid,PASS=omrpasswd";
  list DEFINED FILTER="- Workspace";
quit;

SASApp - Workspace Server 
        Server class : 440196D4-90F0-11D0-9F41-00A024BB830C
        Logical name : SASApp - Logical Workspace Server
        Server context : SASApp
        Bridge port : 8591
        Machine name : XXXXXXX.net

**Comment by tomweber-sas** [comment]
Hey @luizcbarros, my first guess is that the failure is because of
```
'appserver' : 'SASApp'
```
That name isn't correct, and the object spawner does a byte compare with that name, so it has to be exact.
Either remove that key (comment it out if you like) since you probably don't need it, or correct it to be
```
'appserver' : 'SASApp - Workspace Server'
```

See if that solves it. Everything else looks correct, from here.

**Comment by luizcbarros** [comment]
Thanks for the reply @tomweber-sas  , but I removed the 'apserver' line and it didn't work I also tried with the corrected 'appserver' line: 'SASApp - Workspace Server' and it didn't work either.

```
winiomlinux = {'java' : 'java',
               'iomhost' : 'XXXXXXX.net',
               'iomport' : 8591
               }
```

Using port 8591 keeps getting the error:” We failed in getConnection.
The application could not log on to the server "XXXXXXX.net:8591". No server is available at that port on that machine.”

I tried to check the connections through the SAS Integration Technologies Configuration Wizard and only the connection with the SAS Metadata Server on port 8561 worked....On Worspace Server and on Object Spawner it didn't connect on port 8591, showing the error:

Connection refused. No connection could be made because the target machine refused it. This usually results from trying to connect to a service that is inactive on the foreign host - i.e. one with no server application running.

Other cfg_personal.py settings:

```
SAS_config_options = {'lock_down': False,
                      'verbose' : True,
                      'prompt' : True
                      }
```

I tried using the 'iomcom' connection but it didn't work, giving the same error:

```
iomcom = {
    'iomhost' : 'XXXXXXX.net',
    'iomport': 8591,
    'class_id': '440196d4-90f0-11d0-9f41-00a024bb830c',
    'provider': 'sas.iomprovider'
    }
```

**Comment by tomweber-sas** [comment]
Well, that leaves me with 2 thoughts, either the machine name for the object spawner isn't being resolved (DNS);  Does the machine name need to be xxxxx.net.something.com instead of only xxxx.net? Or the object spawner isn't up and running on that machine. Do you have a SAS admin who would know the correct machine name/ip of the object spawner for that app server? Yeah, I would use IOM not COM. So lets get that working.

**Comment by tomweber-sas** [comment]
Just to follow up on those thoughts; sorry I didn't have a chance yesterday. I see a different error for the DSN issue than for the case where there's not an Object Spawner listening:
```
# here's a good DSN name, but no spawner
>>> sas = saspy.SASsession(iomhost='tom64-4', cfgname='iomj')
We failed in getConnection
The application could not log on to the server "tom64-4:8591". No server is available at that port on that machine.

# here's a bad DSN name
>>> sas = saspy.SASsession(iomhost='tom64xx-4', cfgname='iomj')
We failed in getConnection
The application could not log on to the server "tom64xx-4:8591". The machine name is not valid.
```
So, it would appear that, even though you saw  that machine name in OMR, that object spawner isn't up on that machine.
Is there a SAS admin you can contact at your site to find out what the right host(s) is (are) where object spawner(s) are running to connect to that workspacce server?

Thanks,
Tom

**Comment by luizcbarros** [comment]
Thanks @tomweber-sas  for the answers, I've already contacted the SAS admin of my company and I'm waiting for an answer.
About 'iomhost' I didn't write the full name of the machine in the comments above but in the configuration I put the full one and it really is in the format xxxxx.net.something.com instead of only xxxx.net

When I get response from the SAS admin I'll let you know.

Thanks.

**Comment by luizcbarros** [comment]
@tomweber-sas  I was able to connect.... Sorry, it was a silly error in the hostname. I don't even believe it.

Thanks a lot for the help!

**Comment by tomweber-sas** [comment]
Hey, that's great news! Better that than the name's right and it doesn't work :)  haha
I'll take the easy ones all day .

I'll close this then, but just reach out again if you need anything1
Thanks,
Tom
