### ISSUE TITLE
SASpy error

### ISSUE THREAD

**Issue by ed8484** [sassoftware/saspy#417]
### Discussed in https://github.com/sassoftware/saspy/discussions/416

<div type='discussions-op-text'>

<sup>Originally posted by **ed8484** November  5, 2021</sup>
`
[<class 'saspy.sasexceptions.SASIONotSupportedError'>, SASIONotSupportedError('STDIO'), <traceback object at 0x000002905FFECAC0>]`

I get this error after importing saspy
`import saspy`

The error that I received is above. I used Anaconda to install SASpy.
I'm using Windows.
I also did download SAS Integration Technologies Client for Windows.

Now, I only have the free SAS studio/SAS OnDemand for Academics. Is this maybe the problem?

I'm guessing I'm missing an important step.

</div>

**Comment by ed8484** [comment]
To add:

The only code is import saspy. I get the error right after that first cell.
I did not do any configuration (this was mentioned in the Q and A) and have no idea what that requires. I assume this may be the issue?

**Comment by tomweber-sas** [comment]
Yes, not configuring it is a problem. But I've not seen any error like this before from nothing but an import statement. Here's the configuration doc:
https://sassoftware.github.io/saspy/configuration.html

What kind of environment are you submitting this in? Any info you can provide will be helpful. I'll look into it on Monday.
Tom

**Comment by ed8484** [comment]
I am submitting this in Jupyter notebook. I use the Anaconda Distribution.
![Screenshot_18](https://user-images.githubusercontent.com/43121335/140614170-b7485df5-06e1-457e-b3b1-ea2a7326103c.png)

**Comment by ed8484** [comment]
"Choosing an Access Method
How do you know how to configure SASPy? Well, the first thing is to know is what SAS instance you are trying to connect to. Next is where are you connecting to it from - what client are you running SASPy on?"

For example, I'm not sure what SAS instance I'm connecting to. I only have the SAS Studio/SAS OnDemand for Academics which I access online for free. I don't have any other SAS software. I use windows 10.

**Comment by ed8484** [comment]
Update:
I have been able to configure things, however; now I don't get errors; it is just stuck on the * forever. 

See below
![Screenshot_19](https://user-images.githubusercontent.com/43121335/140618848-14a6f111-00be-44f6-b520-4e09bfabc53c.png)
:

**Comment by ed8484** [comment]
Hopefully final update. This is the latest error:

![Screenshot_20](https://user-images.githubusercontent.com/43121335/140620780-8b9445d6-7ec4-4a08-a3f3-b250c6298482.png)

**Comment by tomweber-sas** [comment]
Ok, so what I'm seeing is that you are using the SAS kernel for the Jupiter notebook you are using, not the Python kernel for the notebook. Jupyter provides extensibility for different languages in different notebooks (but only one language per notebook). They call the language for the notebook the kernel (language interpreter).

I see you have configured saspy to connect; to ODA you said. Looks like it's working. You can't use any python code in a SAS notebook, you can only use Python (saspy) in a Python notebook. The SAS notebook is only for submitting SAS code, no Python. That kernel just calls saspy under the covers for you; SASsession() to connect, which it did, then submt() for whatever SAS code you type into a cell. The errors you show are SAS errors because it doesn't know Python!

To use saspy yourself, along with any other Python code, use a Python notebook.

I think you are actually good to go!
Tom

**Comment by ed8484** [comment]
Hi Tom,
Sorry I might be a misunderstanding. But it is a SAS notebook. And I have now gotten rid of any reference to Python..but I get the same error.
![Screenshot_21](https://user-images.githubusercontent.com/43121335/140625260-a5ee446d-4e1f-404e-83e4-8c6c916bebad.png)

**Comment by tomweber-sas** [comment]
Yes, you're still confused on something. In jupyter, you can open either a Python notebook, or a SAS notebook.
```
import saspy
```
IS Python code, not SAS code.
```
data a; x=1; run;
proc print; run;
```
IS SAS code.

This picture above is a SAS notebook, and you're trying to submit Python code in it and getting the appropriate SAS error. Same error you'd get if you submitted that in EG.

Are you trying to write SAS code? That's what goes in a SAS notebook. Are you trying to use SASPy and write Python code? Use a Python notebook.

**Comment by tomweber-sas** [comment]
Hey @ed8484, have you got this all resolved and working whichever way you were trying to use it? Anything else I can do, or can we close this?

Thanks,
Tom

**Comment by ed8484** [comment]
I tried only SAS code in a SAS notebook and got the same errors.

> Hey @ed8484, have you got this all resolved and working whichever way you were trying to use it? Anything else I can do, or can we close this?
> 
> Thanks, Tom

**Comment by tomweber-sas** [comment]
Well, you said that last time, but showed a SAS notebook with nothing but a python statement in it and a SAS error that it was invalid syntax, which it was. Can you show me your SAS notebook with SAS code in it and a python note book with python in it? 
The only thing I've seen so far is a SAS notebook with Python code and an appropriate error.

**Comment by ed8484** [comment]
![Screenshot_32](https://user-images.githubusercontent.com/43121335/142486905-90b72230-2fb2-41c2-969b-12613dd32531.png)

**Comment by tomweber-sas** [comment]
ok, that would appear to be a SAS notebook, and it's working.

**Comment by ed8484** [comment]
why am I getting an error for the first cell?

**Comment by tomweber-sas** [comment]
you had an invalid SAS statement, apparently, though that's not in the source in the cell; did you edit that after? but then you aren't looking at the whole log, I don't know what's after that. What you're showing doesn't match. Would need to see the whole thing, not only part of it to be able to have a better idea.

**Comment by ed8484** [comment]
![Screenshot_33](https://user-images.githubusercontent.com/43121335/142488360-3b06c7bd-c103-4f06-a489-e90cdafb2795.png)


**Here is the whole error!**

**Comment by tomweber-sas** [comment]
yep, because that's an error:
```
NOTE: SAS initialization used:
      real time           1.29 seconds
      cpu time            0.23 seconds

  1? data m;
  2? input a b c;
  3? cards;
  4> 0 0 12;

NOTE: The data set WORK.M has 0 observations and 3 variables.
NOTE: DATA statement used (Total process time):
      real time           10.59 seconds
      cpu time            0.06 seconds

4    0 0 12;
     -
     180
ERROR 180-322: Statement is not valid or it is used out of proper order.


  5? run;
  6?
```

So was the case where you had that 'infile;' that you then removed. You have to have SAS syntax right to not get errors from SAS.

Try this:
```
  1? data m;
  2? input a b c;
  3? cards;
  4> 0 0 10
  5> 0 0 11
  6> 0 0 12
  7> ;

NOTE: The data set WORK.M has 3 observations and 3 variables.
NOTE: DATA statement used (Total process time):
      real time           36.66 seconds
      cpu time            0.07 seconds


  8? run;
  9?
```

**Comment by ed8484** [comment]
In SAS System, that would not be an error. The semi-colon does not have to be on a new line.

In any case, thank you!!

**Comment by tomweber-sas** [comment]
Well, yes, I believe it does have to be on the following line. That IS the SAS system. So is the output I ran showing the same error you got. I ran that in SAS:

```
NOTE: Copyright (c) 2016 by SAS Institute Inc., Cary, NC, USA.
NOTE: SAS (r) Proprietary Software V.04.00 (TS04.00M0D11172021)
      Licensed to SAS Institute Inc., Site 1.
NOTE: This session is executing on the Linux 2.6.32-754.11.1.el6.x86_64 (LIN
      X64) platform.



NOTE: Additional host information:

 Linux LIN X64 2.6.32-754.11.1.el6.x86_64 #1 SMP Tue Feb 26 15:38:56 UTC 2019
      x86_64 CentOS release 6.10 (Final)

You are running SAS 9. Some SAS 8 files will be automatically converted
by the V9 engine; others are incompatible.  Please see
http://support.sas.com/rnd/migration/planning/platform/64bit.html

PROC MIGRATE will preserve current SAS file attributes and is
recommended for converting all your SAS libraries from any
SAS 8 release to SAS 9.  For details and examples, please see
http://support.sas.com/rnd/migration/index.html


This message is contained in the SAS news file, and is presented upon
initialization.  Edit the file "news" in the "misc/base" directory to
display site-specific news and information in the program log.
The command line option "-nonews" will prevent this display.




NOTE: SAS initialization used:
      real time           1.42 seconds
      cpu time            0.26 seconds

  1? data m;
  2? input a b c;
  3? cards;
  4> 0 0 12;

NOTE: The data set WORK.M has 0 observations and 3 variables.
NOTE: DATA statement used (Total process time):
      real time           14.84 seconds
      cpu time            0.06 seconds

4    0 0 12;
     -
     180
ERROR 180-322: Statement is not valid or it is used out of proper order.


  5? run;
  6?
  7? data m;
  8? input a b c;
  9? cards;
 10> 0 0 12
 11> ;

NOTE: The data set WORK.M has 1 observations and 3 variables.
NOTE: DATA statement used (Total process time):
      real time           16.09 seconds
      cpu time            0.04 seconds


 12? run;
 13?
```

**Comment by jld23** [comment]
@ed8484 

The `;` has to be on its own line in the cards (datalines) statement.

"The DATALINES statement is the last statement in the DATA step and immediately precedes the first data line. Use a null statement (a single semicolon) to indicate the end of the input data."

here is a [SAS Communites](https://communities.sas.com/t5/SAS-Communities-Library/SAS-Tip-DATALINES-statement-overview/ta-p/557778) article and the [SAS V8 Documentation](https://v8doc.sas.com/sashtml/lgref/z0188182.htm).

**Comment by tomweber-sas** [comment]
So, it would seem that this issue is addressed. You were able to configure SASPy to connect to SAS ODA (I assume that's what you did). And, you can use the SAS_Kernel Notebook to run SAS code, as seen above.
You could also use a python notebook and use saspy, connecting to the same SAS server and write python code w/ SAS interactions via saspy. Don't know if you're even looking at that.
So, is there anything else I can help with, or should we close this issue?

Thanks!
Tom

**Comment by ed8484** [comment]
I've been coding in SAS for years. It works without the semicolon being on its line. 

But thank you for the help on this, and yes, all fixed!
