### ISSUE TITLE
saspy error using windows client

### ISSUE THREAD

**Issue by neocsbee** [sassoftware/saspy#419]
![image](https://user-images.githubusercontent.com/3037022/141529592-7df8313d-c572-45e0-a24a-51e3af531932.png)

Running the ssh command straight from the prompt works and I do get SAS prompt within my Windows prompt. From Python program, it does not work.

**Comment by tomweber-sas** [comment]
Hey, that error says it can't find whatever you put as the path to the ssh command in your config.
The OS error was:
The system can't find the file specified

What's your config?

**Comment by tomweber-sas** [comment]
Sorry, it's in that message (can't cut-n-paste from the picture:
/c/program\ Files\ \....   All that is the problem. What you have in your 'ssh' : '/c/program\ Files\ \.(x86)...'

**Comment by neocsbee** [comment]
![image](https://user-images.githubusercontent.com/3037022/141534989-add7d2e3-7b2d-4d0b-b1bb-870d074adbd2.png)

Here is my sascfg_personal.py

**Comment by tomweber-sas** [comment]
So, you have to make the ssh parameter valid. That sting is the problem.

**Comment by neocsbee** [comment]
I do not see any problem with that string. Can you please suggest a way?

**Comment by tomweber-sas** [comment]
type that into a shell and see if you don't get the same error. The error message gave you the full command to type in to see what happens:
![image](https://user-images.githubusercontent.com/17710182/141535359-0123a87d-e44e-434c-9286-915af6711c23.png)

**Comment by neocsbee** [comment]
I do not get the error when executing from shell.

**Comment by tomweber-sas** [comment]
I have about 15 min right now, can you do a teams thing so I can see what's going on?

**Comment by neocsbee** [comment]
I am not sure I am allowed to do that.

**Comment by tomweber-sas** [comment]
what kind of environment are you trying to run saspy in?

**Comment by neocsbee** [comment]
Windows Python client, SAS Linux server.

**Comment by tomweber-sas** [comment]
are you running python from the same shell?

**Comment by tomweber-sas** [comment]
python and saspy, from the same shell?

**Comment by neocsbee** [comment]
Yes.

**Comment by tomweber-sas** [comment]
the error says that the ssh command (what you provided) isn't found.

**Comment by neocsbee** [comment]
I am trying with Windows style command. Will report if that works.

**Comment by tomweber-sas** [comment]
try bringing up python in the shell and import os and then do an os.dirlist('that path') and see if it complains?

**Comment by neocsbee** [comment]
Will do. Thanks for your help.

**Comment by tomweber-sas** [comment]
No problem, happy to help. Sorry it's late on Friday; if we can get it fixed in the new few, that'll be good!

**Comment by neocsbee** [comment]
No, I understand, thanks again. I will check back with you on Monday. Have a good weekend!

**Comment by neocsbee** [comment]
Hey, it worked!

**Comment by tomweber-sas** [comment]
what did you change it to?

**Comment by neocsbee** [comment]
![image](https://user-images.githubusercontent.com/3037022/141536575-2c453085-2cc5-43e1-8ed0-b749fca478c0.png)

**Comment by neocsbee** [comment]
Thank you so much!

**Comment by tomweber-sas** [comment]
there you go! Nice!

**Comment by tomweber-sas** [comment]
sure thing, want to close this out? Feel free to reach out with anything else you need!

**Comment by neocsbee** [comment]
Yes, will close this! That I will! 🎉
