### ISSUE TITLE
saspy to unpack an EGP file

### ISSUE THREAD

**Issue by neocsbee** [sassoftware/saspy#420]
Is there a way to extract all the sas files within an EGP project file using saspy?

**Comment by tomweber-sas** [comment]
SASPy doesn't have anything that knows about those files, and what's in them varies. But, this came up before and someone said they wrote a tool to help with it. Take a look at this issue, #202 and see if it helps at all. You can just extract the files, and the SAS code can be run w/ saspy. Or the tool may be helpful for running them; I hadn't really looked at it so I'm not sure what it does.

**Comment by neocsbee** [comment]
That is a helpful link. I am not looking to run an EGP file at all, just looking to extract them as separate sas files. Thanks for your reply. I will close this.
