### ISSUE TITLE
Pandas DataFrame to SAS: "None" Values

### ISSUE THREAD

**Issue by gfbarbieri** [sassoftware/saspy#422]
Dataframe2sasdata() to converts a Pandas DataFrame to a SAS dataset, but "None" values in the DataFrame are converted to the string "None". The "None" values are indeed NoneTypes in the DataFrame before converting to a SAS dataset.

**Comment by tomweber-sas** [comment]
Can you show me the code and output showing the df.dtypes and a row of data. Then the output from it. That will help.

**Comment by tomweber-sas** [comment]
Also, what version of saspy and which access method are you using?

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Actually, I see it too. I check for len(0) and for nan, which data frames have even for dtype of Object (strings), sometimes. I wasn't checking for None, but I can easily add that and make it missing too on the SAS data set. Can't believe you're the first to see this! Seems like someone would have notices that before, wow. Should be an easy fix though.

Tom

**Comment by gfbarbieri** [comment]
Tom,

I didn't respond initially because I wouldn't have examples till tomorrow. Seeing this, it looks like you've figured it out--which is great to hear! I appreciate your help and the fact that this product is even available.

GB

**Comment by tomweber-sas** [comment]
Here it is with the fix. I was seeing the string 'None' in column 'a' like you stated prior to this fix.

And, I've pushed this to main, so can you pull it from there and test it out with your scenario, and see that it's behaving as expected for you?

Thanks!
Tom
```
tom64-5> python3.5
Python 3.5.6 (default, Nov 16 2018, 15:50:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy, pandas
>>>
>>> sas = saspy.SASsession(cfgname='iomj');sas
SAS Connection established. Subprocess id is 29143

Access Method         = IOM
SAS Config name       = iomj
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /sastmp/SAS_work7F1000004DCC_tom64-5/SAS_work7E3B00004DCC_tom64-5/
SAS Version           = 9.04.01M4D11092016
SASPy Version         = 3.7.5
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 19916


>>>
>>> df = pandas.DataFrame([{'a':None, 'b':'  ', 'c':' boo ', 'd': ''}])
>>> df
      a   b      c d
0  None       boo
>>>
>>> sd =  sas.df2sd(df)
>>> sd.columnInfo()
     Member  Num Variable  Type  Len   Pos
0  WORK._DF  1.0        a  Char  4.0   0.0
1  WORK._DF  2.0        b  Char  2.0   4.0
2  WORK._DF  3.0        c  Char  5.0   6.0
3  WORK._DF  4.0        d  Char  8.0  11.0
>>> sd.head()
     a    b    c    d
0  NaN  NaN  boo  NaN
>>>
>>> sas.submitLST('proc print data=_df;run;', results='text')

                                                           The SAS System                       16:29 Tuesday, November 16, 2021   1

                                                     Obs    a    b     c     d

                                                      1               boo

```

**Comment by gfbarbieri** [comment]
I have confirmed that the update created the output I expected. I updated my saspy module with the main branch and ran the same code to export the Pandas data frame as a SAS dataset. The "None" values are null character values in the SAS dataset.

**Comment by tomweber-sas** [comment]
awesome, thanks! I'll close this out once I build a new release with this in it. There's another fix from another issue I've pushed and am waiting to hear back on. Once that's verified, I can build a new release with these changes and it will then be the current production version w/ these fixes.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
This is now in the new, current version; v3.7.6, out on Pypi, and here. It'll be build for Conda when the bot notices and schedules it; couple hours or so. I'll go ahead and close this. Let me know if there's anything else!

Thanks!
Tom
