### ISSUE TITLE
SAS session timeout problem

### ISSUE THREAD

**Issue by matsvitt** [sassoftware/saspy#424]
Hi there,

I don't know if this is the right place to ask - however I try it anyway....

I am building a rest-api that is running 24x7 and accesses SAS. So far, everything is running fine (connection, data access etc.) - But when I run the api for , let's say a day, obviously a timeout happens and the session is closed.

So my question is:

- Is there any "heartbeat" method in the SAS session object?
- Can we have multiple SAS Connections or is the Session object a singleton?
- Could we implement "pooled" sessions.
- Or ist the only way to go "poll SAS on a regular basis" or check if a port is open. and re-new the session

Any help is appreciated.

thanks,

Matthias

**Comment by tomweber-sas** [comment]
Hey @matsvitt, which access method are you using? Both IOM and HTTP will have their own timeout configurations. 
You can have as many sessions as you want, you are in control of that. So you could have a pool of them if that's what you needed.
I don't have any kind of heartbeat happening w/in SASPy. It's python, so that's easy enough to do at the application level; just submitting sas.submit("") on whatever interval you want, will do that; though again, depending upon how the server's configured, that may solve it if it's only an inactivity timeout that is what you are seeing. Is this an IOM Workspace server you're connected to?
For HTTP (Viya), there's both an inactivity timeout configured for the Compute Server, as well as a time limit for the authentication token that is required to access the server (or anything in Viya), so that's an extra complication.

**Comment by matsvitt** [comment]
Hey,

Thanks for your message. Yes, It’s an IOM Workspace Server. I think a regular “submit” will do it for now. I don’t have many connections coming in.

Best,

Matthias

**Comment by tomweber-sas** [comment]
Ok, thanks. So it is the Inactivity Timeout that is the reason it's disconnecting you? That should be mitigated by just doing about anything, submit, symget, (about any method). It should be easy to have a separate thread that just has a sleep(x<timeout) and a call to any method. If it's just this inactivity timeout, then that should handle it and you're main thread can do it's usual work. Or any other way you want to implement it (first thought on my end).

**Comment by matsvitt** [comment]
I am now exeucting a submit every 10 seconds which retrievs aleways the same dataset (or part of it) but at some point the session just does not return results anymore. This is really strange. Is there any counter or so that needs to be reset?

**Comment by tomweber-sas** [comment]
Can you show me what you're doing and what the output is? I don't really have any idea just based upon that. How many iterations did you do before you didn't get results? And what does 'didn't get results' actually mean? Did it hang, disconnect, work but w/out expected output (and keep going)?
Thanks,
Tom

**Comment by matsvitt** [comment]
Hi there,

this code does start a minimal flask api using a single endpoint (hiere "/suppliers"). then there is a "keep alive" thread that executes every 10 seconds this endpoint. If it gets a problem it creates a new SAS session. However what I see is, that at some point of time (ususally after 15 minutes or so). the requests stall, i.e. the session object is there (having a SASpid), but the query using submit hangs and nothing happens anymore. No exception is thrown.

```

from flask import Flask,request, jsonify
import time as time
import threading
import saspy as saspy
import pandas as pd
from flask_restx import Resource, Api, fields
import os
import logging
import json
import requests
import asyncio

if __name__ == '__main__':
   logging.basicConfig(
   filename = f"./restapi.log",
   level = logging.DEBUG,
   format = f"[%(asctime)s-service] %(levelname)-7.7s %(message)s",
   datefmt="%Y-%m-%d %H:%M:%S")



app = Flask(__name__)
api = Api(app)

app.config["DEBUG"] = False


def runsas(message,sasSession,str):
   xcode = sasSession.submitLST(str);
   logging.info("Submitted query. Now gathering results")


def ensureConnection(xx):
   _session = None
   try:
       _session = xx.getSession()
       if _session == None:
           raise Exception("EnsureConnection No SAS available. None attached")
       logging.info(f"Using {_session.SASpid}")
       _session.submit("%put _all_;");
   except Exception as ex:
       logging.debug(f"{ex}")
       exStr=f"{ex}"
       if "attach" in exStr:
           logging.info("Creating new SAS Connection")
           _session = saspy.SASsession(cfgfile=f"{dir_path}\\sascfg_personal.py",results='html')
           xx.setSession(_session)

   return _session

def dataset_to_json(sasSession,tablename):
   sas_result=sasSession.sd2df(table=tablename,libref="WORK")
   df = sas_result
   logging.debug(df.head(1))
   return json.loads(df.to_json(orient="records"))

global dir_path
dir_path = os.path.dirname(os.path.realpath(__file__))


global xax

from functools import wraps

def synchronous( tlockname ):
   """A decorator to place an instance based lock around a method """

   def _synched(func):
       @wraps(func)
       def _synchronizer(self,*args, **kwargs):
           tlock = self.__getattribute__( tlockname)
           tlock.acquire()
           try:
               return func(self, *args, **kwargs)
           finally:
               tlock.release()
       return _synchronizer
   return _synched




class SessionProxy():
   _stop = False;
   _session = None
   mylock = None
   def __init__(self):
       self.mylock = threading.RLock()

   @synchronous('mylock')
   def stop(self):
       self._stop = True
   @synchronous('mylock')
   def isStopped(self):
       return self._stop
   @synchronous('mylock')
   def isRunning(self):
       return self._stop is False
   @synchronous('mylock')
   def setSession(self,session):
       self._session = session
       logging.info(f"Session now {self._session}")

   @synchronous('mylock')
   def getSession(self):
       return self._session

   def __str__(self):
       return "xax://{0}".format(self._value)

xax=SessionProxy()


def get_or_create_eventloop():
   try:
       return asyncio.get_event_loop()
   except RuntimeError as ex:
       if "There is no current event loop in thread" in str(ex):
           loop = asyncio.new_event_loop()
           asyncio.set_event_loop(loop)
           return asyncio.get_event_loop()


def checksas(xax):
"""
this is run in a loop every 10 seconds.
"""
   while xax.isRunning() :
       try:
           loop=get_or_create_eventloop()
           f1 = loop.run_in_executor(None,requests.get,"http://localhost:5000/v1/suppliers")
       except Exception as ex:
           logging.debug(f"Got Exception {ex}")
       finally:
           time.sleep(10)


global looptx
looptx=threading.Thread(target=checksas,args=(xax,))

looptx.start()



@api.route('/v1/suppliers')
class Suppliers(Resource):
"""
ensure that there is connection available
"""
   def get(self):
       qstr="""
           libname _X "D:/SAS/Config/Lev1/SASApp/Data/FinancialManagement/StageFM";
           data suppliers(keep=
               SupplierId
               SupplierName
               SupplierAddress
               SupplierIban
               SupplierCountry
               SupplierVatRate
               );
               attrib SupplierVatRate length=$32.;
               rename
                   MEMBER_ID = SupplierId
                   MEMBER_DESC = SupplierName
                   FTER_ADDRESS = SupplierAddress
                   FTER_IBAN = SupplierIban
                   FTER_COUNTRY = SupplierCountry
                   /*FTER_VAT_RATE = SupplierVatRate*/
               ;
               set _X.FTER_SUPPLIER;

               if strip(member_id) ^= "TOTAL";

               if FTER_VAT_RATE = . then do;
                   SupplierVatRate="";
               end;
               else do;
                   SupplierVatRate=strip(put(FTER_VAT_RATE,BEST.));
               end;
           run;
       """


       result=None
       try:
           _session=ensureConnection(xax)
           runsas("/suppliers",_session,qstr)
           result=dataset_to_json(_session,"suppliers")
       except Exception as ex:
           logging.debug(f"Exception:{ex}")

           result = {"message" : "Error in getting suppliers"}
       finally:
           pass
       return result



if __name__ == '__main__':

   app.run(host="0.0.0.0")
```

**Comment by tomweber-sas** [comment]
Well, that's a lot of orchestration, and I can't say I can debug that in my head. Some of the code, I'm not familiar with either, so I'm not sure what the behavior would be. Guess I'd have the following thoughts on tracking it down.
1) are there any external requests coming in in your test case, or only the internal requests being made in your loop? what happens if you have multiple concurrent requests?
2) what happens if it take more than 10 seconds for the request to complete? Would it deadlock perhaps in the synchronization?
3) what happens if you just code the equivalent request in a loop outside of this, just in a stand alone program? does it work indefinitely or does it also fail similarly after 15 min or so? This kind of shows if it's an issue submitting the codee to SAS or more likely with the orchestration in python.
4) Can you actually tell what the code sequence is when this ends up failing? If not, some diagnostic logging from w/in all these methods could help diagnose where/when it goes south and maybe why.

**Comment by tomweber-sas** [comment]
hey @matsvitt , just an fyi that I'll be out w/out any access to this for the next 2 weeks. Sorry about that, but I'll be back on it when I get back.
Thanks!
Tom

**Comment by tomweber-sas** [comment]
Have you made any progress on looking into any of the things I mentioned above? Or figured anything out about what's going on? I'm back from vacation and holidays, so I can help more if needed.

Thanks,
Tom

**Comment by matsvitt** [comment]
Hi there,

I solved my problems. I moved the “keep alive thread” out of my code and also I am using now a pool of SAS connections -  now everything is running happily. Thanks for your help.

Best,

Matthias

**Comment by tomweber-sas** [comment]
Hey, that's great! Glad you tracked it down. I'll go ahead and close this issue then. Let me know if you need anything else!

thanks,
Tom
