### ISSUE TITLE
The method sd2df_DISK hangs indefinitely on one specific table

### ISSUE THREAD

**Issue by mtoma** [sassoftware/saspy#428]
**Describe the bug**
The method sd2df_DISK hangs indefinitely on one specific table. This table probably contains all kind of obscure characters from human filled forms.

**To Reproduce**
Only can be reproduced in production on that one specific table, I'll need some help to get anu kind of feedback from saspy as for now there is no feedback at all from the method.

**Expected behavior**
This method was working perfectly fine on that same table for some time.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Linux
Access Method         = IOM
SAS Config name       = b2b_sas_server
SAS Config file       = /home/admin/.config/saspy/sascfg_personal.py
WORK Path             = /DATA_01/WORK/SAS_work9C4300006F09_su1455/SAS_work936700006F09_su1455/
SAS Version           = 9.04.01M2P07232014
SASPy Version         = 3.3.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = latin9
Python Encoding value = iso8859_15
SAS process Pid value = 28425

**Additional context**
NA

**Comment by FriedEgg** [comment]
@mtoma Thanks for submitting your bug.  I want to first point out that you are using a quite outdated version of saspy, 3.3.7 compared to the current 3.7.6, so you may first want to simply try updating saspy and see if that clears up this issue as I know the `sd2df` family of functions in particular receive a lot of bugfixes.  If that doesn't resolve the issue, or you are not able to upgrade at this time, it would be best if you are you able to produce a sample data set which contains the suspected troublesome characters that reproduces your issue.  This would go a long way in helping us determine the problem.

**Comment by mtoma** [comment]
@FriedEgg Thanks for your quick reply. Indeed, updating to 3.7.6 solved the issue.
