### ISSUE TITLE
sasPY vs AIX

### ISSUE THREAD

**Issue by pgranat** [sassoftware/saspy#43]
Hi,
tried to run sasPY on AIX machine for testing purposes. Received error 
about lack of attribute forkpty. Which is basically true, as header defining this function (pty.h) is not present in AIX according to gnuLib documentation. [https://www.gnu.org/software/gnulib/manual/html_node/pty_002eh.html](url)

I wonder whether someone ever had an idea of rewriting somehow parts of code using forkpty to achieve same functionality .  (maybe other solution?)

It can be a way to have more "other UNIX" friendly solution, as problem may be visible also in HP-UX, Solaris and so far it's the only issue I've noticed with non-Linux Unix systems and sasPY.

```
bash-4.2$ python3
Python 3.6.1 (default, Jun 24 2017, 19:47:36)
[GCC 4.9.2] on aix6
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession(cfgname='default')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...] /lib/python3.6/site-packages/saspy/sasbase.py", line 232, in __init__
    self._io = sasiostdio.SASsessionSTDIO(sascfgname=self.sascfg.name, sb=self, **kwargs)
  File "[...]/lib/python3.6/site-packages/saspy/sasiostdio.py", line 163, in __init__
    self._startsas()
  File "[...]/lib/python3.6/site-packages/saspy/sasiostdio.py", line 227, in _startsas
    pidpty = os.forkpty()
AttributeError: module 'os' has no attribute 'forkpty'
>>>

```

Pawel

**Comment by pgranat** [comment]
Figured it out. 

Using AIX had to change line

`pty = os.forkpty()`

to 

`pty = pty.fork()`

to make it work via stdio:

```
Python 3.6.1 (default, Jun 24 2017, 19:47:36)
[GCC 4.9.2] on aix6
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession(cfgname='default')
SAS Connection established. Subprocess id is 15991530

>>>
SAS Connection terminated. Subprocess id was 15991530
```

To make it nice and clean it will have to be done more or less like this

```
try:
	pty = os.forkpty()
except:
	import pty	
	pty = pty.fork()
```

In sasiostdio.py and sasioiom.py (although I didn't test 2nd one)

Can rewrite this in spare time

**Comment by tomweber-sas** [comment]
Hey, that's great! Good job. I didn't have an AIX or HP-UP box available to try that out on. Glad you figured it out! That looks like a nice simple change. Simple is the best :)
Yes, please go ahead and do a pull request for this when you have the time. Having others in the community make these kind of enhancements is absolutely what we'd like to see! 
Thanks!
Tom

**Comment by jld23** [comment]
@pgranat Thanks for looking at this. Can you make a PR for us to fold in?

**Comment by pgranat** [comment]
Sure. Have to test it a little bit more though, tommorow 'll make PR

**Comment by tomweber-sas** [comment]
That great! Thanks!
On Jul 2, 2017 2:42 PM, Pawel Granat <notifications@github.com> wrote:

EXTERNAL

Sure. Have to test it a little bit more though, tommorow 'll make PR

-

**Comment by tomweber-sas** [comment]
As you've fixed this, I'll close this issue.
Thanks again!
Tom
