### ISSUE TITLE
No able to connect to SAS server in jupyter notebook

### ISSUE THREAD

**Issue by sumit270993** [sassoftware/saspy#431]
Using SAS Config named: oda
We failed in getConnection
The application could not find a command to launch a SAS Workspace Server.
SAS process has terminated unexpectedly. RC from wait was: 4294967290
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

**Comment by tomweber-sas** [comment]
Hey, sorry to not have responded. Just got back from vacation. I'll need some information to help you. Can you show me your config file? Given the error, it seems you're trying to start a local SAS session on your PC. But w/out knowing how you configured it, and what you're really trying to connect to, I don't have any info to go on. Can you tell me where SAS is that you're trying to connect to (I would assume SAS ODA, given the name of the config definition, but that's just a variable name, so I'm not going to assume).

Thanks,
Tom

**Comment by tomweber-sas** [comment]
@sumit270993 is this still an issue for you? Can you provide any information; your configuration and where you client is and what SAS system you're trying to connect to?

Thanks,
Tom

**Comment by sumit270993** [comment]
Yes the issue is still not resolved,  I am working on VM using citrix.. and the software we use to connect to sas server is secure FX and sas enterprise guide.

**Comment by tomweber-sas** [comment]
Hey @sumit270993 thank for replying, but that still provides me no information with which to try to help you. Can you show me your config file?  Since you mention EG, I have to guess you're trying to connect to a SAS 9.4 Workspace Server? Is that correct?

**Comment by tomweber-sas** [comment]
So, do you still need help on this? If so, I'm going to need to have some information on what you're doing and how you've configured saspy? Where is the client and where is the SAS server? Show me your configuration you're using. Other than the error seeming to show that you've tried to configure it for a local windows SAS deployment, I have no information with which to help you.
Thanks,
Tom

**Comment by tomweber-sas** [comment]
If you still need help with this, feel free to reopen, but I have no information to be able to help you figure out what you need. I'm going to close this since there's been no movement on this. It sounds like you are trying to connect to a workspace server, remotely, which is the IOM (Remote)) Access Method, which is documented [here](https://sassoftware.github.io/saspy/configuration.html#iom-using-java). But I don't have any real way to help, so far.
Thanks,
Tom
