### ISSUE TITLE
I can´t found the shared libraries

### ISSUE THREAD

**Issue by Vexillumsoft** [sassoftware/saspy#436]
Hello,

I am using saspy for the first time with SAS EG 6.1. To connect I am using:
```
iomwin   = {'java'      : 'C:\\Program Files (x86)\\Java\\jre1.8.0_261\\bin\\java.exe',
            'iomhost'   : 'vexsas.vexillum.com', #-- > For safety, I cannot share my real host, but it is similar to this
            'iomport'   : 8591,
            }

sas = saspy.SASsession(cfgfile ='C:/Users/vexiart/Desktop/sascfg_personal.py')

```
![image](https://user-images.githubusercontent.com/62475549/147756168-898becc4-0fd3-40ed-9164-f6a09d34404c.png)

And my connection is successful:

```
Using SAS Config named: iomwin
SAS Connection established. Subprocess id is 14280
```
But when I go through my libraries, I only have these:

```

sas.assigned_librefs()

['WORK',
 'SASDATA',
 'MAMISC',
 'STPSAMP',
 'MAMOLIB',
 'MASTATIC',
 'MATABLES',
 'WRSTEMP',
 'WRSDIST',
 'SASHELP',
 'MAPS',
 'MAPSSAS',
 'MAPSGFK',
 'SASUSER']

```
**I have many libraries and I need to access library A. This is a shared library.**

![image](https://user-images.githubusercontent.com/62475549/147756886-8270de82-40ef-46ab-9100-971701dbeb75.png)

I guess I have to connect to a specific server but I don't know which one.

```
Operating System Services - vexsas (#.#)
        Server class : b379c9c1-89e0-4e72-ba43-6a416899b5dd
        Logical name : Operating System Services - vexsas
        Bridge port : 8451
        Machine name : vexsas

    SASApp - SAS DATA Step Batch Server (#.#)
        Server class : e20e54b3-e5f4-47ed-b21d-03109bf9a4b8
        Logical name : SASApp - Logical SAS DATA Step Batch Server
        Server context : SASApp
        Machine name : vexsas

    SASApp - Pooled Workspace Server (#.#)
        Server class : 620963ee-32bf-4128-bf5f-4b0df8ff90eb
        Logical name : SASApp - Logical Pooled Workspace Server
        Server context : SASApp
        Bridge port : 8701
        Machine name : vexsas

    SASApp - Stored Process Server (#.#)
        Server class : 15931E31-667F-11D5-8804-00C04F35AC8C
        Logical name : SASApp - Logical Stored Process Server
        Server context : SASApp
        Bridge port : 8601
        MultiBridge port : 8611
        MultiBridge port : 8621
        MultiBridge port : 8631
        Machine name : vexsas

    SASApp - Workspace Server (#.#)
        Server class : 440196D4-90F0-11D0-9F41-00A024BB830C #----> Try this one but I have the same results when i use "iomcom"
        Logical name : SASApp - Logical Workspace Server
        Server context : SASApp
        Bridge port : 8591
        Machine name : vexsas

    Connect Spawner - vexsas (#.#)
        Server class : Connect Spawner
        Spawnable server component : SASApp - Connect Server
        Operator port : 7541
        Machine name : vexsas

    SASApp - Connect Server (#.#)
        Server class : 028e4060-d545-11d5-880d-aa0004006d06
        Logical name : SASApp - Logical Connect Server
        Server context : SASApp
        Machine name : vexsas

    Share Server - vexsas (#.#)
        Server class : SHARE
        Machine name : vexsas

    SASApp - SAS Digital Marketing Java Batch Server (#.#)
        Server class : 0069e914-b58c-4094-a686-a87df433ec4b
        Logical name : SASApp - Logical SAS Java Batch Server
        Server context : SASApp
```
Maybe it could be another problem but I don't know. Please help me.

Thanks.

**Comment by tomweber-sas** [comment]
Hey @Vexillumsoft, it appears you're connecting to the workspace server in your list. SASPy only connects to a Workspace server, so none of those other server types would work. So, when you connect to that workspace server via EG, you're saying there are other libraries already assigned in your session, but not when you connect via saspy?
If these other libraries are assigned as part of the workspace server configuration, then they should be there regardless of which client connects. Are you using the same credentials to connect w/ saspy as you are with EG? That could make a difference, if the metadata for these libraries requires permission or something.
Is EG connected to the workspace server, and not one of the others?

**Comment by tomweber-sas** [comment]
Is there any info you can provide me to help see if you're connected to the same server from EG and SASPy? Are the libraries you're asking about pre-assigned? Or are you just looking to assign the librefs from code? I'm not sure what that part of a picture is from above, that has 'A' and you say it's a shared library. I'm\not sure what that really is or then what's different in between what you're seeing. I need a little more to go on to help figure out what you need.
Thanks,
Tom

**Comment by tomweber-sas** [comment]
If you still need help with this, feel free to reopen. but w/out any info or response, I'm going to close this just to clean up.
Thanks,
Tom
