### ISSUE TITLE
Idea: Allow custom sascfg.py location

### ISSUE THREAD

**Issue by bbs-csel** [sassoftware/saspy#46]
Hi,

As far as I can tell it's not possible to override the location of where the config-file to look in when establishing the initial SAS-connection (if I'm mistaking, please let me know how - I've been unable to find it in the docs), which makes it harder to versionize and deploy saspy across different enviroments, since one usually wouldn't track changes in the module folder but only the code base. 

One could just put in all the parameters when constructing the connection, but it seems messy compared to maintaining a config-file. Alternatively one could store the config-file in the version-control system and override the package supplyed config on each pull but that again seems cumbersome compared to just pointing to the config-file in the code.

I'm not confident enough with my Python skills to do a pull-request myself, but I'd love to help out in any way I can.

**Comment by bbs-csel** [comment]
Hi again,

An alternative approach to make the config-file relocateable is to have a "dummy" config enabled by default for each connection-type (STDIO, IOM, SSH, Local) and overriding of config at runtime enabled. In that case kwargs on the SASsession can be used to apply the actual config and the config-file location will matter less (and updates of the package easier since one don't need to save and reapply the config-file being overwritten by PIP). Code-wise all the components are there - just the default config that needs changing for this approach.

**Comment by tomweber-sas** [comment]
Hey, sorry for not getting back right a way. So, I'm not 100% sure I understand, but your last post makes me think I'm closer to getting it. Is it that when you pull new code, the sascfg.py can overlay the one you've configured with all your various connection possibilities? The sascfg.py can have all of the different config definitions for all of the different SAS sessions you could get to and you just use SASsession(cfgname='whichone')

As for that config being overlayed upon upgrade, I already have a solution for that in the code, I just haven't gotten to documenting it; I think I'll do that today if I get the chance :)

You can copy sascfg.py to a file named sascfg_persional.py and have all of you configuration in that file. That file doesn't exist in the repo, so it will never be overwritten when you upgrade. You configuration will remain intact. This has been in the code base for some time now. The code tries to import the _personal first, and if that fails it goes to the sascfg.py. 

Does that address your concerns, or maybe only partially? Or not at all? The thing about the cfg file is that it is 'imported' so that everything in it can be directly referenced. I believe that you can add locations to the search path for the import system (I'm not really sure either, this is my first python program; I had to teach myself python to write it). But as long as 'import' can find the file (clearly it's found when in the install location for the package), you could put it anywhere you like. If the real problem is upgrading, then the sascfg_personal.py will hopefully solve that part of the problem.

Let me know if I'm still missing part of this.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
I added doc for this: https://sassoftware.github.io/saspy/install.html#sascfg-personal-py
Again, let me know if this addresses your concerns or if I still need to understand this better.

Thanks,
Tom

**Comment by bbs-csel** [comment]
Hi Tim,

Thanks for getting back. Seen in hindsight I can see my description being a bit weak - I'll try to remedy that below with a more thorough example since what you propose doesn't completely solve the issue (although it's quite an improvement!).

The issue I’m trying to address is two-fold. The first problem is the one that the _personal file remedy which is that the custom configuration will be overwritten on each pull meaning the config will need to be redeployed at each update.

The second issue which still persist, is the fact that most python developers would leave the modules imported though pip outside the repo to keep the repo clean and not track modules outside the project, but instead just reference them in e.g. a requirements file and pull them every time you do a redeployment of the code in the repo. The consequence of this is, that if you update the configuration file (e.g. change the location from which credentials is pulled – in my case they are provided by a setup script and stored in a DB external to the application – or you setup an additional environment for people to use) you’re unable to push these changes to the config along with the rest of the updated code-base. This pose two issues: 1) you need to separate flows for deploying new code (one for the code + pip, one for the config) and 2) in case of a roll-back it’s not just rolling back to a specific commit but you need to dig up the old config-file and redeploy that though other means.

I propose two different solutions to this issue.

Solution 1) When you instantiate the SASsession there could be a parameter which will allow you to overwrite the location of the config-file so it can be kept somewhere in the repo and have a fallback to the “default” location of the config-file. This parameter would be used in the import-statement and with the personal and default config as fallback. 

Solution 2) The config-paramter should allow one to just provide a dict identical to the one found in the config-file. In that case it will skip looking in the config-file and use that instance instead. This could be decided based on if the parameter is a string (name of a config) or of type dict. This will require a not insignificant code-change across all config-objects to implement it properly as far as I can tell. I’ve managed to implement a quick-and-dirty fix with a relatively small code-change but I would recommend against taking that approach and rather re-think how the config-objects work to accommodate such a change in an efficient and clean manner.

Both of the above suggestions have the advantage of putting the config back in the code, allowing us to versionise it quite straight forward compared to having a bunch of symlinks and/or build-scripts that try to deal with this.

Let me know what you think and please don’t hesitate if it’s still a bit unclear.

**Comment by tomweber-sas** [comment]
@bbs-csel I still have to admit my ignorance here. There still some things I don’t understand. So, let me try proposing something and you tell me the parts of it that don’t work.

1)	Don’t touch the sascfg.py file at all. Consider it an example, not something you update.
2)	Create the sascfg_personal.py file (copy sascfg.py and edit it appropriately), and store it anywhere on the file system you like. I think you don't want it in the saspy repo, right?
3)	Append the path to where you stored it to your PYTHONPATH variable, or issue the following before importing saspy (either way should work, sys.path is populated from PYTHONPATH).
```
import sys
sys.path.append('your path to sascfg_personal.py')
import saspy
```
By having your sascfg_personal.py anywhere you want it; out of the repo like I think you're asking for, this will all work as designed and you have no issues with changes in the repo keeping you from pushing or pulling, right?. The config file needs to be imported, and you can store it anywhere you like already. That's what the python search path gets you; the ability to import a module from anywhere on the file system.

Does this get you what you're looking for?

Again, sorry for not seeing the picture clearly.
Tom

**Comment by bbs-csel** [comment]
Hi @tomweber-sas,

What you propose do indeed solve the issue although it seems hacky having to change your sys-path in order for the module to work. What I reckon would be the optimal solution would be allowing to "create" the config at run-time (and not just overwrite already existing) at the point in time where you need the SAS sessesion, e.g. after a user have authenticated against another system and gotten back their SAScredentials or ticket and server-details. An example is this:

We use a scheduling software (non-SAS-product) to run our SAS-jobs. This system takes care of credentials to all systems (incl. databases etc.).

When people submit a job manually they identify themselves to this system which in return will provide them with their credentials in the other system (think delegation not much unlike Kerberos in principale) and which instance to connect to (PROD, TEST, what geografic area etc). For this to work with your approach we'll have to build something into the sascfg_personal that contains all of these combinations and then provide the username and password when we startup SAS. What I would propose is that we can build the "server dict" (identical to those in the config structure-wise) dynamically and pass that to the SASSession-object. That would allow us to change it all in the database and not having to maintain all the different configurations in a seperate file.

Does this help a bit to understand why I try to push for allowing "config creation" dynamicly during the execution instead of relying to "dead" config-files?

**Comment by tomweber-sas** [comment]
So, you want no config file at all, actually, and just pass the parms on the SASsession() call? You can *almost* do this now, but it would require a tweak to the config file for it to work, which means we're still back to a modified config file. Passing the parms as a dict instead of list of keyword values would be another thing to implement. Of course if you can generate the parms as a dict, you can generate them as a list of K/Vs, so that's kind of 6 in one half dozen in the other. 
How many systems are you running saspy on? Is there one system where it's run, and connects to various SAS servers on other different systems? Or, is it installed on everyone's individual machines? Which access methods are you using for connecting to the various SAS servers? IOM or others?
I might have a another idea that would allow you to do what you want, maybe depending on those answers.

**Comment by bbs-csel** [comment]
That's right, and then maybe with a fall-back for config (since many people probably prefer the config-file).

The way I've achived this now is to make a dummy of each needed (IOM and STIDIO) and then allow overwrite, which I then do with kwargs (what I tried to explain in post #2) which is what I suspect you where thinking too (see code below for example)?

```python
SAS_Enviroment  = {
    'java'      : '/usr/bin/java',
    'iomhost'   : conn_details.host,
    'omruser'   : conn_details.login,
    'omrpw'     : conn_details.password,
    #'appserver' : 'SASAppBI',
    'iomport'   : conn_details.port,
    'encoding'  : 'windows-1252',
    #'classpath' : "'{}'".format(conn_details.extra_dejson.get("java_sas_CP"))
    'classpath' : conn_details.extra_dejson.get("java_sas_CP")
}

self.sas = saspy.SASsession(cfgname="iomwin", results='TEXT', **SAS_Enviroment)
```
That combined with the alternative path for _personal will work but still feel a bit hackish (but might just be me).

The amount of combinations is about 10-12 (about half of them being local, the other haft remote/shared servers (prod, test, QC)). Connections to locals are via IOM but prod and test is STDIO for the most part (one execption which is IOM).

**Comment by tomweber-sas** [comment]
Yes, basically, if you create a sascfg_personal.py file and put it in any directory that's already in the pythonpath (I don't think adding a location to the search path is hacky, actually, I think that's the whole point of having a search path; I have to add things to search paths on windows and linux for things to work plenty), and you just have one definition for each access method with only the 'trigger' key, and you set SAS_config_options = {'lock_down': False}, then you can do what you showed above.

This can be your entire sascfg_personal.py:
```
SAS_config_names = ['IOM', 'STDIO', 'SSH']
SAS_config_options = {'lock_down': False}
IOM = {'java'      : 'x'}
STDIO={'saspath': 'x'}
SSH={'ssh'     : 'x'}
```
Then you can build your SAS_Environment as you have and submit the SASsession like you have and it should work today. The only thing you need to do is have that sascfg_personal.py with the 'stub' definitions in a directory in the python search path. Of course, you can put any common keys in the definitions if you don't want to generate all of the them all the time, but if you are generating them all, all you need is a non-zero length value for each of those keys (I just used 'x'). Those keys are what trigger the specific access methods which will then parse your dictionary with the values overriding values.

Thoughts?
Tom

**Comment by bbs-csel** [comment]
Hi @tomweber-sas,

What you propose is pretty much what I ended up doing before opening this issue too - just without the personal config due to not being aware of it's existance.

The part about search-path is not so much to avoid it in general (I use path quite extensively for broadly applied software too), as much as it feels weird to add it for just one module (even though it's only within this session). Considering many projects contain 10-20 modules it would quite easily add up and could end up with conflicts if it was needed for all of them e.g. same name in multiple locations in path but with different content could lead to some hard-to-debug and hard-to-fix problems (under the assumption people generally add entire folders and not just specific files to path). That being said the filename you've opted for is quite unique so it hopefully won't be an issue - just a more general thought.

All that being said it sounds like that's the closest to having a config-generation purely in the application which will work just fine as long as we don't run into overlapping filenames in path.

**Comment by bbs-csel** [comment]
Hi @tomweber-sas ,

I've tried your approach, but seems like it doesn't read the sascfg_personal (see sample-code below, sascfg_personal in the same folder as the script). It only allow those in the "real" config.
`import sys, os
sys.path.append(os.path.dirname(os.path.realpath(__file__)))
import saspy`

I suspect it might be because the import tries to import "saspy.sascfg_personal" and not just "sascfg_personal"?

**Comment by tomweber-sas** [comment]
Hmm, yes I see that. I must have only been trying it with 'import sascfg_personal' when I was testing this out myself. I will investigate removing the 'saspy.' from the internal imports and see if there's any issue with that or not. I can't remember if I qualified that for a specific reason or not; been a long time; probably just narrowing the scope to get the right file. I don't think there will be much chance of finding sascfg_personal in another module though, so I think removing saspy. from the import for the _personal one should be fine.
Then you can have it anywhere. I even tried having it in a directory named saspy, but that didn't make it work either, so it needs to be unqualified it seems.
```
>>> sys.path.append('/u/sastpw/my_personal/saspy')
>>> import saspy.sascfg_personal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'saspy.sascfg_personal'
>>> import sascfg_personal
>>> sascfg_personal
<module 'sascfg_personal' from '/u/sastpw/my_personal/saspy/sascfg_personal.py'>
>>>
```

**Comment by tomweber-sas** [comment]
@bbs-csel  I pushed this fix to master 63bd85a8bef996c70fc74503fdd9cf7860e6c177
Hopefully this addresses it for you and your code will work without issue with this. Give it a try; should be what you tried yourself, but making sure no other issues creep up :)
Thanks!
Tom

**Comment by bbs-csel** [comment]
Hi @tomweber-sas,

Thanks for doing the commit. I've pulled it from the repo and it all seem to work as expected.

Do you expect to push a new version to pip soon?

**Comment by tomweber-sas** [comment]
Good deal. Glad it's working for you too. Well, we just built the current 2.1.6 pip. So I wouldn't be looking to build another until we have more changes and enhancements. Do you need it in a pip?

**Comment by bbs-csel** [comment]
@tomweber-sas It's easier to deploy from but I can do without - I just pull from the repo for now. I'll keep an eye out and switch back to pip when a new version pops up.

**Comment by tomweber-sas** [comment]
Hey, I noticed an issue with this after cleaning up from testing this out. It no longer finds sascfg_personal when it's in the repo (like I have on my system). So, I added back in an attempt to import saspy.sascfg_personal first, then the rest like we had it:
```
try:
   import saspy.sascfg_personal as SAScfg
except:
   try:
      import sascfg_personal as SAScfg
   except:
      import saspy.sascfg as SAScfg
```
The '[install_loc]/site-package' directory is in the search path, but it stops there, so you need the package name as the next level directory to then find files in the package directory: '[install_loc]/site-package/**saspy**/sascfg_personal.py' .

We have some other fixes and PR's in the code base too now, so I'm thinking of building another pip (2.1.7), but there are a couple more things that I expect to go into it in the next week or so. Plus I'll be on vacation some too. so expect a new pip in a few weeks.

I'll close this now; I believe we're square on this. Feel free to reopen if necessary.

Thanks,
Tom
