### ISSUE TITLE
SASPy installation on Windows 

### ISSUE THREAD

**Issue by Pyfin5** [sassoftware/saspy#466]
Hi, 
I tried installing SASpy on windows, but getting the following error. If this issue has been resolved elsewhere, please let me know as I couldn't find anything similar on this forum. 

<img width="960" alt="SASPy" src="https://user-images.githubusercontent.com/88098145/172461274-48767026-b2a6-48cc-9d12-6926f79a1dba.png">

**Comment by Pyfin5** [comment]
Any help would be appreciated. Thanks.

**Comment by tomweber-sas** [comment]
Have you tried using pip from the command line? I haven't seen it work like that from inside a jupyter notebook before; nor did it work in what you showed above. What Python do you have installed? Are you sure you're executing pip from that deployment?

**Comment by tomweber-sas** [comment]
were you able to use pip? Did you get it installed? Do you need anything else, or can we close this?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
If you need any help, feel free to reopen or open a new one for other issues!
Tom
