### ISSUE TITLE
Issue connecting SAS on Linux from Windows Client

### ISSUE THREAD

**Issue by pallavlodhia** [sassoftware/saspy#468]
I am using IOMCOM for connecting to SAS on linux and getting below error . Not sure what is wrong. 

D:\Users\exh3497>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession(cfgfile='D:\\Users\\exh3497\\AppData\\Roaming\\Python\\Python37\\site-packages\\saspy\\sascfg_personal.py')
Using SAS Config named: iomcom
Username: exh3497
Password:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\exh3497\AppData\Roaming\Python\Python37\site-packages\saspy\sasbase.py", line 551, in __init__
    self._io = SASSessionCOM(sascfgname=self.sascfg.name, sb=self, **kwargs)
  File "D:\Users\exh3497\AppData\Roaming\Python\Python37\site-packages\saspy\sasiocom.py", line 204, in __init__
    self.pid = self._startsas()
  File "D:\Users\exh3497\AppData\Roaming\Python\Python37\site-packages\saspy\sasiocom.py", line 254, in _startsas
    server, user, password)
  File "<COMObject SASObjectManager.ObjectFactoryMulti2>", line 4, in CreateObjectByServer
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'SASObjectManager', '<connectionAttempts></connectionAttempts>', None, 0, -2147213310), None)
>>>

**Comment by pallavlodhia** [comment]
This is connection definition 
iomcom = {
    'iomhost' : 'myhoshtname1.com',
    'iomport' : 8591,
    'class_id': '440196d4-90f0-11d0-9f41-00a024bb830c',
    'provider': 'sas.iomprovider',
    'encoding': 'UTF-8'}

**********
Also for Access Method : I want to connect to SAS9.4M7  on linux  from windows machine. Which method is supported ?

**Comment by tomweber-sas** [comment]
Ah, that makes some sense; about why the error. Yes, You can install the jupyter extension SAS_Kernel. It just calls saspy under the covers, which is why you need to configure saspy to begin with. That Kernel allows you to just type in SAS code (there's no Python integration in it), and it just calls sas.submit() with whatever SAS code you typed into a cell. It returns the LST if there is one, else the LOG. That's the same as sas.submitLST() in saspy itself.

**Comment by pallavlodhia** [comment]
I just installed sas_kernel and tried to run code gives error 

proc print data=sashelp.class;run;
[<class 'TypeError'>, TypeError("Frame 0 ({'shell': [b'7ce7caceaa53492bbfe...) does not support the buffer interface."), <traceback object at 0x0000024056CB4DC8>]

**Comment by tomweber-sas** [comment]
Ah, that seems to be an open issue with the SAS_Kernel and maybe the latest Python version?: https://github.com/sassoftware/sas_kernel/issues/83 and https://github.com/sassoftware/sas_kernel/issues/85
Doesn't seem @jld23 has fixed that yet. Maybe if you open another on on there for this issue, it will get some traction and get fixed? Seems there were some work arounds, but I'm not up on that error for that extension.

**Comment by pallavlodhia** [comment]
I have python 3.7 . I just downgrade version of sas_kernel to [V2.1.7 (https://github.com/sassoftware/sas_kernel/releases/tag/V2.1.7) and its working fine without issue.

Thanks for helping out . 🙏

**Comment by tomweber-sas** [comment]
Oh, so backing out SAS_kernel worked too? Good deal. That might be helpful in Jared's digging to figure out what's wrong. Well good, you're all set it seems? Anything else you need?
Thanks,
Tom

**Comment by pallavlodhia** [comment]
We have a grid environment with 5 compute servers. Currently in iomhost we specify only one host. Is there a way to take advantage of grid ?

**Comment by tomweber-sas** [comment]
Hey, yes, you can provide a list of all of those servers for the iomhost key. That is how saspy provides HA (High Availability for Grid), and this supports Grids use of load balanced servers. Note that this is the lists of hosts where the object spawners are running; which may or may not be where the workspace server run. So be sure the configuration has multiple object spawners that you are providing for the iomhost key. Here's a note about it: https://sassoftware.github.io/saspy/configuration.html#remote

There's also the ability (for your admins) to route SASPy work to specific queues on the grid, if they want: https://sassoftware.github.io/saspy/advanced-topics.html#configuring-grid-option-sets-to-have-saspy-run-on-a-specific-queue
Don't know if that matters to them, but they can control that if they want.

**Comment by tomweber-sas** [comment]
Did any of that Grid info help? Able to do what you wanted? Need anything else?

Thanks,
Tom

**Comment by pallavlodhia** [comment]
Yes , it was very helpful. I was able to specify hostnames and its working absolutely fine.  Thank you.

winiomlinux = {'java'   : 'C:\\Program Files\\SASHome\\SASPrivateJavaRuntimeEnvironment\\9.4\\jre\\bin\\java.exe',
            'iomhost'   : ['host1@server.com','host2@server.com'],
            'iomport'   : 8591,
            'authkey'   : 'IOM_Prod_Grid',
            }



Thanks

**Comment by tomweber-sas** [comment]
That's great. I'll go ahead and close this. Let me know if there's anything else.
Tom
