### ISSUE TITLE
Unable to convert Df to SAS dataset

### ISSUE THREAD

**Issue by AnandReddy23** [sassoftware/saspy#469]
Hi Team,

I am executing below simple code that reads a sas dataset to DF and then write back the DF to SAS dataset in the same library and getting below error log. Is dsopts mandatory ?

db=sas.sasdata('TEST','SS',dsopts={'keep' : 'cust_id'})

db=db.to_df()

sas.sd2df(db,'df_sas_table','SS')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-c00a2b644bc5> in <module>

---> 14 sas.sd2df(db,'df_sas_table','SS')

 /projects/lib/python3.6/site-packages/saspy/sasbase.py in sd2df(self, table, libref, dsopts, method, **kwargs)
   1504         """
   1505         dsopts = dsopts if dsopts is not None else {}
-> 1506         return self.sasdata2dataframe(table, libref, dsopts, method, **kwargs)
   1507 
   1508     def sd2df_CSV(self, table: str, libref: str = '', dsopts: dict = None, tempfile: str = None, 

/projects/lib/python3.6/site-packages/saspy/sasbase.py in sasdata2dataframe(self, table, libref, dsopts, method, **kwargs)
   1675 
   1676         dsopts = dsopts if dsopts is not None else {}
-> 1677         if self.exist(table, libref) == 0:
   1678             print('The SAS Data Set ' + libref + '.' + table + ' does not exist')
   1679             return None

/projects/lib/python3.6/site-packages/saspy/sasbase.py in exist(self, table, libref)
    861         :rtype: bool
    862         """
--> 863         return self._io.exist(table, libref)
    864 
    865     def sasets(self) -> 'SASets':

/projects/lib/python3.6/site-packages/saspy/sasiostdio.py in exist(self, table, libref)
   1144       if len(libref):
   1145          code += libref+"."
-> 1146       code += "'"+table.strip()+"'n"+'"'+");\n"
   1147       code += 'v = exist("'
   1148       if len(libref):

/projects/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5139             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5140                 return self[name]
-> 5141             return object.__getattribute__(self, name)
   5142 
   5143     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'strip'

**Comment by tomweber-sas** [comment]
You mention writing back the dataframe as a dataset, and I think you just typed in the wrong method for that:
You had
`sas.sd2df(db,'df_sas_table','SS')` # sas.sasdata2dataframe()
which seems like it should be
`sas.df2sd(db,'df_sas_table','SS')` # sas.dataframe2sasdata()

Probably just a cut-n-paste error. Swap the df and sd and see if that solves it :)
Tom

**Comment by AnandReddy23** [comment]
oh..yeah my bad Tom, I am so sorry I took your time for this silly mistake...
not sure how I missed such a small thing .

many thanks for taking time Tom. Appreciate it !!

**Comment by tomweber-sas** [comment]
No problem. I like these easy ones :)
