### ISSUE TITLE
WORK path from SASsession() is different from local SAS deployment work folder.

### ISSUE THREAD

**Issue by yam3moe** [sassoftware/saspy#478]
Hi,

I am using SASPY for the connection between local SAS install (I believe?) and Python on the same window device.
I could establish the connection using `sas = saspy.SASsesion()`.

The problem arises when I proceed to read a SAS dataset named 't1' in the work folder of SAS.

Using `data_read = sas.sasdata('t1')` returns me an error 
'Table work.t1 does not exist. This SASdata object will not be useful until the data set is created.'

I tried to find out what could be the problem to the best of my ability and I found out that the work path from initiating the SAS session is different from the path directory of work in SAS.

typing 'sas' shows me that WORK path is 
**'C:\...\AppData\Local\Temp\SAS Temporary Files\_TD17036_LCBFI-423A-G1_\Prc2\'**
whereas when I click on the properties of work folder, the path is 
**'C:\...\AppData\Local\Temp\SAS Temporary Files\_TD1104_LCBFI-423A-G1_'**. (photo below)

So, I am at a loss why my SASsession is pointing to a different work path than the one in SAS. I have no idea other how to rectify this problem other than that the two paths should be the same. Any help is appreciated. Thanks!

![Screenshot 2022-08-21 145652](https://user-images.githubusercontent.com/74246882/185808666-04dbfc55-058d-4f21-895a-f459c9126529.png)

**Comment by tomweber-sas** [comment]
Every SAS session has a unique, temporary, WORK library that it creates at startup and deletes at termination. No two sessions share the same WORK library. You use the LIBNAME statement to assign a libref to some directory you want to use across processes (assign the library in each process); that's referred to as a permanent library. You can learn more about how SAS works w.r.t libraries here: https://go.documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/lepg/p0kwlqjluqrm5jn1lz4y3ij4udaq.htm
Tom

**Comment by yam3moe** [comment]
Hi Tom,
I am aware that the work library in SAS is temporary and exists only for the time an SAS session is active. But, what I do not understand is why the default work directory from the initiation of SAS session on jupyterlab has to be different from the temporary work folder of the currently active SAS sesison.

Before I open Jupyter Lab and initiate the SAS session, I opened a SAS session (with its work folder). Thereafter, I went on to initiate the SAS session from Jupyterlab. In this sequence, shouldn't the default work folder from initiation point to the work folder I see on simultaneously running SAS session? I am a little confused here.

**Comment by tomweber-sas** [comment]
What do you mean 'currently active session'?  given this sentence:
`Before I open Jupyter Lab and initiate the SAS session, I opened a SAS session (with its work folder). `
It sounds like you start up your own SAS session (DMS, like in that picture), and then you're saspy to start a session, which has nothing to do with the DMS session you started yourself. Those are 2 different SAS processes, that have nothing to do with one another and don't have the same work library. Same thing would happen if you bring up 2 separate DMS SAS sessions yourself at the same time; they are 2 different processes having nothing to do with one another and have different work libraries.
Is it that you think SASPy is somehow connecting to the SAS session you  started yourself? That's not how it works. SASPy starts it's own SAS session; it can't connect to a DMS session you are already running. I'm guessing that's the confusion?
Do I have that right?

**Comment by yam3moe** [comment]
Hi Tom,

Alright, I understand now. When I start a SAS session from JupyterLab, it was never supposed to be the same as another session I opened on SAS app. Clear now. Thanks!

**Comment by tomweber-sas** [comment]
yeah, there's no way that can work, even from some other client other than saspy either. SAS can't be connected to like that from another client. There are multi user SAS processes, like SAS/Share and Stored Process Servers; multiple clients can connect to those, but SAS on your PC isn't any of that, and SASPy doesn't connect to Share not Stored Process Servers anyway. Each SASsession() you submit creates it's own SAS process that it is connected to. They are all single user sessions, same as starting multiple DMS sessions.

**Comment by tomweber-sas** [comment]
I'll go ahead and close this one. If you need anything else, feel free to open another :)
Thanks,
Tom
