### ISSUE TITLE
ERROR: SAS installation on Python

### ISSUE THREAD

**Issue by saisaspy** [sassoftware/saspy#482]
**Describe the bug**
A clear and concise description of the bug. Then please show the code and run it providing all of the output (don't just cut snippets out of the output). Also, please execute the following and provide all of the output; you only need the print() statements if not running in interactive mode, otherwise they display their info automatically just by submitting the objects/methods:
```
import saspy
print(saspy)
print(saspy.SAScfg)
print(saspy.list_configs())
# if you can establish a SASSession, do so then print it too
# if you can't then provide version information for SASPy with your config info below
sas = saspy.SASsession()
print(sas)
```

**To Reproduce**
1. Submit the following code '...'
2. See that the results are '...' instead of '...'
3. Or, see error '...' instead of it working

**Expected behavior**
A clear and concise description of what you expected to happen if it's not obvious.

**Screenshots**
If applicable, add screenshots to help explain your problem. But, paste code if it's something I will need to run; I can't cut-n-paste from pictures, and don't like to have to transcribe code from a picture :)

**Configuration information. Please provide the configuration you're trying to use (your sascfg_personal.py file) as well as what client system you are on and what kind of SAS deployment you're trying to connect to and where it's deployed (local to the client or remote). **

**Additional context**

**Comment by saisaspy** [comment]
Hi: Issues in installation and configuration - SAS on python.  Any help is greatly appreciated.

Following are the steps that SAS provided.  
I am successfully installed saspy.  But second and third steps is giving me error:

**ERROR: Could not install requirement https://github.com/sassoftware/saspy/releases/saspy-X.X.X.tar.gz because of HTTP error 404 Client Error: Not Found for url: https://github.com/sassoftware/saspy/releases/saspy-X.X.X.tar.gz for URL https://github.com/sassoftware/saspy/releases/saspy-X.X.X.tar.gz**


**Installation
This package installs just like any other Python package. It is a pure Python package and works with Python 3.x installations. To install the latest version using pip, you execute the following:

pip install saspy
or, for a specific release:

pip install http://github.com/sassoftware/saspy/releases/saspy-X.X.X.tar.gz
or, for a given branch (put the name of the branch after @):

pip install git+https://git@github.com/sassoftware/saspy.git@branchname**

**Comment by tomweber-sas** [comment]
I'm afraid I don't understand what problem you are having. Did you install saspy?

**Comment by saisaspy** [comment]
Hi Tom:

I have trues to install saspy and other SAS related python applications.

But the information is not very clear also I tried several  times on my Mac
and finally gave up.

Please provide us step by step mandatory applications to go with python.

Don’t provide ‘or / alternative’ - it’s confusing whether to install that
as well in the steps.

Please don’t provide links rather please provide what’s needed to run SAS
on python.

No good information either in SAS or any websites  for total complete
successful installation steps.

Please advise and provide us your valuable feedback as I extensively use
SAS application to run on python.

If you have any questions please let me know.


Thanks,
HARISH

**Comment by saisaspy** [comment]
Hi:

No, I did not. I gave up as I tried multiple times and does not work for my
Mac system.  I watched YouTube videos but nothing will help me the errors
that I am getting.

I will once again and send you screenshots to this
Email.

Thanks,
Harish

**Comment by tomweber-sas** [comment]
Well, I don't have any information to be able to help you at this point. I don't know what kind of SAS deployment it is that you are trying to connect to. I don't know what configuration you're tried. I don't see any errors from anything posted here. You mention screen shots (again), but I don't (and haven't) seen anything like that. The only thing I see in this track was from trying to use pip install and not seeming to know the syntax. 

I'm happy to try to help, but I have no info at all to go on. Let me know if you want to pursue this or just close it. 

Thanks!
Tom

**Comment by tomweber-sas** [comment]
I'm going to close this, as I have no information with which to help. If you'd like to pursue this further, I need to see your configuration, know what kind of SAS deployment you're trying to connect to, see what errors you're getting, ...
Thanks,
Tom

**Comment by saisaspy** [comment]
Tom: Sure, I will let you know.

Thanks
HARISH

**Comment by saisaspy** [comment]
Tom:

Thanks, I'll check it out.

Thanks for detailed explanation.

HARISH
