### ISSUE TITLE
Running saspy off local machine

### ISSUE THREAD

**Issue by Daviespau** [sassoftware/saspy#49]
I have installed saspy on one of our sas grid servers and this is able to run python queries.

I have now tried to install this on my own PC but I am getting the following Java error:

Please enter the IOM user id: fortis-uk\Daviespau
Java Error:
java.lang.NoClassDefFoundError: com/sas/services/connection/ConnectionFactoryException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sas.services.connection.ConnectionFactoryException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 

Subprocess failed to start. Double check you settings in sascfg.py file.

Attempted to run program C:\ProgramData\Oracle\Java\javapath\java.exe with the following parameters:['C:\\ProgramData\\Oracle\\Java\\javapath\\java.exe', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94260__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94260__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94260__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94260__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '53481', '-stdoutport', '53482', '-stderrport', '53483', '-appname', "'SASAppGrid - Workspace Server'", '-iomhost', 'finsasnode01.fortis-uk.fortis.com', '-iomport', '8591', '-user', 'fortis-uk\\Daviespau', '']

If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
C:\ProgramData\Oracle\Java\javapath\java.exe -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\ProgramData\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 53481 -stdoutport 53482 -stderrport 53483 -appname 'SASAppGrid - Workspace Server' -iomhost finsasnode01.fortis-uk.fortis.com -iomport 8591 -user fortis-uk\Daviespau  

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.

Can you please assist.

**Comment by tomweber-sas** [comment]
Looks like you have a classpath issue. Verify the paths and the jars. Did you try running the command the error says to run?
C:\ProgramData\Oracle\Java\javapath\java.exe with the following parameters:['C:\ProgramData\Oracle\Java\javapath\java.exe', '-classpath', 'C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\ProgramData\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '53481', '-stdoutport', '53482', '-stderrport', '53483', '-appname', "'SASAppGrid - Workspace Server'", '-iomhost', 'finsasnode01.fortis-uk.fortis.com', '-iomport', '8591', '-user', 'fortis-uk\Daviespau', '']

What do you get? Should be the same error, but it could have more information. perhapse, when you run that from the command prompt.

**Comment by tomweber-sas** [comment]
I cut-n-paste the wrong command. It's the one the error message says to run:
C:\ProgramData\Oracle\Java\javapath\java.exe -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94260__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\ProgramData\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 53481 -stdoutport 53482 -stderrport 53483 -appname 'SASAppGrid - Workspace Server' -iomhost finsasnode01.fortis-uk.fortis.com -iomport 8591 -user fortis-uk\Daviespau

You'll find you don't have the right jars, or they aren't in the locations you have in your config file, or you have a typo in your config that's not allowing the jars to found correctly. 

Tom

**Comment by Daviespau** [comment]
HI Tom,

Apologies I have not had time to come back to you on this sooner.

I have reviewed the cause on the link https://sassoftware.github.io/saspy/troubleshooting.html and it seems to indicate that the file paths I have in my config file are incorrect:

cp = "C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\products\\deploywiz__94380__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cp += ";C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\products\\deploywiz__94380__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cp += ";C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\products\\deploywiz__94380__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cp += ";C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\products\\deploywiz__94380__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cp += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar"

However these are the appropriate locations?

[cid:image002.png@01D30D41.76CBF630]

My next thought is that the only difference between the server setup and the local one is that we use enterprise guide on our local machines. I'm not sure if this would cause an issue but thought it best to check before we go any further as the server have client SAS 9.4.

Thanks again for your help with this it is very much appreciated.

Kind regards

Paul Davies
Lead Platform Administrator
Ageas Insurance Limited
Business Intelligence
Tel: +44 (0)2380 353635
p.davies@ageas.co.uk<mailto:Wendy.Stewart@ageas.co.uk>
www.ageas.co.uk

SAS Certified Platform Administrator [cid:image001.png@01D30D40.D1C08700]

**Comment by tomweber-sas** [comment]
@Daviespau , I'm not sure I understand. Looks like you tried to attach a jpg again; those never seems to come through. I can't see it. 
You got a class not found error. Do you even have those jars on your pc? if so, is your path correct? Java doesn't think so.
Do you have SAS on your machine? Are you trying to run against it locally, or again the workspace server on your grid that you've been using?

**Comment by Daviespau** [comment]
HI Tom,

Thought it best to use the hub as part of my email never seem to come through.

Below are the location of the jar files I mentioned again:

cp = "C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\products\\deploywiz__94380__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar" 
cp += ";C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\products\\deploywiz__94380__prt__xx__sp0__1\\deploywiz\\log4j.jar" 
cp += ";C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\products\\deploywiz__94380__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar" 
cp += ";C:\\Program Files\\SASHome94\\SASDeploymentManager\\9.4\products\\deploywiz__94380__prt__xx__sp0__1\\deploywiz\\sas.core.jar" 
cp += ";C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar"

I have attached a screenshot to show that these locations are correct for your sanity. In terms of connection I am using the workspace server as per the settings we put in on the server. In regards to SAS on my machine in my email I mentioned that we are using enterprise guide so not client SAS, this is something I wanted to check wasn't a problem? We are using version 7.1 in case this is relevant.

**Comment by Daviespau** [comment]
[Doc1.docx](https://github.com/sassoftware/saspy/files/1204057/Doc1.docx)

**Comment by tomweber-sas** [comment]
Well, why don't you try copying the jars from one of your deployments that work, to your pc. Just put them in a new directory by themselves. Then point to those in your classpath. With this error you're getting:
java.lang.NoClassDefFoundError: com/sas/services/connection/ConnectionFactoryException
It's a jar issue. I don't know whether there's something different in those jars shipped with EG than in MVA,, so that's the one thing that could be an issue perhaps.

**Comment by Daviespau** [comment]
Thank you Tom.

I have used the jar files from the server so I think there might be an issue using Enterprise guide files for this.

Appreciate your help and please close the track.

Kind regards

Paul Davies
Lead Platform Administrator
Ageas Insurance Limited
Business Intelligence
Tel: +44 (0)2380 353635
p.davies@ageas.co.uk<mailto:Wendy.Stewart@ageas.co.uk>
www.ageas.co.uk

SAS Certified Platform Administrator [cid:image001.png@01D30F92.779BAFD0]

**Comment by tomweber-sas** [comment]
Ok, great! It's possible the EG jversion of the jars is different. Well, apparently it is! 
Thanks,
Tom
