### ISSUE TITLE
Could you make the configuration a little bit Windows oriented?

### ISSUE THREAD

**Issue by bluebirdie** [sassoftware/saspy#504]
I found the documentation is almost 90% about configuration on Linux.
I also use Linux as client but in many cases we also call SAS from Windows client.
Configuration of open source software is often more difficult and less straightforward on Windows.

**Comment by tomweber-sas** [comment]
Can you point me to what pieces of doc, you're referring to? There's a lot of doc. What problem did you have that would be helped by doing something in the doc? BTW, SAS will be closed until Jan 2nd, in the US at least, so I won't be able to look into whatever this is until then. But, wanted to reply as this is the last day before being gone. I was on vacation last week, so today is the only day I've had to check back in on issues.

Thanks,
Tom
