### ISSUE TITLE
Not able to connect to SAS® OnDemand for Academics

### ISSUE THREAD

**Issue by tanish36** [sassoftware/saspy#510]
I am trying to connect to the SAS server using saspy and I am getting the error connection failed.
I have tried doing the same on Google Colab and Linux facing the same issue in both.

```
import saspy
sas = saspy.SASsession(java='/usr/bin/java', iomhost=['odaws02-apse1-2.oda.sas.com'], iomport=8591,omruser ='user' ,omrpw = 'pass')
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Submit the following code 

**Expected behaviour**
it should get connected to SAS Server

**Screenshots**
![image](https://user-images.githubusercontent.com/30778739/213153278-bee03209-b03d-4f4c-9cc6-fc09edb40e73.png)

**Configuration information. Please provide the configuration you're trying to use (your sascfg_personal.py file) as well as what client system you are on and what kind of SAS deployment you're trying to connect to and where it's deployed (local to the client or remote).**

Not using the sascfg_personal.py directly feeding the parameters here 

**Additional Context**
This was working in November 2022 but not now

**Comment by tomweber-sas** [comment]
Hey @tanish36, SAS ODA updated the version of SAS they are using to 9.4 M7 which requires the 3 encryption jars that cannot be included in the SASPy repository on github. They are available in any SAS deployment, but using ODA, you don't have an install available in which to get them. So, there's a download you can use to get them. You can see the documentation for this [here](https://sassoftware.github.io/saspy/configuration.html#attn-as-of-saspy-version-3-3-3-the-classpath-is-no-longer-required-in-your-configuration-file) which includes the link to the download.

Thanks,
Tom

**Comment by tanish36** [comment]
Hi @tomweber-sas 

Thanks for the information was not aware of these changes

**Comment by tomweber-sas** [comment]
Yeah, it happened just before Christmas. Caught me off guard too! But the jars should get you going. Let me know if you need anything else!
