### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by jrderek** [sassoftware/saspy#511]
Cannot use STDIO I/O module on Windows. Try the following: IOM

**Comment by jrderek** [comment]
any idea how to solve Cannot use STDIO I/O module on Windows. Try the following: IOM?

**Comment by tomweber-sas** [comment]
Yes, there's documentation which explains which access method you can use, depending upon what kind of SAS deployment you're trying to connect to (SAS can be deployed in many different ways), as well as how to configure each of them. Look [here](https://sassoftware.github.io/saspy/configuration.html#choosing-an-access-method). So, this error implies that you haven't configured saspy, just using the 'default' example config, which isn't a configuration that is valid on windows. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Were you able to connect to whatever kind of SAS deployment you are using? if you need help, let me know.

**Comment by tomweber-sas** [comment]
Let me know if you need anything. Hopefully reading the configuration doc will suffice.
