### ISSUE TITLE
Function Definition Changes Needed for test_sasstat

### ISSUE THREAD

**Issue by dmsenter89** [sassoftware/saspy#515]
The file test_sasstat.py requires some changes to the function definitions. Many of the included tests aren't run when using `python3 -m unittest ...` since the function names do not start with the `test_` prefix. Examples include [regResult1](https://github.com/sassoftware/saspy/blob/f2c35ea7483963e4185cf916f9342e3e43bdd25c/saspy/tests/test_sasstat.py#L147) through [regResult4](https://github.com/sassoftware/saspy/blob/f2c35ea7483963e4185cf916f9342e3e43bdd25c/saspy/tests/test_sasstat.py#L167), and then from [phregResult1](https://github.com/sassoftware/saspy/blob/f2c35ea7483963e4185cf916f9342e3e43bdd25c/saspy/tests/test_sasstat.py#L393). Several of the test names are also not informative of what test is being run. I propose changing the names of the non-running functions so that these tests will be included in unittesting. 

I'm happy to work on this project and submit a PR when done.

**Comment by tomweber-sas** [comment]
Thanks @dmsenter89, yes, as we've seen there are a number of issues with that file and the tests. It would be great if you wanted to clean those up. I appreciate it!
Thanks,
Tom
