### ISSUE TITLE
Some Defaults For Plot Requests are Non-Standard for PROCs

### ISSUE THREAD

**Issue by dmsenter89** [sassoftware/saspy#516]
The function `SASProcCommons._makeProcCallMacro` sets some defaults for PROC calls that are non-standard. Specifically, it sets the procopts `plot=all` by default for [STAT](https://github.com/dmsenter89/saspy/blob/f2c35ea7483963e4185cf916f9342e3e43bdd25c/saspy/sasproccommons.py#L226) and [ETS](https://github.com/dmsenter89/saspy/blob/f2c35ea7483963e4185cf916f9342e3e43bdd25c/saspy/sasproccommons.py#L231) PROCs (with an exception introduced in #514). This is non-standard; the correct procopts is `plots=all` (with plural s). See for example [PROC TIMESERIES](https://support.sas.com/documentation/cdl//en/etsug/68148/HTML/default/viewer.htm#etsug_timeseries_syntax02.htm), [PROC UCM](https://support.sas.com/documentation/cdl//en/etsug/68148/HTML/default/viewer.htm#etsug_ucm_syntax02.htm), [PROC REG](https://go.documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/statug/statug_reg_syntax01.htm#statug.reg.procplots), and [PROC TTEST](https://go.documentation.sas.com/doc/en/pgmsascdc/9.4_3.4/statug/statug_ttest_syntax01.htm#statug.ttest.tteploopt). Some, but not all, PROCs may translate `plot=all` to `plots=all` behind the scenes, but is safer to use the language default. 

I propose changing the two defaults to `plots=all`. I'm happy to make a PR fixing this.

**Comment by tomweber-sas** [comment]
Sounds great! Thanks again for contributing fixes!
