### ISSUE TITLE
Not able to configure saspy on window

### ISSUE THREAD

**Issue by krishmithlesh** [sassoftware/saspy#528]
Using SAS Config named: default
---------------------------------------------------------------------------
SASIONotSupportedError                    Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_29300/3701923454.py in <module>
----> 1 sas_session = saspy.SASsession()
      2 sas_session

~\anaconda3\lib\site-packages\saspy\sasbase.py in __init__(self, **kwargs)
    554                 self._io = SASsessionSTDIO(sascfgname=self.sascfg.name, sb=self, **kwargs)
    555             else:
--> 556                 raise SASIONotSupportedError(self.sascfg.mode, alts=['IOM'])
    557         elif self.sascfg.mode == 'IOM':
    558             self._io = SASsessionIOM(sascfgname=self.sascfg.name, sb=self, **kwargs)

SASIONotSupportedError: Cannot use STDIO I/O module on Windows. Try the following: IOM

Following is my __authinfo file
oda user ...................... password .........

And this how sascfg_personal.py look like
SAS_config_names=['oda']
oda = {'java' : 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath\\java.exe',
#Asia Pacific Home Region 1
'iomhost' : ['odaws01-apse1.oda.sas.com','odaws02-apse1.oda.sas.com'],
'iomport' : 8591,
'authkey' : 'oda',
'encoding' : 'utf-8'
}

I wasted my two days but still not working. getting SASIONotSupportedError: Cannot use STDIO I/O module on Windows. Try the following: IOM

**Comment by tomweber-sas** [comment]
Hey, I'm on vacation and won't be in till Wednesday. From what you show, it looks like it's not using the config file you are showing. After importing saspy issue the following commands to see what config files it finds and used.
saspy.SAScfg
saspy.list_configs()
Info on this can be found in this section of the doc https://sassoftware.github.io/saspy/configuration.html#sascfg-personal-py

**Comment by krishmithlesh** [comment]
My issue is resolved. Thank you so much for giving me help that too you being on leave..

**Comment by tomweber-sas** [comment]
That's great, I'm glad I was able to help you get going!
