### ISSUE TITLE
Has anyone tried reading a .spds9 file using SASPY? 

### ISSUE THREAD

**Issue by sourabh2404** [sassoftware/saspy#540]
Hi has anyone tried importing a .spds9 file to a pandas dataframe ? If so, how?

Thanks!

**Comment by tomweber-sas** [comment]
Well, that's an sdpe table. So you would just assign a libref with the spde engine for the spde data sets you want to process. It's SAS that reads SAS datasets and then saspy converts them to data frames. So something like this
```
sas.saslib(libref='spd, engine='SPDE', path='/whevever/they/are')
df = sas.sd2df(table='sdpe_table', libref='spd')

**Comment by tomweber-sas** [comment]
Were you able to get at your spde table?

**Comment by sourabh2404** [comment]
Hi Tom, 

Apologies for the late reply. I tried the above way but facing some issue. Is there a trial version or testing environment like (academics/ university edition) where I can test the code with the files on SPD engine?

**Comment by tomweber-sas** [comment]
Yes, there's SAS ODA: https://www.sas.com/en_us/software/on-demand-for-academics.html, and that should get you to these instructions, too, the connection details for SASPy, for once you're signed up: https://support.sas.com/ondemand/saspy.html
