### ISSUE TITLE
Can I have multiple concurrent session using SASpy to the same server, using same user / password?

### ISSUE THREAD

**Issue by sourabh2404** [sassoftware/saspy#557]
Hi,

I have a same code which I'm running from different user accounts on a server. The code tries to connect to SAS server and fetch data from it.  Will it give an issue, if all the users on that server are using the same SAS user id/ password during that time?

**Comment by tomweber-sas** [comment]
Well, if you're using user/pw to connect, then you're either using the IOM access method to connect to Workspace servers, or HTTP to bet to Viya Compute servers. Either way, those are single use SAS sessions that are started up when a client requests a connection (SASsession() call). So, no clients are sharing a single server. Each has it's own. So, from the information provided, that should not be a problem. You can start more than one SAS process at a time.

**Comment by tomweber-sas** [comment]
Did this answer your question? Do you need anything else, or should I close this?

Thanks,
Tom

**Comment by sourabh2404** [comment]
Hi Tom,

Thank you for the response. We can close this issue.
