### ISSUE TITLE
Typos in the documents

### ISSUE THREAD

**Issue by shenzj1994** [sassoftware/saspy#558]
**Describe the bug**
There are a few typos in the SASpy documents:
[Link to Document](https://sassoftware.github.io/saspy/api.html)

**To Reproduce**
See screenshot below:
![image](https://github.com/sassoftware/saspy/assets/12000606/0b6cddaf-01b0-4d01-b2cd-e1abbd06e165)

**Additional context**
For future reference, should we continue submit documentation issue in this repo or there is a better place for those?

**Comment by tomweber-sas** [comment]
Hey thanks! I can fix that. Yes, here is good for this. You can even open a PR with the fixes if you want. I can merge them in that way too. I'll fix this and rebuild the doc. Shouldn't take but a few minutes.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
I found a half dozen of that typo; cut-n-pasted in a bunch of places. Should all be fixed now!

**Comment by tomweber-sas** [comment]
Would you mind double checking that I got all of the ones you saw, and if so, we can close this?
Thanks!
Tom

**Comment by shenzj1994** [comment]
Thank you @tomweber-sas . I think they are fixed.
Did not realize there is a branch stored those HTML docs. Thanks for your reminder and I will do a PR in the future for those.

**Comment by tomweber-sas** [comment]
Actually, in this case, that doc is built from the source (this is the API doc). So, the changes actually went in the source code files, at main here. I just then build the doc and then I push the html to gh-pages. So, it depends upon where the doc picks up the text. The other doc is also here in the doc dir, in .rst files. So yeah, actually, all changes are here in main. Then I build the doc and push the resultant .html file to gh-pages. So, PR's here at main for any typos!
