### ISSUE TITLE
Can't Establish IOM connection on Windows

### ISSUE THREAD

**Issue by johnmrudolph** [sassoftware/saspy#58]
I'm can't connect to local SAS kernal in Jupyter on windows. Very similar to this thread: [https://github.com/sassoftware/saspy/issues/24](url). I'm running SAS 9.4 M4.

Here is the error code returned when I try to run a SAS session with 'winlocal'. From what I can tell I have all the saspy configs set correctly as it appears to be making the Java connection. I also have sspiauth.dll set correctly in my System Path environment variable. Not sure what else to try.

> The application could not find a command to launch a SAS Workspace Server.
> SAS process has terminated unexpectedly. RC from wait was: 4294967290
> SAS Connection failed. No connection established. Double check you settings in sascfg.py file.
> 
> Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Users\\rudolpj\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil_904400.1.0.20160824190000_v940m4\\sas.rutil.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil.nls_904400.0.0.20160427190000_v940m4\\sas.rutil.nls.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sastpj.rutil_6.1.0.0_SAS_20121211183517\\sastpj.rutil.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '50915', '-stdoutport', '50916', '-stderrport', '50917', '-zero', '']
> 
> Be sure the path to sspiauth.dll is in your System PATH
> 
> No SAS process attached. SAS process has terminated unexpectedly.
> No SAS process attached. SAS process has terminated unexpectedly.
> No SAS process attached. SAS process has terminated unexpectedly.

**Comment by tomweber-sas** [comment]
@johnmrudolph , Yes that does look the same. Have you check your registry and group policy settings, as mentioned in that issue? This appears to be an install issue with Base SAS on windows. Do you have your default action for a .sas file extension to start SAS? Does that work when you double click a .sas file? I think that's one of the things tech support said was related. #24 said they had also had problems getting that to work as well, which pointed to a registry, config issue too.

I think that this issue warrants a Tech Support track to help diagnose this problem. They would be the best resource for windows config issues, as I don't have experience with that. You can open a track w/ TS and tell them that you have already opened an issue on saspy (#58), and that I told you to open the ticket. They should be able to read this and #24 and get you to the right group to diagnose and resolve this.

Thanks,
Tom

**Comment by johnmrudolph** [comment]
The default action for .sas file is to open in SAS Enterprise Guide. I'm unable to check the registry because of a permissions issue - admin has disabled registry editing for my user group. I'll go ahead and reach out to tech support.

**Comment by tomweber-sas** [comment]
Thanks! Let me know what the TS track is, so I can keep an eye on it and be sure it gets to the right folks.

**Comment by johnmrudolph** [comment]
The TS # is 7612219874

**Comment by johnmrudolph** [comment]
As an update SAS technical support said that I needed to enable registry editing to get sasPy to work. The system admins at my company can't do this for my user group because it's a security risk. So looks like I'm stuck for the time being.

**Comment by tomweber-sas** [comment]
Thanks for updating here. Yes, I saw the track and I'm glad that it's a known understood thing, but it stinks that you can't support it's requirement. For the record, this is a Base SAS IOM, local (zero config) connection requirement. There's nothing in saspy that can affect this; I can't work around it.
I did see that they mentioned that this wouldn't be a problem connecting to a remote IOM server, which it wouldn't. 
Is that a possibility for you? Do you have workspace servers set up that you could connect to?  

Sorry about that,
Tom

**Comment by johnmrudolph** [comment]
No unfortunately a remote server is also not an option.   I don't have a good understanding of how the Base SAS IOM zero config connection works but I am able to connect to SAS and run this powershell script: [https://gist.github.com/FriedEgg/9085229#file-sasworkspaceexample-java](url) that was referenced in #24 which I thought was supposed to establish a zero config connection to SAS. How is powershell able to establish a zero config local connection on my machine but not sasPy?

**Comment by tomweber-sas** [comment]
Well, that's a good question. I don't know. I looked at the java code in there and it's the same as in saspy:
```
            ZeroConfigWorkspaceServer server = new ZeroConfigWorkspaceServer();
            ManualConnectionFactoryConfiguration config = new ManualConnectionFactoryConfiguration(server);
            ConnectionFactoryManager manager = new ConnectionFactoryManager();
            ConnectionFactoryInterface factory = manager.getFactory(config);
            SecurityPackageCredential cred = new SecurityPackageCredential();
            cx = factory.getConnection(cred);
```

I don't know how you run this in powershell. But maybe this is worth going back to tech support with. I don't know what the requirement about being able to update the registry is about in the first place, but if it works in that case, maybe there's more to this story.

**Comment by FriedEgg** [comment]
The powershell script uses a COM/DCOM connection to establish the zero config workspace server (aka windows local).  This is a different method that used by the Java client.  It is a good sign that this works for you, however, to properly test how saspy works you would need to test the example in that gist called SASWorkspaceExample-local-ZeroConfig.java, this offers the most direct comparison of what is done by this project.

**Comment by FriedEgg** [comment]
Let's try something a bit out of the box:

In your saspy config you have something like:

```
winlocal = {'java'      : 'java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW
            }
```

For the java key we are going to add some properties to the java command

```
'java': 'java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE -config C:\PROGRA~1\SASHome\SASFOU~1\9.4\sasv9.cfg -objectserver -nologo -noterminal -noprngetlist
```

Setting the System Property com.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd should override the behavior in the ZeroConfingWorkspaceServer to use the registry to find the sas command to launch.  Update the path I included above to meet your specific installation.

**Comment by johnmrudolph** [comment]
OK I updated the winlocal config with my install specs

`winlocal = {'java'      : 'java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\Program Files\SASHome\SASFoundation\9.4\SAS.EXE',
            'encoding'  : 'windows-1252',
            'classpath' : cpW
            }`

But now I'm getting this error because the java command isn't getting recognized with the override properties.

> The OS Error was:
> The system cannot find the file specified
> 
> SAS Connection failed. No connection established. Double check you settings in sascfg.py file.
> 
> Attempted to run program java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\Program Files\SASHome\SASFoundation\9.4\SAS.EXE with the following parameters:['java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\\Program Files\\SASHome\\SASFoundation\\9.4\\SAS.EXE', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Users\\rudolpj\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil_904400.1.0.20160824190000_v940m4\\sas.rutil.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil.nls_904400.0.0.20160427190000_v940m4\\sas.rutil.nls.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sastpj.rutil_6.1.0.0_SAS_20121211183517\\sastpj.rutil.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '49695', '-stdoutport', '49696', '-stderrport', '49697', '-zero', '']
> 
> If no OS Error above, try running the following command (where saspy is running) manually to see what is wrong:
> java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\Program Files\SASHome\SASFoundation\9.4\SAS.EXE -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\Users\rudolpj\AppData\Local\Continuum\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar;C:\Program Files\SASHome\SASVersionedJarRepository\eclipse\plugins\sas.rutil_904400.1.0.20160824190000_v940m4\sas.rutil.jar;C:\Program Files\SASHome\SASVersionedJarRepository\eclipse\plugins\sas.rutil.nls_904400.0.0.20160427190000_v940m4\sas.rutil.nls.jar;C:\Program Files\SASHome\SASVersionedJarRepository\eclipse\plugins\sastpj.rutil_6.1.0.0_SAS_20121211183517\sastpj.rutil.jar" pyiom.saspy2j -host localhost -stdinport 49695 -stdoutport 49696 -stderrport 49697 -zero  
> 
> No SAS process attached. SAS process has terminated unexpectedly.
> No SAS process attached. SAS process has terminated unexpectedly.
> No SAS process attached. SAS process has terminated unexpectedly.

**Comment by FriedEgg** [comment]
You should either use the short name for the path or surround the path with double quotes and try again.

**Comment by johnmrudolph** [comment]
I get the same error if I use the short file path or the full file path in double quotes.

> The OS Error was:
> The system cannot find the file specified
> 
> SAS Connection failed. No connection established. Double check you settings in sascfg.py file.
> 
> Attempted to run program java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE with the following parameters:['java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\\PROGRA~1\\SASHome\\SASFOU~1\\9.4\\SAS.EXE', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Users\\rudolpj\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil_904400.1.0.20160824190000_v940m4\\sas.rutil.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil.nls_904400.0.0.20160427190000_v940m4\\sas.rutil.nls.jar;C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sastpj.rutil_6.1.0.0_SAS_20121211183517\\sastpj.rutil.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '57623', '-stdoutport', '57624', '-stderrport', '57625', '-zero', '']

**Comment by FriedEgg** [comment]
What happens when you just try to run the generated command directly.  Open a new command prompt and try running the following:

```
java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\Users\rudolpj\AppData\Local\Continuum\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 49695 -stdoutport 49696 -stderrport 49697 -zero
```

You should receive an Java error, but I only care that command should work...

**Comment by johnmrudolph** [comment]
Here are the results I get when I run the java command directly

```
C:\Users\rudolpj>java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\
PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE -classpath "C:\Program Files\SASHome\SASDe
ploymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\sas.svc
.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deplo
ywiz__94482__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDep
loymentManager\9.4\products\deploywiz__94482__prt__xx__sp0__1\deploywiz\sas.secu
rity.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deployw
iz__94482__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\Users\rudolpj\AppData\Local
\Continuum\Anaconda3\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -h
ost localhost -stdinport 49695 -stdoutport 49696 -stderrport 49697 -zero
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at pyiom.saspy2j.main(saspy2j.java:119)
Exception in thread "main" java.lang.NullPointerException
        at pyiom.saspy2j.main(saspy2j.java:126)
```

**Comment by FriedEgg** [comment]
OK, that is pretty much exactly what I would expect from that command.  In your saspy configuration you have some additional jar files specified, which are only necessary for remote IOM connections using enhanced encryption.  These should be unnecessary for winlocal, so I would recommend you validate the paths you used or just remove those and try making a saspy connection again.

**Comment by tomweber-sas** [comment]
@FriedEgg thanks for helping out! Yes, that last attempt looks right, though we can't really tell if it would have worked, as I set up the sockets before interacting with IOM at all in the java code. 
@johnmrudolph can you add that -D... in the sasioiom.py file and run it (down around line 300ish)?
```
      pgm    = self.sascfg.java
      parms  = [pgm]

      **parms += ["-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE"]**

      parms += ["-classpath",  self.sascfg.classpath, "pyiom.saspy2j", "-host", "localhost"]
      #parms += ["-classpath", self.sascfg.classpath+":/u/sastpw/tkpy2j", "pyiom.saspy2j_sleep", "-host", "tomspc.na.sas.com"]
      parms += ["-stdinport",  str(self.sockin.getsockname()[1])]
      parms += ["-stdoutport", str(self.sockout.getsockname()[1])]
      parms += ["-stderrport", str(self.sockerr.getsockname()[1])]
```
If that works (IOM actually picks that up and uses it) then I can add a 'sascmd' key the the config definition for the IOM access method so this issue can be worked around this way. That would be great, since this silly IOM restriction has hit multiple people so far and we don't seem to have a defined way to work around it. At least I'll be able to work around it in saspy with this.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
OK, so I played with this here and it does seem to take! I'm also looking at another issue in sas_kernel, which is really a saspy issue, having to do with transcoding (garbage characters in output using IOM access method). I think I have an idea on that too, The reason I mention that is it would also require a -D java option. So, I have code where I added 'javaparms' to the config definition such that we can add a list of java parms as necessary:
```
            'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE', '-Dother_java_parms...']
```
No telling what other java tweaks might be wanted by someone, so this would enable this work around and easily add others adhoc.

Thoughts?
Tom

Oh, and sorry about the **'s in the previous post. I highlighted that and hit BOLD, but that didn't really take inside of the code block snippet. Ger rid of the **'s in the code when you try it.

**Comment by FriedEgg** [comment]
Sounds like a well reasoned decision to add.  Still not sure why my original recommendation [threw an OS error](https://github.com/sassoftware/saspy/issues/58#issuecomment-328231353) though...  I am working on some updates to the java code to allow for better testing through running the python generated command.

**Comment by tomweber-sas** [comment]
I haven't tried it, but my guess is that it's because of the way the execv parms have to be built out in python. Maybe instead of
```
winlocal = {'java' : 'java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\Program Files\SASHome\SASFoundation\9.4\SAS.EXE', 'encoding' : 'windows-1252', 'classpath' : cpW }
```
this might get it to work
```
winlocal = {'java' : ['java', '-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\Program Files\SASHome\SASFoundation\9.4\SAS.EXE'], 'encoding' : 'windows-1252', 'classpath' : cpW }
```
None of the parms can have whitespace. Any separation requires each part to be in it's own list entry.

**Comment by FriedEgg** [comment]
@tomweber-sas, that is why I said to use the short name path (no spaces that way)

```
winlocal = {"java" : "java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\\PROGRA~1\\SASHome\\SASFOU~1\\9.4\\SAS.EXE", "encoding" : "windows-1252", "classpath" : cpW }
```

spaces should cause problems with the command regardless of them being build out by python

**Comment by tomweber-sas** [comment]
Sorry, I cut-n-paste the wrong one, and I probably didn't explain it well. it's not the spaces in the windows file name, it's that 'java' and -D...' are 2 separate list entries. There white space between them. And it's not an issue with how this is in the config definition. It's building the parm list for the execv where this is an issue.
So, instead of this
```
winlocal = {"java" : "java -Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\\PROGRA~1\\SASHome\\SASFOU~1\\9.4\\SAS.EXE", "encoding" : "windows-1252", "classpath" : cpW }
```
try
```
winlocal = {"java" : ["java", "-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\\PROGRA~1\\SASHome\\SASFOU~1\\9.4\\SAS.EXE"], "encoding" : "windows-1252", "classpath" : cpW }
```
But, actually, I don't think this will even happen to work, as the 'java' value is passed as the program name, which won't work. You just won't get away with adding -D things onto the java key. 


Here's a better example of what I was talking about:
If you wanted to pass the following parm
```
-host localhost
```
to a program you execute from python, you build out a parm list. That list would need to be
```
["-host", "localhost"]
```
if you tried to use this instead, it won't succeed
```
["-host localhost"]
```
That's what I was trying to work around. BUT the OS error you got (file not found) is due to the program name that was being given was "java -D...' and there's no file named that. So, it wasn't even getting to the parms issue I was trying to work around. 

When I add in a javaparms key, then you can have this bit in a config def:
```
'java'      : 'java',
'javaparms' : ["-Done", "-Dtwo", "-Dthree"]
```
but it you try to do this, it will not work:
```
'java'      : 'java',
'javaparms' : ["-Done -Dtwo -Dthree"]
or
'javaparms' : "-Done -Dtwo -Dthree"
```

Do I make sense now?

**Comment by FriedEgg** [comment]
yes, makes perfect sense.  I forgot about this quirk with os.execv

**Comment by johnmrudolph** [comment]
Appreciate the effort @tomweber-sas  and @FriedEgg. I'm trying to catch up on the updates from above. I'm a bit stuck at the moment as a system update uninstalled SAS on my machine. Hoping to be up an running again tomorrow. 

Trying to figure out what my next steps are in terms of trouble shooting this. Should I still make the update suggested by @tomweber-sas to sasioiom.py and update the config java definitions?

**Comment by tomweber-sas** [comment]
@FriedEgg yeah, I remember trying to figure out just what it wanted to get that to work the first time! :)
@johnmrudolph I've pushed  this to master. You can pull it and add the following to your config definition and try it to see that it works:
```
            'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE']
```
Don't forget to add a comma to the line before this, or this one, depending upon where you add it into the config def.

Tom

**Comment by johnmrudolph** [comment]
I downloaded the new master #60 and tried to run in Jupyter with the new javaparms config from above. Here is what my config file looks like -  I commented out the client side encryption jars as it sounds like these are not needed for the winlocal connection.

```
# build out a local classpath variable to use below for Windows clients
cpW  =  "C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\log4j.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar"
cpW += ";C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.core.jar"
cpW += ";C:\\Users\\rudolpj\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar"

# And, if you've configured IOM to use Encryption, you need these client side jars.
# cpW += ";C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil_904400.1.0.20160824190000_v940m4\\sas.rutil.jar"
# cpW += ";C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sas.rutil.nls_904400.0.0.20160427190000_v940m4\\sas.rutil.nls.jar"
# cpW += ";C:\\Program Files\\SASHome\\SASVersionedJarRepository\\eclipse\\plugins\\sastpj.rutil_6.1.0.0_SAS_20121211183517\\sastpj.rutil.jar"


winlocal = {'java'      : 'java',
            'encoding'  : 'windows-1252',
            'classpath' : cpW,
            'javaparms' : ['-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\PROGRA~1\SASHome\SASFOU~1\9.4\SAS.EXE']
            }
```
Here is the error I'm getting. I have the path to the sspiauth.dll in my system path so don't think this is the issue.

> The native implementation module for the security package could not be found in the path.
> SAS process has terminated unexpectedly. RC from wait was: 4294967290
> SAS Connection failed. No connection established. Double check you settings in sascfg.py file.
> 
> Attempted to run program java with the following parameters:['java', '-Dcom.sas.iom.orb.brg.zeroConfigWorkspaceServer.sascmd=C:\\PROGRA~1\\SASHome\\SASFOU~1\\9.4\\SAS.EXE', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94482__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Users\\rudolpj\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '50648', '-stdoutport', '50649', '-stderrport', '50650', '-zero', '']
> 
> Be sure the path to sspiauth.dll is in your System PATH
> 
> No SAS process attached. SAS process has terminated unexpectedly.
> No SAS process attached. SAS process has terminated unexpectedly.
> No SAS process attached. SAS process has terminated unexpectedly.

**Comment by tomweber-sas** [comment]
So, that looks like the error you get if you don't have sspiauth.dll in your system path.
[https://sassoftware.github.io/saspy/install.html#local](url)

Can you verify that the directory containing that dll is in your windows system path? And if you just put it there, you might have to reboot windows to get it truly picked up.

**Comment by tomweber-sas** [comment]
well, I didn't do that url thing right. try again
[](https://sassoftware.github.io/saspy/install.html#local)

**Comment by tomweber-sas** [comment]
well that didn't work either.
[3rdtimesacharm?](https://sassoftware.github.io/saspy/install.html#local)

**Comment by johnmrudolph** [comment]
I'm up and running! Had a space before the start of my sspiauth.dll path and needed a reboot. Thanks @tomweber-sas and @FriedEgg for all the help.

**Comment by tomweber-sas** [comment]
Sweet!  Cuz if that wasn't it, I was at a loss :)
Thanks @FriedEgg! and I'm glad to have this working. Guess I'll close this and also reopen #24 to show that fixed too.

Thanks,
Tom
