### ISSUE TITLE
SASPy and SAS on demand for Academics: connection terminates with no error message

### ISSUE THREAD

**Issue by olgacrowley** [sassoftware/saspy#590]
I am running SASPY using these instructions:https://www.listendata.com/2021/01/run-sas-in-python-without-installation.html

Here is my Python code:

import saspy,os
import pandas as pd
import pyreadstat

sas = saspy.SASsession(java='C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath\\java.exe',
iomhost = ['odaws01-usw2.oda.sas.com','odaws02-usw2.oda.sas.com','odaws03-usw2.oda.sas.com','odaws04-usw2.oda.sas.com'],
iomport=8591, encoding='utf-8')
sas

Everything is working fine, SAS connection gets established, but then it automatically terminates right away, and there is no error message. It looks like this ('XXX' stands for my user id and password):

Please enter the OMR user id: XXX
Please enter the password for OMR user :XXX 
SAS Connection established. Subprocess id is 12412

SAS Connection terminated. Subprocess id was 12412

If anyone has ever encountered and resolved this issue, please let me know - I would greatly appreciate it!

**Comment by tomweber-sas** [comment]
How are you submitting that code? It would seem not interactively, but rather in 'batch' mode. Submitting as a file or script. Are you using a UI, like vscode or spider or something?

**Comment by tomweber-sas** [comment]
If you need some help, let me know. Happy to help. But since you've not replied, I'll close this. Feel free to reopen if you need anything.
Tom
