### ISSUE TITLE
Issue writing pandas dataframe to SAS dataset using df2sd

### ISSUE THREAD

**Issue by kwangccc** [sassoftware/saspy#593]
Hi, I am trying to convert a pandas dataframe to sas (sas7bdat) format using df2sd. The dataframe dimensions are roughly 700 columns by 20,000 rows so not considered large. I currently have a run time of roughly 7 hours and counting without completion. I am wondering what the issue is with my code below. Thanks in advance.

Code:
`import saspy`
`sas = saspy.SASsession(cfgname='default')`
`sas.saslib(libref='dat', path='/sasdata/modeling/_datasamples/equifax/data')`
`sas.df2sd(df = ONESCORE_CFN_102023, table = 'ONESCORE_CFN_102023', libref='dat')`

sas object output:

Access Method         = STDIO
SAS Config name       = default
SAS Config file       = [/usr/local/anaconda3/lib/python3.9/site-packages/saspy/sascfg.py](https://vscode-remote+ssh-002dremote-002b10-002e6-002e0-002e146.vscode-resource.vscode-cdn.net/usr/local/anaconda3/lib/python3.9/site-packages/saspy/sascfg.py)
WORK Path             = [/saswork/work/SAS_work17840003A29F_ip-10-6-0-146.concertocard.com/](https://vscode-remote+ssh-002dremote-002b10-002e6-002e0-002e146.vscode-resource.vscode-cdn.net/saswork/work/SAS_work17840003A29F_ip-10-6-0-146.concertocard.com/)
SAS Version           = 9.04.01M7P08062020
SASPy Version         = 4.7.0
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 238239

**Comment by tomweber-sas** [comment]
Can you look at the SASLOG and see any information? The paths listed for the sascfg file and WORK library in what you have above look strange. Where is this running? Can you do anything else and look at the LOG to see what's happening on that session?

**Comment by kwangccc** [comment]
I am running using Jupyter Notebook, connecting to a remote server

for this session below is the screenshot for

'import saspy sas = saspy.SASsession(cfgname='default')'
sas.saslib(libref='dat', path='/sasdata/modeling/_datasamples/equifax/data')'

**Comment by tomweber-sas** [comment]
Ok, that helps! Always better to show the output. So the thing is that STSIO uses sockets to transfer data for sd2df, df2sd, upload, download. So, I suspect there's something strange where however you're doing a remote connection that saspy isn't aware of, there probably something going on with that. I would expect if there was a socket problem it would error instead of hang, but I 'm not sure what this environment really is. Can you elaborate on this environment more; where SAS is, where Python is, and what's doing some remote connection? 
And, what happens when you interrupt the process (ctl-c or if jupyter, the little square that says interrupt the kernel)? What's in the saslog after that? It's bound to be a socket issue with the environment you're using.

**Comment by kwangccc** [comment]
For code:

`saspy`

output: `<module 'saspy' from '/usr/local/anaconda3/lib/python3.9/site-packages/saspy/__init__.py'>`

`saspy.SAScfg`

output: `'/usr/local/anaconda3/lib/python3.9/site-packages/saspy/sascfg.py'`

The environment is Visual Studio Code running Jupyter notebook file on a SSH remote server. 

I ran separately the iris dataset (150 rows by 5 columns) and finished in 0.7 seconds. Could it be a dataframe size/datatype issue?

Below screenshot is the saslog after I interrupt the process:

![Screenshot 2024-03-14 at 12 43 40](https://github.com/sassoftware/saspy/assets/127445110/71735f2e-4ae7-4fa4-8ae3-4b0d81461b9d)

**Comment by kwangccc** [comment]
I change the code and now it finishes running but no file is created:

`sas.df2sd(ONESCORE_CFN_102023, 'ONESCORE_CFN_102023', '/sasdata/modeling/_datasamples/equifax/data')`

SASLOG:

![Screenshot 2024-03-14 at 12 50 19](https://github.com/sassoftware/saspy/assets/127445110/49a818b9-c2a1-4e81-9f8f-809a93f03f72)

**Comment by kwangccc** [comment]
I will try that with our IT team and reach out back, Thanks!

**Comment by tomweber-sas** [comment]
Hey, just checking on this. Make any progress? I was thinking I can close this and if you need more help later you could reopen it if necessary.

**Comment by tomweber-sas** [comment]
I'm going to close this, as it's in your court to upgrade to the latest version which has this fix in it. If you need anything else, feel free to reopen it!

Thanks,
Tom
