### ISSUE TITLE
Databricks saspy Connection Error

### ISSUE THREAD

**Issue by grup2986** [sassoftware/saspy#596]
I am trying to connect to connect to a remote SAS server using saspy on a Databricks workspace hosted on Azure - it gives me the following error (redacted host & port):

We failed in getConnection
The application could not log on to the server "iomhost:iomport". The machine name is not valid. 

I can connect locally using the same code but when I test it in my Databricks workspace it fails.  Is this a firewall issue and I have to establish a site to site connection with my remote sas workspace? 

import saspy
import sys

sas = saspy.SASsession(results = 'html', 
                       java = '/usr/bin/java',
                       iomhost = ['iomhost'],  
                       iomport = iomport,
                       encoding =  'utf-8',
                       omruser = '', 
                       omrpw = '')

**Comment by tomweber-sas** [comment]
Hey @grup2986 , that error, from some remote cloud client environment, certainly implies a network is where you don't have access to your on prem from there. That's a DNS error because it has no idea what that host name resolves to. You could try using the IP, but if you don't have access through the firewall it still wont work. You could try it though.

**Comment by tomweber-sas** [comment]
Were you able to see about being able to connect back to your on prem system from there? Anything else that I can do for you? I can't help w/ cooperate firewalls unfortunately.
Tom

**Comment by grup2986** [comment]
Thanks Tom. I have a ticket open with our IT team

**Comment by tomweber-sas** [comment]
Hey, just checking on this. Make any progress? I was thinking I can close this and if you need more help later you could reopen it if necessary.

**Comment by tomweber-sas** [comment]
I'm going to close this, as it's in your court being a network restriction, not something that can be fixed in saspy. If you need anything else, feel free to reopen it!

Thanks,
Tom

**Comment by grup2986** [comment]
Sorry Tom for not responding and thanks for your help!
