### ISSUE TITLE
sd2pq keep schema from previous table

### ISSUE THREAD

**Issue by Debbby57** [sassoftware/saspy#611]
**Describe the bug**
I open a session SAS and I retrieve a first table with sd2pq function. Then I want to retrieve another table with the same function but it raises an error because of the schema. The function uses the schema from the previous table and my table doesn't have the same schema of course.
When I read the code I see that you use a if 'schema' not in pa_parquet_kwargs but when I want to retrieve the 2nd table this argument exists with the schema of the previous table :
https://github.com/sassoftware/saspy/blob/main/saspy/sasioiom.py#L2606
(I'm using winiomlinux connection).

You need to deallocate the pa_parquet_kwargs at the end of the function

**To Reproduce**
```
import saspy
import pyarrow
sas = saspy.SASsession()
sas.sd2pq(table="my_table1", libref="aa", parquet_file_path="./temp1.parquet)
tab1=pyarrow.parquet.read_table("./temp1.parquet).to_pandas()

sas.sd2pq(table="my_table2", libref="aa", parquet_file_path="./temp2.parquet)
tab2=pyarrow.parquet.read_table("./temp2.parquet).to_pandas()
```
the code crashes at the line `sas.sd2pq(table="my_table2", libref="aa", parquet_file_path="./temp2.parquet)` because of the schema. The 2 tables SAS needs to have different schemas.

I modified your code to deallocate the schema in the `finally` part of the function and it works. But I think you need to deallocate all the parameters that a user can pass.

I'm sorry I can't add screenshots or logs because my organization blocks this website so I'm writing this issue from my perosnal laptop...

thanks for you help !

**Comment by tomweber-sas** [comment]
Hey, great writeup Debby! I'll take a look at this and fix it. This was a user contributed method and it has a lot of parameters, all of which I wasn't able to test out as I would have, had I written all of this. It was kinda specific to what he was trying to get working for their production environment, but since it looked useful in general, I merged it in, assuming I might need to tweak it as people started pushing it. I'll see about cleaning this up. Thanks for the clear explanation!
Tom

**Comment by tomweber-sas** [comment]
Yes, I remember this from years ago. The right fix was to set these dict parms to None in the method signature and then assign them to a local variable w/ the proper default if the parm wasn't passed in; wasn't still None. 
I've reworked all the methods for this across all the access methods. Ran my tests, which now include running multiple different tables through to verify this fix. Looks good on my side. I pushed this to main. Are you able to pull from there and test it out with your use cases?
```
pip uninstall -y saspy
pip install git+https://git@github.com/sassoftware/saspy.git
```
is the easiest for that.

Thanks!
Tom

**Comment by Debbby57** [comment]
Hello

Thanks for the quick reply !

I tested the main branch in my use case and it works. I can now use the sd2pq with multiple tables which have differents schemas. 
Thank you !

**Comment by tomweber-sas** [comment]
Hey @Debbby57 I've built this into the newest production release, V5.100.2. I'll close this now as complete. If you need anything else, just let me know!

Thanks,
Tom
