### ISSUE TITLE
COM ERROR: Failed to convert data from 'xxx' to 'utf-16le' encoding

### ISSUE THREAD

**Issue by ka2048** [sassoftware/saspy#618]
### Issue Description
![image](https://github.com/user-attachments/assets/a9bda531-33ac-4bde-a0cd-fa808f4ab31c)

During execution, an error occurs at line 301 related to `LanguageService.FlushLog`.

#### Error Messages

1. **When I set `sasv9.cfg` to `nls/en`, the following error message appears:**
   ```
   pywintypes.com_error: (-2147352567, 'An unexpected error occurred.', (0, '䅓S湩.慌杮慵敧敓癲捩e', '<?xml version="1.0" ?><Exceptions><Exception><SASMessage severity="Error">Failed to transcode data from utf-16le to wlatin1 encoding because it contained characters which are not supported by your SAS session encoding. Please review your encoding= and locale= SAS system options to ensure that they can accommodate the data that you want to process. A portion of the source string, in hex representation is:</SASMessage></Exception><Exception><SASMessage severity="None">572fd8: 0a 00 25 00 66 00 6c 00 61 00 74 00 28 00 69 00 |..%.f.l.a.t.(.i.|</SASMessage></Exception><Exception><SASMessage severity="None">572fe8: 6e 00 64 00 73 00 6e 00 3d 00 61 00 64 00 73 00 |n.d.s.n.=.a.d.s.|</SASMessage></Exception></Exceptions>', None, 0, -2147023783), None)
   ```

2. **When I set `sasv9.cfg` to `nls/u8`, the following error message appears:**
   ```
   pywintypes.com_error: (-2147352567, 'An unexpected error occurred.', (0, '䅓S湩.慌杮慵敧敓癲捩e', '<?xml version="1.0" ?><Exceptions><Exception><SASMessage severity="Error">Failed to transcode data from utf-8 to utf-16le encoding because it contained characters which are not supported by your SAS session encoding. Please review your encoding= and locale= SAS system options to ensure that they can accommodate the data that you want to process. A portion of the source string, in hex representation is:</SASMessage></Exception><Exception><SASMessage severity="None">572fd8: 0a 00 25 00 66 00 6c 00 61 00 74 00 28 00 69 00 |..%.f.l.a.t.(.i.|</SASMessage></Exception><Exception><SASMessage severity="None">572fe8: 6e 00 64 00 73 00 6e 00 3d 00 61 00 64 00 73 00 |n.d.s.n.=.a.d.s.|</SASMessage></Exception></Exceptions>', None, 0, -2147023783), None)
   ```

When I set sasv9.cfg to nls/zh, everything works well. Where should I make changes to ensure that it also works correctly when I specify sasv9.cfg as nls/en or nls/u8?

### Additional Question

Could passing the `LOCALE` and `ENCODING` parameters to `SASObjectManager.ServerDef.ExtraNameValuePairs` resolve this issue?
If not, could someone please tell me what values should be passed for these parameters? I couldn't find any relevant documentation.

**Comment by tomweber-sas** [comment]
Out of curiosity, what is in utf-16? I don't believe SAS supports that as and encoding, and python is utf-8. Maybe it's specific to what you're doing in COM, but I'm not aware of SAS or Python running in that encoding.

**Comment by tomweber-sas** [comment]
did IOM work for you?

**Comment by ka2048** [comment]
> did IOM work for you?
yes it works

**Comment by tomweber-sas** [comment]
Great! Thanks
