### ISSUE TITLE
Prompt in SAS magic cell

### ISSUE THREAD

**Issue by Rhadadi** [sassoftware/saspy#62]
I read the saspy documentation on how to use SAS prompt. I am wondering if I can have prompt using SAS magic cell:
`%% SAS sas
....
`

**Comment by tomweber-sas** [comment]
I believe that SAS magic is just a simple wrapper of the submit() method of the SASsession object. I don't think it supports anything other than just calling submit() with whatever you type in. I don't think it supports prompting.

**Comment by jld23** [comment]
closing this issue as resolved. Please reopen if you have further questions.
