### ISSUE TITLE
SASIOConnectionTerminated: No SAS process attached. SAS process has terminated unexpectedly.

### ISSUE THREAD

**Issue by ka2048** [sassoftware/saspy#621]
**Describe the bug**
Encountered a SASIOConnectionTerminated error while connecting to the Workspace server via IOM.
Server: Ubuntu 22.04
client: Mac OS 15.1

**Screenshots**
![image](https://github.com/user-attachments/assets/9216fb85-4c9c-4e04-a7d8-48b6b5b8b73c)

![image](https://github.com/user-attachments/assets/34d1b8f6-2f2d-42c6-9b49-01178e24bedf)

**Comment by tomweber-sas** [comment]
Did you fix the java path and solve this?

**Comment by ka2048** [comment]
it works, thank u so much
