### ISSUE TITLE
 SASPy and SAS on demand for Academics: connection terminates; no error message;

### ISSUE THREAD

**Issue by menagagp** [sassoftware/saspy#622]
Bug
I am running SASPY using these instructions: https://www.listendata.com/2021/01/run-sas-in-python-without-installation.html
Here is my Python code:
import saspy
saspy.DEBUG = True
import pandas as pd
import os
import logging
# Create a SAS session with logging enabled
sas = saspy.SASsession(cfgname='oda', timeout=300)
print(sas)

To Reproduce: sas config file location: ['C:\\Users\\Lenovo\\AppData\\Roaming\\Python\\Python313\\site-packages\\saspy\\sascfg_personal.py']

SAS_config_names=['oda']
oda = {'java' : 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\jdk-23\\bin\\java.exe',
#US Home Region 2
'iomhost' : ['odaws01-usw2-2.oda.sas.com','odaws02-usw2-2.oda.sas.com'],
'iomport' : 8591,
'authkey' : 'oda',
'encoding' : 'utf-8'
}

Expected behavior
SAS Connection established but terminated

Screenshots of terminal:
<img width="495" alt="image" src="https://github.com/user-attachments/assets/813ac076-aae5-42db-a53c-4acd4b55b736">

Additional context
java 23.0.1 2024-10-15
pyth 3.13.0 2024-10-7
Using vscode to run test.py

**Comment by tomweber-sas** [comment]
You're saying you ran the following code:
```
import saspy
saspy.DEBUG = True
import pandas as pd
import os
import logging
sas = saspy.SASsession(cfgname='oda', timeout=300)
print(sas)
```
and you got that output above.

That worked!  Based upon your comment about running it as test.py from vscode, you ran it a a batch script using the file interpreter. There's nothing else to expect. I'm not sure what you were looking to have happen?

A couple of things, the real instruction for SASPy are [here](https://sassoftware.github.io/saspy/index.html), not that link to a blog; though it got you running, so I'm not knocking it. `saspy.DEBUG` isn't a thing, so I'm not sure where that came from. 

So, this is working for you. I'm not sure what you're expecting unless it's that you wanted to have an interactive session, but you ran a batch script, which isn't an interactive session. Was it something like that?

Tom

**Comment by menagagp** [comment]
Closed

**Comment by tomweber-sas** [comment]
Awesome, I'm glad to hear that! Let me know if you need anything else!
