### ISSUE TITLE
unexpected behavior with df2sd

### ISSUE THREAD

**Issue by brian-the-bungler** [sassoftware/saspy#63]
I was playing with df2sd and nulls.  Below is my test code.
The two strange behaviors are:
- It seems like only the first row gets into work yet i don't see any errors. (maybe sf holds an error log that i am not viewing?)  The cause is the \x00 in second line.
- It gives me a second line (but not 3rd or 4th) if I replace the \x00 with "".  It displayed a "b" for the blank which i found puzzling.

Thanks for all the great features.  Love the library!
```
import pandas as pd
import numpy as np
import saspy
sas = saspy.SASsession(cfgname='winlocal')

df_ST = pd.DataFrame({ 'One': 1,
                       'Letter': 'a',
                       'more': pd.Series(['a', 'b', 'c', 'd'],),
                       'blanks': pd.Series(['happy','\x00', 'days', '\x00'])
                     })
from IPython.display import HTML
# move df_ST to work.test
sf = sas.df2sd(df=df_ST, table='test')
# proc report it
sas_ses = sas.submit("""
proc report data=work.test;
    title 'fun report';
run;
""")
HTML(sas_ses['LST'])
```

**Comment by tomweber-sas** [comment]
Hey thanks! So what version are you running? If you submit 'sas' (the SASsession object) it will display that and other info:
```
>>>sas
Access Method         = IOM
SAS Config name       = winlocal
WORK Path             = C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD15424_d10a626_\Prc2\
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 2.1.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = WLATIN1
Python Encoding value = cp1252
```
There were some recent fixes to the IOM access method to address missing values for df2sd (#50).   I don't believe that would fix embedded nulls in a string ('\x00'), but it should fix the valid null strings ('').
I'll have to dig in a bit to see exactly what's happening, but I expect the embedded nulls will throw off the parser in SAS that's reading the data lines which would account for the strange results.

**Comment by brian-the-bungler** [comment]
Cheers. My version doesn't declare saspy version but pip said 2.1.4  I tried today updating to saspy 2.1.7 but its going to need TLC :-)

Access Method         = IOM
SAS Config name       = winlocal
WORK Path             = C:\Users\xxxx\AppData\Local\Temp\SAS Temporary Files\_TD6208_xxxx_\Prc2\
SAS Version           = 9.04.01M3P06242015
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = UTF-8
Python Encoding value = windows-1252

**Comment by tomweber-sas** [comment]
Yep, I added in the saspy version after 2.1.4 sometime. Before you upgrade, go ahead and copy your sascfg.py to sascfg_personal.py so that your configuration remains intact. I probably didn't have sascfg_personal doc'ed back in 2.1.4, so you might not know about it yet.
https://sassoftware.github.io/saspy/install.html#sascfg-personal-py

The TLC? We you expecting to have any trouble upgrading? Or maybe the config issue (sascfg.py)?

**Comment by brian-the-bungler** [comment]
TLC = Dependency chain failure in PIP.  I probably need to update Anaconda.  I will try out 2.1.7 this weekend.

**Comment by tomweber-sas** [comment]
@brian-the-bungler were you ever able to verify this was fixed for you in a more current version of saspy? 
Just going through issues and cleaning up.
Thanks,
Tom

**Comment by brian-the-bungler** [comment]
Yes it's fixed!

**Comment by tomweber-sas** [comment]
Fantastic! I'll close this then. If you find anything else or need anything, just let me know.

Thanks!
Tom
