### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by mbcann01** [sassoftware/saspy#64]
Hello. 

I'm really excited about trying out saspy. I'm using a local instance of SAS 9.4 on Windows 10 running in Parallels on a Mac. 

Unfortunately, I'm not able to connect. I keep getting this error:
<img width="1148" alt="screen shot 2017-10-16 at 10 00 31 pm" src="https://user-images.githubusercontent.com/12264987/31644790-c1126f18-b2bd-11e7-8930-a12762ce0788.png">

As you can see here, I added the required file paths to sascfg.py:
<img width="1409" alt="screen shot 2017-10-16 at 10 00 54 pm" src="https://user-images.githubusercontent.com/12264987/31644838-11186db4-b2be-11e7-9cec-bfd7facb42cc.png">

I checked, and all the files are in the locations indicated by the file paths.

Finally, I made sure to add "C:\Program Files\SASHome\SASFoundation\9.4\core\sasext" to the system PATH environment variable.

Any suggestions for what I should try next?

Thank you!

**Comment by tomweber-sas** [comment]
Hey, I think this is an easy one. It looks like you've got it all set up right. The error you got means that it can't find 'java', the command. Find your java.exe file and just put the full path to it, including \\java.exe in the 'java'  value of the config definition (winlocal). For example, on my pc I found it here:
```
'java' : 'C:\\ProgramData\\Oracle\\Java\\javapath\\java.exe',
``` 
I think that'll do it for you :)

**Comment by TreeAnts** [comment]
Hi, saspy is amazing, it will help a lot for my future work.  But I have a similar problem as mbcann01.  And I keep getting this error:
<img width="524" alt="default" src="https://user-images.githubusercontent.com/32829910/31674666-f70f310a-b394-11e7-93fd-4744c0ac1998.PNG">
Please give me some suggestions. Thank you!

**Comment by TreeAnts** [comment]
Haha ~Just find it~ "Run as administrator" is done!  ^_^
<img width="555" alt="2" src="https://user-images.githubusercontent.com/32829910/31675463-4bdbe19a-b397-11e7-8e5f-a382f5e12783.PNG">

Thanks all the same!

**Comment by tomweber-sas** [comment]
Huh, that's odd. I was going to say that it looks like you don't have the spiauth.dll directory in your system path. That's what that error suggests. Maybe you don't have permission to that folder? and when you run as admin, they you do????

**Comment by mbcann01** [comment]
Your suggestion resolved my issue. Thank you!

**Comment by tomweber-sas** [comment]
Great! Glad that was it. 
Thanks,
Tom
