### ISSUE TITLE
Response from remote SAS not working for pure python code -  SOCK_NONBLOCK

### ISSUE THREAD

**Issue by bikashdube** [sassoftware/saspy#68]
I have sascfg configured and working in both Notebook standalone as well as Hub. I am using the "ssh" method of connection after setting up passwordless keys etc. Everything works great in "SAS" notebooks via sas_kernel but I am trying pure python notebooks/code and there is no response back.
```python
import saspy
import pandas as pd
sas = saspy.SASsession(cfgname='ssh')
#dir(sas)
stat = sas.sasstat()
#dir(stat)
cars = sas.sasdata("CARS","SASHELP")
#dir(cars)
cars.describe()
```
Immediately in the output window I see (ID of course changes if Python kernel is restarted)
`Using SAS Config named: ssh
SAS Connection established. Subprocess id is 21311`

After a while I have to keyboard interrupt and the error stack is the following everytime. 
````
`~/.pyenv/versions/3.6.3/lib/python3.6/socket.py in accept(self)
    203         For IP sockets, the address info is a pair (hostaddr, port).
    204         """
--> 205         fd, addr = self._accept()
    206         # If our type has the SOCK_NONBLOCK flag, we shouldn't pass it onto the
    207         # new socket. We do not currently allow passing SOCK_NONBLOCK to`
````
Is there some os level property that needs to be set?

**Comment by tomweber-sas** [comment]
Ok, I think I have an idea what this might be. Can you make a change to your SASsession() and see it it works.
```
sas = saspy.SASsession(cfgname='ssh', resutls='html')
```

I think the problem is with connecting back to your client from the SAS remote machine to transfer data back to saspy to create the dataframe (the unfortunate default results setting). If this works, then I'm guessing the socket connect from SAS to saspy isn't happening. May not be able to connect back to your client machine.
And, if that's the case. It could be that you might need to use the new 'tunnel' config definition option that was added recently. 
Let's start w/ seeing if you can get this running in 'html' more instead of pandas and go from there.

Tom

**Comment by bikashdube** [comment]
@tomweber-sas 
Thanks Tom, I tried adding the results='html' switch but it still has the same issue. I am trying to see the documentation for tunnel and see if I can take a shot at it.

**Comment by tomweber-sas** [comment]
Huh, that's odd. I expected that the difference between SAS_kernel over saspy and saspy by itself was the results; html vs. pandas. And that using pandas requires the SAS side to be able to connect back to saspy over the socket saspy is waiting on (assuming so only because your attention seems to have broken out of socket.accept).  But this should have had a different result.
Can you show me your config file (sascfg.py or sascfg_personal.py if you're using that. And what version of saspy do you have? After assigning sas = SASsession(cfgname='ssh', results='html'), you can submit sas and it will display a bunch of information. Actually, just run the following and it will show me these things.

Can you run this whole thing from a shell and send me the whole log.  
```
import saspy
import pandas as pd
sas = saspy.SASsession(cfgname='ssh', results='html')
sas
saspy.SAScfg
saspy.SAScfg.ssh
stat = sas.sasstat()
cars = sas.sasdata("CARS","SASHELP", results='html') 
cars.describe()
``` 
Thanks,
Tom

**Comment by bikashdube** [comment]
I added the tunnel option in sascfg.py (port 9911) and also opened port 9911 via UFW. I see that the issue remains with or without the results switch. 
This makes sense to me though. The -R switch to SSH is supposed open the tunnel port on the _remote_ server, following which, you could access the client box from the SAS remote host via ssh -p _tunnelport_

**Comment by bikashdube** [comment]
OK we were just posting around the same time. I will run it shortly.

**Comment by tomweber-sas** [comment]
ok, no prob. Hey, before submitting the cars.describe (I assume that's the one that hangs???), submit this too
```
print(sas.saslog())
```
Thanks,
Tom

**Comment by bikashdube** [comment]
[saspy.log](https://github.com/sassoftware/saspy/files/1408547/saspy.log)

**Comment by tomweber-sas** [comment]
well, that looks like it's 'working'. My bad to have you use 'html' from a shell. Should set it to results='text' for this test case. It looks like both cars.describe calls returned the results. 
Can you try again w/ results='text' as it looks like this was working.

If so, we can try adding 
```
from IPython.display import HTML
```
in your python notebook and re running with results='html'.

Also, looking at your saspath value in your config definition, that soesn't look like it should work. Having multiple strings w/in a single value when building the parm list for execv usually causes issues. That's a little suspicious to me, but maybe going over ssh happens to let that be ok? And, the path should really be the path to the startup script, and the sas executable itself - something like

/opt/sasinside/SASHome/SASFoundation/9.4/bin/sas_u8
instead of 
/opt/sasinside/SASHome/SASFoundation/9.4/sas

I would have expected it to have to be the following:
```
ssh      = {'saspath' : '/rar/sas',   #though see comment above about .../bin/sas_en oe sas_u8 not sas itself
            'ssh'     : '/usr/bin/ssh',
            'host'    : 'tom64-2',
            'options' : ["-fullstimer", "-work", "/foo/bar"]
            }

```

**Comment by tomweber-sas** [comment]
can't type.   Doesn't not soesn't, though you probably figured that. Also:
path to the startup script, and **NOT** the sas executable itself.

**Comment by bikashdube** [comment]
Excellent points. It looks like the problem was not importing HTML all along and nothing to do with the SSH configuration and or sockets/firewalls. The path to executable is something we have configured in our environment and it is all set and good to go but I do see the way to set it up in options as you pointed out. Even though it is not documented, I am just passing a custom -WORK directory after /path/to/sas but can see how it works in options also !

Thanks for the support on this today. I appreciate it. Please feel free to close it and I am looking forward to other enhancements down the road as well as contribute as time permits.

**Comment by tomweber-sas** [comment]
So, the 'hang' you experienced was due (you think) to not having submitted the following yourself in the python notebook?
```
from IPython.display import HTML
```
I wouldn't think that would actually be necessary unless you used the submit method and wanted to display html results from the LST (returned from submit). Any results that saspy returns (automatically displayed) should render w/out you needing to have imported HTML yourself.

I want to understand this better to be sure there isn't a bug in there I need to fix.

Is it working now with html and pandas in your notebook? And you don't have that 'tunnel' option either? I'm confused :)

Thanks!
Tom

**Comment by bikashdube** [comment]
The "hang" was precisely because of not having the import HTML statement. The following code works great with the output in a Py3 notebook (meaning no SAS statements/magics, just pure python code), with log followed by the output from the Means procedure. (using ```python markdown here for clarity)

```python
import saspy
import pandas as pd
sas = saspy.SASsession(cfgname='ssh', results='html')
print(sas.saslog())
stat = sas.sasstat()
cars = sas.sasdata("CARS","SASHELP", results='html') 
cars.describe()

Without the print(sas.salog()) I get the Means procedure now nicely displayed. I am using IE but it works in Chrome as well. 

I have found that code completion or copying tables (to paste in Excel later) doesn't work in Chrome when using the SAS Kernel notebooks which is why I had been using IE. I have tested the Python notebooks now and it works great in both IE and Chrome for SAS datasets. 

I don't have the tunnel option, it works via the existing ssh keys that I have been using for SAS notebook.  

Also can I delete the saspy.log if you no longer need it ? ;)

Regards,
Bikash

**Comment by tomweber-sas** [comment]
yes, you can delete the saspy.log!

This all still doesn't add up for me. Importing HTML and setting results='html' are two totally different things. Setting results='html' was to avoid having SAS connect back to the waiting socket; when results='pandas'. That does seem to work. But that isn't a 'fix' for the hang, just a diagnostic. 

Second thought. Are you submitting all these statements from a single cell in the notebook? Jupyter doesn't always do well when there's more than one statement that returns results in a single cell. I wouldn't put more than one stmt that displays something into a single cell.

So what happens now when you set results='pandas' (the default if you don't set it to html or text), and you put one result returning stmt in a cell? In fact, you can use results='pandas' in line more too (shell).
Is that working? You can also leave it as html and submit the following to make it create a dataframe.
```
df = cars.to_df()
df
```
That also creates a socket that SAS has to connect back to (python waiting) to stream the data across to build the dataframe w/ the cars data. When using html results, there's no extra socket back to python for data transfer. Is that working for you, cuz that is what I thought the original problem was. Do you have a firewall between the SAS machine and the client?

Sorry, I just want to be sure this is all really working right for you. The data points I have so far just don't add up for me.

Thanks,
Tom

**Comment by bikashdube** [comment]
Alright, so I do have a lot more clarity now (and it is starting to add up :)) 

This one hangs

```python
import saspy
import pandas as pd
sas = saspy.SASsession(cfgname='ssh')
#print(sas.saslog())
stat = sas.sasstat()
cars = sas.sasdata("CARS","SASHELP") 
cars.describe()
```

Error when interrupted is 
````
~/.pyenv/versions/3.6.3/lib/python3.6/socket.py in accept(self)
    203         For IP sockets, the address info is a pair (hostaddr, port).
    204         """
--> 205         fd, addr = self._accept()
    206         # If our type has the SOCK_NONBLOCK flag, we shouldn't pass it onto the
    207         # new socket. We do not currently allow passing SOCK_NONBLOCK to
````

This one hangs (as expected)
```python
import saspy
import pandas as pd
sas = saspy.SASsession(cfgname='ssh',results='pandas')
#print(sas.saslog())
stat = sas.sasstat()
cars = sas.sasdata("CARS","SASHELP") 
cars.describe()
```

This works (No from IPython.display import HTML)

```python
import saspy
import pandas as pd
sas = saspy.SASsession(cfgname='ssh',results='pandas')
#print(sas.saslog())
stat = sas.sasstat()
cars = sas.sasdata("CARS","SASHELP") 
cars.describe()
```

So yes everything is being submitted from a single cell. I had couple of other cells too (independent code and not being executed) but I deleted them for your test cases. So it appears to me that the results=pandas is the difference here. Thoughts? Anything else you need me to test?

**Comment by bikashdube** [comment]
I see that you had me try sas = saspy.SASsession(cfgname='ssh',results='html') the first time around and I came back with "sorry didn't work, let me try tunneling". So I don't know what has changed now.

**Comment by tomweber-sas** [comment]
Yes, we're back to square one I believe. 
1) you don't need to issue 'from IPython.display import HTML' for any of this to work
2) you can get results back from sas in 3 ways: pandas, html, text. For tabular results at least (not graphs,...)
3) text and html results come back through the listing (LST), so these should work if you have a valid connection to SAS, which you do.
4) pandas results (for STDIO access method, which you're using), don't come back through the LST, saspy opens a socket and submits sas code to connect back to the socket and streams the data over to create the dataframe.

4 above is (I believe) the problem I believe you're hitting. It appears saspy is sitting on that socket.accept call in sasdata2dataframe() waiting for SAS to connect, which appears to not be happening. Thus that thought about a firewall or something preventing SAS from connecting back to the client. It could even be a host name resolution issue.

So, lets try the case that hangs again, but with you using the tunnel option. Do you know if you have  a firewall between your client and SAS machines? Also, as far as host name resollution, can you submit this to see what host name is being used?
```
import socket
socket.gethostname()
```

Are you able to logon to the SAS machine and see if you can ping that hostname? That would address that possibility.

So far I think this is the problem, I just don't know specifically when it can't connect back.

**Comment by tomweber-sas** [comment]
'why' it can't connect back

**Comment by bikashdube** [comment]
Both hosts are Linux and have firewalls native to the OS. I do not have sudo rights on the remote SAS host but do on the client from where I am connecting to SAS host.

socket.gethostname() returns "hostname1" and when I do "ping hostname1" it does resolve correctly to hostname1.domain.com and gets the pings back. 

I am using a system id (which exists in corporate ldap) in this case which exists on both hosts. The system ID doesn't allow "interactive" login meaning even if you have ssh keys setup (which I have), if I try to switch user to this ID, I would have to supply my corporate ID/pass. It doesn't matter however for "batch" type of work that we are doing via Jupyter hence the passwordless keys work fine from client to SAS host and back (for sas_kernel as well as python notebooks html/text).

I disabled UFW on the client host to test if the connection back was via random port, but that didn't help. I tried the tunnel option and that doesn't work also.

On the sas host i see ( For this test I setup port 32701 as tunnel integer in saspy.cfg
````
tcp        0      0 127.0.0.1:32701             0.0.0.0:*                   LISTEN
tcp     3441      0 127.0.0.1:32701             127.0.0.1:46482             CLOSE_WAIT
tcp        0      0 127.0.0.1:46482             127.0.0.1:32701             FIN_WAIT2
````

**Comment by bikashdube** [comment]
Ok here may be the important clue
````
hostname1:/home/goodguy $ /usr/bin/ssh -t sashost.domain.com -R 32701:localhost:32701 /path/to/sas -fullstimer -nodms -stdio -terminal -nosyntaxcheck -pagesize MAX

Unauthorized access to or use of this system is prohibited.
All access and use may be monitored and recorded.

Warning: remote port forwarding failed for listen port 32701
````

I do get through to the SAS initialization page without being prompted for password but there is that message about the port forward fail

**Comment by tomweber-sas** [comment]
Let me digest this info and see what I think. Meanwhile, I've just pushed some changes to this module (sasiostdio.py) to better handle this issue. The socket accept call has no timeout option, so I have to just wrap it in a try: except: so I can catch the interupt (you still have to do), but it should pull back the log so you can see the error, and clean things up so you can continue with your session.

Can you pull this from master and see what we see. After interupting, you can run the print(sas.saslog()) to get the rest and we can see what we see.

**Comment by bikashdube** [comment]
Ok will try that here shorty. Also disregard that Warning message. I forgot to interrupt the kernel in the notebook so 32701 was already listening. Trying the command line with the same port number should produce the warning about the remote port failing. After interrupting the kernel 32701 opens up again and trying the command line worked just fine.

**Comment by tomweber-sas** [comment]
Oh, and try it without the 'tunnel' so we can see what the default problem is. Also, good that the host name is fine. Here's a sample of what to expect. I changed the source to sent the wrong port number to SAS to simulate this; so I wait on accept till I hit CTL-C:
```
tom64-3> python3.5
Python 3.5.1 (default, Jan 19 2016, 21:32:20)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession(cfgname='sshtest', results='html')
SAS Connection established. Subprocess id is 25611

>>> sas
Access Method         = SSH
SAS Config name       = sshtest
WORK Path             = /usr/tmp/SAS_work6E4F000027E3_tom64-2/
SAS Version           = 9.04.01M5P09132017
SASPy Version         = 2.1.7
Teach me SAS          = False
Batch                 = False
Results               = html
SAS Session Encoding  = UTF8
Python Encoding value = utf-8

>>> cars = sas.sasdata("CARS","SASHELP", results='text')
>>> cars.head(2)
                                                           The SAS System                  Tuesday, October 24, 2017 12:01:00 PM   1

                                       Drive                   Engine                                 MPG_
 Obs Make  Model          Type  Origin Train     MSRP  Invoice  Size  Cylinders Horsepower MPG_City Highway Weight Wheelbase Length

   1 Acura MDX            SUV    Asia  All    $36,945  $33,337   3.5      6         265       17       23    4451     106      189
   2 Acura RSX Type S 2dr Sedan  Asia  Front  $23,820  $21,761   2.0      4         200       24       31    2778     101      172
>>> df = cars.to_df()
^Csasdata2dataframe was interupted. Trying to return the saslog instead of a data frame.
>>> print(df)

91   filename sock socket 'tom64-3:43582' lrecl=32767 recfm=v termstr=LF;
92    data _null_; set SASHELP.CARS;
93    file sock dlm='02'x ; put 'Make'n 'Model'n 'Type'n 'Origin'n 'DriveTrain'n 'MSRP'n best32. '02'x 'Invoice'n best32. '02'x
93 ! 'EngineSize'n best32. '02'x 'Cylinders'n best32. '02'x 'Horsepower'n best32. '02'x 'MPG_City'n best32. '02'x 'MPG_Highway'n
93 ! best32. '02'x 'Weight'n best32. '02'x 'Wheelbase'n best32. '02'x 'Length'n best32. '02'x '01'x; run;
ERROR: Connection refused.
NOTE: The SAS System stopped processing this step because of errors.
NOTE: DATA statement used (Total process time):
      real time           0.01 seconds
      cpu time            0.02 seconds

94
95
96
97
98
```

**Comment by tomweber-sas** [comment]
So in my case, SAS got a 'Connection Refused' error but saspy is hung till you interrupt. But then, it gets the log, and it should be in a good state to be able to keep running other code.

**Comment by bikashdube** [comment]
````
>>> print(df)

91   filename sock socket 'hostname1:49035' lrecl=32767 recfm=v termstr=LF;
92    data _null_; set SASHELP.CARS;
93    file sock dlm='02'x ; put 'Make'n 'Model'n 'Type'n 'Origin'n 'DriveTrain'n 'MSRP'n best32. '02'x 'Invoice'n best32. '02'x
93 ! 'EngineSize'n best32. '02'x 'Cylinders'n best32. '02'x 'Horsepower'n best32. '02'x 'MPG_City'n best32. '02'x 'MPG_Highway'n
93 ! best32. '02'x 'Weight'n best32. '02'x 'Wheelbase'n best32. '02'x 'Length'n best32. '02'x '01'x; run;
ERROR: Connection refused.
NOTE: The SAS System stopped processing this step because of errors.
NOTE: DATA statement used (Total process time):
      real time           0.04 seconds
      user cpu time       0.01 seconds
      system cpu time     0.00 seconds
````

**Comment by bikashdube** [comment]
[saspy.log](https://github.com/sassoftware/saspy/files/1411588/saspy.log)

Please let me know once you have downloaded it, will remove it after.

**Comment by tomweber-sas** [comment]
Ok! So, now we can see what the problem is. At least that's better! So, are we back to some kind of firewall issue where the SAS machine isn't allowed to connect back to your client? That's what the tunnel option is about, but that isn't working for you either? Do you get this same error with that option? And do you have IT or someone there that can see why this is happening and maybe enable an open port? You can specify the port to use (without the reverse tunnel). If there's a range that's already allowed, you can specify it like
```
df = cars.to_df(port=1024)
```
I just got the log; you can delete it.

**Comment by bikashdube** [comment]
Ok I will try the tunnel option and capture the log, will also try the port switch in the df statement.

**Comment by bikashdube** [comment]
Interesting. Added tunnel option and I get this 
````
>>> print(df)
91   filename sock socket 'localhost:32701' lrecl=32767 recfm=v termstr=LF;
92    data _null_; set SASHELP.CARS;
93    file sock dlm='02'x ; put 'Make'n 'Model'n 'Type'n 'Origin'n 'DriveTrain'n 'MSRP'n best32. '02'x 'Invoice'n best32. '02'x
93 ! 'EngineSize'n best32. '02'x 'Cylinders'n best32. '02'x 'Horsepower'n best32. '02'x 'MPG_City'n best32. '02'x 'MPG_Highway'n
93 ! best32. '02'x 'Weight'n best32. '02'x 'Wheelbase'n best32. '02'x 'Length'n best32. '02'x '01'x; run;
NOTE: The file SOCK is:
      Local Host Name=sashost,
      Local Host IP addr=10.1.1.150,
      Peer Hostname Name=localhost.localdomain,
      Peer IP addr=127.0.0.1,Peer Name=N/A,
      Peer Portno=32701,Lrecl=32767,Recfm=Variable

NOTE: 428 records were written to the file SOCK.
      The minimum record length was 353.
      The maximum record length was 394.
NOTE: There were 428 observations read from the data set SASHELP.CARS.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      user cpu time       0.00 seconds
      system cpu time     0.01 seconds
      memory              462.75k
      OS Memory           8856.00k
      Timestamp           10/24/2017 12:39:17 PM
      Step Count                        10  Switch Count  0
      Page Faults                       0
      Page Reclaims                     124
      Page Swaps                        0
      Voluntary Context Switches        4
      Involuntary Context Switches      0
      Block Input Operations            0
      Block Output Operations           0
````

**Comment by tomweber-sas** [comment]
did you interrupt it while it was running? Looks like that worked.

**Comment by bikashdube** [comment]
Yes I did
````
>>> df = cars.to_df()
^Csasdata2dataframe was interupted. Trying to return the saslog instead of a data frame.
````
Do you want the new saslog?

**Comment by tomweber-sas** [comment]
No, the log you got back had the info. So try again but don't interrupt. Looks like it will work.

**Comment by bikashdube** [comment]
I issued df = cars.to_df() but do not get the python shell prompt back, basically the notebook hang.

**Comment by tomweber-sas** [comment]
did you try submitting something after that in another cell? Like submit df to display the dataframe. It looks like it worked. Is the notebook really hung? Or can you run other things in other cells after that statement?

**Comment by bikashdube** [comment]
Also tried this and it is same behavior where "428 records were written to the file SOCK" but I don't get the shell back
````
df = cars.to_df(port=32701)
````

**Comment by tomweber-sas** [comment]
I'm confused. It seems like it's working. but I don't see what would be hung on the python side. What happens in a python shell; terminal session?

**Comment by bikashdube** [comment]
> did you try submitting something after that in another cell? Like submit df to display the dataframe. It looks like it worked. Is the notebook really hung? Or can you run other things in other cells after that statement?

Was doing all of this in python shell. Should it not finish and get back to the python shell after getting  success response? 

Also simulated this in notebook. Submitted the following 
```python
import saspy
sas = saspy.SASsession(cfgname='ssh', results='html')
cars = sas.sasdata("CARS","SASHELP", results='text')
cars.head(2)
df = cars.to_df()
SAS Connection established. Subprocess id is 20642
```
In another cell 
```python
print(df)
```
and do not get anything back

**Comment by tomweber-sas** [comment]
ok, yes, it should get back to a prompt. just double checking. so, I think this is still off somehow, but I don't get it. I'm doing the same thing here, even with 'tunnel', and it works like it should. What's your 'ssh' config definition look like again?

**Comment by bikashdube** [comment]
````
ssh      = {'saspath' : '/path/to/sas',
            'ssh'     : '/usr/bin/ssh',
            'host'    : 'sashost.domain.com', 
            'tunnel'  : 32701,
            'encoding': 'latin1',
            'options' : ["-fullstimer"]
            }
````

**Comment by tomweber-sas** [comment]
Ok, that all looks just fine.

well, let's try something to see what's going on on the python side. It 'seems' like it's still not getting the connection still. Can you edit the sasiostdio.py file and add some print's in it? Just for diagnostics.
At line 1034, can you add this print -    print(str(newsock))  


      try:
         newsock = sock.accept()
         print(str(newsock))  # add this here
         r = []
         while True:
            data = newsock[0].recv(4096)

I'm not convinced it's actually getting the connection. But this will show us.

**Comment by bikashdube** [comment]
Of course it is firewall and my guess is that somehow 
````
127.0.0.1:32701
```` 
is the issue. I think it needs to listen to all interfaces

**Comment by bikashdube** [comment]
> I'm not convinced it's actually getting the connection. But this will show us.

Sure, will try it here shortly.

**Comment by tomweber-sas** [comment]
Well, I think that the tunnel thing is a trick. I didn't implement that myself, it was contributed, so I'm not 100% on how it works. But, I think the thing is that it (ssh) set's up it's own socket on the remote machine( sas machine) with that port number. So, the remote machine IS connecting to localhost:port. That way ssh is getting whatever is sent there, sending it back over is's connection to the client machine and handing it back to the client's socket. 

Ok, time for me to do some research on this to understand it better. I'm sure we're close, but I need to read up on this so I understand what's going on. Curious to see if we hit that print. Here's what I get with that print:
```
(<socket.socket fd=52, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 32701), raddr=('127.0.0.1', 38790)>, ('127.0.0.1', 38790))
```

**Comment by bikashdube** [comment]
Can't get it to print that line, so it doesn't get to that point in code?

**Comment by tomweber-sas** [comment]
ok, so it's still not actually connecting back. So, what happens if you change your config from
```
 'tunnel'   :  32701
```
to
```
 'port'     :  32701
```

**Comment by bikashdube** [comment]
Ok that is not going to work obviously because SSH works on port 22 on both client and SAS host. I am on a 30 min break and will research how to make the tunnel work on all "local" interfaces

````
SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

Attempted to run program /usr/bin/ssh with the following parameters:['/usr/bin/ssh', '-t', 'sashost.domain.com', '-p', '32701', '-R', '32701:localhost:32701', '/path/to/sas', '-fullstimer', '-nodms', '-stdio', '-terminal', '-nosyntaxcheck', '-pagesize', 'MAX', '']

Try running the following command (where saspy is running) manually to see if you can get more information on what went wrong:
/usr/bin/ssh -t sashost.domain.com -p 32701 -R 32701:localhost:32701 /path/to/sas -fullstimer -nodms -stdio -terminal -nosyntaxcheck -pagesize MAX
````

**Comment by tomweber-sas** [comment]
Sorry, that 'port' isn't the port for the data transfer socket. Never mind that. My bad. I got the options mixed up.
Yes, that should have failed just like that

**Comment by tomweber-sas** [comment]
Gotta go get kids from school. Back on it in a bit.

**Comment by bikashdube** [comment]
So looking at the ssh manpage I see that the issue is 
````
GatewayPorts yes
````
This option needs to be set on the SAS host for the -R to work. I am continuing to see if there is another way around this.

**Comment by tomweber-sas** [comment]
I see that comment also. Checking mine I have the following:
```
tom64-3> sudo grep -i gateway /etc/ssh/sshd_config
#GatewayPorts no
tom64-3>
```
Not sure if whichever ssh I have installed allows this by default. It's not set at all, and the commented out sample has 'no', as if it defaults to yes and you would uncomment that line to turn it off. ??? But, that certainly is something to verify, as it's something that would keep this from working. 

I also just stepped through the code, and looked at the sockets on each system to see what was going on. ssh was creating and listening to this socket on the server, and once connected to it was forwarding on through the existing ssh tunnel. It all matched up on both client and server.

**Comment by bikashdube** [comment]
The default is no for OpenSSH. What is your linux distro?
````
ssh -v localhost
````
Why does this have to use sockets and not work using the existing SSH pipeline?

**Comment by bikashdube** [comment]
So seems to me that there are 2 options to try, the GatewayPorts which we discussed already. The other one is actually where it is failing in my case. I need to have a **local** port on the client that can listen to all interfaces so that the SAS host can connect to it when it sends the pandas response. 
In other words something along the lines of 
````
ssh  -L :32702:*:22 sashost.domain.com
````
From the man page, the * for the hostname makes it bind 32701 to 0.0.0.0 on the local client, which is exactly what I see. 
````
tcp        0      0 0.0.0.0:32701           0.0.0.0:*               LISTEN
tcp6       0      0 :::32701                :::*                    LISTEN
````
Now the remote SAS server should have a port that we can connect via a tunnel. The -R option should do that, so maybe we can have both R and L to address all firewall scenarios.

**Comment by tomweber-sas** [comment]
the first line I get from that is the following.
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013

as for linux:
tom64-3> cat /etc/issue
CentOS release 6.7 (Final)
Kernel \r on an \m

tom64-3> uname -a
Linux tom64-3 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
tom64-3>

So, the 'why' question. Well, I wrote this long before adding on the ability to go over ssh, so it was a purely localhost connection. Later I enhanced stdio to work over ssh. Now we also have IOM access method that lots of people like to use (only way from windows client). For STDIO (over ssh or not), I have sdtin/out/err which let me submit code, get the log and the lst (results of all kinds). Since I wrote this before SSH and IOM, it was local unix only and this was certainly better than trying to stream the data over the log or lst (only choices for exising connection), as they are in use for other things too and have other things written to them. But, I can take another look at this and see if I can come up with something.

**Comment by tomweber-sas** [comment]
I'm pretty sure you need -R not -L. What's in your /etc/hosts on your client machine?
I'm starting to think the problem is actually ssh on your client side (python/saspy) is not connecting to the local port saspy is waiting on. I don't know why that would be, but that's where I'm thinking the problem is now. Anyway, more tomorrow.

Tom

**Comment by bikashdube** [comment]
> So, the 'why' question. Well, I wrote this long before adding on the ability to go over ssh, so it was a purely localhost connection. Later I enhanced stdio to work over ssh. Now we also have IOM access method that lots of people like to use (only way from windows client). For STDIO (over ssh or not), I have sdtin/out/err which let me submit code, get the log and the lst (results of all kinds). Since I wrote this before SSH and IOM, it was local unix only and this was certainly better than trying to stream the data over the log or lst (only choices for exising connection), as they are in use for other things too and have other things written to them.

Makes sense and awesome job there. 

> But, I can take another look at this and see if I can come up with something.

Sorry I did fear that it would mean an STDIO rewrite, but of course this is something you might want to open up in light of firewalled clients for those fringe scenarios.

**Comment by bikashdube** [comment]
> I'm pretty sure you need -R not -L. What's in your /etc/hosts on your client machine?

Correct, this would be -R actually with the update on SSHD on the SAS host. I should be able to get those changes with the help of sysadmins but it will take a couple of days at least as we have to follow procedures.

on my client /etc/hosts

```
## The value '' will be replaced with the local-hostname
127.0.0.1 localhost
```

On the SAS host
```

# created during provisioning
#
127.0.0.1             localhost.localdomain localhost
10.1.1.150                  sashost.domain.com sashost loghost
```

> I'm starting to think the problem is actually ssh on your client side (python/saspy) is not connecting to the local port saspy is waiting on. I don't know why that would be, but that's where I'm thinking the problem is now. 
Yes it is because with the current setup the local port binds only on 127.0.0.1 as we can see from the localhost definition and this is universal. For external hosts, it is necessary for a port to listen on public interfaces as described in Jupyter and JupyterHub guides. Also the UFW needs to have that port enabled which we have taken care of.

>Anyway, more tomorrow.
Sure thing. 

Appreciate your continued support here.

**Comment by tomweber-sas** [comment]
Looking forward to see if enabling the gateway ports on the SAS machine lets this work as expected. Also, I still don't think there's an issue with 'localhost'. It is ssh that is forwarding this extra socket connection over it's already established channel. Given ssh -R 32701:localhost:32702 (changed the ports to be different for clarity), saspy opens and accepts a connection on localhost:32701. It's ssh on that machine that will be connecting to that, on localhost, not the SAS process from the remote machine. And, on the remote machine, it's ssh that opens and accepts localhost:32702, and the filename statement in SAS (that saspy sent) connects to that localhost:32702 (the local port forwarded over the ssh tunnel to localhost:32701 on the saspy side by ssh). Neither saspy nor SAS are aware that their 'localhost' connections are being forwarded off-host for them.
So, it is the loopback interface on each machine that is the correct connection for each side. Only ssh knows that it's forwarding the socket from one host to the other.
That's the way I understand this, and I could be wrong. But I believe this is correct and localhost is right on both machines.

Thanks,
tom

**Comment by bikashdube** [comment]
That explanation is correct in terms of "where" SSH is listening on and what ports in respective machines. But we have to keep in mind that data transmitted needs to also go over firewalls which is why the "public interfaces" comes to play in addition to localhost/127.0.0.1/loopback.

As it stands right now there is no problem connecting to and sending the python statements over to the SAS host from the client. The problem is that the SAS host is not able to send back the pd response (so your additional debug statement is not getting executed). I have opened port 32701 on the client host but my theory is that the SAS host is not able to send to the public interface of the client because it is not listening on the public interfaces on any side (Client or SAS host)

The way to make SSH listen on the public interfaces according to the manual 
```python
     -R [bind_address:]port:host:hostport            
 
Specifies that the given port on the remote (server) host is to be forwarded to the given host and port on the local side.  This works by allocating a socket to listen to port on the remote side, and whenever a connection is made to this port, the connection is forwarded over the secure channel, and a connection is made to host port hostport from the local machine.

Port forwardings can also be specified in the configuration file.  Privileged ports can be forwarded only when logging in as root on the remote machine.  IPv6 addresses can be specified by enclosing the address in square brackets.

By default, the listening socket on the server will be bound to the loopback interface only.  This may be overridden by specifying a bind_address.  An empty bind_address, or the address '*', indicates that the remote socket should listen on all interfaces.  Specifying a remote bind_address will only succeed if the server's GatewayPorts option is enabled(see sshd_config(5)).
````

So that makes sense to me and I also think there is a way to iptables hack this to get it to work but don't think we need to get there if the GateWayPorts options does the trick.

We have a change ticket for this that will take a couple of days to be in place. I will update when I have tested it. 

Regards,
Bikash

**Comment by bikashdube** [comment]
Yes sorry Tom, it was resolved after GateWayPorts Yes option. Sorry about the late response.

**Comment by tomweber-sas** [comment]
That's great. Thanks for letting me know. That really was the last thing it could be! 
Thanks!
Tom
