### ISSUE TITLE
Unable to hardcoded links as the data set when using sas.sasdata

### ISSUE THREAD

**Issue by mpmartin618** [sassoftware/saspy#69]
It appears that the current version only allows for users to pull from pre-existing library's that have been created? Is there a way for users to be able to pull from a data set that does not have a library defined within the metadata? Similar to creating a libname statement in sas code. 

For example: 
`test_lib = '/casd/mpmartin/selectABA/Retention/adhoctest/'`
`test4 = sas.sasdata('afrf_base_cmp',test_lib)`

Gives this error: 

Table /casd/mpmartin/selectABA/Retention/adhoctest/.afrf_base_cmp does not exist. This SASdata object will not be useful until the data set is created.

Not sure if there is a work around for this but I did not see anything in the current docs around this issue.

Thanks

**Comment by tomweber-sas** [comment]
Hey, yes, you can assign a libref with the saslib() method. You can assign anything; local directory, a database connection, whatever. The saslib method 'is' the libname statement. Then you can use that libref to create your SASdata object. Try this:
```
sas.saslib('test_lib', "'/casd/mpmartin/selectABA/Retention/adhoctest/'")  #need the extra quotes

sas.datasets('test_lib')  #this will show you the data sets in that library

test4 = sas.sasdata('afrf_base_cmp', 'test_lib') #now you can assign using that libref

test4.head()  #just see the first rows of the table
```
So, no you can't dynamically assign the libref in the sasdata method, you have to issue the saslib first, but then you can get at everything.

Is this good?

Here's the doc for the saslib method too (?sas.saslib):
```
Signature: sas.saslib(libref:str, engine:str=' ', path:str='', options:str=' ', prompt:dict=[]) -> str
Docstring:
:param libref:  the libref for be assigned
:param engine:  the engine name used to access the SAS Library (engine defaults to BASE, per SAS)
:param path:    path to the library (for engines that take a path parameter)
:param options: other engine or engine supervisor options
:return: SAS log
File:      c:\programdata\anaconda3\lib\site-packages\saspy\sasbase.py
Type:      method
```

Thanks,
Tom

**Comment by mpmartin618** [comment]
Perfect, this is exactly what was looking for thanks for the quick response!!

**Comment by tomweber-sas** [comment]
Great! No problem. I'll close this then. If you have any other issues or questions, just let us know!

Thanks,
Tom
