### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by binglin1** [sassoftware/saspy#70]
Hi, I've just started with saspy, I've pip installed on both windows 10 bash and windows 10 environment, and I get the same error when I test if I can import saspy in the python shell.  This is the error I'm currently getting: 

>>> import saspy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/saspy/__init__.py", line 16, in <module>
    from saspy.sasbase        import *
  File "/usr/local/lib/python2.7/dist-packages/saspy/sasbase.py", line 218
    def __init__(self, **kwargs) -> 'SASsession':
                                              ^
SyntaxError: invalid syntax

I didn't have any issue with the pip install, do I need to set a path to SAS for the library? Any help is appreciated, thank you.

**Comment by jld23** [comment]
File "/usr/local/lib/**python2.7**/dist-packages/saspy/init.py", line 16, in 
It looks like you installed the package with python2. You'll need to install python3 on your system before you can use saspy

**Comment by binglin1** [comment]
Hi, sorry about that, I tried the same thing using python 3.4.3 and after typing in import saspy, I get:
ImportError: No module named 'saspy'

Do I have to include saspy to a path somewhere?

**Comment by jld23** [comment]
did you install it again using the pip for python3?
you can type `pip --version` and see which python pip is linked to.
You will likely have to type something like `pip3 install saspy`

You can tell if the package is install by using `pip list` or `pip3 list`

**Comment by binglin1** [comment]
Thank you for you help! I figured out that, that was the likely issue since my first pip installation defaulted to 2.7 and I needed to install pip3 for python3 .

**Comment by tomweber-sas** [comment]
closing this just to clean up. Looks like it was just an unsupported version (2.x) and you're good to go w/ python3.

Thanks,
Tom,
