### ISSUE TITLE
Dependency on pre-commit

### ISSUE THREAD

**Issue by aborsu** [sassoftware/saspy#74]
I don't see any real dependency on pre-commit and I was wondering it was possible to remove it as a dependency or at least to move it to an optional dev dependency?

**Comment by tomweber-sas** [comment]
Yes, I wasn't even sure what that was. It seems it's for pep8 compliance? I think that was put in there day 1 when we were setting all of this up. Boiler plate git stuff I suspect. I don't see any need for it. I'll remove it.

Thanks,
Tom
