### ISSUE TITLE
Unexpected datatype mappings with sas.sasdata2dataframe method

### ISSUE THREAD

**Issue by RandyBetancourt** [sassoftware/saspy#84]
![capture](https://user-images.githubusercontent.com/22532833/33331140-cde5ffce-d42e-11e7-8d27-c91857c21f0c.PNG)

Regardless of the SAS formatting, e.g. character, numeric and date, the the datatypes for sas.sasdata2dataframe method returns an object.

![capture](https://user-images.githubusercontent.com/22532833/33331372-693b693c-d42f-11e7-9b45-c3363bab09ce.PNG)

Of course, one can map the object datatypes to different datatypes as shown.  Are there plans to go beyond the object datatype as the default?  SAS dates could be mapped to datetime64, etc.

**Comment by tomweber-sas** [comment]
Hey Randy, this is odd to me. I wouldn't expect these to come out as objects. I would expect then to be floats. The SAS code doesn't have them as any kind of date/time/datetime, as there is no format, so the date_var is just numeric. 
I just typed in the same code and got what I would expect:
```
>>> import saspy
>>> sas = saspy.SASsession()
Please enter the name of the SAS Config you wish to run. Available Configs are: ['default', 'SASgrid', 'http', 'httptest', 'ssh', 'sshtun', 'httpfred', 'grid', 'tdi', 'tdilat', 'iomj', 'iomc', 'iomjwin', 'winiomj', 'winiomjwin', 'winlocal', 'gridiom', 'wingridiom', 'zos', 'zos2', 'winzos', 'winzos2', 'sshtest', 'sshloc', 'sdssas', 'saskr'] sdssas
SAS Connection established. Subprocess id is 9709

>>> sas.submit('data dates;retain count 0; string = 'dates'; do date_var = '01jan17'd to '31dec17'd by 28; count + 1; output;end;run;')
  File "<stdin>", line 1
    sas.submit('data dates;retain count 0; string = 'dates'; do date_var = '01jan17'd to '31dec17'd by 28; count + 1; output;end;run;')
                                                         ^
SyntaxError: invalid syntax
>>> sas.submit("data dates;retain count 0; string = 'dates'; do date_var = '01jan17'd to '31dec17'd by 28; count + 1; output;end;run;")
{'LST': '', 'LOG': "\n27   ods listing close;ods html5 (id=saspy_internal) file=stdout options(bitmap_mode='inline') device=svg; ods graphics on /\n27 ! outputfmt=png;\nNOTE: Writing HTML5(SASPY_INTERNAL) Body file: STDOUT\n28   \n29   data dates;retain count 0; string = 'dates'; do date_var = '01jan17'd to '31dec17'd by 28; count + 1; output;end;run;\nNOTE: The data set WORK.DATES has 14 observations and 3 variables.\nNOTE: DATA statement used (Total process time):\n      real time           0.18 seconds\n      cpu time            0.01 seconds\n      \n30   \n31   ods html5 (id=saspy_internal) close;ods listing;\n\n\x0c1                                                          The SAS System                           12:43 Tuesday, November 28, 2017\n\nNOTE: html5 Memory Usage (274 events)\n      Total: 2.79MB     High: 1283.74KB     Max: 32807B     Allocs: 16837   Frees: 16837\n32   "}
>>> df = sas.sasdata2dataframe('dates')
>>> df
    count string  date_var
0     1.0  dates   20820.0
1     2.0  dates   20848.0
2     3.0  dates   20876.0
3     4.0  dates   20904.0
4     5.0  dates   20932.0
5     6.0  dates   20960.0
6     7.0  dates   20988.0
7     8.0  dates   21016.0
8     9.0  dates   21044.0
9    10.0  dates   21072.0
10   11.0  dates   21100.0
11   12.0  dates   21128.0
12   13.0  dates   21156.0
13   14.0  dates   21184.0
>>> df.dtypes
count       float64
string       object
date_var    float64
dtype: object
>>> df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
count       14 non-null float64
string      14 non-null object
date_var    14 non-null float64
dtypes: float64(2), object(1)
memory usage: 416.0+ bytes
>>>
```

Can you tell me which access method you're using and what version of saspy you have? If you just submit your SASsession object:
```
sas
```
that will display everything.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
That was with STDIO, and I just tried IOM getting the same results to. There have been some fixes and enhancements to the sasdata2dataframe method (and a new version that uses CSV files for performance reasons) pushed recently. I am running the latest from master. That could be the difference too.

**Comment by tomweber-sas** [comment]
And, if you add a format to your date_var so SAS thinks it's a date, then you get the datetime64[ns] in your dataframe like you expect.
```
>>> ll = sas.submit("data dates;format date_var date.; retain count 0; string = 'dates'; do date_var = '01jan17'd to '31dec17'd by 28; count + 1; output;end;run;")
>>> df = sas.sasdata2dataframe('dates')
>>> df
     date_var  count string
0  2017-01-01    1.0  dates
1  2017-01-29    2.0  dates
2  2017-02-26    3.0  dates
3  2017-03-26    4.0  dates
4  2017-04-23    5.0  dates
5  2017-05-21    6.0  dates
6  2017-06-18    7.0  dates
7  2017-07-16    8.0  dates
8  2017-08-13    9.0  dates
9  2017-09-10   10.0  dates
10 2017-10-08   11.0  dates
11 2017-11-05   12.0  dates
12 2017-12-03   13.0  dates
13 2017-12-31   14.0  dates
>>> df.dtypes
date_var    datetime64[ns]
count              float64
string              object
dtype: object
>>> df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
date_var    14 non-null datetime64[ns]
count       14 non-null float64
string      14 non-null object
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 416.0+ bytes
>>>
```

**Comment by tomweber-sas** [comment]
But, none of that explains why you got only objects. That's for char data, not numeric or date/time's.
Tom

**Comment by RandyBetancourt** [comment]
Thanks, Tom.  And yep, I would have expected to have the same output you show above.  I re-started the Jupyter-kernel and stepped through all of my examples with same results I posted earlier.

![capture](https://user-images.githubusercontent.com/22532833/33568529-b2f72c90-d8f4-11e7-9074-249c887edb8f.PNG)

**Comment by tomweber-sas** [comment]
Hey Randy, I can't explain this as of yet. The code has always handled datatypes, since I first wrote it. Do you have time for a webex? I think that would be the fastest way to track this down. BTW, what version of Pandas and Python do you have? I wonder if something changed in pandas if it's newer than anything I have - maybe deprecated methods I'm using or something??? Just a wild guess as this doesn't make sense to me. I can look at this with you anytime this morning or early afternoon if that works for you.

Thanks,
Tom

**Comment by RandyBetancourt** [comment]
Hi Tom,

Webex is fine.  How about early afternoon on Wednesday?  I'll post the version for panda.  You should know that subsequent calls to sd2df return the expected data types.  

Best,
Randy

**Comment by RandyBetancourt** [comment]
![capture](https://user-images.githubusercontent.com/22532833/33611190-7e7207f4-d99b-11e7-8b3a-a7aabd7c4c22.PNG)

**Comment by tomweber-sas** [comment]
Hey Randy, I think I found the problem. I had reworked the method for performance problems with large data sets. Trying to create a large dataframe from streamed data doesn't scale. So I now create an empty data frame and build out and adjust the data types on a temp dataframe, per chunk of streamed data, and append that temp df to the one I'll inevitably return. The append method doesn't behave consistently. Sometimes the final df gets the dtypes of the temp one I append, while other times it doesn't. I've tweaked my code to account for this - don't create the final (empty) df up front. The first time I would append, just set it to be that temp one (instead of appending) so it for sure has the right data types; not maybe the right and maybe the wrong.

I just pushed this to master. Can you pull that and give it a try? This stinks, cuz I just built that 2.1.8 pypi with this in it. I'll have to build a new one with this fix for the inconsistent behavior. My bug, of course. Glad you found it quickly!

Thanks,
Tom

**Comment by RandyBetancourt** [comment]
Hi Tom,

Yep, will do.

Best,
Randy

**Comment by RandyBetancourt** [comment]
Hi Tom,

See the output from the upgrade below.  Restarted the Python Kernel inside the notebook.  Same results.
I don't think I picked-up your changes.

Best,
Randy

[root@localhost input]# pip install saspy --upgrade
Requirement already up-to-date: saspy in /root/anaconda3/lib/python3.6/site-pack                         ages
Requirement already up-to-date: pygments in /root/anaconda3/lib/python3.6/site-p                         ackages (from saspy)
Requirement already up-to-date: ipython>=4.0.0 in /root/anaconda3/lib/python3.6/                         site-packages (from saspy)
Requirement already up-to-date: simplegeneric>0.8 in /root/anaconda3/lib/python3                         .6/site-packages (from ipython>=4.0.0->saspy)
Collecting setuptools>=18.5 (from ipython>=4.0.0->saspy)
  Downloading setuptools-38.2.4-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 1.1MB/s
Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.4 in /root/anaconda3/                         lib/python3.6/site-packages (from ipython>=4.0.0->saspy)
Requirement already up-to-date: jedi>=0.10 in /root/anaconda3/lib/python3.6/site                         -packages (from ipython>=4.0.0->saspy)
Requirement already up-to-date: decorator in /root/anaconda3/lib/python3.6/site-                         packages (from ipython>=4.0.0->saspy)
Requirement already up-to-date: traitlets>=4.2 in /root/anaconda3/lib/python3.6/                         site-packages (from ipython>=4.0.0->saspy)
Requirement already up-to-date: pickleshare in /root/anaconda3/lib/python3.6/sit                         e-packages (from ipython>=4.0.0->saspy)
Requirement already up-to-date: pexpect; sys_platform != "win32" in /root/anacon                         da3/lib/python3.6/site-packages (from ipython>=4.0.0->saspy)
Requirement already up-to-date: six>=1.9.0 in /root/anaconda3/lib/python3.6/site                         -packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->saspy)
Requirement already up-to-date: wcwidth in /root/anaconda3/lib/python3.6/site-pa                         ckages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->saspy)
Requirement already up-to-date: parso==0.1.0 in /root/anaconda3/lib/python3.6/si                         te-packages (from jedi>=0.10->ipython>=4.0.0->saspy)
Requirement already up-to-date: ipython_genutils in /root/anaconda3/lib/python3.                         6/site-packages (from traitlets>=4.2->ipython>=4.0.0->saspy)
Requirement already up-to-date: ptyprocess>=0.5 in /root/anaconda3/lib/python3.6                         /site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->saspy)
Installing collected packages: setuptools
  Found existing installation: setuptools 38.2.1
    Uninstalling setuptools-38.2.1:
      Successfully uninstalled setuptools-38.2.1
Successfully installed setuptools-38.2.4

**Comment by tomweber-sas** [comment]
Sorry Randy. I haven't built a new pypi image. This is just at master. Do you know how to get that?

**Comment by tomweber-sas** [comment]
I believe it's just:
pip install git+https://github.com/sassoftware/saspy.git@master

**Comment by RandyBetancourt** [comment]
Hi Tom,

Yep--the command worked.  Reloaded the kernel, and it solved the problem.  The team here is continuing to utilize this really cool project!  I really appreciate the quick responses.  Closing the comment.

Best,
Randy

**Comment by tomweber-sas** [comment]
Awesome! Thanks Randy. Sorry about that! Glad you found it though!

**Comment by tomweber-sas** [comment]
BTW, I just built this into the next pypi. So 'pip install saspy' will get it now. ver=2.1.9
