### ISSUE TITLE
Broken pipe:  Fatal I/O error

### ISSUE THREAD

**Issue by RandyBetancourt** [sassoftware/saspy#85]
Hi Tom,

This had worked previously.  Please let me know if I can provide any further diagnostic information.

Best,
Randy

![capture](https://user-images.githubusercontent.com/22532833/33616753-d41e643a-d9ab-11e7-9569-8b0cf6b5725f.PNG)

The SAS log:

1                                                          The SAS System                             23:27 Monday, December 4, 2017

NOTE: Unable to open SASUSER.REGSTRY. WORK.REGSTRY will be opened instead.
NOTE: All registry changes will be lost at the end of the session.

WARNING: Unable to copy SASUSER registry to WORK registry. Because of this, you will not see registry customizations during this 
         session.
NOTE: Copyright (c) 2002-2012 by SAS Institute Inc., Cary, NC, USA. 
NOTE: SAS (r) Proprietary Software 9.4 (TS1M4 MBCS3170) 
      Licensed to PROQUIRE LLC-AIP INTERNAL QA, Site 70183584.
NOTE: This session is executing on the Linux 3.10.0-693.5.2.el7.x86_64 (LIN X64) platform.

NOTE: Updated analytical products:
      
      SAS/STAT 14.2
      SAS/ETS 14.2
      SAS/OR 14.2

NOTE: Additional host information:

 Linux LIN X64 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 13 10:46:25 EDT 2017 x86_64 Red Hat Enterprise Linux Server release 7.4 
      (Maipo) 

You are running SAS 9. Some SAS 8 files will be automatically converted 
by the V9 engine; others are incompatible.  Please see 
http://support.sas.com/rnd/migration/planning/platform/64bit.html

PROC MIGRATE will preserve current SAS file attributes and is 
recommended for converting all your SAS libraries from any 
SAS 8 release to SAS 9.  For details and examples, please see
http://support.sas.com/rnd/migration/index.html

This message is contained in the SAS news file, and is presented upon
initialization.  Edit the file "news" in the "misc/base" directory to
display site-specific news and information in the program log.
The command line option "-nonews" will prevent this display.

NOTE: SAS initialization used:
      real time           0.09 seconds
      cpu time            0.01 seconds
      

NOTE: AUTOEXEC processing beginning; file is /home/sas/autoexec.sas.

MY_NOTE: SAS AUTOEXEC is from: $HOME/autoexec.sas

NOTE: AUTOEXEC processing completed.

1    ;*';*";*/;
2    options svgtitle='svgtitle'; options validvarname=any; ods graphics on;
3    
4    ;*';*";*/;
5    %put E3969440A681A2408885998500000001;
E3969440A681A2408885998500000001
6    ;*';*";*/;
7    libname work list;
NOTE: Libref=   WORK 
      Scope=    Kernel  
      Engine=   V9
      Access=   TEMP
      Physical Name= /tmp/SAS_workDA4F00002967_localhost.localdomain
      Filename= /tmp/SAS_workDA4F00002967_localhost.localdomain
      Inode Number= 105272896
      Access Permission= rwx------
      Owner Name= sas
      File Size=              0KB
      File Size (bytes)= 78
8    
9    ;*';*";*/;
10   %put E3969440A681A2408885998500000002;
E3969440A681A2408885998500000002
11   ;*';*";*/;
12   %put SYSV=&sysvlong4;
SYSV=9.04.01M4P11092016
13   
14   ;*';*";*/;
15   %put E3969440A681A2408885998500000003;
E3969440A681A2408885998500000003
16   ;*';*";*/;
17   proc options option=encoding;run;
    SAS (r) Proprietary Software Release 9.4  TS1M4

 ENCODING=UTF-8    Specifies the default character-set encoding for the SAS session.
NOTE: PROCEDURE OPTIONS used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      
18   
19   ;*';*";*/;
20   %put E3969440A681A2408885998500000004;
E3969440A681A2408885998500000004
21   ;*';*";*/;
22   filename x "/home/sas/input/Crimes_2001_to_present.csv/";
23   proc import datafile=x out=crimes dbms=csv replace; guessingrows=200;  run;
NOTE: Unable to open SASUSER.PROFILE. WORK.PROFILE will be opened instead.
NOTE: All profile changes will be lost at the end of the session.
24    /**********************************************************************
25    *   PRODUCT:   SAS
26    *   VERSION:   9.4
27    *   CREATOR:   External File Interface
28    *   DATE:      04DEC17
29    *   DESC:      Generated SAS Datastep Code
30    *   TEMPLATE SOURCE:  (None Specified.)
31    ***********************************************************************/
32       data WORK.CRIMES    ;
33       %let _EFIERR_ = 0; /* set the ERROR detection macro variable */
34       infile X delimiter = ',' MISSOVER DSD  firstobs=2 ;
35          informat ID best32. ;
36          informat "Case Number"N $8. ;
37          informat Date anydtdtm40. ;
38          informat Block $35. ;
39          informat IUCR $4. ;
40          informat "Primary Type"N $32. ;
41          informat Description $47. ;
42          informat "Location Description"N $33. ;
43          informat Arrest $5. ;
44          informat Domestic $5. ;
45          informat Beat best32. ;
46          informat District best32. ;
47          informat Ward best32. ;
48          informat "Community Area"N best32. ;
49          informat "FBI Code"N $3. ;
50          informat "X Coordinate"N best32. ;
51          informat "Y Coordinate"N best32. ;
52          informat Year best32. ;
53          informat "Updated On"N anydtdtm40. ;
54          informat Latitude best32. ;
55          informat Longitude best32. ;
56          informat Location $31. ;
57          format ID best12. ;
58          format "Case Number"N $8. ;
59          format Date datetime. ;
60          format Block $35. ;
61          format IUCR $4. ;
62          format "Primary Type"N $32. ;
63          format Description $47. ;
64          format "Location Description"N $33. ;
65          format Arrest $5. ;
66          format Domestic $5. ;
67          format Beat best12. ;
68          format District best12. ;
69          format Ward best12. ;
70          format "Community Area"N best12. ;
71          format "FBI Code"N $3. ;
72          format "X Coordinate"N best12. ;
73          format "Y Coordinate"N best12. ;
74          format Year best12. ;
75          format "Updated On"N datetime. ;
76          format Latitude best12. ;
77          format Longitude best12. ;
78          format Location $31. ;
79       input
80                   ID
81                   "Case Number"N $
82                   Date
83                   Block $
84                   IUCR $
85                   "Primary Type"N $
86                   Description $
87                   "Location Description"N $
88                   Arrest $
89                   Domestic $
90                   Beat
91                   District
92                   Ward
93                   "Community Area"N
94                   "FBI Code"N $
95                   "X Coordinate"N
96                   "Y Coordinate"N
97                   Year
98                   "Updated On"N
99                   Latitude
100                  Longitude
101                  Location $
102      ;
103      if _ERROR_ then call symputx('_EFIERR_',1);  /* set ERROR detection macro variable */
104      run;
NOTE: The infile X is:
      Filename=/home/sas/input/Crimes_2001_to_present.csv,
      Owner Name=sas,Group Name=sas,
      Access Permission=-rw-rw-r--,
      Last Modified=04Dec2017:14:12:19,
      File Size (bytes)=1526779979

NOTE: 6488215 records were read from the infile X.
      The minimum record length was 137.
      The maximum record length was 308.
NOTE: The data set WORK.CRIMES has 6488215 observations and 22 variables.
NOTE: DATA statement used (Total process time):
      real time           54.30 seconds
      cpu time            21.56 seconds
      
6488215 rows created in WORK.CRIMES from X.
  
  
  
NOTE: WORK.CRIMES data set was successfully created.
NOTE: The data set WORK.CRIMES has 6488215 observations and 22 variables.
NOTE: PROCEDURE IMPORT used (Total process time):
      real time           54.78 seconds
      cpu time            21.70 seconds
      
105  
106  ;*';*";*/;
107  %put E3969440A681A2408885998500000005;
E3969440A681A2408885998500000005
108  ;*';*";*/;
109  data _null_; e = exist('crimes');
110  te='TABLE_EXISTS='; put te e;run;
TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      
111  
112  ;*';*";*/;
113  %put E3969440A681A2408885998500000006;
E3969440A681A2408885998500000006
114  ;*';*";*/;
115  data _null_; e = exist('user.crimes');
116  te='TABLE_EXISTS='; put te e;run;
TABLE_EXISTS= 0
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      
117  
118  ;*';*";*/;
119  %put E3969440A681A2408885998500000007;
E3969440A681A2408885998500000007
120  ;*';*";*/;
121  data _null_; e = exist('crimes');
122  te='TABLE_EXISTS='; put te e;run;
TABLE_EXISTS= 1
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      
123  
124  ;*';*";*/;
125  %put E3969440A681A2408885998500000008;
E3969440A681A2408885998500000008
126  ;*';*";*/;
127  proc sql;
127!           create view sasdata2dataframe as select * from crimes;
NOTE: SQL view WORK.SASDATA2DATAFRAME has been defined.
127!                                                                 quit;
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds
      
128  data _null_; file STDERR;d = open('sasdata2dataframe');
129  lrecl = attrn(d, 'LRECL'); nvars = attrn(d, 'NVARS');
130  lr='LRECL='; vn='VARNUMS='; vl='VARLIST='; vt='VARTYPE='; vf='VARFMT=';
131  put lr lrecl; put vn nvars; put vl;
132  do i = 1 to nvars; var = varname(d, i); put var; end;
133  put vt;
134  do i = 1 to nvars; var = vartype(d, i); put var; end;
135  run;
NOTE: The file STDERR is:
      Pipe command="<standard error>"
LRECL= 311
VARNUMS= 22
VARLIST=
ID
Case Number
Date
Block
IUCR
Primary Type
Description
Location Description
Arrest
Domestic
Beat
District
Ward
Community Area
FBI Code
X Coordinate
Y Coordinate
Year
Updated On
Latitude
Longitude
Location
VARTYPE=
N
C
N
C
C
C
C
C
C
C
N
N
N
N
C
N
N
N
N
N
N
C

NOTE: 48 records were written to the file STDERR.
      The minimum record length was 1.
      The maximum record length was 20.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds
      
136  
137  ;*';*";*/;
138  %put E3969440A681A2408885998500000009;
E3969440A681A2408885998500000009
139  ;*';*";*/;
140  data _null_; set crimes(obs=1 );put 'FMT_CATS=';
141  _tom = vformatn('ID'n);put _tom;
142  _tom = vformatn('Case Number'n);put _tom;
143  _tom = vformatn('Date'n);put _tom;
144  _tom = vformatn('Block'n);put _tom;
145  _tom = vformatn('IUCR'n);put _tom;
146  _tom = vformatn('Primary Type'n);put _tom;
147  _tom = vformatn('Description'n);put _tom;
148  _tom = vformatn('Location Description'n);put _tom;
149  _tom = vformatn('Arrest'n);put _tom;
150  _tom = vformatn('Domestic'n);put _tom;
151  _tom = vformatn('Beat'n);put _tom;
152  _tom = vformatn('District'n);put _tom;
153  _tom = vformatn('Ward'n);put _tom;
154  _tom = vformatn('Community Area'n);put _tom;
155  _tom = vformatn('FBI Code'n);put _tom;
156  _tom = vformatn('X Coordinate'n);put _tom;
157  _tom = vformatn('Y Coordinate'n);put _tom;
158  _tom = vformatn('Year'n);put _tom;
159  _tom = vformatn('Updated On'n);put _tom;
160  _tom = vformatn('Latitude'n);put _tom;
161  _tom = vformatn('Longitude'n);put _tom;
162  _tom = vformatn('Location'n);put _tom;
163  run;
FMT_CATS=
BEST
$
DATETIME
$
$
$
$
$
$
$
BEST
BEST
BEST
BEST
$
BEST
BEST
BEST
DATETIME
BEST
BEST
$
NOTE: There were 1 observations read from the data set WORK.CRIMES.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds
      
164  
165  
166  ;*';*";*/;
167  %put E3969440A681A2408885998500000010;
E3969440A681A2408885998500000010
168  filename sock socket ':50315' lrecl=32767 recfm=v termstr=LF;
169   data _null_; set crimes;
170   file sock dlm='02'x ; put 'ID'n best32. '02'x 'Case Number'n 'Date'n E8601DT26.6 '02'x 'Block'n 'IUCR'n 'Primary Type'n
170! 'Description'n 'Location Description'n 'Arrest'n 'Domestic'n 'Beat'n best32. '02'x 'District'n best32. '02'x 'Ward'n best32.
170! '02'x 'Community Area'n best32. '02'x 'FBI Code'n 'X Coordinate'n best32. '02'x 'Y Coordinate'n best32. '02'x 'Year'n best32.
170! mmunity Area'n best32. '02'x 'FBI Code'n 'X Coordinate'n best32. '02'x 'Y Coordinate'n best32. '02'x 'Year'n best32. '02'x
170! 'Updated On'n E8601DT26.6 '02'x 'Latitude'n best32. '02'x 'Longitude'n best32. '02'x 'Location'n '01'x; run;
NOTE: The file SOCK is:
      Local Host Name=localhost.localdomain,
      Local Host IP addr=::1,
      Peer Hostname Name=localhost,
      Peer IP addr=127.0.0.1,Peer Name=N/A,
      Peer Portno=50315,Lrecl=32767,Recfm=Variable

ERROR: Broken pipe.
FATAL: Unrecoverable I/O error detected in the execution of the DATA step program.  Aborted during the EXECUTION phase.
NOTE: 217773 records were written to the file SOCK.
      The minimum record length was 453.
      The maximum record length was 563.
NOTE: The SAS System stopped processing this step because of errors.
NOTE: There were 217774 observations read from the data set WORK.CRIMES.
NOTE: DATA statement used (Total process time):
      real time           4.39 seconds
      cpu time            0.59 seconds
      
171  
172  ;*';*";*/;
173  
174  
175  ;*';*";*/;
176  %put E3969440A681A2408885998500000011;
E3969440A681A2408885998500000011

**Comment by RandyBetancourt** [comment]
So far, specific to this data.  i'll try with other datasets.

**Comment by RandyBetancourt** [comment]
It seems to be specific to the crimes dataset.  Other examples work, however, these other examples are orders of magnitude smaller.

**Comment by tomweber-sas** [comment]
ok, I've reproduced this, so that's good. I'll track it down and see what the deal is.

**Comment by tomweber-sas** [comment]
Hey, while I track this down, can you give the new method a try; it worked for me:
pd_crimes = sas.sd2df_CSV('crimes')
It will be a lot faster too, than just sd2df() for this size data.

**Comment by RandyBetancourt** [comment]
Wow!  Yesterday, this was clocking in at 8 minutes elapsed time.  Very nice improvement.  That is almost an order of magnitude performance improvement.

![capture](https://user-images.githubusercontent.com/22532833/33620190-302b381c-d9b5-11e7-8bef-41371e639492.PNG)

**Comment by tomweber-sas** [comment]
Thanks!, yeah, building a df in memory just doesn't scale. And, I see what I did wrong. I fixed the last issue by not creating an empty df, and just checking for the first time to not append:
```
      #df    = pd.DataFrame(columns=varlist)
      df    = None
[...]
         if df:
            df = df.append(tdf, ignore_index=True)
         else:
            df = tdf
```
BUT, you can't apparently say if df: (for df being a dataframe) because when it is a dataframe the if df: throws an exception. Cripes.

So, one more push:
```
         if df is not None:
            df = df.append(tdf, ignore_index=True)
         else:
            df = tdf
```
So now 2.1.10 pypi in  a few minutes.  But, you will certainly want the _CSV versions for this size data, as you saw. The plain one should work now once I push this fix. It just ran slow but successful for me now.

You've got a job in saspy QA if you want it :)

Thanks!
Tom

**Comment by tomweber-sas** [comment]
New pypi available. But I versioned  it 2.2.0. it's the latest.

**Comment by RandyBetancourt** [comment]
Sounds good!  One more item for you.  It looks like you may want to investigate setting the low_memory=False parameter on what I'm guessing is your call to pd.read_csv method.   

![capture](https://user-images.githubusercontent.com/22532833/33622398-b6590ce2-d9bb-11e7-8592-a109d543de84.PNG)

**Comment by tomweber-sas** [comment]
Yes, I saw that warning with some other data when working on this, and I set that option, but it didn't make any difference (for that data anyway). Guess I could set it anyway in hopes if make pandas figure something out better some times, maybe depending on what it's confused about. Guess it just depends upon the data.

**Comment by RandyBetancourt** [comment]
Yes, this warning is data dependent.  

The performance on sd2df_CSV is excellent  Glad you changed the approach.  I can't see a reason to go back to the original sd2df method.

Thanks again, Tom.  Closing this issue.
