### ISSUE TITLE
How to identify IOM connection address and port number in EG?

### ISSUE THREAD

**Issue by 77QingLiu** [sassoftware/saspy#90]
Hope this is not a stupid question.

In the configuration step, the iomhost(IOM host address) and iomport(IOM port number) are required. But I don't know this.
My question is, how can I find this information in EG?
My EG is connecting a SAS Grid Manager. Are there some existing SAS Procedure to help me identify the address and port number? thanks.

**Comment by 77QingLiu** [comment]
Find the solution by submitting the following code
```sas
proc iomoperate
  uri='iom://metadataserver.com:8564;Bridge;USER=my_user,PASS=my_pass';
  list DEFINED FILTER='Workspace';
quit;
```
so i'll close this issue

**Comment by tomweber-sas** [comment]
That's great, I'm glad you tracked it down. I think this is a useful thing for me to add to the configuration documentation in the IOM section. You won't be the only one who needs to find out this info. I'll see about adding this in so other can benefit!
Thanks,
Tom

**Comment by 77QingLiu** [comment]
Yes, you are right. I do think this is a useful thing . 
I am a SAS user but not a SAS IT professional.
In my circumstance, I only know the server address in EG in the following screen shot.
![capture](https://user-images.githubusercontent.com/32193271/35258379-eebb1bda-0039-11e8-96c5-fc41d710aa4f.JPG)


I tried the server address and port number, but It not worked.
After googled and serarched the SAS documentation, Then I realize that this a SAS metadataserver but not a IMO Workspcae Server. And I can find the IOM workspace server by submitting above SAS statement with a SAS metadataserver address.

Thanks,
Qing

**Comment by tomweber-sas** [comment]
I have updated the doc with this information. It is in the Advanced topics section (https://sassoftware.github.io/saspy/advanced-topics.html) and is referenced from the Remote IOM configuration section (https://sassoftware.github.io/saspy/install.html#remote).

Take a look and let me know what you think. If it's good, great. If you have any changes or other thoughts, let me know!

Thanks again,
Tom

**Comment by 77QingLiu** [comment]
That looks great! Thank you Tom.
