### ISSUE TITLE
Teach_me_SAS produces additional semi-colons within sgplot

### ISSUE THREAD

**Issue by Cazziii** [sassoftware/saspy#96]
When running the following within Teach_me_SAS:
mydata.bar('gender', title='My Title')

I get the code as below:
proc sgplot data=mydata._df;
	vbar gender ; ;
	title "My Title";
run;
title;

The additional ; appears on the vbar statement.  
This appears to be present also for the heatmap statement.

**Comment by tomweber-sas** [comment]
I'll see about cleaning that up when I get a chance, thanks!
FWIW, it is still valid SAS syntax. SAS loves semicolons, eats them up :) 
But, this should 'teach' a clean, clear syntax, so I'll fix it up!

Thanks,
Tom

**Comment by Cazziii** [comment]
Hi Tom,  Thanks for this, I appreciate it still works but I just thought it best to mention so you were aware :)

**Comment by tomweber-sas** [comment]
Of course, I do appreciate it. Always want to make saspy better and cleaner. I get stuff about typos in the doc too. I blame those on my keyboard, but really I can't spell :)

**Comment by tomweber-sas** [comment]
Ok, I cleaned this up. The code should look just right now. pushed to master as  14a46f5.

Thanks again!
Tom
